### ISSUE TITLE
Hang after loading ble.sh in vi-mode

### ISSUE THREAD

**Issue by B-bar** [akinomyoga/ble.sh#1]
\# すいません日本語で書かせてください……。

bash 4.4.12 を利用しています。
本スクリプトを `source` した後 `set -o vi` とすると入力を受け付けなくなります。私の場合は外部から強制終了するしか手段がありませんでした。
また，元々 `~/.inputrc` 等で vi-mode に設定していた場合でも，本スクリプトを読み込むと無効になります。
恐らく Readline を再実装されている様なので vi-mode の実現は厳しいでしょうが，せめて警告を出すようにしていただくと嬉しいです。

**Comment by akinomyoga** [comment]
ご迷惑をおかけしてすみません。

**状況**

`set -o vi` にすると何も出力されなくなります。`ble.sh` は `set -o emacs` の `emacs-standard` キーマップを書き換えて Bash に対するキー入力を奪うと共に、Bash 自体の出力も奪っています。`set -o vi` によってキーマップを切り替えると Bash 固有の出力がなされるようになるわけですが、それが `ble.sh` によって抑制されるので何も表示されなくなったのでした。

**修正**

チェックするように修正 (b5df63e12fed48783ba22d180feef7611ff20b80) しました。 修正後の動作は以下のようにしました。master ブランチからご確認頂ければ幸いです:
- `ble.sh` 読み込み時に `set -o emacs` 以外のときは、メッセージを表示し `ble.sh` の本体はロードしません
- `source` した後で `set -o emacs` 以外になったときは、`ble-detach` (`ble.sh` を使わないモードに移行するコマンド) を実行しメッセージを表示します
- `ble-attach` (`ble.sh` を使うモードに移行するコマンド) を呼び出したとき `set -o emacs` 以外なら、メッセージを表示し `ble-attach` の実際の処理は行いません

----

また、`vi` 編集モードを実装することに興味はお持ちでしょうか。或いは、直接に実装していただかなくても、テストユーザになっていただくことに興味はお持ちでしょうか。

当初は `vi` 編集モードを実装することも考えたのですが、私は普段 `vi` モードを使わないので細かい動作で誤った実装をするかもしれないこと、また実際にどれほどのユーザがいらっしゃるのか分からないことから、特に使用者が現れるまでは実装しない方針にしたのでした。

**Comment by B-bar** [comment]
早速の対応感謝いたします。
当方でも確認できました。

vi-mode の実装についてですが，テストユーザであれば喜んで承ります。
また，実装そのものに関してはとりあえずフォークさせて頂くかたちでも宜しいでしょうか。
今の私の知識では到底実用に耐えるものが作れず，時間が掛かると思うので……。

**Comment by akinomyoga** [comment]
> vi-mode の実装についてですが，テストユーザであれば喜んで承ります。

ありがとうございます。今週末に時間が取れればある程度実装してみようかと思います。暫く時間がかかるかもしれませんが、ある程度形になりましたら改めてテストユーザをお願いできないかうかがうことにいたします。よろしくおねがいいたします。

こちらの Issue については一旦閉じることにします。
