### ISSUE TITLE
AWS cli not working.

### ISSUE THREAD

**Issue by Archehandoro** [akinomyoga/ble.sh#102]
**ble version**: 0.4.0-devel3+0506df2
**Bash version**: 5.1.0(1)-release, x86_64-redhat-linux-gnu

**Issue**: Autocompletion for the AWS cli stops working after installing Ble.sh.

**Expected behaviour**: Being able to see available commands for the AWS cli and autocompletion of flags.

**Comment by akinomyoga** [comment]
Thank you for the report! And sorry for the late reply. I could soon reproduce this problem in my environment, so I will fix it by myself. However, currently, there are other pending fixes, so it may be some time later. I'll let you know again when I fix it. Thank you

**Comment by akinomyoga** [comment]
@Archehandoro I added a fix in commit 026432d. It was simply a bug in the code to analyze the output of `complete -p aws`. Could you confirm if the `aws` completion now works fine? You can update `ble.sh` by running the command `ble-update` in a `ble.sh` session. Thank you!

**Comment by Archehandoro** [comment]
Hello, sorry I missed your first comment! :(

Your fix works a charm thanks so much! And fantastic work

**Comment by akinomyoga** [comment]
OK! Thank you for testing! I'll close this issue.
