### ISSUE TITLE
After update: -bash expression (error token is .....

### ISSUE THREAD

**Issue by RakibFiha** [akinomyoga/ble.sh#106]
**ble version**:  0.4.0-devel3+ea05fc5
**Bash version**:  5.0.17(1)-release, x86_64-pc-linux-gnu

 I did ble_update and after that it has stopped working and each time, I open a new terminal window I am getting:

```
ble/term.sh: updating tput cache for TERM=xterm-256color... done
-bash: ((: 32 2 11 32 21 96 95 95 102 122 102 95 99 100 95 95 96 27 5 27 114 13 25 8 27 32 25 27 121 24 24 4: syntax error in expression (error token is "2 11 32 21 96 95 95 102 122 102 95 99 100 95 95 96 27 5 27 114 13 25 8 27 32 25 27 121 24 24 4")
-bash: ((: 32 2 11 32 21 96 95 95 102 122 102 95 99 100 95 95 96 27 5 27 114 13 25 8 27 32 25 27 121 24 24 4: syntax error in expression (error token is "2 11 32 21 96 95 95 102 122 102 95 99 100 95 95 96 27 5 27 114 13 25 8 27 32 25 27 121 24 24 4")
-bash: 32 2 11 32 21 96 95 95 102 122 102 95 99 100 95 95 96 27 5 27 114 13 25 8 27 32 25 27 121 24 24 4: syntax error in expression (error token is "2 11 32 21 96 95 95 102 122 102 95 99 100 95 95 96 27 5 27 114 13 25 8 27 32 25 27 121 24 24 4")
```

**Comment by akinomyoga** [comment]
Thank you for the report. Hmm,

- Q1. Do you remember what is the previous version (commit hash) of `ble.sh` before `ble-update`?
- Q2. Can you identify in which commit does the error start to occur?

**Comment by RakibFiha** [comment]
I have gone back to the old commit `0506df28baa6ac54de6cb6650d2ad208b0c00190` and no issue. I think, I wont be updating for now and be using this version `0506df`

**Comment by akinomyoga** [comment]
OK! Thank you for the information!

**Comment by akinomyoga** [comment]
Ah, OK! I could reproduce the problem. This exactly started to happen ea05fc5.

**Comment by RakibFiha** [comment]
There you go!

**Comment by akinomyoga** [comment]
I pushed a fix c257299. Can you update it? If you cannot start ble.sh correctly, you can update it by loading `ble.sh` with an option `--noinputrc` and then running `ble-update`.

```bash
$ source /path/to/ble.sh --noattach --noinputrc
$ ble-update
```

**Comment by RakibFiha** [comment]
Thank you. Its working now.

**Comment by akinomyoga** [comment]
OK! Thank you for the check!
