### ISSUE TITLE
カーソルが関数の上にある場合に，手引きを開こうとすると正常でないコマンドが実行される

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#11]
Commit ID: 6129766
Bash version: 4.4.12

```console
$ function somefunc() { echo "foo"; }
$ somefun@
```
この状態で，手引き閲覧キー（既定では<kbd>K</kbd>）を押下すると
```
-bash: UTF-8: コマンドが見つかりません
-bash: UTF-8: コマンドが見つかりません
```
という警告が表示され，コマンドラインに戻されます。
本来は（というか以前のコミット; 早くとも 9e68058 の段階では）`somefunc`の内容が表示されます。

**Comment by akinomyoga** [comment]
こちらはその後いかがでしょうか。

**Comment by akinomyoga** [comment]
すみません、恐らく以前 `ble.sh/blerc` に混入していた[バグ](https://github.com/akinomyoga/ble.sh/commit/64fbb596eb4dbda1ea4659f12098badfa6a49123#diff-304457641f8056b4e82241d6d5df3a8dR18)がそちらの設定ファイルに混入してしまっていますね…。お手数をおかけします。以下を同様に修正して頂いて様子を見ていただけないでしょうか。

- https://github.com/cmplstofB/dotfiles/blob/master/etc/blesh/conf.bash#L2

**Comment by cmplstofB** [comment]
@akinomyoga 様
ありがとうございます！
修正したところ，正常な動作に戻りました。また，不具合ではなくて気になっていた，Bashの内部コマンドに対してcommand-helpを実行したときに，単にBashのmanページが表示されるだけで目的の場所に移動しないという状態も，直りました。
細かいことですいません……。

**Comment by akinomyoga** [comment]
直ったようで良かったです! 閉じますね!
