### ISSUE TITLE
[macOS groff] Only groff 1.19.2 available on OS X

### ISSUE THREAD

**Issue by killermoehre** [akinomyoga/ble.sh#112]
**ble version**: `0.4.0-devel3+0506df2`
**Bash version**: 5.1.8(1)-release (x86_64-apple-darwin20.3.0)

On OS X, the default `groff` does not know the `-k` switch. This results in several error messages every time you try to tab complete.

```
usage: /usr/bin/groff [-abceghilpstvzCENRSUVXZ] [-Fdir] [-mname] [-Tdev] [-ffam]
       [-wname] [-Wname] [-Mdir] [-dcs] [-rcn] [-nnum] [-olist] [-Parg]
       [-Larg] [-Idir] [files...]
/usr/bin/groff -h gives more help
--nc/usr/bin/groff: invalid option -- k
```

The default `groff` available is

```
$ /usr/bin/groff -v
GNU groff version 1.19.2
Copyright (C) 2004 Free Software Foundation, Inc.
GNU groff comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of groff and its subprograms
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

called subprograms:

GNU grops (groff) version 1.19.2
GNU troff (groff) version 1.19.2
```

One can install `groff` from `homebrew`, but it adds some unnecassry dependencies.

```
$ /usr/local/bin/groff -v
GNU groff version 1.22.4
Copyright (C) 2018 Free Software Foundation, Inc.
GNU groff comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of groff and its subprograms
under the terms of the GNU General Public License.
For more information about these matters, see the file
named COPYING.

called subprograms:

GNU grops (groff) version 1.22.4
GNU troff (groff) version 1.22.4
```

Quick glance [around](https://pkgs.org/search/?q=groff) suggests that really every other stable distribution already ships 1.22. So I totally understand if you just say OS X is not supported here with this feature. I would just like a better error message.

Commit https://github.com/akinomyoga/ble.sh/commit/7a4a4801749fdc3b7a8084f9871a1cbbbdcb869d#diff-c180d07f9f6314cd0ce60494fd95e4a1a3afaa2f78afd7046897c4c4e6f072d3R2571 added this feature. There is no `preconv` available in default OS X, but one can assume that the environment is regulated in such a way that the `preconv` step shouldn't be necessary.

**Comment by akinomyoga** [comment]
OK! Thank you for the report and investigations! The option `-k` or `preconv` is needed to properly show UTF-8 encoded manual pages. I'll install `groff-1.19` in my local environment and take a look at whether there is a way to handle UTF-8 with `groff-1.19`! It may take some time.

**Comment by akinomyoga** [comment]
It seems it is impossible to show UTF-8 man pages with `groff` in macOS. I decided to always use ASCII (English) man pages in macOS. But I don't have macOS so not sure what kind of `groff` macros are available in macOS. @killermoehre Can you test if the following command works without errors in macOS?

```bash
$ groff -T ascii -m man <<< 'Hello, world!' | uniq
```

**Comment by killermoehre** [comment]
@akinomyoga sure, here
```
$ /usr/bin/groff -T ascii -m man <<< 'Hello, world!' | uniq
Hello, world!

$ /usr/bin/groff -T utf8 -m man <<< 'Hello, world!' | uniq
Hello, world!

```

**Comment by akinomyoga** [comment]
Thank you! Hmm, it seems that `-T utf8` works in your environment. I actually build `groff-1.19.2` in Linux, but `-T utf8` didn't work there. Maybe there are additional packages that I need to install in order to use `-T utf8`...

Can you also test the following commands?

```bash
$ groff -T utf8 -m man <<< 'αβγ' | uniq
$ groff -T utf8 -m man <<< '\[u03B1]\[u03B2]\[u03B3]' | uniq
```

I think the Greek alphabet αβγ can be copied and pasted into the terminal if you don't have an input method for the Greek alphabet.

**Comment by killermoehre** [comment]
@akinomyoga and again
```
$ /usr/bin/groff -T utf8 -m man <<< 'αβγ' | uniq
Î±Î²Î³

$ /usr/bin/groff -T utf8 -m man <<< '\[u03B1]\[u03B2]\[u03B3]' | uniq
αβγ

```

The output is the same for either copied and pasted or directly input via the character chooser.

**Comment by akinomyoga** [comment]
OK! It seems `groff` in macOS is capable of handling `preconv`-style character names, `\[uXXXX]`. Now I think I should implement "`preconv`" by using `od` and `awk`.

**Comment by akinomyoga** [comment]
d4f816b I added a workaround for macOS in `master`. Could you test the master branch (because I don't have macOS)? It tries to detect `preconv` and a newer version of `groff` before using the fallback implementation, so if it is not so too much trouble for you, you may test `master` in macOS without newer versions of `preconv` and `groff`.

**Comment by killermoehre** [comment]
@akinomyoga Works very well. Thank you very much.

**Comment by akinomyoga** [comment]
OK! Thank you again for the report and all your help.
