### ISSUE TITLE
Is there a way to configure the colors of the autocompleted text?

### ISSUE THREAD

**Issue by r3pek** [akinomyoga/ble.sh#115]
![image](https://user-images.githubusercontent.com/3050556/119657581-0102e880-be24-11eb-8d12-6f8b016f4b78.png)

**Comment by akinomyoga** [comment]
I assume you are using the latest version in the `master` branch. The highlighting of that part, i.e., the temporary insertion by `menu-complete`, is made by the face `region_insert`. The default setting is

```bash
ble-face region_insert='fg=12,bg=252'
```

Color code can be checked by

```bash
$ ble palette
```

You may list the current face settings by

```bash
$ ble-face
```

For a detailed description of how to set up the faces, you can check [manual §2](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics).

ble-color-setface region_insert fg=XXX,bg=XXX

**Comment by r3pek** [comment]
Yeah, it was that one :) I just find it hard sometimes to really pinpoint what face matches to what so i needed to ask.

I'm not actually using the latest (master) version, but I packed the -devel2 version for Fedora because I really liked the functionality.

Now that I have colors sorted out, I gonna hit the PS1 (need to read about how to set it too because i've set prompt_rps1 to `'\q{contrib/git-info}'` but I always get this when starting a new shell: ble/propmt: undefined named sequence \q{contrib/git-info} [it still works])

**Comment by akinomyoga** [comment]
> Now that I have colors sorted out, I gonna hit the PS1 (need to read about how to set it too because i've set prompt_rps1 to `'\q{contrib/git-info}'` but I always get this when starting a new shell: `ble/propmt: undefined named sequence \q{contrib/git-info}` [it still works])

How do you load `contrib/prompt-git.bash`? You need to load `contrib/prompt-git` before the prompt is shown so the option `-d`.(delayed load) for `ble-import` cannot be used.

For example this should work

```bash
ble-import contrib/prompt-git
bleopt prompt_rps1='\q{contrib/git-info}'
```

But this would cause the error message you mentioned:

```bash
ble-import -d contrib/prompt-git
bleopt prompt_rps1='\q{contrib/git-info}'
```

**Comment by r3pek** [comment]
Yeah.... that was the problem :)

Now just need to finish a Kali style PS1 and move that rps1 to "normal" ps1.

Btw, you mention the AUR blesh package on the README, feel free to add the [Fedora](https://copr.fedorainfracloud.org/coprs/r3pek/cybersec/package/blesh/) one too if you want.

**Comment by akinomyoga** [comment]
> Btw, you mention the AUR blesh package on the README, feel free to add the [Fedora](https://copr.fedorainfracloud.org/coprs/r3pek/cybersec/package/blesh/) one too if you want.

Oh, thank you!! I'll add the link to README later!

**Comment by r3pek** [comment]
sorry for the spam but, is there an "API" to program the PS1?

in my case, I wanted to use the `\q{contrib/git-info}` stuff but within  brackets and on the "normal" (left side). I can write a function to update it, but if blesh already has one I might just use it

**Comment by akinomyoga** [comment]
> sorry for the spam but, is there an "API" to program the PS1?
> 
> in my case, I wanted to use the `\q{contrib/git-info}` stuff but within brackets and on the "normal" (left side). I can write a function to update it, but if blesh already has one I might just use it

I don't know if I understand your question, but maybe you first want to read [§4.12](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#412-prompt). If you are asking whether `\q{contrib/git-info}` can be used in `PS1`, yes. For example, you can just put the following line:

```bash
PS1='[\q{contrib/git-info}] '
```

If you are asking how to program the `\q{XXXX args...}`, as described in the manual, you can define a function `ble/prompt/backslash:XXXX` and call `ble/prompt/print <STRING>` or `ble/prompt/process-prompt-string <PROMPT_STRING>` inside the function. I think you can look into the file `contrib/prompt-git.bash` for an example implementation.

**Comment by r3pek** [comment]
> I don't know if I understand your question, but maybe you first want to read [§4.12](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#412-prompt). If you are asking whether `\q{contrib/git-info}` can be used in `PS1`, yes. For example, you can just put the following line:

That was it! :) Thx
Just another quick one. Any easy way to add an empty line between commands?
```
# command

#
```

**Comment by akinomyoga** [comment]
> Just another quick one. Any easy way to add an empty line between commands?

Usually, people put a new line (which can be specified by `\n`) in front of `PS1`

```bash
PS1='\n# '
```

**Comment by akinomyoga** [comment]
Has your problem solved? If the problem has been solved, could you close the issue? Thank you
