### ISSUE TITLE
bash: ((: ... error on starting bash in foot terminal

### ISSUE THREAD

**Issue by GorrillaRibs** [akinomyoga/ble.sh#128]
**ble version**: 0.4.0-devel3+899c114
**Bash version**: 5.1.8(1)-release (x86_64-pc-linux-gnu)

The error shows up as
```
bash: ((: 010801: value too great for base (error token is "010801")
bash: ((: 010801: value too great for base (error token is "010801")
```
when I start bash (either manually or as the default shell), but only in foot (from https://codeberg.org/dnkl/foot), doesn't happen in alacritty (the only other terminal I have installed). How would I go about debugging/fixing this?

thanks!

**Comment by akinomyoga** [comment]
Thank you! OK, dnkl/foot seems to reply its version with the format `%02u%02u%02u` for DA2:

- https://codeberg.org/dnkl/foot/src/branch/master/csi.c#L1528

In commit c6473b7, I have added fixes for CSI parameters starting with `0`. Could you check if the problem has been solved?

Also, I have added the code to identiy `dnkl/foot`. I actually haven't tested it with the actual `dnlk/foot`, but now the result of `echo $_ble_term_TERM` should become `foot` inside the terminal `dnkl/foot`. Could you also check this?

```bash
$ echo "$_ble_term_TERM"
```

**Comment by GorrillaRibs** [comment]
The initial problem is gone now! And echoing $_ble_term_TERM gets 
`foot`
which I assume is right here, but now pressing other keys (up/down/left/right) outputs `bash: 10#: invalid integer constant (error token is "10#")`
Is there anything I can do to help debug? This new error also seems to show up in alacritty, so doesn't seem to be foot specific anymore.

**Comment by akinomyoga** [comment]
Ah, OK. This is related to the behavior change in Bash 5.1. I'll later fix it! Thank you!

**Comment by GorrillaRibs** [comment]
Ah, thanks! Can confirm it works fine with bash 5.0, looks like I'll stick with that for a bit.

**Comment by akinomyoga** [comment]
I pushed a fix 2ea48d7. Thank you!

**Comment by GorrillaRibs** [comment]
It's working great, thanks a ton! I'll close the issue then, seems like everything's fixed

**Comment by akinomyoga** [comment]
OK! Thank you again for your report!
