### ISSUE TITLE
how do I disable syntax highlighting?

### ISSUE THREAD

**Issue by br4nnigan** [akinomyoga/ble.sh#134]
Couldn't figure it out from the readme or wiki. There are defaults but if at all I want to start from scratch.

**Comment by akinomyoga** [comment]
Thank you for your feedback. There was already the same question: See #61. The corresponding Wiki item is [here](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#user-content-bleopt-highlight_syntax).
