### ISSUE TITLE
Highlight command line arguments

### ISSUE THREAD

**Issue by Prikalel** [akinomyoga/ble.sh#140]
I've copyed highlight colors settings to my ~/.blerc and replaced all colors to red.
But command-line arguments for commads are with some strange color (maybe, fb=30?)
![Img](https://user-images.githubusercontent.com/67920266/135852735-e4aa5af7-9f1e-4f05-8f25-65d11a745434.png)
Actually I want to specify, which color to use, but I don't know the parameter that can configurate this.

**Comment by akinomyoga** [comment]
Oh, actually the list of faces in `blerc` is not complete. The face that can be used to configure the option name is `argument_option`. To change it to `fg=red`, please use the following setting:

```bash
ble-face argument_option='fg=red'
```

**Comment by akinomyoga** [comment]
I'll later add missing faces to `blerc` and `wiki`. Currently `argument_option` and `cmdinfo_cd_cdpath` are missing in `blerc` and `wiki`.

**Comment by Prikalel** [comment]
Thank you for the answer so soon!

**Comment by akinomyoga** [comment]
OK! Thank you for your feedback!

**Comment by akinomyoga** [comment]
> I'll later add missing faces to `blerc` and wiki. Currently `argument_option` and `cmdinfo_cd_cdpath` are missing in `blerc` and wiki.

FYI, I have now added these faces in `blerc` and wiki. Thank you.
