### ISSUE TITLE
backspace key does not work in shell terminal within vim 

### ISSUE THREAD

**Issue by laoshaw** [akinomyoga/ble.sh#146]
**ble version**: 0.4.0-devel3+0525528

**Bash version**: 
5.0.17(1)-release (x86_64-pc-linux-gnu)

inside vim, hit :term to open a terminal, type something on the command line, then use backspace to delete them backwards, nothing will be deleted and backward key does not move cursors, it does not work. disable ble.sh, it works as expected

**Comment by akinomyoga** [comment]
Thank you for the report! I confirmed the problem. I tried to figure it out couldn't yet find what is happening. At leasst, it seems Bash receives NUL instead of DEL for the user input <kbd>BackSpace</kbd> when `ble.sh` is loaded. I am recently a bit busy, so later I'll look at it in detail.

**Comment by akinomyoga** [comment]
Sorry for the delay. I have fit it in commit 82f74f0. @laoshaw Could you check if the problem has been solved in the latest version (by updating ble.sh using `ble-update`)?

**Comment by laoshaw** [comment]
Did some tests and it seems issue fixed. Thanks!!

**Comment by akinomyoga** [comment]
OK. Thank you again!
