### ISSUE TITLE
[libvirt] Bash syntax error

### ISSUE THREAD

**Issue by telometto** [akinomyoga/ble.sh#147]
**ble version**: 0.4.0-devel3+2243e91
**Bash version**: 5.1.8(1)-release (x86_64-redhat-linux-gnu)

I'm experiencing a weird bug when I try to autocomplete the `virsh` command (so far, this is the only one I've found this happens with): basically, `bash` tells me there's a syntax error, as you can see from the screenshot below.
![scrot_edit](https://user-images.githubusercontent.com/65364211/140650732-8ee5cbbe-fcaf-4623-acf3-cf726103395f.png)

I am 100% sure that it's an issue with ble, since commenting out (i.e. disabling) the `source` at the end of my `.bashrc` does not reproduce the error.

Thanks~

**Comment by akinomyoga** [comment]
Sorry for the late reply. I'm sorry but now am extremely busy. I hope I can respond in detail this weekend.

At the moment, the problem is not observed in my environment.

- **Q1** Could you check if the problem reproduces with only the plain Bash plus `ble.sh` without any user other configuration? This is important to narrow down the condition that the problem arises. Thank you.

**Comment by telometto** [comment]
> Sorry for the late reply. I'm sorry but now am extremely busy. I hope I can respond in detail this weekend.

Don't worry, I have plenty of time ^_^ Besides, I'm only experiencing the issue when I try to autocomplete `virsh` commands.

> * **Q1** Could you check if the problem reproduces with only the plain Bash plus `ble.sh` without any user other configuration? This is important to narrow down the condition that the problem arises. Thank you.

I have tested it out on the default `.bashrc` and can confirm that the issue still happens. I'm using Fedora 35 and I didn't have this issue on F34, so I'm starting to suspect that it might be a conflict between some system configuration file and ble.

**Comment by akinomyoga** [comment]
I confirmed it in fc35. This is a bug of the bash-completion script for virsh (libvirt-client), `/usr/share/bash-completion/completions/virsh`, contained in the package [`libvirt-client-7.6.0-3.fc35.x86_64`](https://fedora.pkgs.org/35/fedora-updates-testing-x86_64/libvirt-client-7.6.0-3.fc35.x86_64.rpm.html).

### Description

The script overwrites the `IFS` environment variable on query for completions. You can confirm the problem without ble.sh by the following commands:

```console
# Start a session without ble.sh

$ declare -p IFS | cat -A
declare -- IFS=" ^I$
"$
$ virsh a[TAB][TAB]
allocpages    attach-device    attach-disk    attach-interface    autostart
$ virsh a[C-c]
$ declare -p IFS | cat -A
declare -- IFS="$
"$
```
Originally the value of IFS is `IFS=$' \t\n'`, but it becomes `IFS=$'\n'` after the trial of the completion. After this, word splitting will not be processed as normal:

```console
$ a='a b c'
$ printf '<%s>\n' $a
<a>
<b>
<c>
$ virsh a[TAB][TAB][C-c]
$ printf '<%s>\n' $a
<a b c>
```

The shell variable `word` is also affected by the virsh completion.

### Fix

The completion function `_virsh_complete` should declare `IFS` and `word` as local before changing them.

```diff
diff --git a/tools/bash-completion/vsh.in b/tools/bash-completion/vsh.in
index 70ade50a02..4399ff0a64 100644
--- a/tools/bash-completion/vsh.in
+++ b/tools/bash-completion/vsh.in
@@ -4,7 +4,7 @@

 _@command@_complete()
 {
-    local words cword c=0 i=0 cur RO URI CMDLINE INPUT A
+    local words cword c=0 i=0 cur word RO URI CMDLINE INPUT A

     # Here, $COMP_WORDS is an array of words on the bash
     # command line that user wants to complete. However, when
@@ -56,7 +56,8 @@ _@command@_complete()
     # the name of the command whose arguments are being
     # completed.
     # Therefore, we might just run $1.
-    IFS=$'\n' A=($($1 ${CMDLINE[@]} complete -- "${INPUT[@]}" 2>/dev/null))
+    local IFS=$'\n'
+    A=($($1 ${CMDLINE[@]} complete -- "${INPUT[@]}" 2>/dev/null))

     COMPREPLY=($(compgen -W "${A[*]%--}" -- ${cur}))
     __ltrim_colon_completions "$cur"
--
2.21.3
```

### Report

- The upstream source of the script is found at [`tools/bash-completion/vsh.in` · master · libvirt / libvirt · GitLab](https://gitlab.com/libvirt/libvirt/-/blob/master/tools/bash-completion/vsh.in).
- This is the development mailing list where we can post patches: libvir-list@redhat.com ([archive](https://listman.redhat.com/archives/libvir-list/))
- I have sent a patch now.

I think I'll later add a workaround for this completion script at the `ble.sh` side.

**Comment by telometto** [comment]
Ah, so it's as I suspected. If you already have sent a patch to the maintainers, then I won't submit a bug report.
I'll just wait for when this gets gets patched upstream, as it's not of vital importance to me.

Thank you for your help ^_^

**Comment by akinomyoga** [comment]
The patch has been accepted in the upstream: [`libvirt/libvirt` @097296c3](https://gitlab.com/libvirt/libvirt/-/commit/097296c30b72f472bcf4e72cf8ab2aeb55903c49).

I think it would take some time for the patch to be applied to the distributed versions, so I added a workaround for this problem to `ble.sh` in commit f985b9a.

Thank you for reporting the issue!
