### ISSUE TITLE
Autocompletion switches have weird escapes

### ISSUE THREAD

**Issue by eadmaster** [akinomyoga/ble.sh#149]
**ble version**: ble-0.4.0-devel2 (from the release page)
**Bash version**: 5.1.4(1)-release

![Screenshot_20211112_042214](https://user-images.githubusercontent.com/925171/141403664-88c02832-0aaf-40f5-bf1f-9ac5b77d0c39.png)

**Comment by akinomyoga** [comment]
Thank you for the report. This was fixed in b5c875a. Can you try using the latest version?

**Comment by eadmaster** [comment]
ok, it's fixed
