### ISSUE TITLE
入れ子になったbashの子シェルからexitした際に大量のログが出る

### ISSUE THREAD

**Issue by Kiikurage** [akinomyoga/ble.sh#15]
ble.sh環境下で `bash` を更に立ち上げexitした際に、以下のように大量のログが出ます

```sh
[1]    Running                 '/bin/stty' "$@"
[2]   Stopped                 '/bin/stty' "$@"
[3]   Stopped                 '/bin/stty' "$@"
(以下、無限に続く）
```

`ble.sh` は `.bashrc` 内で読み込んでおり、入れ子になったシェルの両方にロードされています。

**Comment by akinomyoga** [comment]
ご報告ありがとうございます! こちらでいろいろ試したところ Bash 3.2 で C-d で抜けようとした時に類似の現象が再現するようでした。調べてみます。

**Comment by Kiikurage** [comment]
丁寧に対応していただきありがとうございます。
急ぎではないので、他のissueを優先していただいて構いません。

bashのバージョンですが、今すぐの確認ができないので、今晩、報告させていただきます

2018年10月9日(火) 9:21 Koichi Murase <notifications@github.com>:

**Comment by Kiikurage** [comment]
バージョンを確認しました
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
```
です

**Comment by Kiikurage** [comment]
また、bashのバージョンを上げたところとりあえず問題は発生しなくなりました。

**Comment by akinomyoga** [comment]
確かめていただきありがとうございます! ということはこちらで再現しているのと同じ問題ですね。わざわざ新しい Bash まで試していただいてありがとうございます (実の所、Bash 3.0 は機能が少ないので `ble.sh` は結構無理をした実装になっており動作が遅いのです。従って本当は Bash 4.0 以降が推奨なのでした)。

この問題に関しては #16 が終わってから Bash の動作を調べて対策いたしますね。

**Comment by Kiikurage** [comment]
ご対応くださりありがとうございます。
`d4b39b3` をビルドして使ってみたところ、`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)` で問題が発生しなくなっていることを確認しました。
ありがとうございます。

**Comment by akinomyoga** [comment]
早速ご確認いただきありがとうございます! こちらの Issue は閉じさせていただきますね
