### ISSUE TITLE
[Bash 5.0] Wrong commands mandate shell exit on C-j

### ISSUE THREAD

**Issue by EmilySeville7cfg** [akinomyoga/ble.sh#153]
**ble version**: 0.4.0-devel3+82f74f0
**Bash version**: 5.0.17(1)-release (x86_64-pc-linux-gnu)
**Terminal version**: GNOME Terminal 3.36.2
**OS version**: Linux Mint 20.2 Cinnamon

# Actual behaviour

If I run wrong command via `C-j` bash will exit by default:

![image](https://user-images.githubusercontent.com/42812113/144403582-1cff0bc5-9742-4fcd-a6b9-a35e381c2409.png)

# Expected behaviour

Only error is printed and no bash exit performed.

**Comment by akinomyoga** [comment]
Thank you for the report! But this is actually a bug of Bash-5.0. Last year, I have reported it and sent a related patch to Bash at https://lists.gnu.org/archive/html/bug-bash/2020-08/msg00152.html. It is fixed in Bash 5.1. Could you update your Bash?

**Comment by akinomyoga** [comment]
@EmilySeville7cfg Do you have a plan of closing this issue after you check the behavior with Bash 5.1? If not, you can immediately close the issue. It works as expected in Bash 5.1 at least in my environment.

**Comment by EmilySeville7cfg** [comment]
Sorry but now I can't check it with Bash 5.1 so I am going to close this issue.

**Comment by EmilySeville7cfg** [comment]
I've installed Bash 5.1. Tomorrow I'll check this issue again.

**Comment by akinomyoga** [comment]
Thanks!

**Comment by EmilySeville7cfg** [comment]
It works correctly. ;)
