### ISSUE TITLE
Not all commands support hints for tab completion

### ISSUE THREAD

**Issue by EmilySeville7cfg** [akinomyoga/ble.sh#155]
**ble version**: 0.4.0-devel3+82f74f0
**Bash version**: 5.0.17(1)-release (x86_64-pc-linux-gnu)
**Terminal version**: GNOME Terminal 3.36.2
**OS version**: Linux Mint 20.2 Cinnamon

When I type `echo -` and press `Tab` I see:

![image](https://user-images.githubusercontent.com/42812113/144423672-2fbf268c-0ba2-45d3-8291-ded091531e84.png)

But when I do the same for declare for instance nothing is suggested:

![image](https://user-images.githubusercontent.com/42812113/144423756-d0567f92-393e-41be-afd8-6e608227d0e3.png)

How can I fix it?

**Comment by akinomyoga** [comment]
It's just because it is not supported. Later, I'll look at it. #152 is also closely related.

**Comment by EmilySeville7cfg** [comment]
I will wait. ;) Tab completion is on of my favorite shell features.

**Comment by EmilySeville7cfg** [comment]
It's just for remember what options need to be supported (I will change this table in the future):

| Command      | Missing options in complete |
| ------------ | --------------------------- |
| printf       | `-v`                        |

**Comment by akinomyoga** [comment]
- `declare`: This is subtle because the Readline interface of progcomp is incomplete, i.e., it cannot handle array initialization syntax of `arr=(...)` in the arguments of `declare`. For example, Readline/Bash doesn't work with `declare -a arr=(1 2 3) a[TAB]`. I'm rather thinking that ble.sh should provide a proper support for this rather than making it programmable by users.
- `printf`: I believe we should first consider supporting `printf -v` in `bash-completion`.

**Comment by akinomyoga** [comment]
- I've supported the extraction of option information from the result of `$command --help` in commit e1ad2f1. Now the option `-v` for `printf` is also generated as a completion.
- I've supported the options and descriptions for `declare`, `typeset`, `local`, `export`, and `readonly` in commit da38404.

**Comment by akinomyoga** [comment]
@EmilySeville7cfg What is the goal of this issue? If you literally require support for literally **all** the commands, it is impossible to achieve because there are countless commands.

**Comment by EmilySeville7cfg** [comment]
I guess then it's better to close issue. 😁

**Comment by akinomyoga** [comment]
Thanks!
