### ISSUE TITLE
Better support for test, [ commands

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [akinomyoga/ble.sh#158]
**ble version**: 0.4.0-devel3+82f74f0
**Bash version**: 5.0.17(1)-release (x86_64-pc-linux-gnu)
**Terminal version**: GNOME Terminal 3.36.2
**OS version**: Linux Mint 20.2 Cinnamon

Options for comparing two numbers and strings are missing:

![image](https://user-images.githubusercontent.com/42812113/144427527-e5fe5e31-7000-42f8-a91f-891fe01c498a.png)

**Comment by akinomyoga** [comment]
Actually, these descriptions are automatically generated from the result of `man test` using a certain heuristic approach that can be applied to generic commands. It seems in GNU/Linux, `man test` enumerates the comparison operators in the form of `INTEGER -eq INTEGER`, which is not a common notation in `man test`.

To improve the completion for each command, specialized completion functions are supposed to be defined by users (or in [contrib](https://github.com/akinomyoga/blesh-contrib) repository). Ble.sh provides the interface of defining user-defined completion settings for ble.sh, but sorry, I haven't yet prepared the help page for that. Also, that interface is not well tested for the real cases as I'm somehow satisfied with the bash-completion (which unfortunately doesn't provide the description for each completion).

**Comment by akinomyoga** [comment]
- `test`, `[`: I think better support for `test` and `[` should also be implemented in `bash-completion`.

**Comment by akinomyoga** [comment]
- In commit da38404, I've added the options of `test` and `[` that cannot be extracted from the man page/help in a generic way: `-eq`, `-ne`, `-lt`, `-le`, `-gt`, `-ge`, `-nt`, `-ot`, `-ef`, `-a`, and `-o`.

**Comment by EmilyGraceSeville7cf** [comment]
Are there any updates to this issue? 🌝

**Comment by akinomyoga** [comment]
Thanks. My previous comment (https://github.com/akinomyoga/ble.sh/issues/158#issuecomment-991794886) is the last update. I currently do not see any issue about this topic, so there is no change after that. Could you clarify what would be the remaining issue that should be updated?

**Comment by EmilyGraceSeville7cf** [comment]
Then I guess I can close this issue. Thanks for responding. :)

**Comment by akinomyoga** [comment]
Thanks!
