### ISSUE TITLE
[bash-completion] Error when using tab-completion for man command

### ISSUE THREAD

**Issue by EmilySeville7cfg** [akinomyoga/ble.sh#159]
**ble version**: 0.4.0-devel3+82f74f0
**Bash version**: 5.0.17(1)-release (x86_64-pc-linux-gnu)
**Terminal version**: GNOME Terminal 3.36.2
**OS version**: Linux Mint 20.2 Cinnamon

![image](https://user-images.githubusercontent.com/42812113/144429612-254df749-68c2-4f65-acbb-3c3d94ebb8d1.png)

**Comment by akinomyoga** [comment]
This is a bug of `bash-completion`. It was fixed in https://github.com/scop/bash-completion/pull/600. Please use the latest version (`master` branch) of [bash-completion](https://github.com/scop/bash-completion).
