### ISSUE TITLE
[gawk 4.0] Older gawk version throws a warning sometimes

### ISSUE THREAD

**Issue by Knusper** [akinomyoga/ble.sh#161]
I sometimes get the following warning when typing with ble.sh

 `commandline:74 - gawk: warning: regexp component [:space:]' should probably be[[:space:]]'`

(note: the commandline bit I translated, because the warning is shown in german - but the gawk warning in english is like that.

This happens on a system where there is GNU Awk 4.0.2 - on my other machine I have GNU Awk 4.2.1 and don't have any problems.
Any idea what could be the issue?

**Comment by akinomyoga** [comment]
Oh, thank you for the report! This must be a bug of ble.sh. I'll later look at it.

**Comment by akinomyoga** [comment]
May I ask which version of ble.sh you use?

Also, what is the result of the following command in the system with GNU Awk 4.0.2?

```bash
$ type ble/bin/awk
```

**Comment by akinomyoga** [comment]
Ah, OK. I have identified it. It's not the bug of ble.sh but is a bug of gawk.

```console
[murase@chatoyancy 0 ble.sh]$ gawk-3.0.6 '/[][:space:]]/' <<< [hello]
[hello]
[murase@chatoyancy 0 ble.sh]$ gawk-3.1.8 '/[][:space:]]/' <<< [hello]
[hello]
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/[][:space:]]/' <<< [hello]
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
[hello]
[murase@chatoyancy 0 ble.sh]$ gawk-4.1.4 '/[][:space:]]/' <<< [hello]
[hello]
[murase@chatoyancy 0 ble.sh]$ gawk-4.2.0 '/[][:space:]]/' <<< [hello]
[hello]
[murase@chatoyancy 0 ble.sh]$ gawk-5.0.1 '/[][:space:]]/' <<< [hello]
[hello]
```

Although it produces the warning messages, it seems like working as expected:

```console
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/^[][:space:]]$/' <<< 's'
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/^[][:space:]]$/' <<< ']'
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
]
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/^[][:space:]]$/' <<< ' '
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
 
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/^[][:space:]]$/' <<< ':'
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/^[][:space:]]$/' <<< 's'
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/^[][:space:]]$/' <<< 'p'
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/^[][:space:]]$/' <<< 'a'
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/^[][:space:]]$/' <<< 'c'
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
[murase@chatoyancy 0 ble.sh]$ gawk-4.0.2 '/^[][:space:]]$/' <<< 'e'
gawk-4.0.2: cmd. line:1: warning: regexp component `[:space:]' should probably be `[[:space:]]'
```

This gawk bug actually affects a wide range of codes. I'm not sure if I should change the regular expression to a slower one just to work around the bug in the specific version of gawk. Maybe I will just suppress the warning message from gawk 4.0.2.

**Comment by Knusper** [comment]
Thanks for looking deeper into this.
FYI. The 4.0.2 version of `gawk` ships  with RedHat Enterprise Linux 7.9 and CentOS 7.9.2009 - i.e. not bleeding edge, but something that is being deployed on many computing servers.

**Comment by akinomyoga** [comment]
Thank you! I added a workaround 9771693 in `master` branch. Could you try updating ble.sh by `ble-update` and using it for a while to check whether the warning messages do not appear anymore?

**Comment by Knusper** [comment]
Yes - the error has disappeared.

**Comment by akinomyoga** [comment]
Thank you!
