### ISSUE TITLE
When FIGNORE is set, completions are empty

### ISSUE THREAD

**Issue by seanfarley** [akinomyoga/ble.sh#162]
**ble version**: ble.sh, version 0.4.0-devel3+9771693 (noarch)
**Bash version**: GNU bash, version 5.1.12(1)-release (x86_64-apple-darwin20.6.0)

When the variable FIGNORE is set, it seems that regular bash completions are empty. For example,

```bash
# Have bash ignore the .DS_Store
export FIGNORE=DS_Store
```

Then load `ble.sh` and type `git s<TAB>` and nothing is completed.

**Comment by akinomyoga** [comment]
Thank you for the report and also for narrowing down the causes to `FIGNORE`! I have fixed it in commit 144ea5d. It was a very simple mistake. Could you check if the problem has been fixed in `master` branch? You can update ble.sh by `ble-update` command.l

**Comment by seanfarley** [comment]
Yep, seems to work! Thanks for such a quick fix!

**Comment by akinomyoga** [comment]
OK! Thank you for checking!
