### ISSUE TITLE
menu-complete takes ~15secs on directory with 6000+ files.

### ISSUE THREAD

**Issue by banoris** [akinomyoga/ble.sh#164]
**ble version**: 0.4.0-devel3+a6b4e2c
**Bash version**: 4.2.46(2)-release
**Operating system**: `lsb_release -a` -- Red Hat Enterprise Linux 7.9

NOTE: Duplicate from <https://github.com/banoris/dotfiles/issues/11>.

In vanilla bash, it will warn user if many files, but still able to display all 6000+ files almost instantaneously:
```text
$ vim somedir/
There are 3038 rows, list them anyway? [n/y]
```

With ble.sh. it takes around 15secs to display the files in menu-complete.

**Comment by banoris** [comment]
**Analysis from @akinomyoga**:

I have investigated the bottleneck in the directory with many files. It turned out that there are several reasons that make the menu completion slow. The fixes and workarounds for some bottlenecks are in the mater branch of `ble.sh`, so you can update `ble.sh` by `ble-update`. The workarounds for the other bottlenecks need some user configuration as described below.

## 1. Delayed initialization for menu items did not work (~ 8 secs)[Fixed]

I have fixed it in commit https://github.com/akinomyoga/ble.sh/commit/acc96610912e8524ec855fe4ba8e0090a5c03ff0. `ble.sh` calculates the sizes of menu items in the terminal to determine the layout of the items. I intended to calculate the sizes of only the necessary items for the first page of the menu, but `ble.sh` actually had been calculating the sizes of all the items due to the bug in an expression to calculate some position. The fix reduces the time to about 1--3 seconds.

## 2. Old `_filedir` from `/etc/bash_completion.d/redefine_filedir` (~ 4 secs)

There is a shell function `_filedir` defined by `bash-completion`. It turned out that the implementation of `_filedir` in a certain version of `bash-completion` was very slow. I am using the latest version of `bash-completion`, but somehow the latest version of `_filedir` is overwritten by an older version defined in `/etc/bash_completion.d/redefine_filedir` by Fedora 31 distribution. This caused the second bottleneck in my environment.

I'm not sure if the same happens in your environment, but if you find the following lines in your `bash-completion` (probably `/usr/share/bash-completion/bash_completion` if you are using `bash-completion` from the RHEL distribution), you can instead download and use [the latest version of `bash-completion`](https://github.com/scop/bash-completion):

```bash
_filedir()
{

...

    x=$( compgen -d -- "$cur" ) &&
    while read -r tmp; do
        toks+=( "$tmp" )
    done <<< "$x"

...
} # _filedir()
```

-----\[ **Edit**: I have suggested the following change in the upstream https://github.com/scop/bash-completion/pull/667 \]-----

In addition, if `/usr/share/bash-completion/bash_completion` contains the above lines and there is also a file `/etc/bash_completion.d/redefine_filedir` from the RHEL distribution, you need to disable the setting somehow. I don't know what is the most proper way to disable this, but probably you need to edit your own `bash_completion` in the following way:

```diff
diff --git a/bash_completion b/bash_completion
index 697e7e2b..733c16a2 100644
--- a/bash_completion
+++ b/bash_completion
@@ -39,7 +39,7 @@ fi

 # Blacklisted completions, causing problems with our code.
 #
-_comp_init_blacklist_glob='@(acroread.sh)'
+_comp_init_blacklist_glob='@(acroread.sh|redefine_filedir)'

 # Turn on extended globbing and programmable completion
 shopt -s extglob progcomp
```

I think I'll later open a discussion in `bash-completion` about this issue.

## 3. Quoting the completion candidates depending on the grammatical context (~ 2 secs) [Optimized]

The third bottleneck was the calculation of the quoting of the completion candidates. For example, if the candidate contains special characters such as `(`, `$`, etc., they need to be quoted in the inserted text as `\(`, `\$`, etc. Since `ble.sh` needs to obtain the common prefix of the inserted texts of candidates, it needs to calculate the quoting of all the candidates. This quoting for 10k files took about two seconds in my environment.

In commit https://github.com/akinomyoga/ble.sh/commit/a0b2ad2a313e6f96e7c317f53aa81eab23d0635a, I have re-implemented the quoting in `awk` (which is faster than Bash implementation). Now `ble.sh` switches to the `awk` implementation when the number of candidates is greater or equal to 500.

## 4. Layout and displaying of menu items (~ 3 secs)

After solving all the bottlenecks above, it still takes about four seconds until the menu is shown when I use the full screen (see below).

<img width="80%" src="https://user-images.githubusercontent.com/8982192/146669122-d645bc2d-52fd-46a9-adc2-5e2967c27720.png" />

If we want to show this many items on one page, the three-second delay is inevitable (as far as it is written in slow Bash script). If you would like to reduce this delay, you can decrease the number of items shown on a single page using the settings [`bleopt complete_menu_maxlines`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-bleopt-complete_menu_maxlines) and [`bleopt menu_align_min`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-bleopt-menu_align_min) (I have added this new option `menu_align_min` in commit https://github.com/akinomyoga/ble.sh/commit/22a2449d9886fa7cf17bc8445577429af0546f20):

```bash
# blerc

# Example
bleopt complete_menu_maxlines=10
bleopt menu_align_min=12
```

The setting `complete_menu_maxlines` controls the maximal number of lines used by the menu page. The setting `menu_align_min` controls the minimal horizontal spacing between the menu items. After this setting, the number of items on a single page reduces as in the following example, so that the delay would be shorter.

<img width="80%" src="https://user-images.githubusercontent.com/8982192/146669403-e0d98494-2651-4bea-944a-1c9e4642d1fa.png" />

**Comment by akinomyoga** [comment]
@banoris Thank you! Is the delay resolved in your environment? Are there still remaining issues related to this?

**Comment by banoris** [comment]
Yes, now takes <3secs.

Curious about below settings. I tried it and didn't notice much different. Perhaps reduced by ~0.3secs or so. Is that the case for your machine as well?
```text
# Example
bleopt complete_menu_maxlines=10
bleopt menu_align_min=12
```

**Comment by akinomyoga** [comment]
> Curious about below settings. I tried it and didn't notice much different. Perhaps reduced by ~0.3secs or so. Is that the case for your machine as well?

It actually depends on the original terminal size. The time without the settings can be already sufficiently fast if the terminal is small enough. In that case, I think we cannot expect much speedup by the above settings. If the terminal size is very large, the time should reduce much.

It also depends on the command that we try to complete the arguments for. For example, the arguments of `echo` include options with descriptions which are also shown on the screen, so that the number of candidates shown per page is already small without the above settings of `complete_menu_maxlines` and `menu_align_min`. On the other hand, the arguments for `cat` don't include 
the options so that many completion candidates can be shown in the page without the settings.

I have again measured the total time in the case of the above pictures, and then the time has been reduced by 1.97 secs or 27% (from 7.257 secs to 5.289 secs). Hmm, it actually still takes 5 secs in my environment. Do you think this is still a problem?

**Comment by banoris** [comment]
> It actually depends on the original terminal size. 

Ahah, I missed this -- that's why I didn't see much difference.

~2.5secs for 6000+ files is good for me. Will close this.

**Comment by akinomyoga** [comment]
OK! Thank you for all your help! Maybe later I'll again check if further improvements are possible.
