### ISSUE TITLE
Bug when autocompleting non-installed programs

### ISSUE THREAD

**Issue by telometto** [akinomyoga/ble.sh#167]
**ble version**: 0.4.0-devel3+3e136a6
**Bash version**: 5.1.8(1)
**OS and version**: Fedora 35

Sorry to be a pain in the ass, but I've encountered another issue: writing `hdparm`, and hitting `TAB` in the terminal of Fedora 35 when said program is not installed will result in the error (?) shown in the picture below.

![scr](https://user-images.githubusercontent.com/65364211/148655108-6de79ec5-7352-445d-81d7-4b99f23c47b4.png)

**Comment by akinomyoga** [comment]
Thank you for the report! I have pushed a fix 8039b77 in the `master` branch. Could you check it?

> Sorry to be a pain in the ass,

Not at all! These are very helpful. You find other strange behaviors, please feel free to report them!

**Comment by telometto** [comment]
Can confirm that the update fixes the issue. Again, many thanks ^_^

**Comment by akinomyoga** [comment]
OK! Thanks.
