### ISSUE TITLE
Intermittent issue - double carriage return when using starship prompt

### ISSUE THREAD

**Issue by returntrip** [akinomyoga/ble.sh#168]
GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)
ble.sh, version 0.4.0-devel3+d8e6ea7 (noarch)

This is a really difficult problem to nail down.

For my prompt am using starship and for some reason when i switch workspace (am using sway), I see the
prompt moving down the equivalent of two carriage returns, like so:

```
~
❯     #This is the first prompt

~
❯     #This prompt and the one below are showing when i switch back and forth between workspaces in sway

~
❯   
```

If I stop using starship (removing it from my .bashrc), this issue disappears.

Am not sure if this is a ble.sh problem or a starship one.

**Comment by akinomyoga** [comment]
Thank you for the report.

> when i switch workspace (am using sway)

I actually don't know about Sway and workspaces. Could you describe what is the "workspace" and what they do on switching workspaces? How that would affect the terminal environments?

> If I stop using starship (removing it from my .bashrc), this issue disappears.
> 
> Am not sure if this is a ble.sh problem or a starship one.

Do you mean that the problem only arises when both `ble.sh` and `starship` are enabled?

If it is related to the terminal size change, maybe you could try [`bleopt canvas_winch_action=redraw-prev`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#user-content-bleopt-canvas_winch_action) or other values of that setting to see if the problem still persists.

**Comment by returntrip** [comment]
Thanks or the quick reply!

Sway workspaces are similar to Gnome workspaces, it is like a virtual desktop. You can switch between workspaces and could have a workspace with Firefox and a Terminal window, a workspace with Chromium and Openoffice Sheets and so on.

That is correct, the issue happens only when both are running/enables at the same time.

Setting `bleopt canvas_winch_action=redraw-prev` seems to sort this annoyance. Thanks!

Should i close this or you wish me to provide more info?

**Comment by akinomyoga** [comment]
> Setting `bleopt canvas_winch_action=redraw-prev` seems to sort this annoyance. Thanks!
> 
> Should I close this or you wish me to provide more info?

OK, I think my guess was correct, so you can close the issue now. I think the terminal window size is changed when it goes to the background workspace. If you have faced the same problem later even with `canvas_winch_action=redraw-prev`, you can reopen the issue at that time. Thank you.
