### ISSUE TITLE
[構文強調] コマンドの直前に後からコメント開始文字を挿入しても着色が適切に変化しない

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#17]
Commit ID: b7291a7
Version of GNU Bash: 4.4.12

コマンドとなる文字列（ble-color-setfaceにおいてcommand_*で着色設定されうる文字列）の直前に，コマンドとなる文字列を入力し終わった状態でコメント開始文字（`#`）を入力すると，本来はそれ以降がble-color-setfaceにおいてsyntax_commandで着色される筈ですが，されません。

```console
$ echo 'foo'@
# 先頭に`#`を挿入
$ #echo 'foo'
   ^^^^
```
波下線部が，元の着色のままになります。
* `'foo'`などの引数部分は正常に着色がコメントを表わすものに変化します
* コマンドラインの直前だけではなくコマンドの直前でこの挙動をします
```console
$ echo 'foo' | cat@
# `cat`の直前に`#`を挿入
$ echo 'foo' | #cat
                ^^^
```
波下線部が元の着色のままです。

**Comment by akinomyoga** [comment]
- 641583f これは直しました (犯人は 854c3b4 でした。単語着色・脱色に使う関数の仕様を厳密にしたら、適当に呼び出していた所が動かなくなったのでした)

**Comment by cmplstofB** [comment]
確認いたしました。対応ありがとうございます。
