### ISSUE TITLE
Newline character inserted when copying long commands

### ISSUE THREAD

**Issue by banoris** [akinomyoga/ble.sh#170]
**ble version**: GNU bash, version 4.2.46(2)-release (x86_64)
**Bash version**: ble.sh, version 0.4.0-devel3+d8e6ea7 (noarch)

Suppose we have the following long commands, where the terminal wraps it to multiline (see snapshot):
```bash
make -C $PROJ_ROOT/some/long/path1/ clean && make -C $PROJ_ROOT/some/long/path2/ build && make -C $PROJ_ROOT/some/long/path2/ build
```
![image](https://user-images.githubusercontent.com/3672634/150650767-33ce08de-703f-4191-9540-97325b889329.png)

Then, let's say I want to rerun the same command in another terminal. I would copy it using mouse highlight, and paste it to other terminal. It failed to run since the wrapped lines contain newline:
```bash
make -C $PROJ_ROOT/some/long/path1/ clean && make -C $PROJ_ROOT/some/long/path2/ build && make -C
 $PROJ_ROOT/some/long/path2/ build

# ... some output ...

# make : option requires an argument -- 'C'
```

Notice the last `make` command where the argument for `-C` appears on the next line, causing error.

Edit: added snapshot and more clarifications.

**Comment by akinomyoga** [comment]
Thank you for the report! I have fixed it in commits 02b9da6 and dc3827b. @banoris Could you check the behavior by updating ble.sh using `ble-update`?

Note: Actually, the text representation on the display is not ensured to be the same as its actual contents. For example, ESC in the command line is represented as `^[` in the display. In this case, if one simply copies the text displayed in the terminal, ESC is not correctly preserved. This also applies to TAB characters which are represented by a certain number of spaces (depending on the tabstop boundaries).

But in most cases, we don't have these special characters in the command line so it is fair that we expect preserving the newline state (i.e. there is no real newline there) on the line folding. Nevertheless, there are actually still corner cases that the real newlines are inserted. I have added another workaround for such a case, but I'm not sure if it always works correctly. Anyway, now it seems to work as expected in most cases. Thank you.

**Comment by banoris** [comment]
It seems to break my environment, not sure why. I thought it's because of my PS1 setting, but it doesn't seem since I can reproduce it on basic bashrc.

I tried the default ubuntu bashrc [here](https://gist.githubusercontent.com/marioBonales/1637696/raw/93a33aa5f1893f46773483250214f8b8b496a270/.bashrc), run `source ble.sh/out/ble.sh`. and got the error below:
```text
bash: unexpected EOF while looking for matching `"'
bash: syntax error: unexpected end of file
bash: unexpected EOF while looking for matching `"'
bash: syntax error: unexpected end of file
```

I'm curious if you didn't face above error? Perhaps something wrong in my environment, I'll check further and update later.

**Comment by akinomyoga** [comment]
Thank you for the feedback. Hmm, I don't face the error. I have also tried the update from d8e6ea7 to the latest version, and there are no errors. I'm not sure what happened in your environment, but maybe you can try regenerating ble.sh by

```bash
$ cd /path/to/your/blesh-repository/ble.sh
$ make clean
$ make all
```

**Comment by banoris** [comment]
OK, I tried on another machine, and it works fine -- no more newline.

Probably environment issue on the other machine.

Anyway, appreciate the help, thanks! I'll close this.

**Comment by akinomyoga** [comment]
Thank you for the information! I have also tried updating in Ubuntu but couldn't reproduce the problem. If you can consistently reproduce the problem in your machine that you first tried and cannot fix the error, please feel free to reopen the issue. Anyway, thank you for your report!

**Comment by akinomyoga** [comment]
> I tried the default ubuntu bashrc [here](https://gist.githubusercontent.com/marioBonales/1637696/raw/93a33aa5f1893f46773483250214f8b8b496a270/.bashrc), run `source ble.sh/out/ble.sh`. and got the error below:
> 
> ```
> bash: unexpected EOF while looking for matching `"'
> bash: syntax error: unexpected end of file
> bash: unexpected EOF while looking for matching `"'
> bash: syntax error: unexpected end of file
> ```
> 
> I'm curious if you didn't face above error? Perhaps something wrong in my environment, I'll check further and update later.

I could reproduce the issue with Bash 4.2. I have fixed it in the latest push a75bb25. This was a regression introduced by 4590997, and `ble.sh` run in Bash 3.0..4.2 are affected. Thank you for the information!

**Comment by banoris** [comment]
Thanks! Now it makes sense. The other machine that worked fine is using bash 4.4, while the broken one is 4.2. I didn't realize that. Works fine now for both.

Now that you mention it, it's probably time for me to use the newer bash :D

**Comment by akinomyoga** [comment]
Great. Thank you for checking the fix!
