### ISSUE TITLE
Breaks nixpkgs sqlite3 repl

### ISSUE THREAD

**Issue by SuperSandro2000** [akinomyoga/ble.sh#172]
**ble version**: 0.4.0-devel3+7d05a28
**Bash version**: 5.1.8(1)-release (x86_64-pc-linux-gnu)

When I open an sqlite3 repl and try to press backspace I get the previous character with a backwards slash, instead that the character disappears. When I unload with ble-detach deleting characters works again.

![image](https://user-images.githubusercontent.com/7258858/151776000-f598a894-1b9c-4349-8505-e42e3d5bd22e.png)

This only happens with the sqlite3 from nixpkgs, not Debian. I compared the compile options in https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/sqlite/default.nix with the ones in the debian rules file and didn't spot any obvious difference which would explain this. Do you have any ideas?

**Comment by SuperSandro2000** [comment]
Derp. I need to use the ``sqlite-interactive`` package instead of sqlite3. Going to make this more obvious in nixpkgs.

**Comment by akinomyoga** [comment]
Thanks. Hmm, but if the problem is solved by `ble-detach`, that means that some interference with the TTY settings by `ble.sh` is causing the problem. Can you check the difference of the TTY controller in attached/detached states in the nix environment by the following commands?

```bash
$ stty -a > stty1.txt
$ ble-detach
$ stty sane;
$ stty -a > stty2.txt
$ diff -u stty1.txt stty2.txt
```

I just tried Fedora sqlite3, which doesn't seem to reproduce the problem.

**Comment by akinomyoga** [comment]
Maybe another possibility is that the problem is unrelated to `ble.sh` nor `ble-detach` but just solved by running `stty sane`. If you could reproduce the problem without ble.sh from the beginning, the initial TTY setting of the environment is somewhat broken.

**Comment by SuperSandro2000** [comment]
The only obvious difference is that I disabled flow control.

```diff
--- stty1.txt   2022-01-31 12:36:47.148566800 +0100
+++ stty2.txt   2022-01-31 12:36:54.558566800 +0100
@@ -1,7 +1,7 @@
 speed 38400 baud; rows 45; columns 188; line = 0;
-intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = <undef>; stop = <undef>; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V;
-discard = ^O; min = 1; time = 0;
+intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O;
+min = 1; time = 0;
 -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
--ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany imaxbel iutf8
+-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany imaxbel -iutf8
 opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop echoprt echoctl echoke -flusho -extproc
+isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

![image](https://user-images.githubusercontent.com/7258858/151787610-55ac1dae-f456-4b28-9c21-f8a38257b9f9.png)


> Maybe another possibility is that the problem is unrelated to `ble.sh` nor `ble-detach` but just solved by running `stty sane`

Yeah, that was the case.

**Comment by akinomyoga** [comment]
Hmm, the default state of `echoprt` in your environment is related. At least, it is different from my environments and also the state after running `stty sane`. If that default state is set up by some component of nixpkgs, we might also want to check it.

**Comment by SuperSandro2000** [comment]
I tried ripgrepping for the echoprt with smartcase but only found occurrences of it in vendored go packages. I am not sure why this is changed and cannot remember ever changing it. Maybe some tool I use changes it but it could take a while to find that.

**Comment by akinomyoga** [comment]
I see. Yeah, it might be changed by completely different parts of the system.
