### ISSUE TITLE
Strange output when updating ble.sh

### ISSUE THREAD

**Issue by telometto** [akinomyoga/ble.sh#174]
**ble version:** 0.4.0-devel3+5065fda 
**Bash version:** 5.1.8(1)-release 

I started getting some strange output when updating `ble.sh` yesterday. After running `ble-update`, I go the following output:
```sh
cd into /home/MYUSER/Documents/from_git/ble.sh...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 30 (delta 22), reused 30 (delta 22), pack-reused 0
Unpacking objects: 100% (30/30), 9.25 KiB | 83.00 KiB/s, done.
From https://github.com/akinomyoga/ble.sh
   e332dc5..5065fda  master     -> origin/master
Fetching submodule contrib
fatal: remote error: upload-pack: not our ref 0ea05b0468d1ca40373c2f564cda6998e97d7a99
Errors during submodule fetch:
	contrib
[ble: exit 1][ble: elapsed 45.919s (CPU 101.7%)]
```

This morning, a few minutes ago, I re-ran `ble-update`, and I got the following output:
```sh
Nothing to do.
cd into /home/MYUSER/Documents/from_git/ble.sh...
Already up to date.
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 588 bytes | 588.00 KiB/s, done.
From https://github.com/akinomyoga/blesh-contrib
   bb09bcb..0ea05b0  master     -> origin/master
Submodule path 'contrib': checked out '0ea05b0468d1ca40373c2f564cda6998e97d7a99'
cp -p contrib/fzf-initialize.bash out/contrib/fzf-initialize.bash
bash make_command.sh install "out/contrib/fzf-initialize.bash" "/home/MYUSER/.local/share/blesh/contrib/fzf-initialize.bash"
cp -p contrib/README.md out/doc/contrib/README.md
bash make_command.sh install "out/doc/contrib/README.md" "/home/MYUSER/.local/share/doc/blesh/contrib/README.md"
```

Oddly enough, if I re-run `ble-update` after having gotten this "error", the command successfully completes (`Nothing to do.`).

**EDIT:** removed personal info from the paste.

**Comment by akinomyoga** [comment]
Sorry, it was just because I forgot to push the latest version of the submodule [ble.sh/contrib](https://github.com/akinomyoga/blesh-contrib) to GitHub. I have noticed it several hours later and pushed it to the submodule repository, so now it should work fine.

**Comment by telometto** [comment]
Well, then all is good 👌

**Comment by akinomyoga** [comment]
Anyway, thanks for the report.

**Comment by SuperSandro2000** [comment]
You can set `push.recurseSubmodules` in git to avoid this https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushrecurseSubmodules

**Comment by akinomyoga** [comment]
Oh, thanks! That's good to know. I didn't know that!
