### ISSUE TITLE
Use ble.sh along with oh-my-bash

### ISSUE THREAD

**Issue by tonycituk** [akinomyoga/ble.sh#178]
Hello there, i find awesome the features of ble.sh.
How can i use it along with oh-my-bash prompt?

I install ble.sh from the AUR.
As the README says, I added ```[[ $- == *i* ]] && . /usr/share/blesh/ble.sh``` to bashrc.
Before:
![jue 17 feb 2022 08:37:24 CST](https://user-images.githubusercontent.com/56138035/154504048-6960bf89-cae7-4514-b661-87732a5f0593.png)
After:
![jue 17 feb 2022 08:38:53 CST](https://user-images.githubusercontent.com/56138035/154504281-23a5972d-2488-4805-bd7d-655f759f0b56.png)
Working as expected, but no more stylish prompt.

Note: I'm not a native english speaker, sorry for the grammatical errors.

**Comment by SuperSandro2000** [comment]
You need to source ble.sh first then load oh-my-bash.

**Comment by akinomyoga** [comment]
Thanks! In my environment, it seems to work regardless of the loading order of `oh-my-bash.sh` and `ble.sh` for both `ble-0.3` and `master` version.

- **Q1**: Which version of ble.sh do you use? In particular, which of AUR `blesh` or `blesh-git` do you use?
- **Q2**: Which version of oh-my-bash do you use? Could you update oh-my-bash by running `upgrade_oh_my_bash` and see if anything changes?
- **Q3**: As suggested by @SuperSandro2000, is the situation changed by moving `[[ $- == *i* ]] && . /usr/share/blesh/ble.sh` before the line `source $OSH/oh-my-bash.sh`?

**Comment by akinomyoga** [comment]
@tonycituk ping?

**Comment by akinomyoga** [comment]
@tonycituk

**Comment by snqzspg** [comment]
Try adding the following line before `ble-attach`.

```
_omb_theme_PROMPT_COMMAND
```

This issue seems to only surface on SOME terminal emulators (like gnome-terminal)
