### ISSUE TITLE
丸括弧で囲われた部分のコマンド類の手引きを表示できない

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#18]
**Commit ID**: d518830
**Bash version**: 4.4.12

```console
$ (bash --version@)
$ ( pwd | cat ; bash --version @) # ←丸括弧の前後に空白がある場合，複数のコマンドがある場合
```
上のように丸括弧で囲まれたコマンドラインにおいて，手引きを表示（Vimモードでの既定は<kbd>K</kbd>キーに束縛されている）する函数`vi_nmap/command-help`を実行しても，「command `' not found」という警告が表示される以外なにも起こりません。
丸括弧の内部のコマンドラインにおいても適当な手引き表示処理を行なうようにして欲しいです。

**Comment by akinomyoga** [comment]
c3270f6 ご報告ありがとうございます! 直しました。バグでした

**Comment by cmplstofB** [comment]
確認いたしました。対応感謝します！

**Comment by akinomyoga** [comment]
いつもありがとうございます! 閉じますね
