### ISSUE TITLE
Use return key to accept auto-complete by default

### ISSUE THREAD

**Issue by laoshaw** [akinomyoga/ble.sh#180]
Most of the time ble.sh auto-completes what I want to do, as shown below:

![image](https://user-images.githubusercontent.com/18351761/155548492-b2cdbaf3-7c75-4fe4-a86b-711d577fed83.png)

To accept it, I either have to TAB then select, or use a right-arrow-key or end-key before I can hit return-key(other wise the rest auto-completion will be cut-off). Can I just use return-key directly to accept the whole auto-completion instead?

The major use case for ble.sh is to cache previous commands for me, thus auto-completion is the best feature. If we can have one less key-typing to just accept the suggestion, that will be a great way to leverage the cache.

**Comment by akinomyoga** [comment]
That is <kbd>C-j</kbd> or <kbd>C-RET</kbd>. Although whether <kbd>C-RET</kbd> is supported or not is depending on the terminal, <kbd>C-j</kbd> is always available for the one-key execution command.

You can check the default keybindings at [`auto-complete`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-sec-auto-complete), or by running the following command:

```bash
$ ble-bind -m auto_complete -P
ble-bind -m 'auto_complete' -f __defchar__ auto_complete/self-insert
ble-bind -m 'auto_complete' -f __default__ auto_complete/cancel-default
ble-bind -m 'auto_complete' -f __line_limit__ nop
ble-bind -m 'auto_complete' -f auto_complete_enter auto_complete/notify-enter
ble-bind -m 'auto_complete' -f end auto_complete/insert-on-end
ble-bind -m 'auto_complete' -f right auto_complete/insert-on-end
ble-bind -m 'auto_complete' -f S-RET auto_complete/insert
ble-bind -m 'auto_complete' -f C-RET auto_complete/accept-line
ble-bind -m 'auto_complete' -f C-e auto_complete/insert-on-end
ble-bind -m 'auto_complete' -f C-f auto_complete/insert-on-end
ble-bind -m 'auto_complete' -f C-g auto_complete/cancel
ble-bind -m 'auto_complete' -f C-j auto_complete/accept-line
ble-bind -m 'auto_complete' -f 'C-x C-g' auto_complete/cancel
ble-bind -m 'auto_complete' -f C-S-m auto_complete/insert
ble-bind -m 'auto_complete' -f M-f auto_complete/insert-word
ble-bind -m 'auto_complete' -f M-right auto_complete/insert-word
ble-bind -m 'auto_complete' -f C-M-g auto_complete/cancel
```

If you would like to change the behavior of <kbd>RET</kbd>, you can add the following keybindings (Note that <kbd>C-m</kbd> is usually the key sent by terminal when you hit <kbd>Enter</kbd> or <kbd>Return</kbd>; see also *[§3.1.1 Representation of RET, ESC, TAB, BS, DEL, and C-BS](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#311-representation-of-ret-esc-tab-bs-del-and-c-bs)*).

```bash
# blerc

ble-bind -m 'auto_complete' -f C-m auto_complete/accept-line
ble-bind -m 'auto_complete' -f RET auto_complete/accept-line
```

**Comment by laoshaw** [comment]
ble-bind with C-m and RET works well for me now. Thanks!!!
