### ISSUE TITLE
why so many blank in my terminal

### ISSUE THREAD

**Issue by dongxi8** [akinomyoga/ble.sh#181]
**ble version**: 0.3.3
**Bash version**: 4.3.48(1)-release (x86_64-pc-linux-gnu)

I use this terminal and find this bug

![image](https://user-images.githubusercontent.com/1157840/155964170-b0567269-4613-46e2-8129-6f2e9cda4775.png)

![image](https://user-images.githubusercontent.com/1157840/155963696-1206ae5a-1421-40ee-b139-d491a087d4a1.png)

os：

![image](https://user-images.githubusercontent.com/1157840/155963727-e585dc47-1b97-48ef-b352-dc7c121de871.png)

**Comment by akinomyoga** [comment]
> *Quoted from https://github.com/ohmybash/oh-my-bash/issues/314*
>
> This is a bug of the old library `vte-0.28.2` that Terminator 0.98 is relying on. Terminator 0.98 (or `vte-0.28.2`) doesn't support the terminal control function `DECSCUSR` yet sets `TERM=xterm` environment variable. `TERM=xterm` implies that the terminal supports `DECSCUSR` although Terminator 0.98 doesn't actually support it. You can check the problematic behavior of Terminator by running the following command (without ble.sh) where you'll see some garbage strings in Terminator 0.98:
> 
> ```shell
> $ tput Ss 1
> $
> ```
> 
> I pushed a workaround [akinomyoga/ble.sh@70277d0](https://github.com/akinomyoga/ble.sh/commit/70277d0758d1b649543abe3cf1cf89bd1fa22b1b) in ble.sh `master` branch. You can update ble-0.4 by running `ble-update`. In the workaround, ble.sh doesn't use `DECSCUSR` when it detects an old version of `vte` library even if the `TERM` environment variable says `DECSCUSR` is available.
