### ISSUE TITLE
cd not a recognized command?

### ISSUE THREAD

**Issue by stankovictab** [akinomyoga/ble.sh#182]
**ble version**: 0.4.0-devel3+8940434 
**Bash version**: 5.1.8(1)-release

As pictured, `cd` for some reason isn't highlighted as a recognized command by default,\
however, when I set an `alias cd='cd'`, it does get recognized.\
Is this intended behaviour? Could I have done something to mess this up?\
All the best!

![image](https://user-images.githubusercontent.com/62820268/160303614-83e9566c-7206-4ee5-906b-0244db1ca2c3.png)

**Comment by stankovictab** [comment]
Upon further investigation, I noticed it's not actually an error, it just looks like it.\
Same thing with `echo`, too.
I changed the syntax error color setting to see the difference.\
`ble-color-setface syntax_error fg=003` (yellow)

Care to explain what's going on?

![2022-03-28_00-33-12](https://user-images.githubusercontent.com/62820268/160303942-546a3588-3f02-465e-8e79-e42cfd659a21.png)

**Comment by akinomyoga** [comment]
The red foreground color in the default color settings does not mean *unrecognized commands* but means the *builtin commands*. `cd` and `echo` are builtin commands. The default color for different types of commands can be checked by `ble-face command_@`:

![image](https://user-images.githubusercontent.com/8982192/160304706-0e6b378d-f446-4237-bfe7-172fc99f00a2.png)

This is different from the unrecognized commands that are highlighted in the red background by default:

![image](https://user-images.githubusercontent.com/8982192/160304805-0d57f63d-e690-4eb9-94f7-88de6aa975af.png)

**Comment by stankovictab** [comment]
Yeah, that makes a lot more sense now, thanks for the fast answer!
