### ISSUE TITLE
How to set up Ctrl+Shift+Arrow?

### ISSUE THREAD

**Issue by DUOLabs333** [akinomyoga/ble.sh#187]
I know you're supposed to do something with `@marked forward-char`, but it's not really well explained in the manual.

**Comment by akinomyoga** [comment]
Thank you! It actually relies on the support of the terminal the user uses. If it's not working by default, your terminal doesn't seem to support the function-key modification. If your terminal supports configuring the sequences sent by <kbd>Ctrl+Shift+Arrow</kbd>, `ESC [ 1 ; 6 A`, `ESC [ 1 ; 6 B`, `ESC [ 1 ; 6 C`, and `ESC [ 1 ; 6 D` can be set for <kbd>C-S-up</kbd>, <kbd>C-S-down</kbd>, <kbd>C-S-right</kbd>, and <kbd>C-S-left</kbd>, respectively. If your terminal doesn't even support configuring the sequence of each key combination, unfortunately, you cannot use these key combinations unless you change the terminal. Which terminal do you use?

**Comment by akinomyoga** [comment]
I have added cursor keys in the table of the escape sequences in [§3.6.3 Settings for terminals without `modifyOtherKeys` feature](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#363-settings-for-terminals-without-modifyotherkeys-feature).

**Comment by DUOLabs333** [comment]
I use Konsole.

**Comment by DUOLabs333** [comment]
Doing `cat -v` and pressing `Ctrl+Shift+Right` doesn't output anything.

**Comment by akinomyoga** [comment]
I have checked the settings of Konsole. The setups in Konsole seem to be described in Ref. [1].

- [1] [Chapter 5. Terminal Key Bindings](https://docs.kde.org/trunk5/en/konsole/konsole/key-bindings.html)

## 1. First, open the list of profiles
![image](https://user-images.githubusercontent.com/8982192/164917279-ffeb4ecd-f4de-46f3-90c5-2efcc9d821b8.png)

## 2. If you do not have a custom profile, create one
![image](https://user-images.githubusercontent.com/8982192/164919528-94589110-c50f-4b8d-bbef-502141ba7996.png)
![image](https://user-images.githubusercontent.com/8982192/164933700-f84afaed-f2d0-4db5-8a4b-b5fcbc9dfa06.png)

## 3. In the Profile Editor window, create a new Keybinding (or edit an existing one)
![image](https://user-images.githubusercontent.com/8982192/164920120-323b1f9e-863f-4c8f-9bce-3353bc68b8f5.png)

## 4. Add bindings and edit them
![image](https://user-images.githubusercontent.com/8982192/164924393-199473d6-06e2-4336-adaa-1f2d390ba56f.png)

In particular for the cursor keys, you need to add the following eight keybindings:

![image](https://user-images.githubusercontent.com/8982192/164933994-d75fbb7d-cb7e-4eeb-b4ec-fab67ea5eeaa.png)

Press `[OK]` to apply the change.

## 5. Select the modified keybindings and close the profile editor by `[OK]`
![image](https://user-images.githubusercontent.com/8982192/164934039-aa85a5b7-4bbb-4248-a98d-52b61960abde.png)

## 6. Select the modified profile and make it default
![image](https://user-images.githubusercontent.com/8982192/164934067-d69cf5da-4d54-4189-bbbe-9a764e291fad.png)

## 7. Switch the profile for the current session
![image](https://user-images.githubusercontent.com/8982192/164934100-eee04337-371b-480b-9ec7-7d2b218184ad.png)

**Comment by akinomyoga** [comment]
Sorry, there were mistakes. All `\e` in the second picture of step 4 actually need to be `\E`.

**Comment by DUOLabs333** [comment]
It works!
