### ISSUE TITLE
描画属性指定子にSGRの値を指定できるようにしてほしい

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#19]
[描画属性指定子](https://github.com/akinomyoga/ble.sh/wiki/%E8%AA%AC%E6%98%8E%E6%9B%B8#21-%E6%8F%8F%E7%94%BB%E5%B1%9E%E6%80%A7%E6%8C%87%E5%AE%9A%E5%AD%90-gspec)にSGRの値を指定できるようにしてほしいです。
例えばこのような方法で指定できることを望みます。
```bash
# ble-color-setface <face_name> sgr=<SGR_varue>
ble-color-setface filename_directory sgr='01;34'
```
---
蛇足気味ですが，こういった指定方法を追加してほしい理由を述べます。
GNU版のls(1)ユーティリティでは`$LS_COLORS`環境変数に（多くはdircolor(1)ユーティリティを用いて）ファイルの属性とSGRの値を設定することで表示されるファイルに着色することができます。僕はコマンドライン上のファイルの色などをls(1)ユーティリティが着色するファイルの色と協調させようと思っており，`$LS_COLORS`から「di=\<SGR_varue>」の値を抜き出してble-color-setface関数などで利用したいのです。

**Comment by akinomyoga** [comment]
SGR の指定を直接使うのではなく gspec という指定方法を導入したのは、SGR は端末によって微妙に意味が異なったりして、それらの実装の差異を吸収するのが目的でした。なので、gspec の仕様に入れるかどうかは考えさせて下さい。

**Comment by cmplstofB** [comment]
そうなんですね。わかりました。

**Comment by akinomyoga** [comment]
`underline,sgr='01;34'` などのように gspec の指定と SGR の指定を混合することってあるでしょうか。もしそうでなければ、一つの案として `ble-color-setface` の仕様の方を変更するのが自然かなと思いました。例えば、

```bash
ble-color-setface FACE_NAME TYPE:SPEC

FACE_NAME
  設定する描画設定の名前

TYPE
  描画属性の指定方法
    "gspec"  描画属性指定子 (既定)
    "sgr"    SGR引数
    "face"   他の描画設定
    "gflags" 描画属性値 (ble内部使用)
    "seq"    制御シーケンス

SPEC
  値

```

**Comment by cmplstofB** [comment]
ありがとうございます！（いつもおかしな要望ばかりですいません……）

> gspec の指定と SGR の指定を混合することってあるでしょうか。

（少なくとも僕個人の目的としては）ないです。
もしも実装してくださるなら，提示していただいたような仕様でお願いします。

**Comment by akinomyoga** [comment]
SGRの解釈は、ANSIに従った解釈ではなくて、現在の端末に応じた (`terminfo` に従った) 解釈の方が都合が良いですよね。

内部的には face は g 値 (gspec と一対一に対応する整数値) で管理しているので、SGRの引数で指定された場合も一旦それを解釈して g 値に変換しなければなりません。その時に、ANSIのSGRとして解釈するか、現在の端末に応じた (`terminfo` に従った) 解釈にするかという選択肢があります。

**Comment by cmplstofB** [comment]
初回起動時にキャッシュされるのですね。もしそうなら，すいませんが，terminfoのほうを優先してほしいです。よろしくおねがいします。

**Comment by cmplstofB** [comment]
確認いたしました。ありがとうございます！

**Comment by akinomyoga** [comment]
> 僕はコマンドライン上のファイルの色などをls(1)ユーティリティが着色するファイルの色と協調させようと思っており，$LS_COLORSから「di=<SGR_varue>」の値を抜き出してble-color-setface関数などで利用したいのです。

今更ですみませんが、以下の機能を実装しようかなと思っています。どう思われますか

```
# memo.txt#L1861

2016-07-20

  * ファイル名の色付けに LS_COLORS を参照する?
    https://github.com/trapd00r/zsh-syntax-highlighting-filetypes

    ble.sh の枠組で使用する為には ble-color.sh/gflags に変換しなければならない。
    しかし、実際に使っている terminal と sequence が異なる場合に齟齬が生じる。
    従って直接 LS_COLORS を用いるよりは、bleopt_filename_ls_colors 的な変数に指定して貰う事にする。
    そのまま LS_COLORS を使用したい場合は bleopt_filename_ls_colors=$LS_COLORS などとする。
    展開を実行するようにする。
```

**Comment by cmplstofB** [comment]
是非おねがいします！

**Comment by akinomyoga** [comment]
c7ff302 対応しました。簡単で良いので確認をお願いしてもよろしいでしょうか。

```bash
# 設定方法
bleopt filename_ls_colors="$LS_COLORS"
```

**Comment by cmplstofB** [comment]
すいません，遅くなりました。
ec31aab にて
```bash
bleopt filename_ls_colors="$LS_COLORS"
```
とやったのですが，「bleopt: unknown bleopt option `filename_ls_colors'」と怒られてしまいます。
filename_ls_colorsを設定する場所はblercの「bleopt undo_point=orig」などと同じような場所（なにもフックなどを呼び出していない範囲）でいいんですよね？

**Comment by akinomyoga** [comment]
ご報告ありがとうございます!

> 「bleopt undo_point=orig」などと同じような場所（なにもフックなどを呼び出していない範囲）でいいんですよね？

そのつもりでした。こちらではそれで動いているような気がします。確認してみます

**Comment by cmplstofB** [comment]
> make && make install が通っていない可能性

すいません，これが原因でした……。詳しくは省きますが，環境変数を変更したことを失念していた為まったく更新されていない状態で使用していました。ご迷惑おかけしました……。

**Comment by akinomyoga** [comment]
そうでしたか。良かったです!

**Comment by akinomyoga** [comment]
@cmplstofB 取り敢えず特に動作に問題がなければ、あるいは、改良することなどがなければ閉じようと思います。お使いになって (いただけたのれあれば) いかがでしょうか

**Comment by cmplstofB** [comment]
文句なしです！ ほんとうにありがとうございます。

**Comment by akinomyoga** [comment]
確認ありがとうございます! 閉じますね
