### ISSUE TITLE
Two potential bugs

### ISSUE THREAD

**Issue by telometto** [akinomyoga/ble.sh#192]
**ble version**: 0.4.0-devel3+d340233
**Bash version**: 5.1.8(1)-release (x86_64-redhat-linux-gnu)
**Distro**: Fedora 35

I do not know what is causing it, but there's an issue I discovered by chance when I tried to pass the command `gcc -v`: as soon as i enter the `v` it prompts me to install a package, which is impossible to escape. I've tried both `N` and `y`, but the terminal is stuck and I have to exit it by pressing the 'x' (a pop-up window then shows up and asks me if I really want to kill the terminal window when there's a process still running). Please refer to the image below.

![bug](https://user-images.githubusercontent.com/65364211/166311323-373a4221-db70-43b0-8563-0f6111a586e8.png)

Also, not an issue per sé, but maximizing and minimizing the terminal does the following (I maximized and minimized several times for the screenshots):

_Minimizing_
![min](https://user-images.githubusercontent.com/65364211/166311818-a06b7fee-b4dd-4442-b463-3038470b7be0.png)

_Maximizing_
![max](https://user-images.githubusercontent.com/65364211/166311856-11f2b575-0100-4dd7-83b0-24be18682c26.png)

**EDIT:** edited to reflect correct OS version.

**Comment by akinomyoga** [comment]
Thank you for the report.

- Could you provide me with the result of pressing <kbd>Ctrl+x Ctrl+v</kbd>?
- What would be the result of the following commands?

```bash
$ complete -p gcc
$ type command_not_found
```

> Also, not an issue per sé, but maximizing and minimizing the terminal does the following (I maximized and minimized several times for the screenshots):

Could you describe it more? Is the picture of *minimizing* the expected behavior? Or is the picture of *maximizing* the expected one? I do not have information about what is your prompt setup (such as prompt_rps1, prompt_ps1_transient, etc.) and thus do not know what would be the expected result. For example, What is the result of the following commands:

```bash
$ declare -p PS1 | cat -v
$ bleopt prompt_@
```

**Comment by telometto** [comment]
- <kbd>Ctrl + X Ctrl + V</kbd> yields this:

```sh
GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)
ble.sh, version 0.4.0-devel3+d340233 (noarch)
bash-completion, version 2.11 (hash:3503cc3400612a3c6b4373391bc2835efb70e1d6, 76322 bytes) (noarch)
locale: LANG=en_US.UTF-8 LC_COLLATE=C LC_MEASUREMENT=nb_NO.UTF-8 LC_MONETARY=nb_NO.UTF-8 LC_NUMERIC=nb_NO.UTF-8 LC_PAPER=nb_NO.UTF-8 LC_TIME=nb_NO.UTF-8
terminal: TERM=xterm-256color wcwidth=14.0-west/14.0-2+ri, vte:6602 (65;6602;1)
```

- `complete -p gcc`
`bash: complete: gcc: no completion specification`

- `type command_not_found`
`bash: type: command_not_found: not found`

>Could you describe it more?

Yes, well, the thing that happens is that the input prompt comes up again. Same as if you press <kbd>Enter</kbd> inside the terminal without typing anything, if that makes sense?

- The two commands:

```sh
$ declare -p PS1 | cat -v
declare -- PS1="\\[\\e[1;35m\\]\\u\\[\\e[0m\\]@\\[\\e[1;36m\\]\\H\\[\\e[0m\\]:\\[\\e[1;32m\\]\\w\\[\\e[0m\\]\\n\\[\\e[1;32m\\]\$\\[\\e[0m\\] "

$ bleopt prompt_@
bleopt prompt_command_changes_layout=
bleopt prompt_eol_mark=$'\e[94m[ble: EOF]\e[m'
bleopt prompt_ps1_final=
bleopt prompt_ps1_transient=
bleopt prompt_rps1=
bleopt prompt_rps1_final=
bleopt prompt_rps1_transient=
bleopt prompt_ruler=
bleopt prompt_screen_title=
bleopt prompt_status_align=$'justify=\r'
bleopt prompt_status_line=
bleopt prompt_term_status=
bleopt prompt_xterm_title=
```

**Comment by akinomyoga** [comment]
Thank you for the information.

> ```shell
> $ complete -p gcc
> bash: complete: gcc: no completion specification
> ```

Does it change after the error message has been shown?

> ```shell
> $ type command_not_found
> bash: type: command_not_found: not found
> ```

Thank you. Hmm, then, I don't have an idea. Maybe I need to set up Fedora 36. It doesn't reproduce at least in Fedora 35.

Is `gcc` installed in your Fedora 36? I'd like to know whether the problem arises when `gcc` is installed or when `gcc` is not installed.

----

> > Could you describe it more?
> 
> Yes, well, the thing that happens is that the input prompt comes up again. Same as if you press Enter inside the terminal without typing anything, if that makes sense?

OK, then this is actually a duplicate of #142, #154, #163, and #173. This behavior is an intended one and is related to the general problem of terminal implementations of text reflowing, which vary largely among terminals. The reasoning behind the current behavior of ble.sh is explained in https://github.com/akinomyoga/ble.sh/issues/142#issuecomment-950036015. This general problem is also discussed in [README of powerlevel10k](https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window).

The behavior of ble.sh can be configured by [`bleopt canvas_winch_action`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#user-content-bleopt-canvas_winch_action). As explained in https://github.com/akinomyoga/ble.sh/issues/173#issuecomment-1026833761, duplicate prompt lines on resizing can be suppressed by the following setting (though it might possibly delete previous command outputs on resizing):

> ```shell
> # blerc
> bleopt canvas_winch_action=redraw-prev
> ```

**Comment by telometto** [comment]
>Maybe I need to set up Fedora 36. It doesn't reproduce at least in Fedora 35.

No need to install F36: I noticed yesterday that I had written 36, so I corrected it to 35 😅

>Hmm, then, I don't have an idea.

If you can't reproduce it, then the problem is on my end... it's my configuration that's causing this. Thanks for the help, though!

>This behavior is an intended

Then everything is in order! I'll configure the canvas the way I like. Many thanks for the help 😊

**Comment by akinomyoga** [comment]
> I do not know what is causing it, but there's an issue I discovered by chance when I tried to pass the command `gcc -v`: as soon as i enter the `v` it prompts me to install a package, which is impossible to escape. I've tried both `N` and `y`, but the terminal is stuck and I have to exit it by pressing the 'x' (a pop-up window then shows up and asks me if I really want to kill the terminal window when there's a process still running). Please refer to the image below.

@telometto There has been an issue #203 about the same problem. I've identified the cause and added a workaround in commit 64d471a.

**Comment by telometto** [comment]
@akinomyoga oh, so it wasn't a problem on my end?

I'll update as soon as I'm back from work and give you an update 👌

**Comment by akinomyoga** [comment]
This seems to happen only when the packages `bash-completion` and `PackageKit` are installed in Fedora. I hadn't installed `PackageKit` in my Fedora 35/36 (I've upgraded to Fedora 36 recently), which was the reason that it didn't reproduce in my environment.

**Comment by telometto** [comment]
> This seems to happen only when the packages `bash-completion` and `PackageKit` are installed in Fedora.

You're probably right. I tried disabling `PackageKit` using `# systemctl disable --now packagekit` and re-running `gcc -v` after updating `ble` but the problem still persists; I get the "pop-up" again and I force quit the window, I reopen a terminal and check the `systemctl status packagekit` and it is magically enabled again. It's not much of a problem, since I do not check GCC's version and happened to stumble across it. Thanks for the update ^_^

**Comment by telometto** [comment]
@akinomyoga 
> Sorry for disturbing you repeatedly

Not at all! If anything, I've been the one disturbing you 😅

> if you have time, could you again update `ble.sh` and see if it is finally fixed?

I've updated it, and it works a charm! The fix worked 🚀
Thanks a lot for fixing this!

**Comment by akinomyoga** [comment]
Thank you!
