### ISSUE TITLE
debugging(gdb) in vscode no longer works for c++ when ble.sh is used

### ISSUE THREAD

**Issue by laoshaw** [akinomyoga/ble.sh#196]
**ble version**: 
0.4.0-devel3+022d38b
**Bash version**: 
5.0.17(1)-release (x86_64-pc-linux-gnu)

vscode with c++ program works well until I launch a debugging session(use gdb by default on ubuntu 20.04), the terminal will ask me to type Ctrl+j to execute, after I did it, the terminal closes and the debug session is unusable(no step/next button shown etc).
after I disabled ble.sh, it works well(the executable built by vscode runs automatically and gdb becomes active for normal use.

**Comment by akinomyoga** [comment]
`ble.sh` detects the insertion of multiline commands that is not directly made by user keyboard inputs and fall into the multiline mode. Can you try this setting?

```bash
# blerc [in Ubuntu 20.04]
bleopt accept_line_threshold=-1
```

**Comment by akinomyoga** [comment]
@laoshaw How's the situation? Have you already solved the problem?

**Comment by akinomyoga** [comment]
> sorry for the delay, with that setting vscode-debug seems working for me.

OK! Thank you for the information! Thank you again for your report!
