### ISSUE TITLE
How to turn off the option completion and instead complete filenames?

### ISSUE THREAD

**Issue by akinomyoga** [akinomyoga/ble.sh#204]
Let me move the issue https://github.com/rsteube/carapace-bin/issues/1219 to here.

----

_Originally posted by @geekscrapy in https://github.com/rsteube/carapace-bin/issues/1219#issue-1294255779_

Firstly, great tool!
 
Hi, How can I turn off argument completion? I would prefer filenames/directories to be shown instead. <img alt="image" width="563" src="https://user-images.githubusercontent.com/11225502/177330735-ad1854ba-3bf6-4971-9418-2118bc78aebf.png">
 
Second question: I loose some key bindings when I invoke ble.sh. For example I am on a mac (with iterm) and use ALT+DELETE to delete a previous word. This is disabled when I use ble.sh

**Comment by akinomyoga** [comment]
@geekscrapy How's the situation? You can just give answers to Q1-3 and two more questions about ALT-DELETE in https://github.com/akinomyoga/ble.sh/issues/204#issuecomment-1178042642. In short, you can give us the result of the following commands and key inputs:

```bash
$ ble-update
$ [press Ctrl+X][press Ctrl+V]
$ complete -p ls
$ echo [press Ctrl+V][press ALT+DELETE]
$ echo [press Ctrl+V][press DELETE]
```

**Comment by geekscrapy** [comment]
Q1: `Already up to date.` (as of 2022-07-12)
Q2: 
```bash
GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin21.1.0)
ble.sh, version 0.4.0-devel3+14f3c81 (noarch)
locale: LANG=(unset) LC_COLLATE=C LC_CTYPE=UTF-8 LC_TERMINAL=iTerm2 LC_TERMINAL_VERSION=3.4.16
terminal: TERM=xterm-256color wcwidth=12.1-west/14.0-2+ri, xterm:95 (0;95;0)
```
Q3:
```bash
$ complete -p ls
-bash: complete: ls: no completion specification
[ble: exit 1]
```

**Comment by geekscrapy** [comment]
## Re: ALT-DELETE in iTerm2
This issue has gone away for now oddly... I will keep an eye out for it coming back!

I am however getting the error: `/bin/zsh: no such option: noprofile` when the shell is loaded and .bash_profile is sourced. is this related?

**Comment by akinomyoga** [comment]
Thank you for the information!

> ```shell
> GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin21.1.0)
> ble.sh, version 0.4.0-devel3+14f3c81 (noarch)
> locale: LANG=(unset) LC_COLLATE=C LC_CTYPE=UTF-8 LC_TERMINAL=iTerm2 LC_TERMINAL_VERSION=3.4.16
> terminal: TERM=xterm-256color wcwidth=12.1-west/14.0-2+ri, xterm:95 (0;95;0)
> ```

Ah, OK. I got the situation! Actually, the filenames and directory names are also generated but do not fit in a terminal. If you attempt the completion in a sufficiently large terminal window, you will find the filenames at the end of the list. Here's an example of the completion in a larger terminal window where we see the filenames are shown at the end of the list:

![image](https://user-images.githubusercontent.com/8982192/178479119-e5567ee5-2343-4ebd-a98e-b89fa9d153e0.png)
.
The options precede the filenames because of the typical sorting order by `LC_COLLATE`. `LC_COLLTE=C` uses the character codes, and the hyphen `-` has a smaller code than the alphabets.

I have never cared about this situation, but now it seems reasonable not to generate option names when there are possible filenames considering the limited size of the window. I'll later adjust the behavior.

**Comment by geekscrapy** [comment]
Thanks! What might I be able to do to test this theory?

**Comment by akinomyoga** [comment]
If you want to test the theory, you can press <kbd>Tab</kbd> twice to enter `menu-completion` and press <kbd>PageDn</kbd>s to go to next pages and see if the filenames are present in the last page.

**Comment by geekscrapy** [comment]
Yep, this works better now. If I'm honest I was actually expecting rows of the files like this:
```
$ echo /tmp/blesh
blesh boost_interprocess com.apple.launchd.gNBFSqjeAc com.google.Keystone tmp00005647 tmps28ku8b4cacert.pem
```
Although I get the column based selection. Is there a way to only ever get the row based menu like above rather than the column based one?

**Comment by akinomyoga** [comment]
How about this 1c7f7a1? Could you update ble.sh and check the behavior again?

**Comment by akinomyoga** [comment]
> that quite confusing with the arguments.

Oh, this is something unexpected. It doesn't reproduce in my Linux system. I guess this is related to the man page format used in macOS, but I cannot test it directly because I don't have macOS. I'm not sure if I can identify the problem without reproducing it, but will take a look at the related code later when I have time.

**Comment by akinomyoga** [comment]
@geekscrapy Sorry for the delay. I have added a workaround fa32829. I'm not sure if it really solves the problem in your environment because I don't have macOS. Could you update ble.sh by running `ble-update` in a ble.sh session and check the behavior?

**Comment by akinomyoga** [comment]
@geekscrapy Have you tried the latest version to see if the garbage string `__ble_desc__` went away? If you are not using ble.sh, that's fine, but could I close the issue? Thank you!

**Comment by geekscrapy** [comment]
Hey! Yes I stopped using ble.sh actually, I think I wanted simpler things 😅
Thanks for the help though, keep going!

**Comment by akinomyoga** [comment]
OK, thank you for your response!
