### ISSUE TITLE
Fzf tab completion not working

### ISSUE THREAD

**Issue by ferdinandyb** [akinomyoga/ble.sh#206]
```
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
ble.sh, version 0.4.0-devel3+64d471a (noarch)
bash-completion, version 2.10 (hash:b6da7f7edfc1c3c5196c86c81fb05fce96f83c03, 74550 bytes) (noarch)
fzf key-bindings, version +9cb7a364 (noarch) (integration: on)
fzf completion, version +9cb7a364 (noarch) (integration: on)
starship, version 1.9.1-master+4e9b8409 (rustc 1.61.0 (fe5b13d68 2022-05-18), 2022-06-27 19:07:32 +00:00)
locale: LANG=en_US.UTF-8 LC_ADDRESS=hu_HU.UTF-8 LC_COLLATE=C LC_IDENTIFICATION=hu_HU.UTF-8 LC_MEASUREMENT=hu_HU.UTF-8 LC_MONETARY=hu_HU.UTF-8 LC_NAME=hu_HU.UTF-8 LC_NUMERIC=hu_HU.UTF-8 LC_PAPER=hu_HU.UTF-8 LC_TELEPHONE=hu_HU.UTF-8 LC_TIME=hu_HU.UTF-8
terminal: TERM=xterm-kitty wcwidth=14.0-west/14.0-2+ri, kitty:0 (1;4000;25)
```

I have the following in my `init.sh`
 ```
_ble_contrib_fzf_base=$HOME/.fzf
ble-import -d contrib/fzf-completion
ble-import -d contrib/fzf-key-bindings
```

And most things work, but the [fzf fuzzy completion](https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh) for e.g. `kill -9` is not working. Do you have any ideas on how to fix this?

Btw, really great piece of software! I still need to figure out how to painlessly change the colortheme of the highlighting (I haven't been able to find any presets yet), and a few other things, but in general I already really like it :)

**Comment by akinomyoga** [comment]
Thank you for the report! I could reproduce the problem in my environment, so I have fixed it. Could you update `ble.sh` by running `ble-update` in a `ble.sh` session and see if it works as expected?

**Comment by ferdinandyb** [comment]
Thanks for the super fast response! `kill -9` completion now works perfectly!
