### ISSUE TITLE
[zoxide, fzf] zoxide interactive fzf completion triggered without user intent and then going into infinite loop

### ISSUE THREAD

**Issue by ferdinandyb** [akinomyoga/ble.sh#207]
```
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
ble.sh, version 0.4.0-devel3+c0abc95 (noarch)
bash-completion, version 2.10 (hash:b6da7f7edfc1c3c5196c86c81fb05fce96f83c03, 74550 bytes) (noarch)
fzf key-bindings, version +9cb7a364 (noarch) (integration: on)
fzf completion, version +9cb7a364 (noarch) (integration: on)
starship, version 1.9.1-master+4e9b8409 (rustc 1.61.0 (fe5b13d68 2022-05-18), 2022-06-27 19:07:32 +00:00)
locale: LANG=en_US.UTF-8 LC_ADDRESS=hu_HU.UTF-8 LC_COLLATE=C LC_IDENTIFICATION=hu_HU.UTF-8 LC_MEASUREMENT=hu_HU.UTF-8 LC_MONETARY=hu_HU.UTF-8 LC_NAME=hu_HU.UTF-8 LC_NUMERIC=hu_HU.UTF-8 LC_PAPER=hu_HU.UTF-8 LC_TELEPHONE=hu_HU.UTF-8 LC_TIME=hu_HU.UTF-8
terminal: TERM=xterm-kitty wcwidth=14.0-west/14.0-2+ri, kitty:0 (1;4000;25)
```
I have `zoxide` installed. Normally there's two ways to get into the interactive cd mode, one is to start zoxide with `zi` or after having typed some keywords leaving a space and pressing tab, e.g. `z kutat pi <TAB>` should drop me into fzf, with the remaining entries that match `kutat` and `pi`. With `ble.sh` there are some strange things going on

### Behaviour without `ble.sh`

I type `z kutat pi <TAB>` and go into fzf:
![image](https://user-images.githubusercontent.com/6343487/178110669-bd47d94e-abf9-4f46-8769-30804ad41b2c.png)
Press enter to select first match:
![image](https://user-images.githubusercontent.com/6343487/178110691-52d83e1e-c4d0-454a-affd-daa8503904ff.png)
And then another enter to actually perform the cd.

#### Interactive mode triggered without user intent:

I type `z kutat pu` (previously it did it with `z kutat pi` also but now it only does it with any other letter after the `p`, so I totally don't understand with is going on :D): I get dropped into fzf, but I shouldn't since I didn't do the `<space><TAB>`:
![image](https://user-images.githubusercontent.com/6343487/178110918-024e3a77-b9b5-4ebd-9294-0e1364dc2be6.png)
I press enter on the first match, but I'm again dropped back into fzf, but I lose my prompt
![image](https://user-images.githubusercontent.com/6343487/178110925-745a865b-4fb4-4842-b8cd-ed0f6d7c4c8f.png)
Trying out some non-matches and pressing enter results in multiple zoxide errors, so it seems I am being dropped back infinitely into the zoxide interactive prompt.
![image](https://user-images.githubusercontent.com/6343487/178110938-f2ab63ba-5d14-445f-afce-b59209b020f5.png)

At this point I'm also totally unable to exit from anything, `Ctrl-C` doesn't seem to kill the program (although I think pressing `Ctrl-c` is doing something different than it usually would with `ble.sh` in general, I just still haven't figured out what).

I tried with a few other combos and it seem that any `z [first search term] [singlecharacter]` followed by any other second character in the second search term will trigger this unexpected, uninterruptible fzf search.

#### Interactive mode triggered with user intent

I am now careful to not type the second letter so go `z kutat p <tab>` and as expected I get dropped into fzf:
![image](https://user-images.githubusercontent.com/6343487/178111156-f5187fc3-a34a-474c-a5d9-80cb4d392ffd.png)
I press enter and the prompt is cleared of everything:
![image](https://user-images.githubusercontent.com/6343487/178111171-6de7b163-fc4c-41b1-88d7-ce83398fdf41.png)
I press enter again and the cd is performed, but I lost the command that took me here
![image](https://user-images.githubusercontent.com/6343487/178111186-9f05efbd-e48e-4da7-8f04-11448597bff9.png)

As a precaution, I checked everything without starship, but it is the same. I also checked without `bash_completion`.

### side note: bash_completion?

I noticed on some of the issues, that maybe `bash_completion` is not needed when you have `ble.sh`. What is the case with that?

**Comment by akinomyoga** [comment]
Thank you for the report! This turned out to be because `zoxide` uses a kind of *hack* to run some interactive operations in the programmable completion just as `fzf` does. For this reason, we need to introduce a *reverse* hack on `zoxide` and `fzf`. I have newly implemented it for `zoxide` (a96bafe, https://github.com/akinomyoga/blesh-contrib/commit/5fdf55608c0db9d97c80cb8ab6c12e2b911786e8). Could you update `ble.sh` and check if it works?

**Comment by ferdinandyb** [comment]
Thank you, it works perfectly!

**Comment by akinomyoga** [comment]
Thank you for checking!

> ### side note: bash_completion?
> I noticed on some of the issues, that maybe `bash_completion` is not needed when you have `ble.sh`. What is the case with that?

I forgot to answer this question. I'm not sure if I correctly understand the question, but `ble.sh` by default uses its own built-in completer, which generates filenames and, if the current word is starting with `-`, also options extracted from the `man` page of the current command. When `bash-completion` or other programmable completions are set up, `ble.sh` uses these settings instead of the built-in completer.

**Comment by ferdinandyb** [comment]
Thanks, that pretty much answers my question, I think I will then try the built-in and see how it works :)
