### ISSUE TITLE
New, similar bug to my previously reported one

### ISSUE THREAD

**Issue by telometto** [akinomyoga/ble.sh#208]
**ble version:** 5.1.16(1)-release (x86_64-redhat-linux-gnu)
**Bash version:** 0.4.0-devel3+d5fe1d1 

It looks like a new problem has arisen: when opening a terminal for the first time, if you press a wrong key while typing out a command, you get an output. This only seems to happen if you use `doas` (does not seem to happen with `sudo`) and if you press a wrong button while typing out `bash` commands. You can see it happens when using `echo` and `doas dnf` (I mistyped to `dnc`).
Please refer to the screenshot below.

![kleki](https://user-images.githubusercontent.com/65364211/178112339-5c101269-5c3a-4678-9d5e-8e6eae5cb591.png)

I'm starting to become your personal bug-tester 😆 Jokes aside, though, I'm sorry to create issues all the time.

**Comment by akinomyoga** [comment]
@telometto Ah, it's a trivial mistake. This is my carelessness. Thank you! I have fixed it in commit [`973ae8c`](https://github.com/akinomyoga/ble.sh/commit/973ae8c2878ceb8895b657b2824e4f09c9e408e6#diff-c180d07f9f6314cd0ce60494fd95e4a1a3afaa2f78afd7046897c4c4e6f072d3).

**Comment by telometto** [comment]
Sorry, I forgot to give feedback. Everything seems in order now 😊

**Comment by akinomyoga** [comment]
OK! Thank you!
