### ISSUE TITLE
Current directory on prompt doesn't update correctly after certain commands are run

### ISSUE THREAD

**Issue by 3ximus** [akinomyoga/ble.sh#217]
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
ble.sh, version 0.4.0-devel3+a450775 (noarch)
bash-completion, version 2.11 (hash:b42f5d6a7ad6d4921ec73838ba54a96d6bd30936, 77071 bytes) (noarch)
fzf key-bindings, (hash:e066d23e81ee3cb0d5da449b64f7c24e92d8657d, 3075 bytes) (noarch)
locale: LANG=en_CA.UTF-8 LC_COLLATE=C
terminal: TERM=screen-256color wcwidth=14.0-west/14.0-2+ri, tmux:0 (84;0;0), unknown:- (0;115;0)
```
Hi there again :)

So I'm experiencing a strange issue.
When I run this NestJs application through `yarn` (only yarn, npm doesn't cause this issue)  in watch mode it causes `ble.sh` to keep the same path forever (apparently). On the clip bellow you can see that the path is not changing when running through yarn, instead of running with the nest cli. 
I've tested running the same command without `ble.sh` (running `ble-detach` beforehand) and the path update works correctly, so it could be some issue in `ble.sh` ?
Also, for the prompt I'm using the `\w` escape sequence for using the current work directory.

![Peek 2022-07-26 14-23](https://user-images.githubusercontent.com/9083012/181084808-2f4ca60a-758f-4bc3-b633-b2c5140a88f2.gif)

Thanks once again for all your work :+1: 
And let me know what other info I can gather.
Cheers!

**Comment by akinomyoga** [comment]
Thank you for the report! Hmm, this is strange.

- **Q1**: Could you share the value of `PS1`?

```bash
$ cat -v <<< "$PS1"
```

- **Q2**: Does it also happen with a simple prompt `PS1='\w\$ '`?
- **Q3**: When the current directory and the prompt do not match, what is shown with the following commands?

```bash
$ pwd
$ echo "$PWD"
$ var='\w'; echo "${var@P}"
```

- **Q4**: Does it also happen with a new NestJS project?

----

I tried to reproduce the problem in my environment but do not seem to be able to reproduce it in my environment. I am new to NestJS, so maybe I do something wrong, but I tried the following commands:

```bash
# What I have tried

nest new world      # Note: selected "yarn" as a package manager
cd world
yarn run start      # Note: I have killed it with C-c
cd -
cd -
yarn run debug:start      # Note: I have killed it with C-c
cd -
```

**Comment by 3ximus** [comment]
Thanks for the quick reply

  * **Q1**: Could you share the value of `PS1`?
```
$ cat -v <<< "$PS1"
^A^[[37m^B#\#$(__virtualization)^A^[[1;35m^B$(__job_count)$([[ $__MainColor != $__UserColor ]] && echo "^A^[[1;30m^B \u@\h") ^A^[[1;34m^B\w$(__virtual_env)^A^[[0m^B $(__nested_level)$([[ $_COMMAND_FAILED_ == 1 ]] && echo -e "^A^[[1;31m^B")\$ ^A^[[0m^B
```

Somewhere in there I have `\w` 



  * **Q2**: Does it also happen with a simple prompt `PS1='\w\$ '`?
Yes, You can see the screenshot bellow
  * **Q3**: When the current directory and the prompt do not match, what is shown with the following commands?

![image](https://user-images.githubusercontent.com/9083012/181285771-5a1b05c0-5cb7-47ff-8348-9e08d406b179.png)
  * **Q4**: Does it also happen with a new NestJS project?

Yes event with a new NestJS with the basic prompt

![image](https://user-images.githubusercontent.com/9083012/181286501-04909d90-049c-4e0c-98d7-757046116fdf.png)

Thank you :)

**Comment by akinomyoga** [comment]
Thank you. It seems the shell variable `PWD` is not correctly updated, but I don't have an idea how that could happen. I'm interested in the behavior in a plain Bash with a clean environment.

- **Q5**: Could you also check the behavior with the following commands? [ This starts a plain Bash, load ble.sh without `~/.blerc`. Does the problem reproduce in this setup? Also, I'm interested in the working directory of the process and also the variable attributes of `PWD`. ]

```bash
$ env -i INPUTRC=/dev/null HOME=$HOME USER=$USER TERM=$TERM HISTFILE=~/a.tmp PS1='\w\$ ' bash --norc --noprofile
$ source /path/to/ble.sh --norc
$ cd ~/Desktop/example      # <-- go to the directory of a NestJS project
$ yarn start:debug
^C
$ ls -l /proc/$$/cwd
$ declare -p PWD
$ cd
$ ls -l /proc/$$/cwd
$ declare -p PWD
$ exit
```

**Comment by 3ximus** [comment]
Hum, starting a bash session like that does seem to work correctly:
![image](https://user-images.githubusercontent.com/9083012/181396370-61d3ec6c-a523-4e64-a15c-a22781e5b674.png)

And I did a few more tests and setting `--norc` for ble.sh on my .bashrc seems to solve the issue for that session on bash

**Comment by akinomyoga** [comment]
Thank you!

> And I did a few more tests and setting `--norc` for ble.sh on my .bashrc seems to solve the issue for that session on bash

This means that some settings in `~/.blerc` (or `~/.config/blesh/init.sh`) are related to the problem. Could you identify which settings are related by turning off? If you could share your blerc file, I think I could also try to reproduce the problem in my environment again.

**Comment by 3ximus** [comment]
Well, I was doing more tests toggling some settings on `blerc`, and also ended up updating `ble.sh` to the latest version and now I can't reproduce the error anymore... 
Idk what happened... I've been noticing this issue for some time but only now decided to post an issue about it.
Anyway, I'll close the issue for now. If the problem comes back I'll reopen :)
Thank you for your time as always
Cheers !!

**Comment by akinomyoga** [comment]
Hmm, thank you for the information! I have checked again the recent changes a450775...0b95d5d9 but not sure which commit could affect the behavior of `PWD`.
