### ISSUE TITLE
Not clear about how to disable features.

### ISSUE THREAD

**Issue by zihadio** [akinomyoga/ble.sh#224]
In [homepage](https://github.com/akinomyoga/ble.sh#22-disable-features) you have said what to disable. But not sure where is the config file?
where am I supposed to edit this file? it's not in .local/share/blesh.
```
# Disable syntax highlighting
bleopt highlight_syntax=
```

**Comment by akinomyoga** [comment]
It is written just two paragraphs before the link you provided: see [the beginning of §2](https://github.com/akinomyoga/ble.sh#2-basic-settings). It is also written in [§1.4](https://github.com/akinomyoga/ble.sh#14-user-settings-blerc).

**Comment by zihadio** [comment]
@akinomyoga thanks. I had to create `~/.blerc` file.
