### ISSUE TITLE
[st] Overrides terminal cursor shape to block

### ISSUE THREAD

**Issue by StavromulaBeta** [akinomyoga/ble.sh#225]
I have setup my terminal (st 0.8.4) such that the default cursor shape is an underline, and this usually works fine. However, when I use ble.sh it overrides this and sets the cursor shape to a block.

**Comment by StavromulaBeta** [comment]
thanks I didn't realize this was an st issue!!

**Comment by akinomyoga** [comment]
I have added a workaround at ble.sh side in commit 39efcf9aac90176ccb6a197e0e80da5f02e57123. As far as you do not configure the cursor shape for ble.sh, I think it will just work without problems. If you would like to configure the cursor shape for some modes of ble.sh by using `ble-bind -m KEYMAP --cursor NUMBER`, you might need to explicitly specify the cursor shapes to ble.sh like

```bash
# blerc

# set the cursor shape in executing user commands (4: steady underline)
bleopt term_cursor_external=4

# set the cursor shape of the default keymap of ble.sh (4: steady underline)
ble-bind --cursor 4
```

**Comment by StavromulaBeta** [comment]
excellent - thank you!!!
