### ISSUE TITLE
how to shut down auto-complete 

### ISSUE THREAD

**Issue by 0226zy** [akinomyoga/ble.sh#23]
[Describe your queation or problem here. If sample terminal contents are available, you may copy and paste them here.]
hi,how to shut down auto-complete

**Comment by akinomyoga** [comment]
Hi! Thank you for a report.

- If you want to stop the current auto-complete suggestion, please type <kbd>C-g</kbd>.
- If you don't want `auto-complete` at all, you can put the following setting in your `~/.blerc` and `auto-complete` will never be invoked.
  ```bash
  # ~/.blerc

  bleopt complete_auto_complete=
  ```
- Or, maybe you want to set a delay to start `auto-complete` after the last user input as follows:
  ```bash
  # ~/.blerc

  bleopt complete_auto_delay=300 # Note: the unit is millisecond
  ```

**Comment by 0226zy** [comment]
Thanks, it work. cool!

**Comment by goyalyashpal** [comment]
hi!  the ble.sh's autocompletion is hanging up every too often.  even when using variables in command and trying to move the cursor across it.

auto-completion is nice, but not when it starts to actively block you from doing _anything_ on CLI.

i press ctrl-g when it is hung up, but there's no feedback anywhere on if it's enabled or not.  and it takes significant time to get over the hang.

**Comment by akinomyoga** [comment]
@goyalyashpal There are no problems in my environment. What is the result of the following command?

```console
$ ble summary
```

I'm not sure if it is related, but I've recently noticed a TTY problem when the user connect to Git Bash / MSYS2 / Cygwin from Windows Terminal. The ConPTY implementation or Windows Terminal seems to behave in a strange way at the C API level when a file descriptor is duplicated in a certain condition, but I haven't identified the root problem so far.

**Comment by goyalyashpal** [comment]
hi, sorry to forget mentioning, i am on linux nixos.

do you want this matter to go in a separate issue?

```console
$ ble summary
ble (ble.sh): unrecognized subcommand 'summary'.
[ble: exit 2]

$ ble --version
ble.sh, version 0.4.0-devel3+1a5c451c (noarch)

$ nix run nixpkgs#inxi -- --filter --system --extra  # -zSx
System:
  Kernel: 6.12.34 arch: x86_64 bits: 64 compiler: gcc v: 14.3.0
  Desktop: Cinnamon v: 6.4.7 Distro: NixOS 25.11 (Xantusia)

```

<details><summary>longer outputs of other <tt>ble</tt> subcommands: <tt>help</tt> and <tt>check</tt></summary>
<p>

```console
$ ble --help
usage: ble [SUBCOMMAND [ARGS...]]

SUBCOMMAND
  # Manage ble.sh
  attach  ... alias of ble-attach
  detach  ... alias of ble-detach
  update  ... alias of ble-update
  reload  ... alias of ble-reload
  help    ... Show this help
  version ... Show version
  check   ... Run unit tests

  # Configuration
  opt     ... alias of bleopt
  bind    ... alias of ble-bind
  face    ... alias of ble-face
  hook    ... alias of blehook
  sabbrev ... alias of ble-sabbrev
  palette ... alias of ble-color-show

$ ble check
MACHTYPE: x86_64-pc-linux-gnu
BLE_VERSION: 0.4.0-devel3+1a5c451c
BASH_VERSION: 5.2.37(1)-release
locale: LANG=en_IN LC_ADDRESS=hi_IN LC_IDENTIFICATION=hi_IN LC_MEASUREMENT=hi_IN LC_MONETARY=hi_IN LC_NAME=hi_IN LC_NUMERIC=hi_IN LC_PAPER=hi_IN LC_TELEPHONE=hi_IN LC_TIME=hi_IN
100.0% [section] ble/main: 19/19 (0 fail, 0 crash, 0 skip)
100.0% [section] ble/util: 1214/1214 (0 fail, 0 crash, 12 skip)
100.0% [section] ble/canvas/trace (relative:confine:measure-bbox): 5/5 (0 fail, 0 crash, 12 skip)
100.0% [section] ble/canvas/trace (cfuncs): 17/17 (0 fail, 0 crash, 1 skip)
100.0% [section] ble/canvas/trace (justify): 2/2 (0 fail, 0 crash, 28 skip)
100.0% [section] ble/canvas/trace-text: 11/11 (0 fail, 0 crash, 0 skip)
100.0% [section] ble/textmap#update: 5/5 (0 fail, 0 crash, 0 skip)

   ...

 89.1% [section] ble/unicode/GraphemeCluster/c2break (GraphemeBreakTest.txt): 2898/3251 (353 fail, 0 crash, 0 skip)
100.0% [section] ble/decode: 33/33 (0 fail, 0 crash, 0 skip)
100.0% [section] ble/edit: 2/2 (0 fail, 0 crash, 0 skip)
100.0% [section] ble/syntax: 22/22 (0 fail, 0 crash, 0 skip)
100.0% [section] ble/complete: 7/7 (0 fail, 0 crash, 0 skip)
ble.sh: The test log was saved to '/home/asr/.cache/blesh/0.4/test.20250703.123817.log'.
[ble: exit 1]

```

</p>
</details>
