### ISSUE TITLE
Shortened flags in utilities tab completion

### ISSUE THREAD

**Issue by bbyfacekiller** [akinomyoga/ble.sh#231]
Hi, is it possible to have shortened flags alongside full flag names in utilities tab completion?
Something like this?
![Screenshot_2022-09-14_09-31-31](https://user-images.githubusercontent.com/52286285/190077059-70db7969-c0db-480a-be8c-9a6325168a1b.png)

**Comment by akinomyoga** [comment]
It is currently not supported, but I think we can support it in some way.

**Comment by akinomyoga** [comment]
I have experimentally supported it (not yet pushed to master), but I'm not sure if this is actually what you expect. Currently, it looks like the following:

![image](https://user-images.githubusercontent.com/8982192/190320559-0209e2b8-9f67-47cd-b403-e8ac1e377e6d.png)

@bbyfacekiller Is this something you expected? Or do you actually expect something different? Let me hear what you think.

**Comment by bbyfacekiller** [comment]
This looks great! This is exactly what I've been expecting. Thank you for your work, for this tool you are creating!

**Comment by akinomyoga** [comment]
Thank you for checking! I have pushed the commit 60b6989. Could you see if it works in your environment? Thank you!

**Comment by bbyfacekiller** [comment]
Works great! Thanks a lot!

**Comment by akinomyoga** [comment]
Thank you!
