### ISSUE TITLE
`bash: DEBUG warning: run_pending_traps: recursive invocation while running trap for signal 28` when resizing terminal

### ISSUE THREAD

**Issue by StavromulaBeta** [akinomyoga/ble.sh#234]
GNU bash, version 5.2.0(1)-rc2 (x86_64-pc-linux-gnu) [Debian GNU/Linux bookworm/sid]
ble.sh, version 0.4.0-devel3+793dfad (noarch)
locale: LANG=en_GB.UTF-8
terminal: TERM=st-256color wcwidth=13.0-west/14.0-2+ri

When I resize (enlarge or make smaller) the terminal, the message `bash: DEBUG warning: run_pending_traps: recursive invocation while running trap for signal 28` is printed to the screen many times such that it fills the entire display. I have tested this in both st and lxterminal.

**Comment by akinomyoga** [comment]
I feel this is just a warning that is used to debug Bash itself. The error message is produced at [trap.c#L316 @ bash devel](https://git.savannah.gnu.org/cgit/bash.git/tree/trap.c?h=devel#n316) using the function [`internal_debug` (error.c#L299)](https://git.savannah.gnu.org/cgit/bash.git/tree/error.c?h=devel#n299), but this function only outputs messages [when Bash is compiled with `DEBUG`](https://git.savannah.gnu.org/cgit/bash.git/tree/error.c?h=devel#n306).

**Comment by StavromulaBeta** [comment]
ah I see, strange that Debian is shipping a debug version of bash. Maybe it's because I'm on unstable

**Comment by akinomyoga** [comment]
Oh, so Debian unstable distributes rc2. Bash 5.2 is not released yet, and "rc2" in the version string stands for *the second release candidate*, which is a debug version. By the way, the latest debug version is "rc4". I'm also testing ble.sh in debug versions of Bash, but these are what I manually built from the git repository of Bash.

**Comment by StavromulaBeta** [comment]
ah I see that makes sense - sorry for creating so many issues!!!

**Comment by akinomyoga** [comment]
No worries!
