### ISSUE TITLE
Warning(bash version) について

### ISSUE THREAD

**Issue by taiseiyo** [akinomyoga/ble.sh#236]
扱いやすいツールを作成して頂きありがとうございます。**ble.sh** 毎日愛用させて頂いてます。
現在、ble.sh を起動すると以下のような warning が表示されます。現在、WSL を使用しているので
bash のバージョンが自動で version up するまで待っておけば良いでしょうか。

もしこの warning を解決する方法があれば教えて頂ければと思います。

```
ble.sh may become very slow because this is a debug version of Bash 
(version '5.2.0(1)-rc2', release status: 'rc2'). 
We recommend using ble.sh with a release version of Bash.          
```

**Comment by akinomyoga** [comment]
こんにちは。ble.sh を使っていただきありがとうございます!

Warning のメッセージを見るにお使いの Bash のバージョンは 5.2.0(1)-rc2 であり、これは未だリリースされていない Bash 5.2 の 2つ目の release candidate (rc) です。なので、Bash 5.2 がリリースされた後にディストリビューションの側でそれが反映されると思うのですが、その後にパッケージのアップデートを行った際に Bash がリリースバージョンに置き換わると思います。

従って、待っておけば良いというのはその通りです。ただし、実際にどれだけ待てば良いのかは未だ分かりません。rc2 が出たのが2ヶ月程前で、10日前に rc4 が出ています。最近は rc の問題のレポートも出てこなくなったので、恐らくそろそろ次が本当のリリースになるのではないかという気がしています。もしそうなら一ヶ月以内にリリースされるような気がしますが、実の所よく分かりません。

もし何日も待てなければ、Bash の最新のリリース版 (5.1.16) を https://ftp.gnu.org/gnu/bash/ からダウンロードしていただいて自前でビルドしてお使いいただくのが良いように思います。

----

WSL の上にどの Linux ディストリビューションを入れて使っていらっしゃいますか。Bash のバージョンは WSL 自体が決めている訳ではなくて、その上にパッケージを提供しているディストリビューションが決めています。本来は、rc はリリース前のものであり Bash 自体のデバグ用のコードが埋め込まれているので、ディストリビューションで配布するべきようなものではない気がするのですが、どうも Debian Sid (unstable) が rc 版を配布しているみたいです。

一方で、デバグ用のコードが有効になっている rc 版の Bash の上で ble.sh を動かそうとすると現実的な速度では到底動かないように思うのですが、お使いいただいていかがでしょうか。表示している警告メッセージはそのことを注意しているものです。しかし、もしかするとディストリビューションの側でビルドフラグを指定してデバグ用のコードの一部を無効にした rc 版を配布している可能性もあります。もしそうであればそれを検出して、その時に限り rc 版でも warning を表示しないように ble.sh の側を調整することも可能かもしれません。以下のコマンドの結果として表示される内容を教えていただければ幸いです。

```bash
$ grep ^CFLAGS= "${BASH}bug" 
```

**Comment by taiseiyo** [comment]
丁寧にご回答して頂きありがとうございます。
Linux ディストリビューションとして /etc/os-release の内容を貼りつけさせて頂きます。

```
PRETTY_NAME="Debian GNU/Linux bookworm/sid"                                                      
NAME="Debian GNU/Linux"                                                                          
ID=debian                                                                                        
HOME_URL="https://www.debian.org/"                                                               
SUPPORT_URL="https://www.debian.org/support"                                                     
BUG_REPORT_URL="https://bugs.debian.org/"  
```

また、grep command の結果は以下のようになっています。
```
grep: /bin/bashbug: No such file or directory
```

ご返信お待ちしております。

**Comment by akinomyoga** [comment]
早速のお返事ありがとうございます!

まさに Debian sid のようですね。更に bashbug をパッケージに含めていないのですね…と思ったら別のパスにあるのですね。。今手元で Bash の rc2 のデバグ用コードを on にしたものと off にしたものを実際にビルドして確認してみたのですが、どうやら bashbug の `CFLAGS` (またはその他の変数) にはその設定は記録されないみたいです…。お手数をおかけしてすみませんが次のコマンドの結果も教えていただけますか。

```bash
$ strings "$BASH" | sort -u | grep malloc
```

あと実際に rc2 の上でお使いいただいて、コマンド入力に対する応答速度などについて遅いなどの違和感はありますか。

**Comment by taiseiyo** [comment]
以下結果になります。

```
malloc_trace_at_exit
xmalloc
xmalloc: size argument is 0
```

今の所、長いコマンド等を打つと固まる場合があるという感触です。
普段扱う分に関しては、扱う事ができないという程ではないかなという感じです。

**Comment by akinomyoga** [comment]
ありがとうございます!

長いコマンドで遅くなってしまうのは普通の Bash でもあることですね。普段遣いで扱えない程ではないということであれば、やはりデバグ用のコードは除去した上で rc2 を配布しているのだという気がします。そうだとすると、それを検出できたら warning は表示しないというようにしたいですね。

`grep malloc` の結果についてはどうもこちらの手元と結果が異なるみたいです。

<details><summary>こちらの手元ですと <code>strings ... | sort -u | grep malloc</code> はこのような結果になります。</summary>

```
# 普通にビルドした rc2 の時
Total mallocs: %d, total frees: %d, total reallocs: %d (%d copies)
_imalloc_fopen
_malloc_block_signals
_malloc_ckwatch
_malloc_nwatch
_malloc_trace_buckets
_malloc_unblock_signals
fprint_malloc_stats
malloc: %p: %s: last %s from %s:%d
malloc: %s:%d: assertion botched
malloc: %s:%d: warning: request for %d bytes not aligned on %d byte boundary
malloc: block on free list clobbered
malloc: watch alert: %p %s
malloc_bucket_stats
malloc_flags
malloc_free_blocks
malloc_mmap_threshold
malloc_register
malloc_set_register
malloc_set_trace
malloc_set_tracefn
malloc_set_tracefp
malloc_trace
malloc_trace_at_exit
malloc_trace_bin
malloc_unwatch
malloc_usable_size
malloc_watch
sh_malloc
sh_xmalloc
trace_malloc_stats
xmalloc
xmalloc: %s:%d: size argument is 0
xmalloc: size argument is 0

# デバグ用コードオフ (make DEBUG= MALLOC_DEBUG=) の時
_malloc_block_signals
_malloc_unblock_signals
malloc: %s:%d: assertion botched
malloc: block on free list clobbered
malloc_flags
malloc_mmap_threshold
malloc_register
malloc_trace
malloc_trace_at_exit
malloc_usable_size
sh_malloc
sh_xmalloc
xmalloc
```
</details>

何かもっと異なる種類の細工をした rc2 を配布しているのかもしれません。なのだとすると、この方法で検出できるかどうかはちょっと微妙ですね。。

**Comment by akinomyoga** [comment]
恐らく Debian sid で配布されている rc2 で問題なく動くので、一番簡単な方法は「Bash 5.2 がリリースされるまで一時的に各々 ble.sh を書き換える」ということかもしれません。その場合には [ble.pp L843..849](https://github.com/akinomyoga/ble.sh/blob/49e55f40dc09cff0fa6412e4a8971cac61dd2dbe/ble.pp#L843-L849) をコメントアウトすれば良いです (ble.sh をアップデートする時には元に戻す必要はあります)。

**Comment by taiseiyo** [comment]
了解しました。丁寧に対応して頂きありがとうございました！

**Comment by akinomyoga** [comment]
余りお力になれずすみません。こちらこそ御報告いただきありがとうございました! 取り敢えず閉じさせていただきますね。

**Comment by akinomyoga** [comment]
- bash-5.2-release frozen: [bdfa4b08@bash.git - "minor updates for release"](https://git.savannah.gnu.org/cgit/bash.git/commit/?h=devel&id=bdfa4b088eb4c35bdaff832d7e18b3159953986f)

**Comment by taiseiyo** [comment]
お世話になっています。上記に関してですが、bash-5.2 が release され使用可能になったのでしょうか？

また、release されている場合ソースはどこから取得する事ができるのでしょうか？

**Comment by taiseiyo** [comment]
確認してみた所 bash-5.2.0-rc4 でした

**Comment by akinomyoga** [comment]
お騒がせしてすみません! 未だリリースされていません。リリース状況を追跡しようと思っていて、今は丁度、一番上流で Bash 5.2 リリース版確定のコミット (上記リンク) が入った段階です。恐らく数日の内にマスターに反映されて、リリースされて、アナウンスされるのではないかと思います。Bash は以下で公開されていて、ここに `bash-5.2.tar.gz` が追加されます。

- [Index of /gnu/bash](https://ftp.gnu.org/gnu/bash/)

その後で Debian sid の Bash 担当の人が Bash 5.2 にパッケージを更新した後に、ユーザーの手元でパッケージを更新した時に反映されると思いますが、これにはまた時間がかかるかもしれません。Debian sid の Bash パッケージについては以下で状況が確認できます。

- [bash (Debian sid)](https://packages.debian.org/ja/sid/bash)

**Comment by taiseiyo** [comment]
情報詳細に共有して頂いてありがとうございます。

一旦 bash の新 version が公開された段階でバージョンを上げてみて ble.sh を試してみようと
思います。

**Comment by akinomyoga** [comment]
Bash 5.2 リリースされました: [bug-bash 2022-09 \#56](https://lists.gnu.org/archive/html/bug-bash/2022-09/msg00056.html)

**Comment by taiseiyo** [comment]
- https://ftp.gnu.org/gnu/bash/bash-5.2.tar.gz

上記の bash-5.2 では、error が消えないという感じでした。
bash のバージョンが 5.2.0(1)-release となっていますが何が原因なのでしょうか？

**Comment by akinomyoga** [comment]
うーん。私もそのバージョンをインストールして試していますが、こちらの手元ですと警告は表示されていませんね。<kbd>C-x C-v</kbd> を押した時に何が表示されますか。

**Comment by taiseiyo** [comment]
特になにも表示されませんでした。

**Comment by akinomyoga** [comment]
それは何か変ですね (念の為 C-x C-v は Bash を開いた状態で Bash に対して、ということでしか)。代わりに以下ではそうですか。

```bash
$ echo "$BASH"
```

**Comment by taiseiyo** [comment]
```
/bin/bash
```
となっています

**Comment by taiseiyo** [comment]
```
ble.sh may become very slow because this is a debug version of Bash
  (version '5.2.0(1)-rc2', release status: 'rc2').
  We recommend using ble.sh with a release version of Bash.
```

これを見ている感じ、ble.sh が旧バージョンを認識していそうなのですが
これについて問題ないでしょうか？

**Comment by taiseiyo** [comment]
```
GNU bash, version 5.2.0(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

現在のバージョンは上記のようになっています。一応、bash のリロードまた、
ble-update は既に行っております。

**Comment by akinomyoga** [comment]
> ```
> /bin/bash
> ```
>
> となっています

あ、だとしたらユーザー側での設定が足りていないという状況でございます。

`/bin/bash` はディストリビューションに付属している Bash なので、Bash-5.2-rc2 のままです。`bash-5.2.tar.gz` でインストールした時の構成によりますが、デフォルトの構成ですと tarball からインストールする場合、`/usr/local/bin/bash` に配置されます。なので、ユーザーの設定でログインシェルを `/usr/local/bin/bash` に変更する必要があります。

**Comment by taiseiyo** [comment]
```
which bash
/usr/local/bin/bash
```

```
bash --version
version 5.2.0(1)-release (x86_64-pc-linux-gnu)
```

ログインシェルを変更しましたがまだ、ble.sh の方で上記のエラーがでてきます。

**Comment by akinomyoga** [comment]
> ```
> which bash
> /usr/local/bin/bash
> ```
> 
> ```
> bash --version
> version 5.2.0(1)-release (x86_64-pc-linux-gnu)
> ```

残念ながら `which bash` や `bash --version` で見つかる bash と、ログインシェルとして何が設定されているかは関係ないんですよね。これらは別個の設定に依存しています。

> ログインシェルを変更しましたがまだ、ble.sh の方で上記のエラーがでてきます。

うーん。不思議ですね。端末は何を使っていますか。一つの可能性なのですが、普通だと端末はログインシェルを起動するのですが、もしかすると環境変数 `SHELL` を参照している端末があったら、システムを再起動しないと反映されないという可能性もあります。

**Comment by taiseiyo** [comment]
おっしゃる通りシステムを再起動するとエラーメッセージがなくなりました。
長い間サポートして頂きありがとうございました。

**Comment by akinomyoga** [comment]
良かったです!

(本来はログインシェルを変更した時点で反映されるべきで、その端末の振る舞いがちょっと変な気もしますが…)

**Comment by taiseiyo** [comment]
WSL を使用しているのでここに問題があるような気もします

**Comment by akinomyoga** [comment]
今幾つか端末の実装を調べていたのですが、すみません、ログインシェルの方が優先されるべきというのは私の勘違いみたいです。調べた端末はほぼ全て優先順位的に (環境変数 `SHELL`) > (ログインシェル) > `/bin/sh` となっている様です (st, terminology, mintty, wezterm, tmux)。今のところ libvte (GNOME Terminal, etc) のみが (ログインシェル) > (環境変数 `SHELL`) > `/bin/sh` です。因みに urxvt は (環境変数 `SHELL`) > `/bin/sh` であって、ログインシェルは確認しないみたいです。

なるほど WSL は色々と取り扱いが異なりそうです。
