### ISSUE TITLE
[starship] `prompt_rps1` prints above `ps1`

### ISSUE THREAD

**Issue by rashil2000** [akinomyoga/ble.sh#239]
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-msys) [MSYS2]
ble.sh, version 0.4.0-devel3+a144ffa (noarch)
bash-completion, version 2.11 (hash:4022782d30a6bf29434ba700d5207e8f936e0c37, 76765 bytes) (noarch)
fzf key-bindings, version +04d0b022 (noarch) (integration: on)
starship, version 1.10.3-master (rustc 1.63.0 (4b91a6ea7 2022-08-08),stable-x86_64-pc-windows-msvc 2022-09-08 17:12:28 +00:00)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.0-2+ri, wt:0 (0;10;1)
```

I'm trying to integrate some advanced functionalities of [starship](https://github.com/starship/starship) into ble.sh, but running into a weird problem. My left side starship prompt contains 2 lines, and what I see is that when I set ble.sh's `prompt_rps1`, it gets printed above the PS1 line, instead of below it:

![image](https://user-images.githubusercontent.com/46838874/193552828-0f208f84-cae3-4da7-8fa2-719d9f906773.png)

The correct location should be below the PS1 line (and on the right side of cursor), as seen in the pwsh and cmd shells below:

![image](https://user-images.githubusercontent.com/46838874/193553278-f6e7626d-e3cf-4086-aee9-48e502f08aa8.png)

![image](https://user-images.githubusercontent.com/46838874/193553074-36adddb1-f126-4e02-bbdd-0a9e72a72e6c.png)

How should I fix this?

My starship config file can be found here: https://github.com/rashil2000/dotfiles/blob/master/starship/starship.toml

**Comment by akinomyoga** [comment]
Thanks for the report! I'll later set up `starship` and check this (probably a few days later), but may I ask why don't you put [the right-aligned part of the first line](https://github.com/rashil2000/dotfiles/blob/7ca84c86beeef9f9e16dd9417eebc36b3f136894/starship/starship.toml#L10-L15) in the right prompt?

**Comment by rashil2000** [comment]
The way the left and right prompts work is like this:

- `format` option - this is for anything that starts from the very left side of the terminal, up until the cursor (i.e. _before_ the cursor). So, it can contain segments, newlines, fillers and any supported option.
- `right_format` option - this is for anything that comes _after_ the cursor, up until the very right side of the terminal.

So you see, the command duration, env var and other related segments should be in the `format` option, if I want to see them on the left of the cursor (left here means anywhere on the left, including the lines before and above the cursor).

**Comment by akinomyoga** [comment]
Thank you for the explanation! So, it means that the layout models of starship and ble.sh are completely different from each other. If you don't want to prepare a separate `starship` configuration for ble.sh but want to use the existing starship configuration as is, I think I need to implement a new mechanism in `ble.sh` (independent of the existing rps1) to directly support it.

Hmm, I found the environment variable [`STARSHIP_CONFIG`](https://starship.rs/config/#prompt) for `starship` configuration. Couldn't we use this to generate rps1 for ble.sh?

**Comment by rashil2000** [comment]
> I experimented with this approach. Could you check the attached configuration?
> 
> * [sample.zip](https://github.com/akinomyoga/ble.sh/files/9697717/sample.zip)
> 
> To try it, you can put `starship-left.toml` and `starship-right.toml` in `~/.config` and copy the content of `blerc` in your `~/.blerc`.

I tried it, and it works. 

But ideally speaking, I would like to implement it in a way so that people don't have to modify their starship.toml files (specifically for bash, because they might be using some other shell too). I was thinking of perhaps modifying starship's bash init script by adding this:
```bash
if [[ ${BLE_VERSION-} ]]; then
    bleopt prompt_rps1="$(starship prompt --right)"
    # some other stuff, like transient prompt
    # and transient right_prompt
    # ...
fi
```

(for reference, you can check out init scripts for other shells here: https://github.com/starship/starship/tree/master/src/init where many of the advanced features are implemented)


Since ble.sh's `rps1` implementation is independent of cursor position (from what I understand), perhaps we can specify a vertical offset for the `prompt_rps1`? That is, the total height of left prompt, so that `rps1` gets drawn at the correct y-position. (Since starship's `right_format` does not allow newlines, we only have to worry about left prompt's height, which can be calculated easily. This method is already being used in the [pwsh init script](https://github.com/starship/starship/blob/master/src/init/starship.ps1#L157).).

**Comment by aiotter** [comment]
@rashil2000 Don't you enable [`add_newline` config](https://starship.rs/config/#prompt) on your `starship.toml`? This adds newline character at the beginning of `PS1`.
I don't have the same problem you have despite the fact I use the same config with `prompt_rps1`. Note that `add_newline` is set to `true` by default.
You can get the similar output as `add_newline=true` by `bleopt prompt_ruler='empty-line'`.

**Comment by rashil2000** [comment]
> Note that `add_newline` is set to `true` by default.

Okay, so I added `add_newline = false` in my config file, but now I don't see the rps1 at all 😅

![image](https://user-images.githubusercontent.com/46838874/194815262-40bd6be0-4d36-4737-9f87-34b8b0275ea8.png)

**Comment by aiotter** [comment]
That's because you use `$fill` module. As your left prompt takes full width, there is no more room for ble.sh to show right prompt.
Are you sure your that your right prompt is correctly shown along with that left prompt with `$fill` module on other shells like `zsh` or something?

**Comment by rashil2000** [comment]
Yes, they all work as expected. `add_newline` doesn't affect rprompt:

![image](https://user-images.githubusercontent.com/46838874/194822918-e69c8cfb-942a-42fb-9b06-4b7242319eb3.png)

**Comment by aiotter** [comment]
Showing `$RPROMPT` at the bottom seems the default behaviour of `zsh`. I don't know about any other shells thou.

```zsh
# ~/.zshrc
PROMPT="THIS IS PROMPT
$ "
RPROMPT="THIS IS RPROMPT"
```
<img width="461" alt="image" src="https://user-images.githubusercontent.com/37664775/194834799-0510d80f-734b-4891-b697-aa062083a7c3.png">

On the other hand, ble.sh shows `prompt_rps1` at the top.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/37664775/194835656-43a65ce9-2d5b-4704-a279-d488fea6390d.png">


If zsh way is the de facto between the shells, ble.sh might better follow it.

**Comment by akinomyoga** [comment]
Sorry for the delay. I confirmed that there is a bug in the coordinate calculation of rps1. But I think the fix might further delay until around Oct 20 (I may lose the internet connection because I'm in the middle of trip to a workshop held in a mountain area).

**Comment by akinomyoga** [comment]
I'm sorry for the long blank. I have been busy recently. Now I took time to fix stacking issues of ble.sh. As I mentioned in the previous reply, there was a bug in the coordinate calculation of `prompt_rps1`, and I fixed it in commit [`cdf74c2`](https://github.com/akinomyoga/ble.sh/commit/cdf74c24d678d5afec98491b4b97850e8bda030e#diff-30e60cf46b3920efe746a5a806da0d726e25206db44de73b18fd9af4a1b111a9L1516-R1520).

After updating ble.sh by running the command `ble-update` in a ble.sh session, now you can adjust the position of `prompt_rps1` by inserting newlines as

```bash
# blerc

blehook PRECMD+='bleopt prompt_rps1="\n\n$(starship prompt --right)"'
```

If you wouldn't want to run the command through the blehook `PRECMD` every time a user command is executed, another way is to define a custom prompt sequence, e.g. `\q{my/starship-right}`, as

```bash
# blerc

function ble/prompt/backslash:my/starship-right {
  local right
  ble/util/assign right 'starship prompt --right'
  ble/prompt/process-prompt-string "$right"
}
bleopt prompt_rps1="\n\n\q{my/starship-right}"
```

**Comment by rashil2000** [comment]
Thanks so much for fixing this! I can confirm both the methods work now. 

Now I just need to find out the number of newlines in the **PS1** and use that in place of `\n\n` so that the function works for all starship configs.

Closing this as solved :)

**Comment by rashil2000** [comment]
Okay, so I was able to incorporate the changes in [bash's init script](https://github.com/starship/starship/blob/master/src/init/starship.bash):

```diff
diff --git "a/.\\nnn" "b/.\\.local\\share\\starship.bash"
index a4cf377..5932257 100644
--- "a/.\\nnn"
+++ "b/.\\.local\\share\\starship.bash"
@@ -57,9 +57,25 @@ starship_precmd() {
         STARSHIP_END_TIME=$(::STARSHIP:: time)
         STARSHIP_DURATION=$((STARSHIP_END_TIME - STARSHIP_START_TIME))
         PS1="$(::STARSHIP:: prompt --terminal-width="$COLUMNS" --status=$STARSHIP_CMD_STATUS --pipestatus="${STARSHIP_PIPE_STATUS[*]}" --jobs="$NUM_JOBS" --cmd-duration=$STARSHIP_DURATION)"
+        if [[ ${BLE_VERSION-} ]]; then
+            nlns_count="${PS1//[!$'\n']/}"
+            RPS1="$(::STARSHIP:: prompt --right --terminal-width="$COLUMNS" --status=$STARSHIP_CMD_STATUS --pipestatus="${STARSHIP_PIPE_STATUS[*]}" --jobs="$NUM_JOBS" --cmd-duration=$STARSHIP_DURATION)"
+            for ((c=1;c<=${#nlns_count};c++)); do RPS1="\n${RPS1}"; done
+            bleopt prompt_rps1="$RPS1"
+        fi
         unset STARSHIP_START_TIME
     else
         PS1="$(::STARSHIP:: prompt --terminal-width="$COLUMNS" --status=$STARSHIP_CMD_STATUS --pipestatus="${STARSHIP_PIPE_STATUS[*]}" --jobs="$NUM_JOBS")"
+        if [[ ${BLE_VERSION-} ]]; then
+            nlns_count="${PS1//[!$'\n']/}"
+            RPS1="$(::STARSHIP:: prompt --right --terminal-width="$COLUMNS" --status=$STARSHIP_CMD_STATUS --pipestatus="${STARSHIP_PIPE_STATUS[*]}" --jobs="$NUM_JOBS")"
+            for ((c=1;c<=${#nlns_count};c++)); do RPS1="\n${RPS1}"; done
+            bleopt prompt_rps1="$RPS1"
+        fi
     fi
     STARSHIP_PREEXEC_READY=true  # Signal that we can safely restart the timer
 }
```

Do you think it can be optimized?

One bottleneck I can see here is that we are calculating the newline count `nlns_count` every time - I feel we can do it just once, at the end of this script - but then the `PS1` variable won't have the desired value there...

**Comment by rashil2000** [comment]
I also created a PR in upstream Starship to recognize ble.sh 💖 - https://github.com/starship/starship/pull/4902

**Comment by akinomyoga** [comment]
Thanks for your suggestion.
