### ISSUE TITLE
delete word (alt-backspace) fails using ble.sh

### ISSUE THREAD

**Issue by KiaraGrouwstra** [akinomyoga/ble.sh#243]
in bash, one may use alt-backspace to erase a whole word.
in ble.sh this seems to fail.
it would be nice if this functionality would work in ble.sh as well.

**Comment by akinomyoga** [comment]
By default, <kbd>Alt-Backspace</kbd> (<kbd>M-DEL</kbd>) copies the previous word in ble.sh. If you would like to make it behave as the same as in the plain Bash, you may rebind it. For example, could you try the following keybinding?

```bash
# blerc

ble-bind -f 'C-M-?' kill-backward-cword
```

**Comment by KiaraGrouwstra** [comment]
thank you, that's perfect!
