### ISSUE TITLE
Appreciation and suggestion :)

### ISSUE THREAD

**Issue by cevhyruz** [akinomyoga/ble.sh#245]
Hi! Thanks for this awesome project!

If you don't mind, Im just wondering what is the principle behind this project? Im doing a simple line editing project but can't think of any way to do it but using only bash `read`.

It also would be awesome if you can provide the link about the zsh article you mentioned in the readme :)

Thanks! This project rocks!

**Comment by akinomyoga** [comment]
Thank you!

> If you don't mind, Im just wondering what is the principle behind this project? Im doing a simple line editing project but can't think of any way to do it but using only bash `read`.

I assume you are asking about how ble.sh reads the inputs from the user. I was once asked about it and other questions on how ble.sh works by [Oil](https://github.com/oilshell/oil/)'s author `@andychu`, and I explained them in several issues and wikis of Oil. I later summarized the answers in [a page](https://github.com/akinomyoga/ble.sh/wiki/Internals) of ble.sh's Wiki. Particularly, I think [this section](https://github.com/akinomyoga/ble.sh/wiki/Internals#processing-user-inputs) answers your question. I also considered the use of `read` builtin, but the reason that I finally did not use it was that the line editor shouldn't stop working even when the shell receives signals but the `read` loop may be killed by signals.

> It also would be awesome if you can provide the link about the zsh article you mentioned in the readme :)

I actually don't remember exactly which articles I read at that time (it's mostly ten years ago after all), but I read several articles then and I think most of them were written in Japanese. When I wrote the history section in README about a year ago, I tried to find the article but couldn't remember which articles they were.

One article I vaguely remember explained Zsh's built-in programming interface of specifying colors that `zsh-syntax-highlighting` relies on. I searched for it again. This is just a guess, but probably it was the following article (use machine translation if needed. I wouldn't translate it for you):

- [zsh 5.0.0 のコマンドラインハイライトを使う - スプーキーズの中の人。](https://blog.spookies.co.jp/entry/blog/zsh-5-0-0-%25e3%2581%25ae%25e3%2582%25b3%25e3%2583%259e%25e3%2583%25b3%25e3%2583%2589%25e3%2583%25a9%25e3%2582%25a4%25e3%2583%25b3%25e3%2583%258f%25e3%2582%25a4%25e3%2583%25a9%25e3%2582%25a4%25e3%2583%2588%25e3)

This article explained an essential part of the interface in a concise form, which helped me a lot in reading the implementation of zsh-syntax-highlighting.

**Comment by akinomyoga** [comment]
@cevhyruz Do you have further questions? If not, can I close the issue?

**Comment by akinomyoga** [comment]
pnig

**Comment by cevhyruz** [comment]
@akinomyoga sorry for the unresponsiveness. there are still pieces I don't understand but I think I can start with something now. currently experimenting with `readline` (It's really hard to find a documentation on this). will close this issue now. 

Thank you so much for this! 

PS: Is it alright if I drop you an email if I have some questions?

**Comment by akinomyoga** [comment]
Thank you for your reply!

> PS: Is it alright if I drop you an email if I have some questions?

Yes, sure! Questions and discussions are welcome, though sometimes I might be busy and slow to respond.
