### ISSUE TITLE
cannot download blesh-git

### ISSUE THREAD

**Issue by Firestar-Reimu** [akinomyoga/ble.sh#247]
I download blesh-git from AUR and:

```
==> Starting prepare()...
Submodule 'contrib' (/home/firestar/.cache/yay/blesh-git/blesh-contrib) registered for path 'contrib'
Cloning into '/home/firestar/.cache/yay/blesh-git/src/ble.sh/contrib'...
fatal: transport 'file' not allowed
fatal: clone of '/home/firestar/.cache/yay/blesh-git/blesh-contrib' into submodule path '/home/firestar/.cache/yay/blesh-git/src/ble.sh/contrib' failed
Failed to clone 'contrib'. Retry scheduled
Cloning into '/home/firestar/.cache/yay/blesh-git/src/ble.sh/contrib'...
fatal: transport 'file' not allowed
fatal: clone of '/home/firestar/.cache/yay/blesh-git/blesh-contrib' into submodule path '/home/firestar/.cache/yay/blesh-git/src/ble.sh/contrib' failed
Failed to clone 'contrib' a second time, aborting
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: blesh-git
```

but blesh 0.3.3 is fine.

**Comment by akinomyoga** [comment]
Thanks for reporting. I already noticed your report in the AUR page, and I just updated the PKGBUILD a few minutes ago. Could you try it again? I'm also going to test it in my local Arch Linux.

**Comment by akinomyoga** [comment]
I confirmed that it now works with my local Arch Linux (with git 2.38.1). @Firestar-Reimu How about it in your environment?

I also replied in the report in the AUR page (https://aur.archlinux.org/packages/blesh-git#comment-887957):
> Thank you for the report. This seems to be the general issue affecting all the AUR packages using "git submodule" as reported in Refs. [1,2]. It is related to the change of the default git configuration in git 2.38.1-1. I just updated PKGBUILD as suggested in these discussions. I confirmed that it now works in my environment.
>
> - [1] https://bbs.archlinux.org/viewtopic.php?id=280571
> - [2] https://bbs.archlinux.org/viewtopic.php?pid=2063104#p2063104
>
> Cross-Reference: https://github.com/akinomyoga/ble.sh/issues/247

**Comment by Firestar-Reimu** [comment]
I can download it now.
