### ISSUE TITLE
After update, EOF marker & error exit marker & elapsed-time marker has gone

### ISSUE THREAD

**Issue by Firestar-Reimu** [akinomyoga/ble.sh#248]
After update, **EOF marker & error exit marker & elapsed-time marker** has gone.

```
[bash @ ArchLinux ~] (11:34:30)
$ date
Fri Nov  4 11:34:33 AM CST 2022
[bash @ ArchLinux ~] (11:34:33)
$ 
```

although I set `~/.blerc` like this:

```
bleopt complete_auto_delay=0

bleopt exec_errexit_mark=$'\e[91m[ble: exit %d]\e[m'

bleopt exec_elapsed_mark=$'\e[94m[ble: elapsed %s (CPU %s%%)]\e[m'
```

**Comment by akinomyoga** [comment]
> After update, **EOF marker & error exit marker & elapsed-time marker** has gone.
> 
> ```
> [bash @ ArchLinux ~] (11:34:30)
> $ date
> Fri Nov  4 11:34:33 AM CST 2022
> [bash @ ArchLinux ~] (11:34:33)
> $ 
> ```

I don't think it worked before the update as you expected. There are specific conditions that the markers are shown. They will be sometimes shown but sometimes not shown. For the above specific case, it is expected that all those markers are not shown:

- The EOF marker is only shown when the previous command output doesn't end with a newline. The `date` command outputs a newline as expected by the POSIX standard for the commands outputting texts, so the marker is not shown.
- The error exit marker is only shown when the previous command fails (i.e., exits with a non-zero exit status). The `date` command always succeeds in a normal situation, so the marker is not shown.
- By default, the elapsed-time marker is only shown for the commands that took a long time to execute. The `date` command finishes instantly, so the marker is not shown.

Currently, there is no way to show the EOF marker even when the command properly ends with a newline.

If you want to always print the error status regardless of the exit status and the output of the previous command, you need to turn off the built-in one and instead print them by yourselves or include it in the prompt:

```bash
bleopt exec_errexit_mark=
blehook POSTEXEC+="printf $'\e[91m[ble: exit %d]\e[m\n' \"\$?\""
```

If you want to always print the elapsed-time marker, you can change the setting `bleopt exec_elapsed_enabled`, which controls the condition to show the elapsed-time marker. To always enable the marker, you can just set `1` to the setting.

```bash
bleopt exec_elapsed_enabled=1
```

> ```bash
> bleopt complete_auto_delay=0
> ```

`complete_auto_delay` is unrelated to the markers.
