### ISSUE TITLE
draw new line when resizing the height of konsole

### ISSUE THREAD

**Issue by Firestar-Reimu** [akinomyoga/ble.sh#249]
**ble version**: 0.4.0-devel3+a144ffa
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu)

I use KDE Konsole + ble.sh and when I drag the edge to resize the height (both bigger and smaller), ble.sh will draw new lines.

![Screenshot_20221109_175706](https://user-images.githubusercontent.com/65082432/201256584-f7171d8d-ec26-4f7d-aa4a-e8a876df3de3.png)

**Comment by akinomyoga** [comment]
This is a duplicate of #142, #154, #173, #168, and #192. This is the intended behavior. To quote the explanation in https://github.com/akinomyoga/ble.sh/issues/173#issuecomment-1026833761,

> This is somewhat an intended behavior. If you would like the behavior the same as Readline, you can use the following setting:
> 
> ```shell
> # blerc
> bleopt canvas_winch_action=redraw-prev
> ```
> 
> The reasoning for the default behavior is explained at [#142 (comment)](https://github.com/akinomyoga/ble.sh/issues/142#issuecomment-950036015). This is related to the general problem of terminal text reflowing. There is a nice summary of the problem in [README of powerlevel10k](https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window).

**Comment by Firestar-Reimu** [comment]
so why not making `bleopt canvas_winch_action=redraw-prev` by default?

**Comment by akinomyoga** [comment]
> so why not making `bleopt canvas_winch_action=redraw-prev` by default?

See the above comment where I already mentioned:

> > The reasoning for the default behavior is explained at [#142 (comment)](https://github.com/akinomyoga/ble.sh/issues/142#issuecomment-950036015).

**Comment by Firestar-Reimu** [comment]
> The default behavior (canvas_winch_action=redraw-here) was not so much changed from before, but I would like to improve the behavior in the future so that it reduces the chances of the prompt reposition as far as the outputs of the previous commands are ensured to be not lost.

Thanks!
