### ISSUE TITLE
[略語展開]複合コマンドの直後で略語展開できない

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#25]
**ble version**: 0.4.0-devel1+64ae8ce
**Bash version**: 5.0.3(1)-release

表題の通りです。略語展開ができない状況を2例ほど挙げます。
（`blerc/complete-load-hook`函数内で`ble-sabbrev f='| foo'`などと登録している）
```console
$ if true; then
> echo 'foo'
> fi f
     ^ ここで展開されない。
```

```console
$ [[ -v BLE_VERSION ]] f
                       ^ ここで展開されない。
```

重箱の隅を突くような指摘で恐縮です……。

**Comment by akinomyoga** [comment]
いつもありがとうございます! ca6e03d 対応しました。ご確認お願いいたします

**Comment by cmplstofB** [comment]
確認いたしました。ありがとうございます。

**Comment by akinomyoga** [comment]
OK。ありがとうございました!
