### ISSUE TITLE
[fzf-completion] completion for cd will remove escape char '\'

### ISSUE THREAD

**Issue by MK-Alias** [akinomyoga/ble.sh#250]
Goodday,

Ble.sh autocomplete removes escape-char `\` from auto-completion when typing cd <TAB>. For example:

```console
.. $ cd ~
~ $ mkdir space\ test
```
Now we have a "space test" directory in our home directory. If we use something like `ls` and use auto-complete we this [dessired] result:

```console
~ $ ls space\ test/
```

But, if we use `cd` and use auto-complete we will have this [undessired] result:

```console
~ $ cd space test/
```

Can this be fixed somehow?

Thanks!

=========================================================================
**ble version**: 0.4.0-devel3+8cb9b84
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu)

```console
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) [Arch Linux]
ble.sh, version 0.4.0-devel3+8cb9b84 (noarch)
fzf key-bindings, (hash:f6797d49b943726015b46ee8d6af610479f9b0bd, 3912 bytes) (noarch)
fzf completion, (hash:4b1e0dba58dca1d6d7d9de510c034aa5e5e52379, 10141 bytes) (noarch) (integration: on)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.0-2+ri, vte:7001 (65;7001;1)
```

**Comment by akinomyoga** [comment]
@MK-Alias Thank you for the report! It turned out to be an issue of the integration with fzf-completion. I have fixed it in https://github.com/akinomyoga/blesh-contrib/commit/e102241466dfda8cf3e7efb6891e223102e0b2a9. Could you update ble.sh by running `ble-update` and see if the problem is solved in your environment? Thank you!

**Comment by MK-Alias** [comment]
After updating the problem was solved!
Thanks alot for fixing it! And the incredible speed in which you've done that!

**Comment by akinomyoga** [comment]
Thank you for checking!
