### ISSUE TITLE
`ble-bind -m 'auto_complete' -f C-RET auto_complete/accept-line` not working

### ISSUE THREAD

**Issue by auwsom** [akinomyoga/ble.sh#262]
`ble-bind -m 'auto_complete' -f C-RET auto_complete/accept-line` is set by default. C-j works to accept the suggestion. However C-RET does not. This should be Control+Enter, no?

I'm actually trying to restore the usage of tab for completion before installing ble.sh. I have to use the arrow key to accept. Tab key accepts only one argument at a time. 

I would like those to be switched. Tab accepts line and arrow accepts each argument.

I'm using Ubuntu latest 22.04 with KDE Konsole.

`ble-bind -m 'auto_complete' -f S-RET auto_complete/insert` also doesnt seem to do anything. The Enter key just sends what has been written, "ech" for example.

I tried `ble-bind -m 'auto_complete' -f TAB auto_complete/insert-on-end`, but it didnt work.

**Comment by akinomyoga** [comment]
> `ble-bind -m 'auto_complete' -f C-RET auto_complete/accept-line` is set by default. C-j works to accept the suggestion. However C-RET does not. This should be Control+Enter, no?
>
> [...]
>
> `ble-bind -m 'auto_complete' -f S-RET auto_complete/insert` also doesnt seem to do anything. The Enter key just sends what has been written, "ech" for example.

Yes, <kbd>C-RET</kbd> corresponds to <kbd>Control+Enter</kbd>. However, as mentioned in [README §3.3](https://github.com/akinomyoga/ble.sh#33-use-auto-complete), <kbd>C-RET</kbd> (and also <kbd>S-RET</kbd>) can be used as a distinct key combination *only when your terminal supports it*. The details are explained in [Manual §3.6.4](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#364-settings-for-terminals-without-modifyotherkeys-feature).

- For example, if the terminal capability `modifyOtherKeys` is supported by your terminal and is activated, <kbd>C-RET</kbd> is sent from the terminal in a way that it can be distinguished from <kbd>RET</kbd>.
- In kitty terminal, kitty's keyboard protocol can be used as a replacement of `modifyOtherKeys`.
- In the terminals that accept the configuration of the escape sequence sent by each key combination, the user needs to manually set up the corresponding escape sequences that the user would like to use. KDE Konsole, which you are using, actually supports this!
 
The configuration in KDE Konsole is explained in https://github.com/akinomyoga/ble.sh/issues/187#issuecomment-1107551319. You can look up the corresponding escape sequences for <kbd>C-RET</kbd> and <kbd>S-RET</kbd> in the second table of [Manual §3.6.4](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#364-settings-for-terminals-without-modifyotherkeys-feature). For the KDE Konsole configuration, these are represented as `\E[13;5u` and `\E[13;2u`, respectively. You may also add other missing key combinations.

> I tried `ble-bind -m 'auto_complete' -f TAB auto_complete/insert-on-end`, but it didnt work.

This is explained in [Manual §3.1.1](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#311-representation-of-ret-esc-tab-bs-del-and-c-bs). As your terminal does not support `modifyOtherKeys`, you need to use `C-i` to specify the <kdb>Tab</kbd> key. `TAB` and `C-i` are distinguished in ble.sh to allow users to assign different widgets to each in the capable terminals, but if you would like to make it work consistently in all the terminals, you can bind the same widget to both as

```bash
ble-bind -m 'auto_complete' -f TAB auto_complete/insert-on-end
ble-bind -m 'auto_complete' -f C-i auto_complete/insert-on-end
```

**Comment by auwsom** [comment]
@akinomyoga Thank you. I figured there was a setting for it. It seems you have really thought deeply about all the configuration of ble. I will look through the settings you suggested and keep this page for reference. So far the last command you suggested works beautifully, so thanks for that!

**Comment by akinomyoga** [comment]
Thank you for the report! I think I later need to add the links to these manual sections in README.
