### ISSUE TITLE
Different colors for different folders on the path in the prompt?

### ISSUE THREAD

**Issue by linwaytin** [akinomyoga/ble.sh#265]
First, this is an AMAZING library! The bash team should consider including this tool officially.

I also like the `time-elapsed` function in `contrib`. This is so useful for people doing numerical work. 

One quick question: I usually want to know the path relative to $HOME, which can be done by `\W` in `PS1`. When the working directory is deep inside some project, the output string becomes long and hard to read. I know there are many packages like `powerline` which can separate different folder levels in fancy ways, but is there a simple way to do that in `blesh`?

I think just using different colors for different folders can make the output quite readable.

**Comment by akinomyoga** [comment]
Thank you for trying ble.sh!

> which can be done by `\W` in PS1.

I guess `\w`? I think `\W` shows always the directory name of the top level, but not the path.

> I know there are many packages like powerline which can separate different folder levels in fancy ways, but is there a simple way to do that in blesh?

I think the answer depends on what you are looking for exactly, but for example,

- If you would like to use some of the powerlines themes or similar, you can simply use them with ble.sh.
- If you would like to trim directory names to show a smaller number of levels, you can set a variable `PROMPT_DIRTRIM` (which is a built-in feature of the plain Bash).
- If you would like to write your own prompt that shows the current path in a different way, you can embed the command substitution `$(...)` that produce the desired result. 
- If you would like to define a new prompt sequence of `\q{...}`, you can refer to [Manual §4.12.2](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#4122-user-defined-prompt-sequences).
- If you are asking whether there is already an existing special prompt sequence for that in ble.sh, the answer is no, though I can implement it newly if you could provide more details about the design.

> I think just using different colors for different folders can make the output quite readable.

There is no existing feature for this. If you would like to implement it by yourself, you could consider `$(...)` or `\q{...}` listed above.

If you would like to request for the feature, I think I can implement it in `contrib` but would like to have detailed explanation about the behavior in that case. For example, how the colors of the different directory levels should be determined? Would these colors be pre-defined, configurable, or random? If it would be random, how the set of colors from which a color is picked should be determined, etc.

**Comment by linwaytin** [comment]
> I guess `\w`? I think `\W` shows always the directory name of the top level, but not the path.

Yes, I meant `\w`. You can see I'm not familiar with bash lol.

Roughly speaking, I want the path showed like `~/dir1/dir2/dir3/...`, where `dir1`, `dir2`, `dir3`... have different colors. What colors should be used is a problem, as you said. I think it might be a good idea to used gradient. For example, the upper directory has `fg=255`, and the next upper level has `fg=254`, and so on till maybe the 10th upper level, and then with fixed color `fg=245`. Usually I care more about upper levels closer to the current directory, so this might be a good visual guide.

I'm not sure how to specify the colors, and need to play with different settings, but the first thing is how to implement different colors for different parts of the path. I guess since `\w` returns the string for the path, we can split the string and give a new one with color specifiers? If you could implement some function like this, it would be great. Otherwise could you please tell me about the direction I should go? You mentioned `$(...)` or `\q{...}`. Which one is better?

Thanks a lot. I really appreciate this work.

**Comment by akinomyoga** [comment]
> Otherwise could you please tell me about the direction I should go? You mentioned `$(...)` or `\q{...}`. Which one is better?

It depends. If you would like to use it also without ble.sh, you need to use `$()` because `\q{...}` is an extension by ble.sh. If you use it only with ble.sh, `\q{...}` is efficient and faster.

This is an example of defining `\q{linwaytin/pwd}`:

```bash
# blerc

_ble_contrib_linwaytin_pwd_gspecs=(fg=27 fg=57 fg=141 fg=63)

function ble/prompt/backslash:linwaytin/pwd {
  ble/prompt/unit/add-hash '$PWD'
  ble/prompt/.update-working-directory
  local str=$prompt_cache_wd

  local -a dirs=()
  while ble/string#match "$str" '^([^/]*/|[^/]+$)'; do
    ble/array#push dirs "$BASH_REMATCH"
    str=${str:${#BASH_REMATCH}}
  done

  local count=${#dirs[@]}
  local n=${#_ble_contrib_linwaytin_pwd_gspecs[@]} index ret
  for dir in "${dirs[@]}"; do
    ((index=--count,index<n||(index=n-1)))
    ble/prompt/process-prompt-string "\g{${_ble_contrib_linwaytin_pwd_gspecs[index]}}"
    ble/prompt/.escape-control-characters "$dir"
    ble/prompt/print "$ret"
  done
  ble/prompt/print "$_ble_term_sgr0"
  return 0
}

PS1='\q{linwaytin/pwd}'
```

where the used colors can be specified to the array `_ble_contrib_linwaytin_pwd_gspecs`. The first element is used for the rightmost directory name, i.e., the current directory basename, the next element is used for the second last path segment, etc.

**Comment by linwaytin** [comment]
This is much more complicated than I thought. I'm not able to make it by myself soon. Thank you so much. 

The result is great! 
![](https://i.imgur.com/cw8IfZ2.png)
