### ISSUE TITLE
[openSUSE inputrc] How do I use heredoc? (cat << EOF)

### ISSUE THREAD

**Issue by Ultra980** [akinomyoga/ble.sh#268]
Hello, I just switched to `bash` and `ble.sh`, and aside from POSIX and scripting one of the reasons for me was heredoc (`cat << EOF`). However, I saw that this doesn't work:

```bash
$ cat << EOF
bash: warning: here-document at line 5 delimited by end-of-file (wanted `EOF')
{ ble-edit/exec:gexec/.save-lastarg; } &>/dev/null
```

I saw some references to heredoc in the code, but I don't know how to start the heredoc editor. Is there a special command or keyboard shortcut?

**Comment by akinomyoga** [comment]
Thank you for the report! Hmm, it's supposed to work without special command or keyboard shortcut if you write `cat << EOF` and then press <kbd>RET</kbd>. We need more information about your situation.

- **Q1**: Could you provide us with the output of the following command?

```bash
$ ble/widget/display-shell-version
```

Maybe your terminal sends `\n` (<kbd>C-j</kbd>) instead of `\r` (<kbd>C-m</kbd>, <kbd>RET</kbd>)  when you press <kbd>Enter</kbd> or <kbd>Return</kbd>.

- **Q2**: What is your terminal? Do you set up some special escape sequences for the key Return/Enter?

Another possibility is that \r is converted to \n by a setting of the TTY handler.

- **Q3**: What is the result of the following command?

```bash
$ stty -a
```

Even another possibility would be that you set up a custom keybinding in Bash for <kbd>RET</kbd> (through `bind` in `~/.bashrc`, `~/.inputrc`, the system `/etc/inputrc`, etc.)

- **Q4**: What is the result of the following command?


```bash
$ ble-bind -m emacs -P | grep C-m       # <-- if you are using the emacs editing mode
$ ble-bind -m vi_imap -P | grep C-m     # <-- if you are using the vi editing mode
```

**Comment by Ultra980** [comment]
* A1:
```
GNU bash, version 5.2.15(1)-release (x86_64-suse-linux) [openSUSE MicroOS]
ble.sh, version 0.4.0-devel3+e3cdb9d (noarch) [git 2.39.0, GNU Make 4.4, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.1.1-p1, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:37a0fec4e27779dc87253aa7f27cfa8d14d6a4a6, 77846 bytes) (noarch)
starship, version 1.12.0-master (rustc 1.65.0 (897e37553 2022-11-02), 2022-12-13 16:12:30 +00:00)
locale: LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-musl/15.0-2+ri, xterm:115 (1;115;0)
```
* A2: I'm using konsole, I haven't changed any keybinds in it.
* A3: 
```
speed 38400 baud; rows 20; columns 138; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z;
rprnt = ^R; werase = ^W; lnext = <undef>; discard = <undef>; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```
Eol (which I assume is end of line) and eol2 are both <undef>, could this be the problem?
I also haven't set any custom keybindings in the mentioned files.

* Q4:
```
ble-bind -m 'emacs' -f 'C-m' 'accept-line'
```

* Q4':
```
ble-bind -m 'emacs' -f 'RET' 'accept-single-line-or-newline'
ble-bind -m 'emacs' -f 'C-RET' 'accept-line'
ble-bind -m 'emacs' -f 'M-RET' 'newline'
```
It seems like M-RET is the keybinding for newline. Indeed, heredoc does work if I press Alt+Enter instead of enter.

**Comment by Ultra980** [comment]
If it helps, this is my `.bashrc`:

```bash
test -s ~/.alias && . ~/.alias || true
export PATH=$PATH:/usr/bin
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/home/ultra/.local/bin:/home/ultra/bin:/usr/bin:/home/ultra/.cargo/bin
export GPG_TTY=$(tty)
source ~/.local/share/blesh/ble.sh
eval "$(starship init bash)"
alias cls="clear"
alias dben="distrobox-enter"
alias cls="clear"
alias exa="exa --icons"
alias dbex="distrobox-export --export-path ~/.local/bin --bin "
alias trupd="sudo transactional-update"
alias szi="sudo zypper in"
alias sz="sudo zypper"
alias sam="git commit -sam"
export GPG_TTY=$(tty)
```

**Comment by Ultra980** [comment]
Also, I don't know why the terminal would send `\r`, wasn't that windows-only?

**Comment by akinomyoga** [comment]
> * A1:

Thanks, I will also try openSUSE later to see if the behavior is reproduced.

> * A2: I'm using konsole, I haven't changed any keybinds in it.

Thanks for the information. I now tried `konsole` in Fedora 37 Server, but the problem doesn't seem to be reproduced.

> * A3:

Thanks. I took diff of the output with mine, but there seem to be no relevant differences.

> Eol (which I assume is end of line) and eol2 are both , could this be the problem?

I don't think this would cause the problem. `eol` and `eol2` seem to be typically set to non-trivial key combinations such as <kbd>M-DEL</kbd> in 8-bit transmission mode, which wouldn't be usually used in modern terminals.

> I also haven't set any custom keybindings in the mentioned files.

Even if you do not set up any, the distribution can set something non-trivial in the system inputrc or in the `skel` ~/.inputrc. In fact, openSUSE provides some non-trivial keybindings in `/etc/inputrc` and `/etc/inputrc.keys`. Hmm, but looking at the result of Q4 and Q4', I think this is not the issue.

> * Q4:
> 
> ```
> ble-bind -m 'emacs' -f 'C-m' 'accept-line'
> ```
> 
> * Q4':
> 
> ```
> ble-bind -m 'emacs' -f 'RET' 'accept-single-line-or-newline'
> ble-bind -m 'emacs' -f 'C-RET' 'accept-line'
> ble-bind -m 'emacs' -f 'M-RET' 'newline'
> ```

OK, these results are normal.

> If it helps, this is my .bashrc:

Thanks for the information. As far as I see this content, I think your `~/.bashrc` is just fine.

> Also, I don't know why the terminal would send `\r`, wasn't that windows-only?

If you are talking about text files, yes, `\r` representing a newline combined with \n is Windows-specific, but terminal communication is not a text file. The byte `\r` [ also represented in many different ways as `13`, `0x0D`, `\x0D`, `\015`, `0/13`, `RET`, `CR`, etc. ] is used for other purposes in terminal communication. For example, in host-to-terminal transmission, `\r` means that the cursor position should be moved to the beginning of the current line. In terminal-to-host transmission, `\r` means the key input <kbd>Return</kbd> or <kbd>C-m</kbd>.

**Comment by akinomyoga** [comment]
OK, I could reproduce the issue in openSUSE. I'll take a look.

**Comment by Ultra980** [comment]
Ok, thanks for the help so far!
Until I figure out a solution, if I need to use heredoc, I'll use `Alt+Enter`.

<sub>P.S. I also tried `ble-bind -m 'emacs' -f 'RET' 'newline'`, but it didn't work.</sub>

**Comment by akinomyoga** [comment]
Ah, wait. I now see what is happening. I dismissed the problem in your output of Q4.

> Q4:
>
> ```
> ble-bind -m 'emacs' -f 'C-m' 'accept-line'
> ```

The widget corresponding to `C-m` is supposed to be `accept-single-line-or-newline` instead of `accept-line`, but it is reset to `accept-line`. This is caused by the following lines of `/etc/inputrc.keys` provided openSUSE.

```bash
/etc/inputrc.keys:570:"\eOM":           accept-line
/etc/inputrc.keys:749:"\eOM":           accept-line
```

I also observe other issues caused by openSUSE `/etc/inputrc.keys`, such as <kbd>Home</kbd> and <kbd>End</kbd> are somehow redirected to <kbd>PageUp</kbd> and <kbd>PageDn</kbd>. I recommend turning inputrc off using the command line option of ble.sh. You can turn it off by the following change of `~/.bashrc`:

```diff
--- .bashrc~^I2023-01-28 17:07:59.724646069 +0900
+++ .bashrc^I2023-01-28 17:08:11.774642573 +0900
@@ -2,7 +2,7 @@
 export PATH=$PATH:/usr/bin
 export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/home/ultra/.local/bin:/home/ultra/bin:/usr/bin:/home/ultra/.cargo/bin
 export GPG_TTY=$(tty)
-source ~/.local/share/blesh/ble.sh
+source ~/.local/share/blesh/ble.sh --noinputrc
 eval "$(starship init bash)"
 alias cls="clear"
 alias dben="distrobox-enter"
```

**Comment by akinomyoga** [comment]
For reference, #89 and #105 are also related to openSUSE inputrc. I once submitted a fix https://github.com/openSUSE/aaa_base/pull/84 for a general issue, which caused problems even in plain Bash.

**Comment by Ultra980** [comment]
> ```diff
> +source ~/.local/share/blesh/ble.sh --noinputrc
> ```

Thanks, this worked!

**Comment by Ultra980** [comment]
> > ```diff
> > +source ~/.local/share/blesh/ble.sh --noinputrc
> > ```
> 
> Thanks, this worked!

Now I can also move to the EOL with `End` instead of it entering a sort of selection mode (I thought it was a keybind but it was just remapped by openSUSE)!

<sub>Btw, how do you write keys such as End in markdown?</sub>

**Comment by akinomyoga** [comment]
> Btw, how do you write keys such as End in markdown?

You can mark it up as `<kbd>End</kbd>`.

**Comment by Ultra980** [comment]
<kbd>Thanks!</kbd>

**Comment by Ultra980** [comment]
In the screenshot it's the `nvim` terminal inside a distrobox, but it also happens in konsole outside of the distrobox.

**Comment by akinomyoga** [comment]
![image](https://user-images.githubusercontent.com/8982192/215488247-e6c4defa-1563-4740-8e87-59c788855471.png)

**Comment by akinomyoga** [comment]
I decided to change the default treatment of inputrc in openSUSE in commit 7da9bce.
