### ISSUE TITLE
What a fantastic project!!!

### ISSUE THREAD

**Issue by ChanderG** [akinomyoga/ble.sh#27]
Excellent work. Hats off.

Have been searching for something like this for years, did not want to move to fish/zsh. But was never sure if this was even possible in pure bash. I even attempted at providing such features via urxvt's perl scripts at the terminal layer, but of course that's not portable.

Thanks for doing this. Looking forward to using this and looking into the codebase.

Not really an issue; feel free to close this.

**Comment by akinomyoga** [comment]
Thank you very much for your encouraging comment. If you have any troubles, questions or suggestions for `ble.sh`, please feel free to make an issue here.
