### ISSUE TITLE
Move cursor backward with words separated by underscores

### ISSUE THREAD

**Issue by linwaytin** [akinomyoga/ble.sh#270]
It is common for me that a filename is like `foo_bar_X_Y_Z`, and I would like to move cursor by words separated by the underscore `_`. Currently the `cword` considers the underscores as a part of a single word. Is there anyway to achieve this? Thanks.

**Comment by akinomyoga** [comment]
Have you tried [`eword`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#44-wordwise-movement-and-operation) instead of `cword`? For example,

```bash
ble-bind -f 'C-right' '@nomarked forward-eword'
ble-bind -f 'C-left' '@nomarked backward-eword'
ble-bind -f 'C-S-right' '@marked forward-eword'
ble-bind -f 'C-S-left' '@marked backward-eword'
```

**Comment by linwaytin** [comment]
I didn't know them! That works. Thank you!
