### ISSUE TITLE
Problem to build ble.sh with gmake

### ISSUE THREAD

**Issue by Fulgurance** [akinomyoga/ble.sh#271]
Hi, today I tried to build ble.sh with gmake, but I had this error:

```
zohran@alienware-m17-r3 ~/Downloads/ble.sh-0.3.3 $ gmake -j16
mkdir -p out
mkdir -p out/keymap
mkdir -p out/lib
DEPENDENCIES_PHONY=1 DEPENDENCIES_OUTPUT=out/ble.dep DEPENDENCIES_TARGET=out/ble.sh FULLVER=0.3.3 \
  /usr/bin/gawk -f ext/mwg_pp.awk ble.pp >/dev/null
cp -p keymap/emacs.sh out/keymap/emacs.sh
cp -p keymap/vi.sh out/keymap/vi.sh
cp -p keymap/vi_digraph.sh out/keymap/vi_digraph.sh
cp -p keymap/vi_digraph.txt out/keymap/vi_digraph.txt
cp -p keymap/vi_test.sh out/keymap/vi_test.sh
cp -p keymap/emacs.rlfunc.txt out/keymap/emacs.rlfunc.txt
cp -p keymap/vi_imap.rlfunc.txt out/keymap/vi_imap.rlfunc.txt
cp -p keymap/vi_nmap.rlfunc.txt out/keymap/vi_nmap.rlfunc.txt
cp -p lib/init-term.sh out/lib/init-term.sh
cp -p lib/init-bind.sh out/lib/init-bind.sh
cp -p lib/core-complete.sh out/lib/core-complete.sh
/usr/bin/gawk -f ext/mwg_pp.awk lib/core-syntax.sh > out/lib/core-syntax.sh
cp -p lib/core-edit.ignoreeof-messages.txt out/lib/core-edit.ignoreeof-messages.txt
cp -p lib/init-cmap.sh out/lib/init-cmap.sh
cp -p lib/vim-surround.sh out/lib/vim-surround.sh
fatal: not a git repository (or any of the parent directories): .git
```

I missed a step ?
I would like to compile it, not use a ready to use binary.

**Comment by akinomyoga** [comment]
If you would like to build it, you need to build it from a git repository. First you need to clone a repository, go to the directory, and run `gmake`.

> I would like to compile it, not use a ready to use binary.

In case you misunderstand, the read-to-use version is not a binary but a set of script files. The build process just combines multiple script files into a single script file `ble.sh`, and it's *NOT* a compilation process that produces a binary.

**Comment by Fulgurance** [comment]
So if I would like to run gmake, I need to use the git repo. So I guess if I would like to build a stable version, I had to clone with a tag.

So in one word, I can use the standard provided archive, because ble don't have any binary, right ?

**Comment by akinomyoga** [comment]
> So in one word, I can use the standard provided archive, because ble don't have any binary, right ?

Right.

**Comment by akinomyoga** [comment]
@Fulgurance If you don't have further problems, can I close the issue? Thank you!

**Comment by Fulgurance** [comment]
Yes sorry, I need to improve my github use sorry

**Comment by akinomyoga** [comment]
Don't worry! I just wanted to confirm! Thank you!
