### ISSUE TITLE
[Cygwin, Git for Windows w/ autocrlf] More Help Installing it

### ISSUE THREAD

**Issue by danil0man** [akinomyoga/ble.sh#275]
Hello Aki. Sorry to bother you again but I have now another issue when trying to install ble on my personal computer. I keep trying going back and forth but I cannot get it working. Would you be so kind and help me again?

**ble version**:  I cannot install it
**Bash version** 4.4.12(3)-release (x86_64-unknown-cygwin)

Getting this error when I run ble command to install
![image](https://user-images.githubusercontent.com/72052103/217807752-36b707ed-c30f-4ade-9bb5-2e87e5bca688.png)

I have done some research and it seems somehow my machine is using window carriage and not linux. but I have tried to convert my files to linux end doing dos2unix and still dont work. Please help

**Comment by akinomyoga** [comment]
This problem typically happens when there are different versions of Git.

- **Q1**: Which version of Git do you use? Is it Git installed from the Cygwin? Or is it other versions for Windows such as "Git for Windows"?

```bash
$ type git
$ git --version
```

The solution depends on the situation.

**Comment by danil0man** [comment]
Q1
![image](https://user-images.githubusercontent.com/72052103/217824006-1a8a6812-839c-4da5-b8d3-97c192cbc981.png)

**Comment by akinomyoga** [comment]
OK, so this means that you are using Git for Windows.

There are two options for the solution.

- (a) One is to install the Cygwin version of Git using the Cygwin installer.
- (b) Another is to configure Git for Windows properly for the newlines. In this case, you can run the following command

```bash
$ git config --global core.autocrlf false
```

Then, you can again clone the repository of `ble.sh`.

**Comment by danil0man** [comment]
That worked as a charm. You are a genius! your debugging skills are off the chart :D I make sure to star this repo

**Comment by akinomyoga** [comment]
Thanks! Closing.
