### ISSUE TITLE
the cmdinfo_cd_cdpath face appears to be undocumented

### ISSUE THREAD

**Issue by bkerin** [akinomyoga/ble.sh#278]
$ echo $BLE_VERSION 
0.4.0-devel3+46ac426
2 $ echo $BASH_VERSION 
5.0.17(1)-release

The page here:

     https://github.com/akinomyoga/ble.sh/wiki/Manual-§2-Graphics

doesn't mention cmdinfo_cd_cdpath that ble-face reports as existing:

     $ ble-face | grep 'cmdinfo_cd_cdpath'
     ble-face cmdinfo_cd_cdpath=fg=26,bg=155

**Comment by akinomyoga** [comment]
It is an extension by the completion module so is documented in [Manual §7.2.11 Completion - `cmdinfo_cd_cdpath`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-face-cmdinfo_cd_cdpath).

**Comment by akinomyoga** [comment]
@bkerin By the way, are you satisfied with the above reply? Can I close the issue?

**Comment by bkerin** [comment]
On Fri, Feb 17, 2023, 3:33 PM Koichi Murase ***@***.***>
wrote:

> @bkerin <https://github.com/bkerin> By the way, are you satisfied with
> the above reply? Can I close the issue?
>
Yes I should have searched better.  It might be worth mentioning when the
listing command is first described that modules can add options described
in other sections, but it might not.  I don't know how many people go
through the docs in order or don't do bigger search.

**Comment by akinomyoga** [comment]
> It might be worth mentioning when the listing command is first described that modules can add options described in other sections,

I already did that just two hours before this reply.

https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#23-basic-faces

**Comment by akinomyoga** [comment]
@bkerin For this, also.

**Comment by bkerin** [comment]
Yes, satisfied thanks

**Comment by akinomyoga** [comment]
Thanks!
