### ISSUE TITLE
How can I change the color of the file path?

### ISSUE THREAD

**Issue by jaamivstheworld** [akinomyoga/ble.sh#279]
All of the other syntax highlighting is the same as my colorscheme, but for the file path it's a pretty ugly and vibrant dark blue color. How can I change it?

**Comment by akinomyoga** [comment]
The way to change the color is described in [README §2.6](https://github.com/akinomyoga/ble.sh#26-highlight-colors).

You can check the current setting for the directory colors by:

```bash
$ ble-face @_directory
```

The default setting is

```bash
ble-face command_directory=fg=26,underline
ble-face filename_directory=fg=26,underline
```

If you want to use the color from the terminal's 16-color scheme, e.g. you can use

```bash
# ~/.blerc

ble-face command_directory='fg=navy,underline'
ble-face filename_directory='fg=navy,underline'
```

or, if you like bright blue,

```bash
# ~/.blerc

ble-face command_directory='fg=blue,underline'
ble-face filename_directory='fg=blue,underline'
```

The color specification is explained in [Manual §2.1](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#21-graphics-specifier-gspec).
