### ISSUE TITLE
typo in manual section 7.1.13

### ISSUE THREAD

**Issue by bkerin** [akinomyoga/ble.sh#280]
I think the title for this section should be:

7.1.13 Shopt force_fignore

**Comment by akinomyoga** [comment]
Ah, thanks! I have fixed it. By the way, in case you might not notice it, you can actually edit the wiki by yourself if you want to.

**Comment by akinomyoga** [comment]
@bkerin

**Comment by akinomyoga** [comment]
@bkerin Are you satisfied with the answer? If you are satisfied, please make comments instead of leaving them unresolved. Can I close the issue?

**Comment by bkerin** [comment]
Yes, perfectly satisfied thx

**Comment by akinomyoga** [comment]
Thanks for your reply!
