### ISSUE TITLE
prompt get corrupted on long menu with complete_menu_style=linewise and menu_linewise_prefix='%d'

### ISSUE THREAD

**Issue by bkerin** [akinomyoga/ble.sh#286]
With only the two configuration lines:

```
bleopt complete_menu_style=linewise
bleopt menu_linewise_prefix='%d'
```

Entering menu completion on (for example) a file list that goes off the screen causes the trailing space (present in the default PS1 for me at least) of the command prompt to get overwritten.  The character overwriting the space then persists. This doesn't happen for fixed prefixes (ones that don't include %d).

![screenshot](https://user-images.githubusercontent.com/7434164/221442899-b1552421-85b1-4bdc-af11-2386e9ecb525.jpg)

**Comment by akinomyoga** [comment]
Ah, yes. I recognized this issue when you made a request at #284. I'll fix it when I have time. Thank you for the report.

**Comment by akinomyoga** [comment]
This was an easy fix cc852dc6b32d772418669dc3d051c8644ca78923.

@bkerin Could you check if it is fixed in the latest master? (You can update ble.sh by running `ble-update`.) Thank you!

**Comment by bkerin** [comment]
It's fixed :)

**Comment by akinomyoga** [comment]
Thanks!
