### ISSUE TITLE
[zoxide, bind -x] Weird behavior when using zi from zoxide

### ISSUE THREAD

**Issue by linwaytin** [akinomyoga/ble.sh#293]
**ble version**: 0.4.0-nightly+32277da
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu)

 
On some not-so-commmon terminals, like `mlterm` and `zutty`, the following weird behavior shows up. I use `zoxide` and its command `zi` quite often and thus I have `bind -x '"\ej":zi'` (I believe it's equivalent to `ble-bind -x 'M-j' zi`) in my bashrc. I can then hit `Alt-j` and get the interactive widget provided by `zi`. 

On most terminals, I can use `Ctrl+n` and `Ctrl+p` to select the next and previous candidates. On `mlterm` and `zutty`, when I hit `Ctrl+n` I got `;5;110~` in the input field, and `;5;112~` for `Ctrl+p`. 

This issue is obviously related to the terminals, but at least on `zutty` it doesn't happen for the normal bash, so I think it should be reported here. Anyway, I think this is a rare case. I posted here mainly for record keeping.

**Comment by akinomyoga** [comment]
This is because ble.sh doesn't expect the commands called from `bind -x` start another interactive session by default. So far, I have required such commands explicitly adjusts the terminal states by themselves, but now I decided to make `bind -x` always adjust the terminal states (even if the commands called from `bind -x` might not start an interactive session). I pushed commit 5d14cf1.

@linwaytin Could you update ble.sh to the latest version (`ble-update`) and check if it works now?

**Comment by linwaytin** [comment]
Thanks for dealing with this case. I appreciate it. 

After update, the situation is changed. I can use the `C-p` and `C-n` to move the selection up and down, but hitting `Enter` doesn't jump to the directory (this is what `zoxide` should do). Instead, it just prints the path I choose. This happens on all terminal emulators I have, including `alacritty` and `xfce-terminal`. It seems the command does not "connect" back to the original state correctly?

When entering the interactive mode by typing `zi` on the prompt, there is not any issue, just like before.

**Comment by akinomyoga** [comment]
Thank you for checking! Hmm, it doesn't reproduce in my environment. I also tried `alacritty` and `xfce4-terminal`, but there doesn't seem to be the issue for <kbd>Enter</kbd>.

> It seems the command does not "connect" back to the original state correctly?

I'm not sure if it is related, but I think the only difference between the command from `bind -x` and the user command is the state of the pseudo-terminal device.

- **Q1**: What is shown by the following setting?

```bash
$ bind -x '"\ej": stty -a'
$     # <-- press M-j
```

- **Q2**: Does the behavior change with the following setting?

```bash
$ bind -x '"\ej": ble/term/stty/leave; zi; ble/term/stty/enter'
```

Note: This setting is just for testing purposes and might cause other problems when you press <kbd>C-c</kbd> or other keys handled by the terminal handler.

**Comment by linwaytin** [comment]
For **Q1**, I got
```
speed 38400 baud; rows 35; columns 146; line = 0;
intr = <undef>; quit = <undef>; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S;
susp = <undef>; rprnt = ^R; werase = ^W; lnext = <undef>; discard = <undef>; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig -icanon iexten -echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```
in `mlterm`, and similar output for `alacritty`.

**Q2** makes the command usable! `C-n` `C-p` and `Enter` show expected results.
(Some side effects appeared, like the prompt color is changed.)

Thanks a lot for investigating this issue.

**Comment by akinomyoga** [comment]
Thank you for the information. I compared the result with mine. The difference seems to be essentially only `brkint` and `ignpar`,  but settings these in my environment still does not seem to reproduce the problem.

```diff
--- mine^I2023-03-03 10:03:33.297735311 +0900
+++ yours^I2023-03-03 10:03:05.904726480 +0900
@@ -1,6 +1,6 @@
-speed 38400 baud; rows 75; columns 239; line = 0;
+speed 38400 baud; rows 35; columns 146; line = 0;
 intr = <undef>; quit = <undef>; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = <undef>; rprnt = ^R; werase = ^W; lnext = <undef>; discard = <undef>; min = 1; time = 0;
 -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
--ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff -iuclc -ixany -imaxbel iutf8
+-ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8
 opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
 isig -icanon iexten -echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

----

> **Q2** makes the command usable! `C-n` `C-p` and `Enter` show expected results.
> (Some side effects appeared, like the prompt color is changed.)

Thank you! So this means that some of `stty` settings affect the behavior. I would like to identify which setting is the culprit.

- **Q4**: What is the ouput of the following command?

```bash
$ declare -p _ble_term_stty_state
```

- **Q5**: Does the problem reproduce with the following setup?

```bash
$ bind -x '"\ej": stty echo icanon; zi; ble/bin/stty -echo -icanon'
```

**Comment by linwaytin** [comment]
**Q4** The output of `declare -p _ble_term_stty_state` is 
```
declare -- _ble_term_stty_state=""
```
**Q5** The setup doesn't reproduce the problem seen before.

**Comment by akinomyoga** [comment]
> **Q5** The setup doesn't reproduce the problem seen before.

Thank you! I think we almost identified the related setting.

- **Q6**: How about this? Does this reproduce the problem?

> ```shell
> $ bind -x '"\ej": stty icanon; zi; ble/bin/stty -icanon'
> ```

**Comment by linwaytin** [comment]
No, **Q6** also does not reproduce the problem.

**Comment by akinomyoga** [comment]
Thank you! I have pushed another fix dc7de6b. Could you add the following settings in your bashrc, update ble.sh by `ble-update`, and check if the problem is solved with `bind -x '"\ej": zi'`?

```bash
# blerc

ble-import -d integration/zoxide
```

**Comment by linwaytin** [comment]
Thank you. I just tried it and it works!
However, I found a side effect. After update, part of the prompt would change color after I run arbitrary command. For example, at the beginning of running `mlterm`, some part of the prompt is white. I then run `ls`, and that part becomes blue.

I noticed that the part being changed is the part which has no specified color in `PS1`. This is really a minor issue, and I think you don't need to spend more time on it. I bring it up for reference in the future.

**Comment by akinomyoga** [comment]
> Thank you. I just tried it and it works!

Thank you for checking!

----

> However, I found a side effect. After update, part of the prompt would change color after I run arbitrary command.

Thanks for the report. I tried to think about it, but I currently don't have an idea. Maybe you are busy, but if you have time, I'd appreciate it if you could check the outputs of the following commands.

```bash
$ bleopt prompt_eol_mark
$ declare -p _ble_term_sgr0 _ble_term_sc _ble_term_rc | cat -v
```

Also, does the issue happen with other terminals in addition to `mlterm`?

Does the issue reproduce after the following settings?

**test setup 1**
```bash
$ bleopt prompt_eol_mark=
# <-- check if the problem reproduce
```

**test setup 2**

```bash
$ bleopt -ur
# <-- check if the problem reproduce
```

**Comment by linwaytin** [comment]
The output:
> $ bleopt prompt_eol_mark

bleopt prompt_eol_mark=$'\e[94m[ble: EOF]\e[m'

> $ declare -p _ble_term_sgr0 _ble_term_sc _ble_term_rc | cat -v

declare -- _ble_term_sgr0="^[(B^[[m"
declare -- _ble_term_sc="^[7"
declare -- _ble_term_rc="^[8"

The color/font issue happens in `mlterm`, `zutty`, `alacritty` and `xfce-terminal`.
The **test setup 1** shows the same issue, but the **test setup 2** does not reproduce the issue. Actually, **test setup 2** changes the prompt back to its normal color/font, even after the prompt gets changed.

**Comment by akinomyoga** [comment]
Thank you for your quick response!

> but the **test setup 2** does not reproduce the issue.

OK, so this means that some of the `bleopt` settings are related. What is the output of the following command?

```bash
$ bleopt -u
```

> Actually, **test setup 2** changes the prompt back to its normal color/font, even after the prompt gets changed.

Yes, that was my intent. `bleopt -ur` reverts the `bleopt` settings of the current session to the default.

**Comment by linwaytin** [comment]
The output of `bleopt -u` is 
```
bleopt char_width_mode=west
bleopt char_width_version=14.0
bleopt prompt_rps1='\g{fg=75,italic}\q{contrib/elapsed}'
```

**Comment by akinomyoga** [comment]
> ```bash
> bleopt prompt_rps1='\g{fg=75,italic}\q{contrib/elapsed}'
> ```

Ah, OK. I could reproduce the problem with this line. I'll fix it at my side. Thank you!

**Comment by linwaytin** [comment]
Thank you!

**Comment by akinomyoga** [comment]
I added a fix ea99d944.

**Comment by linwaytin** [comment]
That works! The `zi` widget works, and I haven't seen any side effect. I think this bug is fixed. 

Thank you so much!

**Comment by akinomyoga** [comment]
Great! Thank you again for your report and patience!
