### ISSUE TITLE
comments after failed command cause exec_errexit_mark to latch on

### ISSUE THREAD

**Issue by bkerin** [akinomyoga/ble.sh#295]
$ echo $BLE_VERSION                                         
0.4.0-devel3+46ac426
$ echo "$BASH_VERSION ($MACHTYPE)"                          
5.0.17(1)-release (x86_64-pc-linux-gnu)

As shown here:

```
$ false                                                                                                                                                                                             
[ble: exit 1]
$ #foo                                                                                                                                                                                              
[ble: exit 1]
$ # wsefs                                                                                                                                                                                           
[ble: exit 1]
$ # ok now?                                                                                                                                                                                         
[ble: exit 1]
$ true                                                                                                                                                                                              
$ # and now?                                                                                                                                                                                        
$ 
```

Not a big deal obviously but I often write note-to-self or prospective new command-in-development to myself particularly after a failed command so it's noticeable.

**Comment by akinomyoga** [comment]
The answer would be the same as https://github.com/akinomyoga/ble.sh/issues/296#issuecomment-1448899636. The marker shows the current status of `$?`, so it is somehow expected to repeat the marker when the user command did not change `$?`. If you would like to turn it off when the user command does not contain an actual command, you can write your own similarly to the solution to #296. I have included an example implementation for the comments also in the example provided in https://github.com/akinomyoga/ble.sh/issues/296#issuecomment-1448899636.

**Comment by bkerin** [comment]
Resolved, thanks.

**Comment by akinomyoga** [comment]
Thanks!
