### ISSUE TITLE
Alt-Shift-o doesn't work correctly on Vi-mode

### ISSUE THREAD

**Issue by mozirilla213** [akinomyoga/ble.sh#298]
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) [Arch Linux]
ble.sh, version 0.4.0-devel3+46ac426 (noarch) [git 2.39.1, GNU Make 4.4, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:2d02f73e803daa87a06e94e33b2a7b3e672a2c0c, 76338 bytes) (noarch)
locale: LANG=C
terminal: TERM=xterm-256color wcwidth=15.0-west/13.0-2+ri, xterm:115 (1;115;0)
```

With vi-mode, on insert mode you can press `Alt-<key>` to quickly go back to normal mode and use the keybind. This works fine, but not with the `'O'` key, which would be the command to insert a previous line `vi_nmap/insert-mode-at-backward-line`. So when pressing `Alt-Shift-o` in insert mode, I would expect for a new previous line to appear and still be in insert mode (like in vim), but it doesn't.

To reproduce:
```bash
$ \
one
two<Alt-Shift-o>
```
Expectation:
```
$ \
one
 # ← here in insert mode
two
```
When pressing the shortcut nothing immediately happens, but after pressing another key, different things may happen, like if you then press `k`, a `+` will appear in the same line, or a `,` when pressing `l`. On certain keys a new previous line does appear with the correct character, like with `z` or `h`.

I also tried `ble-bind -m 'vi_imap' -f 'M-S-o' 'vi_nmap/insert-mode-at-backward-line'` with no avail, sometimes the cursor goes to the beggining of the line though

**Comment by akinomyoga** [comment]
I cannot reproduce the reported behavior, but in my terminal, <kbd>Alt-Shift-o</kbd> in `vi_imap` behaves the same as <kbd>Alt-o</kbd>. I.e., it inserts a newline *after* the current line while keeping the insert mode.

- **Q1**: I'm intereted in what your terminal sends for the key press <kbd>Alt-Shift-o</kbd>. Could you try the following and paste the output?

```bash
$ ble-import core-debug
$ ble/debug/keylog#start
$                       # <-- Here, press Alt-Shift-o (and clear the command line by HVLd or whatever
$ ble/debug/keylog#end
```

> When pressing the shortcut nothing immediately happens,

Have you set up [timeouts](https://github.com/akinomyoga/ble.sh/wiki/Vi-%28Vim%29-editing-mode#2-setting-timeout-for-esc) for escape sequences?

Also, ble.sh actually tries to distinguish the user's ESC key input and the Meta modifier (both represented by the byte 27) based on the timing information. This means that pressing <kbd>Alt-Shift-o</kbd> and pressing <kbd>ESC</kbd> and then <kbd>Shift-o</kbd> are treated differently in ble.sh. If you would like to always make any Meta modifier treated as an independent ESC key, please set [`bleopt decode_isolated_esc`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#user-content-bleopt-decode_isolated_esc).


```bash
# blerc

bleopt decode_isolated_esc=esc
```

> I also tried `ble-bind -m 'vi_imap' -f 'M-S-o' 'vi_nmap/insert-mode-at-backward-line'` with no avail, sometimes the cursor goes to the beggining of the line though

The widgets starting with `vi_nmap/` are not expected to be run in `vi_imap`.

**Comment by akinomyoga** [comment]
I have added some adjustments 600e845, but I'm not sure if that changes any behavior in your terminal. It seems the control sequence sent by the key press <kbd>Alt+Shift+?</kbd> largely depends on the terminal (and the CapsLock state and the keyboard layout). I'm now thinking of switching the behavior depending on the terminal if necessary.

- **Q4**: What is your terminal? (though the DA2 response `1;115;0` implies something based on Konsole 22.03.80+)

**Comment by mozirilla213** [comment]
> Q4: What is your terminal?

I'm testing right now with Alacritty 0.11.0-2 and Konsole 22.12.3-1, but the behavior really seems to be the same. I also checked that the terminal keybind configs aren't interfering. I'm testing on ble.sh 0.4.0_devel3.r1922.ea99d94-1 now.

> Q1: I'm intereted in what your terminal sends for the key press Alt-Shift-o. Could you try the following and paste the output?

I'm sorry, what does clearing by HVLd mean? After running `ble-import core-debug; ble/debug/keylog#start`, I pressed `Alt-Shift-o`, then copy-pasted `ble/debug/keylog#end` and hit Enter.

Output in both alacritty and konsole:
```
===== bytes =====
192 155 79 192 155 91 50 48 48 126 98 10
8 101 47 100 101 98 117 103 47 107 101 1
21 108 111 103 35 101 110 100 192 155 91
 50 48 49 126 13

===== chars =====
ESC O ESC [ 2 0 0 ~ b l e / d e b u g /
k e y l o g # e n d ESC [ 2 0 1 ~ RET

===== keys =====
paste_begin C-m
```

> Q2: Have you set up [timeouts](https://github.com/akinomyoga/ble.sh/wiki/Vi-%28Vim%29-editing-mode#2-setting-timeout-for-esc) for escape sequences?

Yes, I had this `builtin bind 'set keyseq-timeout 1'` in my blerc, but commenting it out doesn't seem to make anything different

> Q3: Have you set bleopt decode_isolate_esc?

I had not, but setting it doesn't seem to make anything different either

What is your terminal by the way? Maybe I could see the behavior there

**Comment by akinomyoga** [comment]
> > Q4: What is your terminal?
> 
> I'm testing right now with Alacritty 0.11.0-2 and Konsole 22.12.3-1, but the behavior really seems to be the same. I also checked that the terminal keybind configs aren't interfering. I'm testing on ble.sh 0.4.0_devel3.r1922.ea99d94-1 now.

Thank you for the information.

Ah, OK. I could reproduce the problem.

> > Q1: I'm intereted in what your terminal sends for the key press Alt-Shift-o. Could you try the following and paste the output?
> 
> I'm sorry, what does clearing by HVLd mean?

Sorry for the confusing writing, but it was just a `nmap` command, i.e., `H` (go to the beginning line), `V` (start the linewise visual mode), `L` (go to the last line), and `d` (delete).

> After running `ble-import core-debug; ble/debug/keylog#start`, I pressed `Alt-Shift-o`, then copy-pasted `ble/debug/keylog#end` and hit Enter.
> 
> Output in both alacritty and konsole:
> 
> ```
> ===== bytes =====
> 192 155 79 192 155 91 50 48 48 126 98 10
> 8 101 47 100 101 98 117 103 47 107 101 1
> 21 108 111 103 35 101 110 100 192 155 91
>  50 48 49 126 13
> 
> ===== chars =====
> ESC O ESC [ 2 0 0 ~ b l e / d e b u g /
> k e y l o g # e n d ESC [ 2 0 1 ~ RET
> 
> ===== keys =====
> paste_begin C-m
> ```

Ah, OK... Now I see what is happening. These terminals send `ESC O` on the keypress <kbd>Alt-Shift-o</kbd>, but `ESC O` is actually a prefix `SS3` to some key sequences in Application Mode (DECKAM) (e.g. see [1]).

- [1] [XTerm ctlseqs(ms) - PC-Style Function Keys](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-PC-Style-Function-Keys)

In the sense of ISO-2022, `SS3` (Single Shift 3) is supposed to be combined with the next byte to form a distinct graphic character. The application mode function key sequences of `SS3 <char>` would fit in this ISO-2022 convention, so ble.sh tries to always combine `SS3` with the next character. If the combination of `SS3` plus the next character is a known key sequence, ble.sh translates it to the key, or otherwise the combination is discarded. This is what we observe in these terminals.

> > Q2: Have you set up [timeouts](https://github.com/akinomyoga/ble.sh/wiki/Vi-%28Vim%29-editing-mode#2-setting-timeout-for-esc) for escape sequences?
> [...]
> > Q3: Have you set bleopt decode_isolate_esc?
> 
> I had not, but setting it doesn't seem to make anything different either

Thank you for checking these.

> What is your terminal by the way?

Uhh, I'm actually using [a terminal that I wrote from scratch](https://github.com/akinomyoga/contra), which sends `ESC <Shift-o>` on the keypress <kbd>Alt+Shift+o</kbd>, where `<Shift-o>` is encoded within the `modifyOtherKeys` scheme. But you can see a working example also within XTerm, which sends `<Meta-Shift-O>`.

----

I'll think about the way to work around the case where `ESC O` is sent as separate two keys rather than a part of a longer key sequence.

**Comment by akinomyoga** [comment]
@mozirilla213 I pushed a workaround d721049465e362f67b75022d97f2a1b763414f38. Could you test it?

**Comment by akinomyoga** [comment]
@mozirilla213

**Comment by akinomyoga** [comment]
@mozirilla213

**Comment by mozirilla213** [comment]
I tested it on my current version `0.4.0-devel4+0906fd95` for Alacritty, Konsole and Kitty, and it does work! Thank you so much for the fix!

**Comment by akinomyoga** [comment]
Thank you for checking!
