### ISSUE TITLE
`C-z` を bash 相当の挙動にして/行内に文字列があるかどうかの判定を含めて欲しい

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#3]
\# こういうのは new issue でいいんでしょうか……？

ble.sh の `C-z` は譬え行内に入力されている文字列があったとしても、問答無用で `fg` を実行するようです。

```sh
$ sleep 10
```
を実行し、`C-z` を入力してプロンプトに戻り

```sh
$ ls
```

と入力してから `C-z` とすると `fg ls` が実行され、

```sh
$ ls
bash: fg: カレント: そのようなジョブはありません。
$ ls
```

となる。

bash では `C-z` はプロンプトにおいて意味を持ちません。

しかし空行での `C-z` が `fg` を呼び出すというのは便利なので、
(Bash では見掛けないですが Zsh の利用者はそういった関数を作っている方も多いようです)
`C-d` 等に割り振られている `-or-` 系の widget にして欲しいです。

**Comment by akinomyoga** [comment]
ご報告ありがとうございます。実は上記の動作は (自分の趣味ではありますが) 意図的なものです。

どういう動作かというと、`C-z` は現在編集中のコマンドをそのままにして、それとは独立に `fg` を実行するというものです。再び suspend すれば "また編集の続きを行える" という動作になっています。私は、ファイルの中身を確認しながら少しずつコマンドラインを編集するときに、エディタとコマンドラインを行ったり来たりするのに使っています。(使いにくいでしょうか?)

> と入力してから C-z とすると fg ls が実行され、

`fg ls` ではなくて単に `fg` が実行されるはずなのですが、確かに `fg ls` が実行されていますか? (それは考えにくいのですが、もしそうであれば何らかのバグですね) こちらの手許では以下のようになり、`C-z` で `sleep 10` が再開されます。申し訳ありませんが、今一度、再現性についてご確認いただけませんか。

```sh
[murase@padparadscha 1 ble]$ sleep 10
^Z
[2]+  停止                  sleep 10
[ble: exit 148]
[murase@padparadscha 2 ble]$ ls
sleep 10
[murase@padparadscha 1 ble]$ ls
```

> bash では C-z はプロンプトにおいて意味を持ちません。

まさにそうであるからこそ、勝手ながら趣味の (そして個人的にお薦めの) 機能を `ble.sh` に盛り込んだのでございました。

> しかし空行での C-z が fg を呼び出すというのは便利なので、
(Bash では見掛けないですが Zsh の利用者はそういった関数を作っている方も多いようです)
C-d 等に割り振られている -or- 系の widget にして欲しいです。

個別に widget を作成して `ble.sh` に入れても良いですが、取り敢えず以下のように設定を書いて頂ければ空行のときだけ `fg` を実行するというようにできます。

```sh
function ble/widget/fg-on-empty-line {
  if [[ $_ble_edit_str ]]; then
    ble/widget/bell
  else
    ble/widget/.SHELL_COMMAND fg
  fi
}

ble-bind -f 'C-z' fg-on-empty-line
```

**Comment by cmplstofB** [comment]
> 使いにくいでしょうか?

いえ、使いやすいです。Zsh を利用していた頃は私も似たような挙動にしていました。
また、「プロンプトに入力文字が戻る」という仕様なら、空行かどうかの判定は必要ないですね。失礼しました。

> ファイルの中身を確認しながら少しずつコマンドラインを編集する

なるほど、確かにこれは便利ですね。
私はずっと Vim 内蔵の `:sh` を使っていましたが、寧ろ `C-z` で行き来する方が楽かもしれないです。
(`:sh` は一度終了すると履歴は残りますがプロンプト行が保存されないので)

---

`fg` でなく `fg ls` が実行される件ですが、最新版では akinomyoga の仰る通りの挙動になりました。もしかすると私の勘違いだった可能性もあります……。
お手数おかけして申し訳無いです。

Commit ID: [e92fec8](https://github.com/akinomyoga/ble.sh/commit/e92fec89b8b180b0f3210e92451a153083730639 "e92fec89b8b180b0f3210e92451a153083730639")

あとストーカみたいで気持ち悪いですが、誕生日おめでとうございます :birthday:

**Comment by akinomyoga** [comment]
> あとストーカみたいで気持ち悪いですが、誕生日おめでとうございます 🎂

ご丁寧にありがとうございます! @cmplstofB さまは物理の学生さんなのですか?

----
取り敢えずこちらの Issue は Close しますね。もし

> fg でなく fg ls が実行される件ですが、最新版では akinomyoga の仰る通りの挙動になりました。

が再現した場合には改めてこちらを Open して下さいませ

**Comment by cmplstofB** [comment]
> 物理の学生さんなのですか?

まあ，一応そうです。察せると思いますがかなり馬鹿です。

**Comment by akinomyoga** [comment]
いえ、そんなことありますか? 若いのに (すみません九重りんで検索しました) よくご存知で感心しているところです。

唯の社交辞令で仰っているだけかもしれないところ老婆心ながら私見を述べさせていただきましてすみませんが、学生だと「頭の良し悪し」のような発想にとらわれがちですがそのようなものはありません (あるとしても普通はそれが効くほど頭を使い切ることはありません)。環境さえ整っていれば、結局のところ「その物事に純粋に自分の興味を見いだせたかどうか」だけしかないな、というのは最近つくづく思うことでございます。
