### ISSUE TITLE
Incompatibility with colored prompts (PS1 with colors)

### ISSUE THREAD

**Issue by Dave-Elec** [akinomyoga/ble.sh#30]
**ble version**:0.4.0-devel1+4f442d0
**Bash version**: 4.4.20

Weird characters appear if the PS1 environment variable is set to have colors.
My setup: `\[\e[1;32m\]\u\[\e[m\]\[\e[1;33m\]@\[\e[m\]\[\e[1;31m\]\h\[\e[m\]:\[\e[34m\]\w\[\e[32m\]$(__git_ps1 "  %s ")\[\e[m\]\$`
Output of my shell: `user@hostname:~$`
Note: the characters here are not decoded by the terminal so I am seeing something like
 __
|00|
|01|

**Comment by akinomyoga** [comment]
Thank you very much for the report! Does the latest commit 3cd79e2 fix the problem?

**Comment by akinomyoga** [comment]
ping @Dave-Elec

**Comment by Dave-Elec** [comment]
Yes 3cd79e274aaa6188b96f9c1d9c2160b3e41c4702 Has fixed the issue. Thanks.

**Comment by akinomyoga** [comment]
Thank you very much!
