### ISSUE TITLE
candidate list visual corruption when completing long candidates on narrower terminal under complete_menu_style=linewise

### ISSUE THREAD

**Issue by bkerin** [akinomyoga/ble.sh#307]
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu) [Linux Mint 20.3]
ble.sh, version 0.4.0-devel3+2eadcd5 (noarch) [git 2.25.1, GNU Make 4.3, GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)]
bash-completion, version 2.10 (hash:b6da7f7edfc1c3c5196c86c81fb05fce96f83c03, 74550 bytes) (noarch)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=12.1-west/15.0-2+ri, vte:6003 (65;6003;1)

with   bleopt complete_menu_style=linewise at least there is some sort of render corruption in the candidate list that sets in when candidate file names longer than the terminal width are tabbed through for completion.  I haven't isolated this carefully relative to unmodified ble.sh, I can do so if it isn't obvious.

The attached screenshot shows both the dir set on which completion is being attempted and the results after tab has been pressed 4 times. 

The same completion attempt works right when the terminal is wider than the file names.

It also seems to work right without complete_menu_style=linewise

![screenshot_after_4_tabs](https://user-images.githubusercontent.com/7434164/227070950-c0af58d9-12a7-4446-beb0-e0ee42d60377.jpg)

**Comment by akinomyoga** [comment]
Thank you for the report. I'll later fix it.

**Comment by akinomyoga** [comment]
I pushed a fix 4c6a47756a1296f7f30d6d26648f59fd2a01d4c3.
