### ISSUE TITLE
map "jk" to go to normal mode in vi-mode

### ISSUE THREAD

**Issue by divramod** [akinomyoga/ble.sh#31]
Hey, thx for the awesome project!!!!

I like to use "jk" in vi-insert-mode to switch to normal mode.
Can you please help me to find the right mapping configuration?

thx in advance!!!

**Comment by akinomyoga** [comment]
Hi! Thank you very much for your feedback!

You can add the following line in `~/.blerc`. (If you copied `ble.sh/blerc` file, I recommend to put it in the function `blerc/vim-load-hook`.)

```bash
ble-bind -m vi_imap -f 'j k' 'vi_imap/normal-mode'
```

If you want timeout after the key input `j`, please tell me. Currently the timeout is not supported in `ble.sh`, and therefore I have to take time (probably this weekend) to implement it.

**Comment by divramod** [comment]
hey @akinomyoga, thx for your fast reply!

this is exactly what i was looking for.

about the delay. i prefer to press both keys at the same time, because i have to do it the whole day and its faster. in vim i am using https://github.com/kana/vim-arpeggio to be able to use simultaneous keypresses. that really boosted some of my workflows.

so if you start doing something about that it would be nice, if i would be able to press both keys at the same time ;-)

thx again, great project. finally a reason i can completely switch to bash :-) the abbreviation feature and shell completion were the major reasons for me to stay with fish.

**Comment by divramod** [comment]
a thing i'd like to ask too is a mapping in normal and a mapping in insert mode to open the current command in vim. it would be nice to be able to open that command with ```vim -x```.

i think there is a standard mapping for that but i never found the name for that feature. i had that running in fish and zsh too.

**Comment by divramod** [comment]
i added 

```
ble-bind -m vi_imap -f 'j k' 'vi_imap/normal-mode'
ble-bind -m vi_imap -f 'k j' 'vi_imap/normal-mode'
```

now i can press both keys simultaneously :-)

**Comment by akinomyoga** [comment]
> a thing i'd like to ask too is a mapping in normal and a mapping in insert mode to open the current command in vim. it would be nice to be able to open that command with `vim -x`.

Do you mean `vim -X`? Then, add the following settings:

```bash
VISUAL='vim -X'
ble-bind -m vi_imap -f '...' 'edit-and-execute-command'
ble-bind -m vi_nmap -f '...' 'vi-command/edit-and-execute-command'
```

**Comment by akinomyoga** [comment]
@divramod Hi! I implemented a timeout for key bindings. Could you try the latest commit 272344e to see if it works?

By the following example, you can trigger `vi_imap/normal-mode` only when the interval of `j` and `k` is less than 40 milliseconds or otherwise `j` and `k` have the original meaning.
```bash
ble-bind -m vi_imap -f 'j k' 'vi_imap/normal-mode'
ble-bind -m vi_imap -f 'k j' 'vi_imap/normal-mode'
ble-bind -m vi_imap -T j 40
ble-bind -m vi_imap -T k 40
```

I also added an extension library `lib/vim-arpeggio.sh` to make the above settings easier. Instead of the above settings, you can put the following settings. `bleopt vim_arpeggio_timeoutlen` is the settings for the timeout, i.e., the maximal interval of two keys to be interpreted as "simultaneous":

```bash
# blerc

function blerc/vim-arpeggio-hook {
  source "$_ble_base/lib/vim-arpeggio.sh"
  bleopt vim_arpeggio_timeoutlen=40

  ble/lib/vim-arpeggio.sh/bind -f jk 'vi_imap/normal-mode'
  # Here, you can add further simultaneous-key bindings...
  # usage: ble/lib/vim-arpeggio.sh/bind [-m keymap] -[fxc@s] kspecs command
}
blehook/eval-after-load keymap_vi blerc/vim-arpeggio-hook
```

**Comment by akinomyoga** [comment]
@divramod I close this issue. If you have any other questions, please feel free to open an issue anytime.
