### ISSUE TITLE
Export environments from file works different with ble.sh and without ble.sh

### ISSUE THREAD

**Issue by pt12lol** [akinomyoga/ble.sh#311]
**ble version**: 0.4.0-nightly+2eadcd5
**Bash version**: 5.0.17(1)-release (x86_64-pc-linux-gnu)

I cannot export envs from file the way I can do so without `ble.sh`.

# Test case

## Prerequisites

```
$ echo -e FOO=foo\\nBAR=bar > .env
```

## Test command

```
$ export $(xargs < .env) && echo $FOO $BAR
```

## When ble.sh is loaded (actual behavior)

```
$ export $(xargs < .env) && echo $FOO $BAR
foo BAR=bar
```

## When ble.sh is NOT loaded (expected behavior)

```
$ export $(xargs < .env) && echo $FOO $BAR
foo bar
```

**Comment by akinomyoga** [comment]
It doesn't reproduce in my environment with the provided commands. I think the `IFS` environment variable doesn't have a proper value when you load ble.sh. I suspect it is related to your setup of ble.sh.

- **Q1** What is the result of the following command?

```bash
$ declare -p IFS
```

- **Q2**: How do you load ble.sh? For example, do you source ble.sh inside a shell function? Do you run `ble-update` inside a shell function?

**Comment by pt12lol** [comment]
# Q1 What is the result of the following command?
## With `ble.sh`
```
$ declare -p IFS
declare -x IFS=""
```
## Without `ble.sh`
```
$ declare -p IFS
declare -x IFS=" 	
"
```
# Q2 How do you load `ble.sh`?
Plain call in my `~/.bashrc`
```
$ tail -n 2 ~/.bashrc
source ~/.local/share/blesh/ble.sh
```

**Comment by akinomyoga** [comment]
Thanks. So something is affecting `IFS`.

- **Q3**: Is your `source ~/.local/share/blesh/ble.sh` located at the end of `~/.bashrc`? If not, does the problem reproduce when ble.sh is loaded at the last line of `~/.bashrc`?

**Comment by pt12lol** [comment]
### Q3 Is your source `~/.local/share/blesh/ble.sh` located at the end of `~/.bashrc`?
Yes, it is. I tailed it from `~/.bashrc`.

**Comment by akinomyoga** [comment]
Ah, OK. You are right. Sorry for the stupid question.

- **Q4**: Could you see what is output when you add `declare -p IFS PROMPT_COMMAND` around `source .../ble.sh`?

```bash
# at the end of your bashrc

declare -p IFS PROMPT_COMMAND
source ~/.local/share/blesh/ble.sh
declare -p IFS PROMPT_COMMAND
```

- **Q5**: Does the situation change when you put `ble-attach` as the next line of `source ~/.local/share/blesh/ble.sh`?

**Comment by pt12lol** [comment]
### Q4 Could you see what is output when you add `declare -p IFS PROMPT_COMMAND` around `source .../ble.sh`?
```
declare -- IFS=" 	
"
bash: declare: PROMPT_COMMAND: not found
declare -- IFS=" 	
"
declare -- PROMPT_COMMAND="ble/function#lambda/0"
```
### Q5 Does the situation change when you put `ble-attach` as the next line of `source ~/.local/share/blesh/ble.sh`?
```
$ tail -n 3 ~/.bashrc
source ~/.local/share/blesh/ble.sh
ble-attach
```
```
$ export $(xargs < .env) && echo $FOO $BAR
foo BAR=bar
```
Nothing has changed after adding `ble-attach` after `source ~/.local/share/blesh/ble.sh`.

**Comment by akinomyoga** [comment]
Thank you for checking. Hmm, I don't have an idea how `IFS` is changed. At least, the IFS seems unaffected after sourcing ble.sh.

- **Q6**: I would like to check the points where IFS is modified / referenced. Could you see what is output with the following setting?

```bash
# at the end of .bashrc

declare -gn IFS='__ifs[$(echo "$BASH_SOURCE:$LINENO ($FUNCNAME) [_ble_edit_IFS=$_ble_edit_IFS, IFS=$IFS]" >/dev/tty)]'
__ifs=$' \t\n'
source ~/.local/share/blesh/ble.sh
```

Start a new Bash session and run the following command.

```bash
$ declare -p IFS
```

**Comment by pt12lol** [comment]
### Q6 Could you see what is output with the following setting?
These settings hangs up starting `ble.sh`.

**Comment by akinomyoga** [comment]
Thank you for trying that.

- **Q7**: Could you turn off (e.g. comment out) all the other settings (except ble.sh) in your bashrc and see if the problem still arises?
- **Q8**: If the problem stops happening with Q7, could you identify which setting interferes with ble.sh by changing the part turned off?

**Comment by pt12lol** [comment]
### Q7 Could you turn off (e.g. comment out) all the other settings (except ble.sh) in your bashrc and see if the problem still arises?
Yes, it still does occur.
### Q8 If the problem stops happening with Q7, could you identify which setting interferes with ble.sh by changing the part turned off?
Seems irrelevant.

**Comment by akinomyoga** [comment]
> ### Q7 Could you turn off (e.g. comment out) all the other settings (except ble.sh) in your bashrc and see if the problem still arises?
> Yes, it still does occur.

Thanks, then I next suspect settings prepared by the operating system.

- **Q9** What is your Linux distribution? What is shown with the following command?

```bash
$ ble/widget/display-shell-version
```

- **Q10**: Does the problem happen in a child Bash session (started inside the terminal by running `bash`)?

```bash
$ bash # <-- In a bash session, you can start another Bash session
$ declare -p IFS # <-- Does the unexpected value of IFS reproduce here?
$ exit
```

**Comment by pt12lol** [comment]
### Q9 What is your Linux distribution?
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu) [Ubuntu 20.04.6 LTS]
ble.sh, version 0.4.0-nightly+2eadcd5 (noarch) [git 2.39.2, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
locale: LANG=en_US.UTF-8 LC_ADDRESS=pl_PL.UTF-8 LC_IDENTIFICATION=pl_PL.UTF-8 LC_MEASUREMENT=pl_PL.UTF-8 LC_MONETARY=pl_PL.UTF-8 LC_NAME=pl_PL.UTF-8 LC_NUMERIC=pl_PL.UTF-8 LC_PAPER=pl_PL.UTF-8 LC_TELEPHONE=pl_PL.UTF-8 LC_TIME=pl_PL.UTF-8
terminal: TERM=xterm-256color wcwidth=12.1-west/15.0-2+ri, xterm:276 (0;276;0)
### Q10 Does the problem happen in a child Bash session (started inside the terminal by running bash) (with the single line `source ~/.local/share/blesh/ble.sh` in your `~/.bashrc`)? 
```
$ bash
$ declare -p IFS
declare -x IFS=""
$ exit
```

**Comment by akinomyoga** [comment]
I'll try to reproduce it in Ubuntu 20.04 LTS later. I also would like to know the terminal that you use.

- **Q11**: What is your terminal? Does the empty IFS reproduce in other terminals?

**Comment by pt12lol** [comment]
### Q11 What is your terminal? Does the empty IFS reproduce in other terminals?
I first observed in in the terminal inside vscode, but then I tried your empty IFS advice and Gnome Terminal doesn't work well for me either.

**Comment by akinomyoga** [comment]
Thanks.

Hmm, maybe I have confused you, but the empty IFS is not my advice. The empty IFS is *the source of the problem*, so if you set `IFS` to empty, please remove that setting.

**Comment by akinomyoga** [comment]
Ah, now I can reproduce the empty IFS in Ubuntu 20.04.6 LTS. I'm not sure if this is exactly the same as the problem you are faced with since some behavior is different from the behaviors in your report, but anyway I'll bisect it at my side.

**Comment by pt12lol** [comment]
Problem still occurs when I upgraded to 5.2.15.

**Comment by pt12lol** [comment]
Great! It works now! Thanks!
