### ISSUE TITLE
[broot] Alt+Enter does not work

### ISSUE THREAD

**Issue by linwaytin** [akinomyoga/ble.sh#319]
**ble version**: 0.4.0-nightly+f4c973b
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu)

[Broot](https://github.com/Canop/broot) allows to quit and change to the directory by `Alt+Enter`. This functionality works fine on most terminal (at least on alacritty and xfce-terminal), but on `mlterm` somehow it doesn't work with `ble.sh`, but for original `bash` it can work. 

I feel this might be related to the issue I reported before #293. If that is not the case and no easy fix exists, please just ignore this issue at this moment.

**Comment by akinomyoga** [comment]
@linwaytin Sorry for the late reply. I checked the behavior of `mlterm`. As you have guessed correctly, this is related to the implementation of modifyOtherKeys by each terminal. `mlterm` seems to send Alt+Enter with an escape sequence with modifyOtherKeys set to 1. Does setting the following solve the problem?

```bash
# blerc
bleopt term_modifyOtherKeys_external=0
```

**Comment by linwaytin** [comment]
No worries. Yes, that setup solves the problem. Thanks for taking care of this. I appreciate that.

**Comment by akinomyoga** [comment]
Thank you!
