### ISSUE TITLE
Case-insensitive completion

### ISSUE THREAD

**Issue by maxstu** [akinomyoga/ble.sh#32]
Hi! This project is super cool, thanks for making it.

I'm not sure if this is a feature that doesn't exist or if I just can't find the setting for it, but I'd love to be able to make completion - both tab and auto - case insensitive. By which I mean `cd ~/docu` would complete to `cd ~/Documents`, or `networkma` to `NetworkManager`.

Thanks!

**Comment by akinomyoga** [comment]
Thank you for your feedback! For case insensitive completion, `ble.sh` refers to the setting of Readline. Please add the following line in your `~/.bashrc` or `~/.blerc`:

```bash
bind 'set completion-ignore-case on'
```

**Comment by maxstu** [comment]
Ah, fantastic. Thanks for your help!
