### ISSUE TITLE
typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by bkerin** [akinomyoga/ble.sh#320]
colon should be a semicolon in the below

name = hyphenated_name extension                     (* public                          *)
     | '.' hyphenated_name :                         (* private                         *)

**Comment by akinomyoga** [comment]
Ah, right thanks!

By the way, it's not in the `master` branch. It's still in the PR #317 branch, so could you leave comments on the coding style in #317? I need more comments on #317 as I don't think the current draft of the coding style covers everything, and I'd like to supplement the parts that interest users.

**Comment by akinomyoga** [comment]
> colon should be a semicolon in the below
> 
> name = hyphenated_name extension (* public _) | '.' hyphenated_name : (_ private *)

**Comment by akinomyoga** [comment]
moved to #317

**Comment by bkerin** [comment]
I'll try but this is likely to be a situation where the unknown unknowns are large

**Comment by akinomyoga** [comment]
Thanks! You don't have to try to cover everything, but I'm interested in whether there is something that you are interested in. If you don't have anything that you are interested in for now, that's fine.
