### ISSUE TITLE
ble.sh not working when source written in .bashrc

### ISSUE THREAD

**Issue by D3vil0p3r** [akinomyoga/ble.sh#321]
**ble version**: 0.3.4+566651e
**Bash version**: echo "$BASH_VERSION ($MACHTYPE)"

I got Ble.sh from Arch Linux AUR package, and I noted that, when I run BASH shell, and I run `source /usr/share/blesh/ble.sh`, it seems to work correctly.

When I insert it in `.bashrc` file, at the top or at the bottom, it starts to have weird behavior, like recursive output:
![image](https://user-images.githubusercontent.com/83867734/236620515-0e32891a-b849-4100-af34-4d931d89ca64.png)

I also followed the `1.3` README section with no luck.

The content of `.bashrc` I'm using (with no source to ble.sh) is:
```bash
### EXPORT ###
export EDITOR=/usr/bin/nvim
export VISUAL='nano'
export HISTCONTROL=ignoreboth:erasedups:ignorespace
HISTSIZE=100000
HISTFILESIZE=2000000
shopt -s histappend
export PAGER='most'

#Configure zoxide for bash
eval "$(zoxide init bash)"

#Ibus settings if you need them
#type ibus-setup in terminal to change settings and start the daemon
#delete the hashtags of the next lines and restart
#export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=dbus
#export QT_IM_MODULE=ibus

PS1="\e[1;32m┌──[HQ🚀🌐\e[1;31m$(ip -4 addr | grep -v '127.0.0.1' | grep -v 'secondary' | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | sed -z 's/\n/|/g;s/|\$/\n/' | rev | cut -c 2- | rev)🔥\u\e[1;32m]\n└──╼[👾]\[\e[1;36m\]\$(pwd) $ \[\e[0m\]"

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Bash aliases
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# COLOURS! YAAAY!
export TERM=xterm-256color

# Change up a variable number of directories
# E.g:
#   cu   -> cd ../
#   cu 2 -> cd ../../
#   cu 3 -> cd ../../../
function cu {
    local count=$1
    if [ -z "${count}" ]; then
        count=1
    fi
    local path=""
    for i in $(seq 1 ${count}); do
        path="${path}../"
    done
    cd $path
}


# Open all modified files in vim tabs
function vimod {
    vim -p $(git status -suall | awk '{print $2}')
}

# Open files modified in a git commit in vim tabs; defaults to HEAD. Pop it in your .bashrc
# Examples: 
#     virev 49808d5
#     virev HEAD~3
function virev {
    commit=$1
    if [ -z "${commit}" ]; then
      commit="HEAD"
    fi
    rootdir=$(git rev-parse --show-toplevel)
    sourceFiles=$(git show --name-only --pretty="format:" ${commit} | grep -v '^$')
    toOpen=""
    for file in ${sourceFiles}; do
      file="${rootdir}/${file}"
      if [ -e "${file}" ]; then
        toOpen="${toOpen} ${file}"
      fi
    done
    if [ -z "${toOpen}" ]; then
      echo "No files were modified in ${commit}"
      return 1
    fi
    vim -p ${toOpen}
}

# 'Safe' version of __git_ps1 to avoid errors on systems that don't have it
function gitPrompt {
  command -v __git_ps1 > /dev/null && __git_ps1 " (%s)"
}

# Colours have names too. Stolen from Arch wiki
txtblk='\[\e[0;30m\]' # Black - Regular
txtred='\[\e[0;31m\]' # Red
txtgrn='\[\e[0;32m\]' # Green
txtylw='\[\e[0;33m\]' # Yellow
txtblu='\[\e[0;34m\]' # Blue
txtpur='\[\e[0;35m\]' # Purple
txtcyn='\[\e[0;36m\]' # Cyan
txtwht='\[\e[0;37m\]' # White
bldblk='\[\e[1;30m\]' # Black - Bold
bldred='\[\e[1;31m\]' # Red
bldgrn='\[\e[1;32m\]' # Green
bldylw='\[\e[1;33m\]' # Yellow
bldblu='\[\e[1;34m\]' # Blue
bldpur='\[\e[1;35m\]' # Purple
bldcyn='\[\e[1;36m\]' # Cyan
bldwht='\[\e[1;37m\]' # White
unkblk='\[\e[4;30m\]' # Black - Underline
undred='\[\e[4;31m\]' # Red
undgrn='\[\e[4;32m\]' # Green
undylw='\[\e[4;33m\]' # Yellow
undblu='\[\e[4;34m\]' # Blue
undpur='\[\e[4;35m\]' # Purple
undcyn='\[\e[4;36m\]' # Cyan
undwht='\[\e[4;37m\]' # White
bakblk='\[\e[40m\]'   # Black - Background
bakred='\[\e[41m\]'   # Red
badgrn='\[\e[42m\]'   # Green
bakylw='\[\e[43m\]'   # Yellow
bakblu='\[\e[44m\]'   # Blue
bakpur='\[\e[45m\]'   # Purple
bakcyn='\[\e[46m\]'   # Cyan
bakwht='\[\e[47m\]'   # White
txtrst='\[\e[0m\]'    # Text Reset

# Prompt colours
atC="${txtpur}"
nameC="${txtpur}"
hostC="${txtpur}"
pathC="${txtgrn}"
gitC="${txtpur}"
pointerC="${txtgrn}"
normalC="${txtwht}"

# Red name for root
if [ "${UID}" -eq "0" ]; then 
  nameC="${txtred}" 
fi

# Local settings go last
if [ -f ~/.localrc ]; then 
  source ~/.localrc
fi

#shopt
shopt -s autocd # change to named directory
shopt -s cdspell # autocorrects cd misspellings
shopt -s cmdhist # save multi-line commands in history as single line
shopt -s dotglob
shopt -s histappend # do not overwrite history
shopt -s expand_aliases # expand aliases


# # ex = EXtractor for all kinds of archives
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

export SHELL=$(which bash)
export PROMPT_COMMAND='source ~/.bashrc'

buffer_clean(){
	free -h && sudo sh -c 'echo 1 >  /proc/sys/vm/drop_caches' && free -h
}
#create a file called .bashrc-personal and put all your personal aliases
#in there. They will not be overwritten by skel.

[[ -f ~/.bashrc-personal ]] && . ~/.bashrc-personal

# reporting tools - install when not installed
#neofetch | lolcat
#screenfetch
#alsi
#paleofetch
#fetch
#hfetch
#sfetch
#ufetch
#pfetch
#sysinfo
#sysinfo-retro
#cpufetch
#colorscript random

#bfetch configuration:
#export BFETCH_INFO="pfetch"                                                                                                                                          
#export BFETCH_ART="$HOME/.local/textart/fetch/unix.textart"                                                                                                      
#export PF_INFO="Unix Genius"

#export BFETCH_INFO="curl --silent --location 'wttr.in/rome?0pq'"                                                                                                   
#export BFETCH_ART="printf \"\033[35m\"; figlet -f Bloody Spooky"                                                                                                    
#export BFETCH_COLOR="$HOME/.local/textart/color/icon/ghosts.textart"

#export BFETCH_INFO="exa -la"                                                                                                                                         
#export BFETCH_ART="$HOME/.local/textart/fetch/pacman-maze.textart"                                                                                                 
#export BFETCH_COLOR="$HOME/.local/textart/color/icon/pacman.textart"

export BFETCH_INFO="pfetch"                                                                                                                                          
export BFETCH_ART="cowsay '<3 Athena OS'"                                                                                                                           
export BFETCH_COLOR="$HOME/.local/textart/color/icon/panes.textart"

export PAYLOADS="/usr/share/payloads"
export SECLISTS="$PAYLOADS/SecLists"
export PAYLOADSALLTHETHINGS="$PAYLOADS/PayloadsAllTheThings"
export FUZZDB="$PAYLOADS/FuzzDB"
export AUTOWORDLISTS="$PAYLOADS/Auto_Wordlists"
export SECURITYWORDLIST="$PAYLOADS/Security-Wordlist"

export MIMIKATZ="/usr/share/windows/mimikatz/"
export POWERSPLOIT="/usr/share/windows/powersploit/"

export ROCKYOU="$SECLISTS/Passwords/Leaked-Databases/rockyou.txt"
export DIRSMALL="$SECLISTS/Discovery/Web-Content/directory-list-2.3-small.txt"
export DIRMEDIUM="$SECLISTS/Discovery/Web-Content/directory-list-2.3-medium.txt"
export DIRBIG="$SECLISTS/Discovery/Web-Content/directory-list-2.3-big.txt"
export WEBAPI_COMMON="$SECLISTS/Discovery/Web-Content/api/api-endpoints.txt"
export WEBAPI_MAZEN="$SECLISTS/Discovery/Web-Content/common-api-endpoints-mazen160.txt"
export WEBCOMMON="$SECLISTS/Discovery/Web-Content/common.txt"
export WEBPARAM="$SECLISTS/Discovery/Web-Content/burp-parameter-names.txt"
```

**Comment by akinomyoga** [comment]
Thank you for trying ble.sh. This is because you have the following line in your .bashrc:

```bash
export PROMPT_COMMAND='source ~/.bashrc'
```

As ble.sh initializes the line editor and calls `PROMPT_COMMAND` itself, this sets up an infinite loop of

ble.sh -> PROMPT_COMMAND -> .bashrc -> ble.sh -> PROMPT_COMMAND -> .bashrc -> ble.sh -> ...

A workaround should be to conditionally source `ble.sh` in your .bashrc. For example,

```bash
[...]

export PROMPT_COMMAND='source ~/.bashrc without-blesh'

[...]

if [[ $1 != without-blesh ]]; then
  source /usr/share/blesh/ble.sh
fi
```

But maybe I should ask why you would like to source `.bashrc` from `PROMPT_COMMAND`?

**Comment by D3vil0p3r** [comment]
Thank you for your answer. I keep `PROMPT_COMMAND` in `.bashrc` because I need that, each time I run something on terminal, it must update again the prompt of shell (my shell could update due to other tools).

**Comment by akinomyoga** [comment]
Thank you! OK, so did you solve the problem with the above workaround? Can I close the issue?

**Comment by D3vil0p3r** [comment]
@akinomyoga that workaround seems to work. I have only one further issue I'm noting:

On my system, I use both BASH and FISH shell. Mainly FISH. My user is assigned to BASH shell at installation time, and I added at the end of `.bashrc` the following code:
```
if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} ]]
then
    exec fish
fi
```
In this manner, when I open a terminal, FISH shell is called so I can use FISH as shell directly.

You could ask: why don't you assign FISH directly to the user? If I do that, all bash scripts in `/etc/profile.d/` won't be executed because FISH and BASH have different syntax. So, when the user logins, it starts with BASH, then all starting bash scripts are executed, and at the end `.bashrc` calls `exec fish`.

My current issue is: when I add that code at the end of `.bashrc` for calling FISH shell, and I keep that `blesh` code, and I run the terminal, FISH shell will be open with weird characters like `[1;2R`:
![image](https://github.com/akinomyoga/ble.sh/assets/83867734/84780c0f-75e9-4d0a-8c0f-4e0be9d24b9d)

**Comment by akinomyoga** [comment]
Thank you for testing!

With such a setup, the standard way is to write init files in the following way:

```bash
# ~/.bash_profile

<Environtment settings>

if [[ -f ~/.bashrc ]]; then
  source ~/.bashrc
fi
```

```bash
# ~/.bashrc

# Note: exec comes to the top
if <condition>; then
  exec <other_shell>
fi

# ble.sh is an interactive setting
<Interactive settings for Bash>
```

Or if you wouldn't like to manage two files, you could alternatively write `~/.bashrc` as

```
# ~/.bashrc

<Environment settings>

<exec other_shell>

<interactive settings for Bash>
```

In your case, the interactive settings and environment settings are both written in .bashrc. You can first separate these two settings and make sure that `exec fish` would be called before the interactive settings.

**Comment by akinomyoga** [comment]
I've reordered and separated the settings for you. If you have additional environment settings in `~/.localrc` and `~/.bashrc-personal`, you can remove the sourcing of these files before `exec fish`.

```bash
# ~/.bashrc

### EXPORT ###
export EDITOR=/usr/bin/nvim
export VISUAL='nano'
export HISTCONTROL=ignoreboth:erasedups:ignorespace
HISTSIZE=100000
HISTFILESIZE=2000000
shopt -s histappend
export PAGER='most'

#Ibus settings if you need them
#type ibus-setup in terminal to change settings and start the daemon
#delete the hashtags of the next lines and restart
#export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=dbus
#export QT_IM_MODULE=ibus

# COLOURS! YAAAY!
export TERM=xterm-256color

export SHELL=$(which bash)

#export BFETCH_INFO="pfetch"
#export BFETCH_ART="$HOME/.local/textart/fetch/unix.textart"
#export PF_INFO="Unix Genius"

#export BFETCH_INFO="curl --silent --location 'wttr.in/rome?0pq'"
#export BFETCH_ART="printf \"\033[35m\"; figlet -f Bloody Spooky"
#export BFETCH_COLOR="$HOME/.local/textart/color/icon/ghosts.textart"

#export BFETCH_INFO="exa -la"
#export BFETCH_ART="$HOME/.local/textart/fetch/pacman-maze.textart"
#export BFETCH_COLOR="$HOME/.local/textart/color/icon/pacman.textart"

export BFETCH_INFO="pfetch"
export BFETCH_ART="cowsay '<3 Athena OS'"
export BFETCH_COLOR="$HOME/.local/textart/color/icon/panes.textart"

export PAYLOADS="/usr/share/payloads"
export SECLISTS="$PAYLOADS/SecLists"
export PAYLOADSALLTHETHINGS="$PAYLOADS/PayloadsAllTheThings"
export FUZZDB="$PAYLOADS/FuzzDB"
export AUTOWORDLISTS="$PAYLOADS/Auto_Wordlists"
export SECURITYWORDLIST="$PAYLOADS/Security-Wordlist"

export MIMIKATZ="/usr/share/windows/mimikatz/"
export POWERSPLOIT="/usr/share/windows/powersploit/"

export ROCKYOU="$SECLISTS/Passwords/Leaked-Databases/rockyou.txt"
export DIRSMALL="$SECLISTS/Discovery/Web-Content/directory-list-2.3-small.txt"
export DIRMEDIUM="$SECLISTS/Discovery/Web-Content/directory-list-2.3-medium.txt"
export DIRBIG="$SECLISTS/Discovery/Web-Content/directory-list-2.3-big.txt"
export WEBAPI_COMMON="$SECLISTS/Discovery/Web-Content/api/api-endpoints.txt"
export WEBAPI_MAZEN="$SECLISTS/Discovery/Web-Content/common-api-endpoints-mazen160.txt"
export WEBCOMMON="$SECLISTS/Discovery/Web-Content/common.txt"
export WEBPARAM="$SECLISTS/Discovery/Web-Content/burp-parameter-names.txt"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# switch to fish
if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} ]]
then
    exec fish
fi

#Configure zoxide for bash
eval "$(zoxide init bash)"

PS1="\e[1;32m┌──[HQ🚀🌐\e[1;31m$(ip -4 addr | grep -v '127.0.0.1' | grep -v 'secondary' | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | sed -z 's/\n/|/g;s/|\$/\n/' | rev | cut -c 2- | rev)🔥\u\e[1;32m]\n└──╼[👾]\[\e[1;36m\]\$(pwd) $ \[\e[0m\
\]"

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

# Bash aliases
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# Change up a variable number of directories
# E.g:
#   cu   -> cd ../
#   cu 2 -> cd ../../
#   cu 3 -> cd ../../../
function cu {
    local count=$1
    if [ -z "${count}" ]; then
        count=1
    fi
    local path=""
    for i in $(seq 1 ${count}); do
        path="${path}../"
    done
    cd $path
}


# Open all modified files in vim tabs
function vimod {
    vim -p $(git status -suall | awk '{print $2}')
}

# Open files modified in a git commit in vim tabs; defaults to HEAD. Pop it in your .bashrc
# Examples:
#     virev 49808d5
#     virev HEAD~3
function virev {
    commit=$1
    if [ -z "${commit}" ]; then
      commit="HEAD"
    fi
    rootdir=$(git rev-parse --show-toplevel)
    sourceFiles=$(git show --name-only --pretty="format:" ${commit} | grep -v '^$')
    toOpen=""
    for file in ${sourceFiles}; do
      file="${rootdir}/${file}"
      if [ -e "${file}" ]; then
        toOpen="${toOpen} ${file}"
      fi
    done
    if [ -z "${toOpen}" ]; then
      echo "No files were modified in ${commit}"
      return 1
    fi
    vim -p ${toOpen}
}

# 'Safe' version of __git_ps1 to avoid errors on systems that don't have it
function gitPrompt {
  command -v __git_ps1 > /dev/null && __git_ps1 " (%s)"
}

# Colours have names too. Stolen from Arch wiki
txtblk='\[\e[0;30m\]' # Black - Regular
txtred='\[\e[0;31m\]' # Red
txtgrn='\[\e[0;32m\]' # Green
txtylw='\[\e[0;33m\]' # Yellow
txtblu='\[\e[0;34m\]' # Blue
txtpur='\[\e[0;35m\]' # Purple
txtcyn='\[\e[0;36m\]' # Cyan
txtwht='\[\e[0;37m\]' # White
bldblk='\[\e[1;30m\]' # Black - Bold
bldred='\[\e[1;31m\]' # Red
bldgrn='\[\e[1;32m\]' # Green
bldylw='\[\e[1;33m\]' # Yellow
bldblu='\[\e[1;34m\]' # Blue
bldpur='\[\e[1;35m\]' # Purple
bldcyn='\[\e[1;36m\]' # Cyan
bldwht='\[\e[1;37m\]' # White
unkblk='\[\e[4;30m\]' # Black - Underline
undred='\[\e[4;31m\]' # Red
undgrn='\[\e[4;32m\]' # Green
undylw='\[\e[4;33m\]' # Yellow
undblu='\[\e[4;34m\]' # Blue
undpur='\[\e[4;35m\]' # Purple
undcyn='\[\e[4;36m\]' # Cyan
undwht='\[\e[4;37m\]' # White
bakblk='\[\e[40m\]'   # Black - Background
bakred='\[\e[41m\]'   # Red
badgrn='\[\e[42m\]'   # Green
bakylw='\[\e[43m\]'   # Yellow
bakblu='\[\e[44m\]'   # Blue
bakpur='\[\e[45m\]'   # Purple
bakcyn='\[\e[46m\]'   # Cyan
bakwht='\[\e[47m\]'   # White
txtrst='\[\e[0m\]'    # Text Reset

# Prompt colours
atC="${txtpur}"
nameC="${txtpur}"
hostC="${txtpur}"
pathC="${txtgrn}"
gitC="${txtpur}"
pointerC="${txtgrn}"
normalC="${txtwht}"

# Red name for root
if [ "${UID}" -eq "0" ]; then
  nameC="${txtred}"
fi

# Local settings go last
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi

#shopt
shopt -s autocd # change to named directory
shopt -s cdspell # autocorrects cd misspellings
shopt -s cmdhist # save multi-line commands in history as single line
shopt -s dotglob
shopt -s histappend # do not overwrite history
shopt -s expand_aliases # expand aliases

# # ex = EXtractor for all kinds of archives
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

export PROMPT_COMMAND='source ~/.bashrc'

buffer_clean(){
  free -h && sudo sh -c 'echo 1 >  /proc/sys/vm/drop_caches' && free -h
}
#create a file called .bashrc-personal and put all your personal aliases
#in there. They will not be overwritten by skel.

[[ -f ~/.bashrc-personal ]] && . ~/.bashrc-personal

# reporting tools - install when not installed
#neofetch | lolcat
#screenfetch
#alsi
#paleofetch
#fetch
#hfetch
#sfetch
#ufetch
#pfetch
#sysinfo
#sysinfo-retro
#cpufetch
#colorscript random

#bfetch configuration:

source /usr/share/blesh/ble.sh

**Comment by D3vil0p3r** [comment]
Ty @akinomyoga I used your last `.bashrc` content in the last comment and I also used:
```
[...]

export PROMPT_COMMAND='source ~/.bashrc without-blesh'

[...]

if [[ $1 != without-blesh ]]; then
  source /usr/share/blesh/ble.sh
fi
```
as you suggested above, for avoiding the recursive `[ble: reload]` message. In this manner, all the issues seem to be fixed.

Is there a way to customize or remove the background colors on the suggested string in ble.sh? For example, I'm getting this output:
![image](https://github.com/akinomyoga/ble.sh/assets/83867734/54e063a5-caf1-4fc6-ab30-9301e8436f1c)

Is there the way to remove that white highlighting and leave only the greyed out string as occurs in fish?
![image](https://github.com/akinomyoga/ble.sh/assets/83867734/29c19e40-d761-49a3-9653-22a821f2e842)

**Comment by D3vil0p3r** [comment]
> > Is there a way to customize or remove the background colors on the suggested string in ble.sh? For example, I'm getting this
> 
> * [README §2.6](https://github.com/akinomyoga/ble.sh#26-highlight-colors) - `auto_complete`
> * [Q&A - Completions - How to change the color of suggestions of auto-complete?](https://github.com/akinomyoga/ble.sh/wiki/Q&A#completions)

I'm trying `ble-face` but I'm getting `command not found`. The `ble-` commands I have are the following:
![image](https://github.com/akinomyoga/ble.sh/assets/83867734/695ffd65-6688-48bc-933a-69907587ab91)

but I don't see `ble-face`.

**Comment by akinomyoga** [comment]
Ah, OK. You are using ble-0.3. In that case, it's written in README of `v0.3-master` branch:

- [README - Basic settings - Highlight Colors](https://github.com/akinomyoga/ble.sh/tree/v0.3-master#basic-settings)

There is also an old answer on StackOverflow

- [bash - Autocompletion Background Colour in ble.sh - Super User](https://superuser.com/a/1512656/980046)

**Comment by D3vil0p3r** [comment]
@akinomyoga thank you for your availability and your help. All this information solves my issues and my doubts.

Thanks again and thank you for your awesome project!

**Comment by D3vil0p3r** [comment]
Hey @akinomyoga , is there a way to suppress `[ble: exit ...]` and the initial string when you run bash with blesh for the first time?

For `[ble: exit ...]` I tried to add to `.blerc` either `TRAPERR() { :; }` or `bleopt exec_errexit_mark=''` with no luck.

**Comment by akinomyoga** [comment]
For `[ble: exit ...]` use ble-0.4 with `bleopt exec_errexit_mark`. For the initial string, no, there isn't. Is it needed?

**Comment by D3vil0p3r** [comment]
> For `[ble: exit ...]`, use [ble-0.4](https://aur.archlinux.org/packages/blesh-git) with `bleopt exec_errexit_mark=`. For the initial string, no, there isn't. Is it needed?

The initial string is this one `ble/term.sh: updating tput cache for TERM=xterm-256color... done` that appears when I run bash for the first time after the first installation of blesh.

About `[ble: exit ...]` is there a solution for ble-0.3?

**Comment by akinomyoga** [comment]
> The initial string is this one `ble/term.sh: updating tput cache for TERM=xterm-256color... done` that appears when I run bash for the first time after the first installation of blesh.

Yes, I correctly understand what you are talking about, and the answer to "is there a way" is "no, there isn't (a way)". And, my question is "is it (i.e., the way to disable the initial string) needed"?

> About `[ble: exit ...]` is there a solution for ble-0.3?

`TRAPERR() { :; }` should work. As far as I test in my environment, it works in ble-0.3. If you still want to use ble-0.3 and it doesn't work, what is the output of the following command?

```bash
$ type TRAPERR
```

**Comment by D3vil0p3r** [comment]
> Yes, I correctly understand what you are talking about, and the answer to "is there a way" is "no, there isn't (a way)". And, my question is "is it (i.e., the way to disable the initial string) needed"?

It could be interesting for someone.

> `TRAPERR() { :; }` should work. As far as I test in my environment, it works in ble-0.3. If you still want to use ble-0.3 and it doesn't work, what is the output of the following command?
> `type TRAPERR`

Here my test:
```
┌──[HQ🚀🌐192.168.126.138🔥athena]
└──╼[👾]/home/athena $ bash
┌──[HQ🚀🌐192.168.126.138🔥athena]
└──╼[👾]/home/athena $ exit
[ble: exit]

┌──[HQ🚀🌐192.168.126.138🔥athena]
└──╼[👾]/home/athena $ bash
┌──[HQ🚀🌐192.168.126.138🔥athena]
└──╼[👾]/home/athena $ type TRAPERR
TRAPERR is a function
TRAPERR () 
{ 
    :
}
┌──[HQ🚀🌐192.168.126.138🔥athena]
└──╼[👾]/home/athena $ 
```

**Comment by akinomyoga** [comment]
> It could be interesting for someone.

Someone? Then, I'll not support it for now.

> Here my test:

OK, so you are not talking about `[ble: exit ...]` but `[ble: exit]`. These are two different features in ble.sh. Currently, there is no way to turn `[ble: exit]` off.

**Comment by D3vil0p3r** [comment]
> > It could be interesting for someone.
> 
> Someone? Then, I'll not support it for now.
> 
> > Here my test:
> 
> OK, so you are talking about `[ble: exit]` but not `[ble: exit ...]`. These are two different features in ble.sh. Currently, there is no way to turn `[ble: exit]` off.

Ah ok

**Comment by D3vil0p3r** [comment]
Hey @akinomyoga I'm continuing my tests on ble.sh and I'm noting another weird behavior.

In practice, if I use any terminal (i.e., I'm testing it by GNOME Terminal and Kitty), and you open it, and then you move to another folder, for example `/etc/ca-certificates/extracted`, then you expand the terminal window to full screen, and then execute `ls e-[press TAB for multiple choices to be highlighted by ble.sh`, the PROMPT is outputting shifting characters.

Here my test by Kitty:
(before pressing TAB)
![image](https://github.com/akinomyoga/ble.sh/assets/83867734/dc0198f2-0f59-46e1-8338-9dda412208ca)

(after pressing TAB)
![image](https://github.com/akinomyoga/ble.sh/assets/83867734/940155e8-8d9e-4a22-a09e-f25718fac2ff)

You can see that the inital string is duplicated, and if I try to delete all that command, the terminal remains like this:
![image](https://github.com/akinomyoga/ble.sh/assets/83867734/e0f85aa9-deda-481f-89e4-83e314f95384)

This issue occurs only when I enable the source of ble.sh on `.bashrc`. If ble.sh is not enabled, this issue does not appear.

I'm testing on latest Arch Linux kernel zen in GNOME 44.1 Xorg.

**Comment by akinomyoga** [comment]
Could you switch to 0.4? 0.3 doesn't support the widths of emojis.

**Comment by D3vil0p3r** [comment]
> Could you switch to 0.4? 0.3 doesn't support the widths of emojis.

Just one question: 0.4 is on beta version (since I read `Devel 0.4.0-devel3` on release page) or it is a stable version? Because I'm getting it by [AUR] (https://aur.archlinux.org/packages/blesh) package and this package seems still to be at 0.3. I see you are the maintainer of AUR package. Could you please update it to 0.4?

**Comment by akinomyoga** [comment]
Use the package [`blesh-git`](https://aur.archlinux.org/packages/blesh-git) instead of `blesh`. 0.4 is still in a devel state. I can technically update the AUR package `blesh` (0.4), but I will not because 0.4 contains a part that is half-implemented but the design is not yet finalized. The interfaces exposed to users are stable enough also with 0.4.

**Comment by D3vil0p3r** [comment]
> Use the package [`blesh-git`](https://aur.archlinux.org/packages/blesh-git) instead of `blesh`. 0.4 is still in a devel state. I can technically update the AUR package `blesh` (0.3 -> 0.4), but I will not because 0.4 contains a part that is half-implemented but the design is not yet finalized. The documented interfaces exposed to users are stable enough also with 0.4.

I confirm that with 0.4 the issue has been solved.

**Comment by akinomyoga** [comment]
Thank you for the confirmation!

**Comment by D3vil0p3r** [comment]
Hello @akinomyoga 
When a user runs a command that does not return results (as `grep`), ble.sh returns always the exit string. For example if I grep a file content in order to not match anything:
```
cat .bash_aliases | grep xclip
[ble: exit 1]
```
Is there no way to suppress this kind of exit message?
