### ISSUE TITLE
bashログイン時のエラー

### ISSUE THREAD

**Issue by tm99hjkl** [akinomyoga/ble.sh#322]
## バージョン
**ble version**: 0.4.0-devel4+f4c973b8

**Bash version**: 5.1.16(1)-release(x86_64-pc-linux-gnu)

## バグと思われる挙動について

このような[.bashrc](https://github.com/tm99hjkl/dotfiles/blob/main/.bashrc)を使っています．以下に挙動の動画を添付いたします．

https://user-images.githubusercontent.com/66460638/236823442-025496ca-7d64-484a-bd5e-c5893b4c5556.mp4

この動画は，[.bashrcの114行目](https://github.com/tm99hjkl/dotfiles/blob/main/.bashrc#L114)をコメントアウトしている場合は正常に動作し，コメントアウトを解除して新しいシェルにログインすると，エラーが一気に出力される様子のキャプチャです．

ble.shを愛用していますので，bugfixしていただけますと大変助かります．よろしくお願いいたします．

**Comment by tm99hjkl** [comment]
参考になるかはわかりませんが，`screenfetch`の結果も添付します．
![3_3  tm@DESKTOP-6CIE7VC_ ~ 2023_05_08 21_33_31](https://user-images.githubusercontent.com/66460638/236825214-c7c3459a-2637-471e-84fa-36078955b70d.png)

**Comment by akinomyoga** [comment]
ble.sh をお使いいただきありがとうございます。ご報告ありがとうございます!

ご報告いただいた .bashrc を試してみたのですが再現できません。Ubuntu 22.04/WSL2 も設定して試してみましたがそれでも再現しないようです。ただ、neofetch の出力する OS/Kernel 情報が異なるので何か構成が異なるのかもしれません。
![image](https://user-images.githubusercontent.com/8982192/236910601-583dedec-6e47-497a-a539-368c27a89019.png)

質問がございます。114行目を追加すると問題が発生するとのことですが、逆に ble.sh 以外の設定をコメントアウトした場合にも症状は再現するでしょうか。もしそうでなければどの設定と一緒に用いた時に問題が発生するのか特定していただけますと助かります。

症状を拝見しますに恐らく ble.sh の内部関数の `ble/util/assign` が用いている一時ファイルの内容が混ざり合っていることによるものではないかと現在は推測しています。114行目をコメントアウトした状態で以下のコマンドを実行した時の結果を教えていただけますと幸いです。

```bash
$ type ble/util/assign
$ type ble/util/assign/.mktmp
$ type local
$ echo "$SUBSHELL:$BASHPID:$$"
$ (echo "$SUBSHELL:$BASHPID:$$")
$ declare -p _ble_local_tmpfile
```

ちなみにご報告のエラーメッセージだけでしたら [.bashrc 12行目](https://github.com/tm99hjkl/dotfiles/blob/2300e1d0ca871ec89093aa549911fc87cae8de77/.bashrc#L12) で `--inputrc=none` を追加して関連する機能を off にしていただければ、取り敢えずは抑えることができるのではないかと思いますが、恐らく根本的解決にはならないのではないかと考えています。

**Comment by tm99hjkl** [comment]
早速ご確認いただきありがとうございます。

まず，以下を確認しました：
* [.bashrcの114行目](https://github.com/tm99hjkl/dotfiles/blob/main/.bashrc#L114)だけを有効にし，他すべてをコメントアウトしたとき，同様のエラーは起きませんでした．
* [.bashrcの12行目](https://github.com/tm99hjkl/dotfiles/blob/main/.bashrc#L12)と114行目を有効にし，他すべてをコメントアウトしたとき，同様のエラーが起きました．

いただいたコメント内のコマンドを実行すると以下のようになりました:
```
$ type ble/util/assign
ble/util/assign is a function
ble/util/assign ()
{
    local _ble_local_tmpfile;
    ble/util/assign/.mktmp;
    builtin eval -- "$2" >| "$_ble_local_tmpfile";
    local _ble_local_ret=$? _ble_local_arr=;
    mapfile -t _ble_local_arr < "$_ble_local_tmpfile";
    ble/util/assign/.rmtmp;
    IFS='
' builtin eval "$1=\"\${_ble_local_arr[*]}\"";
    return "$_ble_local_ret"
}
```

```
$ type ble/util/assign/.mktmp
ble/util/assign/.mktmp is a function
ble/util/assign/.mktmp ()
{
    _ble_local_tmpfile=$_ble_util_assign_base.$((_ble_util_assign_level++));
    ((BASH_SUBSHELL)) && _ble_local_tmpfile=$_ble_local_tmpfile.$BASHPID
}
```

```
$ type local
local is a shell builtin
```

```
$ echo "$SUBSHELL:$BASHPID:$$"
:1089:1089
```

```
$ (echo "$SUBSHELL:$BASHPID:$$")
:1560:1089
```

```
$ declare -p _ble_local_tmpfile
-bash: declare: _ble_local_tmpfile: not found
```

```
$ declare -p _ble_base_run
declare -- _ble_base_run="/mnt/wslg/runtime-dir/blesh"
```

```
$ ls -la "$_ble_base_run"
.rw-r--r-- 0 tm  9 May 10:19 1089.load
.rw-r--r-- 0 tm  9 May 10:21 1089.util.assign.tmp.0
.rw-r--r-- 0 tm  9 May 10:19 1089.util.message
.rw-r--r-- 0 tm  9 May 10:19 1089.util.message-listening
.rw-r--r-- 0 tm  8 May 21:05 16280.load
.rw-r--r-- 0 tm  8 May 21:05 16280.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 21:07 16518.load
.rw-r--r-- 0 tm  8 May 21:07 16518.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 21:07 16544.load
.rw-r--r-- 0 tm  8 May 21:07 16544.trap.DEBUG
.rw-r--r-- 0 tm  8 May 21:07 16544.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 21:07 16544.util.assign.tmp.1
.rw-r--r-- 0 tm  8 May 21:08 17280.load
.rw-r--r-- 0 tm  8 May 21:08 17280.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 21:08 17469.load
.rw-r--r-- 0 tm  8 May 21:08 17469.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 21:08 17636.load
.rw-r--r-- 0 tm  8 May 21:08 17636.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 21:09 18181.load
.rw-r--r-- 0 tm  8 May 21:09 18181.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 21:09 18181.util.assign.tmp.1
.rw-r--r-- 0 tm  8 May 21:09 18181.util.message
.rw-r--r-- 0 tm  8 May 21:09 18181.util.message-listening
.rw-r--r-- 0 tm  8 May 21:11 19434.load
.rw-r--r-- 0 tm  8 May 21:12 19434.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 21:11 19434.util.message
.rw-r--r-- 0 tm  8 May 21:11 19434.util.message-listening
.rw-r--r-- 0 tm  8 May 21:56 20213.load
.rw-r--r-- 0 tm  8 May 21:56 20213.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 21:56 20213.util.message
.rw-r--r-- 0 tm  8 May 21:56 20213.util.message-listening
.rw-r--r-- 0 tm  8 May 22:01 20448.load
.rw-r--r-- 0 tm  9 May 09:58 20448.util.assign.tmp.0
.rw-r--r-- 0 tm  8 May 22:01 20448.util.message
.rw-r--r-- 0 tm  8 May 22:01 20448.util.message-listening
.rw-r--r-- 0 tm  9 May 10:06 31501.load
.rw-r--r-- 0 tm  9 May 10:06 31501.util.assign.tmp.0
.rw-r--r-- 0 tm  9 May 10:06 31501.util.message
.rw-r--r-- 0 tm  9 May 10:06 31501.util.message-listening
```

---
（また，[.bashrc 12行目](https://github.com/tm99hjkl/dotfiles/blob/2300e1d0ca871ec89093aa549911fc87cae8de77/.bashrc#L12) で --inputrc=none を追加して新しいシェルにログインしたところ，プロンプトに`RR1R5R9R2R6RRRR2R6RRRR2R`という文字列が入力された状態でシェルが開始されることを確認しました．参考になるかは分かりませんが...）

**Comment by akinomyoga** [comment]
ご回答いただきありがとうございます。

先の返信にて環境の構成が異なるかもしれないとお書きしましたが screenfetch を neofetch と勘違いしておりました。改めて screenfetch で確認した所、Linux kernel version が異なる以外は同様の環境のようです。失礼いたしました。

![image](https://github.com/akinomyoga/ble.sh/assets/8982192/3ea7c4ff-fbf7-4b58-ac05-ee2ddb4a4c97)

----

ble.sh の設定だけで問題が発生するとのこと承知しました。そうするとシステムの bash 設定、inputrc 設定や端末などの外部要因が関係しているのかもしれません。

一連のコマンドの結果についてご提供いただきありがとうございます。これらを拝見する限りは特に大きな異常はないように思います。ただ、`ls -la "$_ble_base_run"` の結果の中に `.` および `..` の結果がないのは気になります。改めて以下も確認していただけますか。

```bash
$ ls -ld "$_ble_base_run"
```

関係あるかどうかは分かりませんが WSL1 で https://github.com/microsoft/WSL/issues/9025 のような報告もあるようです。

ところで、先のコマンドで `SUBSHELL` は `BASH_SUBSHELL` の誤りだったので、余分なお手数をおかけしてすみませんが以下のコマンドを追加で確認していただければ幸いです。

```bash
$ (echo "$BASH_SUBSHELL")
```

また、実際にシェル関数 `ble/util/assign` の振る舞いを確認しておきたいと考えています。ble.sh のセッションの中で以下を実行して結果を見ていただくことは可能でしょうか (セッション自体が開始できない場合は前述の --inputrc=none でも試していただければ幸いです)。

```bash
$ ble/util/assign a 'ble/util/assign b "echo c"'; declare -p a b
```

----

> （また，[.bashrc 12行目](https://github.com/tm99hjkl/dotfiles/blob/2300e1d0ca871ec89093aa549911fc87cae8de77/.bashrc#L12) で --inputrc=none を追加して新しいシェルにログインしたところ，プロンプトに`RR1R5R9R2R6RRRR2R6RRRR2R`という文字列が入力された状態でシェルが開始されることを確認しました．参考になるかは分かりませんが...）

もしかするとこれはまた独立な問題かもしれませんね…。この文字列は、端末の文字幅テーブルのバージョンを特定するための ble.sh の問い合わせに対して、端末が返した応答の一部のはずです。しかし本来はこれらの応答は切り分けられてプロンプトに現れることはないはずなので、応答データが何処かで壊れている可能性が考えられます。

端末の構成について確認させていただきたく思います。お使いの端末エミュレータは何でしょうか。どのように WSL に接続されていますか。もし端末マルチプレクサなどをお使いで問題が端末マルチプレクサ使用時に固有のものであれば、その情報もお願い致します。

また、(12行目だけある状態で) 以下のコマンドの結果についても教えていただけると助かります。

```bash
$ ble/widget/display-shell-version
```

**Comment by tm99hjkl** [comment]
ご対応ありがとうございます．

`ls -la "$_ble_base_run"` の結果の中に `.` および `..` の結果がないのは，`ls`に別のlsライクなコマンドをエイリアシングしていたからでした．紛らわしくてすみません...

一応，GNUの`ls`では以下のようになりました：
```
$ /bin/ls -la "$_ble_base_run"
total 0
drwx------ 2 tm tm    680 May 10 14:49 .
drwx------ 6 tm users 200 May  9 15:12 ..
-rw-r--r-- 1 tm tm      0 May  9 10:19 1089.load
-rw-r--r-- 1 tm tm      0 May  9 10:23 1089.util.assign.tmp.0
-rw-r--r-- 1 tm tm      0 May  9 10:19 1089.util.message
-rw-r--r-- 1 tm tm      0 May  9 10:19 1089.util.message-listening
-rw-r--r-- 1 tm tm      0 May  9 13:18 11390.load
-rw-r--r-- 1 tm tm      0 May 10 14:42 11390.util.assign.tmp.0
-rw-r--r-- 1 tm tm      0 May  9 13:18 11390.util.message
-rw-r--r-- 1 tm tm      0 May  9 13:18 11390.util.message-listening
-rw-r--r-- 1 tm tm      0 May  9 16:23 13544.load
-rw-r--r-- 1 tm tm      0 May  9 16:25 13544.util.assign.tmp.0
-rw-r--r-- 1 tm tm      0 May  9 16:23 13544.util.message
-rw-r--r-- 1 tm tm      0 May  9 16:23 13544.util.message-listening
-rw-r--r-- 1 tm tm      0 May 10 11:40 14640.load
-rw-r--r-- 1 tm tm      0 May 10 14:42 14640.util.assign.tmp.0
-rw-r--r-- 1 tm tm      0 May 10 11:40 14640.util.message
-rw-r--r-- 1 tm tm      0 May 10 11:40 14640.util.message-listening
-rw-r--r-- 1 tm tm      0 May 10 12:39 15175.load
-rw-r--r-- 1 tm tm      0 May 10 12:39 15175.util.assign.tmp.0
-rw-r--r-- 1 tm tm      0 May 10 12:39 15175.util.message
-rw-r--r-- 1 tm tm      0 May 10 12:39 15175.util.message-listening
-rw-r--r-- 1 tm tm      0 May 10 14:19 16278.load
-rw-r--r-- 1 tm tm      0 May 10 14:42 16278.util.assign.tmp.0
-rw-r--r-- 1 tm tm      0 May 10 14:19 16278.util.message
-rw-r--r-- 1 tm tm      0 May 10 14:19 16278.util.message-listening
-rw-r--r-- 1 tm tm      0 May 10 14:42 16594.load
-rw-r--r-- 1 tm tm      0 May 10 14:42 16594.util.assign.tmp.0
-rw-r--r-- 1 tm tm      0 May 10 14:42 16594.util.message
-rw-r--r-- 1 tm tm      0 May 10 14:42 16594.util.message-listening
-rw-r--r-- 1 tm tm      0 May  9 10:25 8699.load
-rw-r--r-- 1 tm tm      0 May 10 14:42 8699.util.assign.tmp.0
-rw-r--r-- 1 tm tm      0 May  9 10:25 8699.util.message
-rw-r--r-- 1 tm tm      0 May  9 10:25 8699.util.message-listening
```
```
$ /bin/ls -ld "$_ble_base_run"
drwx------ 2 tm tm 680 May 10 14:49 /mnt/wslg/runtime-dir/blesh
```

また，`(echo "$BASH_SUBSHELL")`と`ble/util/assign a 'ble/util/assign b "echo c"'; declare -p a b`も実行してみました：
```
$ (echo "$BASH_SUBSHELL")
1
```
```
$ ble/util/assign a 'ble/util/assign b "echo c"'; declare -p a b
declare -- a=""
declare -- b="c"
```

---

また，端末エミュレータは[wezterm](https://github.com/wez/wezterm)を使っています．が，別の端末エミュレータである[WindowsTerminal](https://github.com/microsoft/terminal)でも同じ症状を確認しました．端末マルチプレクサは使用していないです．

`ble/widget/display-shell-version`の結果も添付いたします．
```
$ ble/widget/display-shell-version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) [Ubuntu 22.04.2 LTS]
ble.sh, version 0.4.0-devel4+f4c973b8 (noarch) [git 2.34.1, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:b42f5d6a7ad6d4921ec73838ba54a96d6bd30936, 77071 bytes) (noarch)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=auto-auto/15.0-2+ri
````

お手数ですが再度ご確認いただけますと幸いです．
（どうやらble.shがというより，他の問題がありそうな気がしてきました・・・）

**Comment by tm99hjkl** [comment]
ご返信ありがとうございます．

> 先ず、子 Bash セッションで command not found の問題が再現するか確認していただけますか。

これは，やはり子 Bash セッションにおいても問題は発生しました．

念のため，問題の`.bashrc`ではない場合，つまり応急処置で`--inputrc=none`を追記した場合での子 Bash セッション起動もしてみました．（こちらの動画も添付いたします．）

https://github.com/akinomyoga/ble.sh/assets/66460638/2c5c614d-85a9-44fd-9fb7-c432cd518d43

---

また，デバッグトレースを以下に置きます：[xtrace.txt.gz](https://github.com/akinomyoga/ble.sh/files/11450411/xtrace.txt.gz)

---

最後に，`bash --noprofile`の出力結果についてですが，問題の`bashrc`においては`command not found`の問題が起き，`--inputrc=none`を追記した場合では`RRR...`の問題が起きました．

何度もご対応いただいてすみません，ありがとうございます．

**Comment by tm99hjkl** [comment]
コメントに載せていただいたコマンドの一つ目を実行した際に気づいたのですが，`nawk`というコマンドがあることを知らずに，`nawk`という名前の自作コマンドを`/usr/local/bin`に置いてしまっていました... orz

申し訳ないのですが`nawk`の再インストールの方法が分からず，ひとまず`ln -s /usr/bin/nawk /usr/local/bin/nawk`として，書いていただいたコマンドを実行しました：
```
$ /usr/local/bin/nawk --version
GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)
Copyright (C) 1989, 1991-2020 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.
```

```
$ echo __BIND0__ | LC_ALL= LC_CTYPE=C /usr/local/bin/nawk -v q=\' -v _ble_bash=50116 '/^__BIND0__$/ { next; }'
$ # 出力結果はありませんでした
```

```
$ ble/builtin/bind/read-user-settings/.reconstruct | head
bind -m emacs '"\e\e[D": backward-word'
bind -m emacs '"\e[5D": backward-word'
bind -m emacs '"\e[1~": beginning-of-line'
bind -m emacs '"\e[4~": end-of-line'
bind -m emacs '"\e\e[C": forward-word'
bind -m emacs '"\e[5C": forward-word'
bind -m emacs '"\e[2~": quoted-insert'
```

以上です．よろしくお願いいたします．

**Comment by tm99hjkl** [comment]
`ln -s /usr/bin/nawk /usr/local/bin/nawk` として ble.sh を再インストールしたら解決しました... 
丁寧にご対応いただいて本当に助かりました，ありがとうございました．
（自分の環境のせいなのに ble.sh のバグ扱いしまってすみません... orz）

**Comment by akinomyoga** [comment]
なるほど、そういうことでしたか。納得です。手助けになれたようで幸いです! また何かあればお気軽にご相談ください。
