### ISSUE TITLE
組み込みコマンドのハイライトがおかしい

### ISSUE THREAD

**Issue by Hayao0819** [akinomyoga/ble.sh#323]
**ble version**: 0.4.0-nightly+f4c973b
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu)

組み込みコマンドを入力した際に間違ったシンタックスハイライティングが表示されます。

<img width="461" alt="image" src="https://user-images.githubusercontent.com/32128205/237006613-23667f4d-e875-4620-ab0a-cf42535b68d8.png">

**Comment by akinomyoga** [comment]
ご報告ありがとうございます!

画面の拝見する限りは何れも私が既定で意図したハイライティングになっているのですが、どのような動作を期待されていますか。恐らく特に `hoge` のハイライティングのことを指しているのだと推察いたします。`hoge` はエイリアスなのでエイリアスの着色 (`ble-face command_alias` で確認・設定いただけます) が適用されることになっています。

注記: キーワードに対するエイリアスだけは構文解析に直に影響するので特別にキーワードであることを検出していますが、これは例外的な実装です。

**Comment by Hayao0819** [comment]
外部コマンドと同じ様に緑色になると思ってました。

すみませんこれで適切な状態だったんですね。

**Comment by Hayao0819** [comment]
`ble-face -s command_builtin fg=green`で外部コマンドと同様の色に変更できました。

お騒がせしました。
