### ISSUE TITLE
[fzf-completion] Shrink paths in completion

### ISSUE THREAD

**Issue by teutat3s** [akinomyoga/ble.sh#329]
Hello,

thank you for creating and maintaining `ble.sh`!

**ble version**: `0.4.0-devel3+1a5c451c`
**Bash version**: `5.2.15(1)-release (x86_64-pc-linux-gnu)`

Is it possible to shrink paths in `desc` completion menu mode? Currently, with long paths, the filenames get truncated, and the results get a lot less useful like this. Please see the following output to illustrate the issue:

```
❯ cp ~/CodeRoom/github.com/TritonDataCenter/prr/<TAB>
~/CodeRoom/github.com/TritonDataCenter/prr/bin    file (???)              | ~/CodeRoom/github.com/TritonDataCenter/prr/Makefi file (???)
~/CodeRoom/github.com/TritonDataCenter/prr/deps   file (???)              | ~/CodeRoom/github.com/TritonDataCenter/prr/node_m file (???)
~/CodeRoom/github.com/TritonDataCenter/prr/.git   file (???)              | ~/CodeRoom/github.com/TritonDataCenter/prr/packag file (???)
~/CodeRoom/github.com/TritonDataCenter/prr/.gitig file (???)              | ~/CodeRoom/github.com/TritonDataCenter/prr/packag file (???)
~/CodeRoom/github.com/TritonDataCenter/prr/.gitmo file (???)              | ~/CodeRoom/github.com/TritonDataCenter/prr/README file (???)
~/CodeRoom/github.com/TritonDataCenter/prr/lib    file (???)              | ~/CodeRoom/github.com/TritonDataCenter/prr/remote file (???)
~/CodeRoom/github.com/TritonDataCenter/prr/LICENS file (???)              | ~/CodeRoom/github.com/TritonDataCenter/prr/tags   file (???)
```

Maybe there is a setting I missed that I can use to make the output more useful?
One suggestion that occurs to me would be to shrink the path to the current directory after x levels of directories.

I'm using ` bleopt complete_menu_style=desc`.

**Comment by akinomyoga** [comment]
Thanks for the report. Do you use `fzf` completions? `ble.sh` shrinks the path by default, but `fzf` completion seems to generate the full path for the completions.

What are the outputs of the following commands?

```bash
$ ble/widget/display-shell-version
$ (shopt -s extdebug; declare -F _fzf_path_completion)
```

**Comment by akinomyoga** [comment]
OK, thanks for the confirmation! I think I'll later consider adding workarounds/adjustments to the fzf completion.

**Comment by teutat3s** [comment]
Turning the bash integration off also disables the fzf history widget (CTRL-R) so that's not an option sadly.

I can confirm the directory completion without fzf works like you describe and shortens the path correctly. Maybe there is some flag I can pass to fzf to behave the same way?

**Comment by akinomyoga** [comment]
I don't think there is a flag that can be passed to `fzf`. I feel like Home Manager `fzf.nix` should provide an option to control both separately.

**Comment by teutat3s** [comment]
Thank you for the idea.

I was able to only enable the history widget but no completion from fzf like so:
nix home-manager configuration:
```
programs.fzf.enableBashIntegration = false;
```
bashrc:
```
source ${pkgs.fzf}/share/fzf/key-bindings.bash
```

I will test this out to see if this way and can get the best of both tools.

**Comment by akinomyoga** [comment]
I added a fix f16c0d807c8e1fe26fa5d990b561829382cbdc72 so that the path is correctly shrunk even when the fzf completion is used. Could you test the behavior? Thank you.

**Comment by teutat3s** [comment]
I can confirm that the path gets correctly shrunk with fzf now. Thank you very much!

**Comment by akinomyoga** [comment]
Thank you for the confirmation!
