### ISSUE TITLE
Sourcing problem `unexpected EOF`

### ISSUE THREAD

**Issue by BuddhiLW** [akinomyoga/ble.sh#331]
**ble version**: 0.4.0-devel2+
**Bash version**: 5.2.15(1)-release (x86_64-pc-linux-gnu)

`source ble.sh`

returns:

```shell
bash: command substitution: line 1: unexpected EOF while looking for matching `''
Command 'awk:' not found, did you mean:
  command 'awk' from deb gawk (1:5.2.1-2)
  command 'awk' from deb mawk (1.3.4.20200120-3.1)
  command 'awk' from deb original-awk (2022-09-12-1)
Try: sudo apt install <deb name>
```

I have awk, though
```shell
whereis awk

awk: /usr/bin/awk /usr/lib/x86_64-linux-gnu/awk /usr/share/awk /usr/share/man/man1/awk.1.gz
```

**Comment by BuddhiLW** [comment]
Initiating a bash session gives: 
```shell
bash: eval: line 7054: syntax error near unexpected token `('
```

My config in `.bashrc`:
```shell
[[ $- == *i* ]] && source /path/to/ble.sh --noattach

(... configs)

[[ ${BLE_VERSION-} ]] && ble-attach
```

**Comment by akinomyoga** [comment]
Thanks for the reporit.

> **ble version**: 0.4.0-devel2+

This implies that the generated `ble.sh` is broken.

- **Q1** What are the results of the following commands?

```bash
$ awk --version
$ gawk --version
$ cat /etc/os-release
```
- **Q2** Does the problem change with adding `unalias -a` in the following way?

```bash

unalias -a
[[ $- == *i* ]] && source /path/to/ble.sh --noattach

(... configs)

unalias -a
[[ ${BLE_VERSION-} ]] && ble-attach
```

Note: Those are just for testing purposes to identify the problem, so please remove the added lines after the testing. `unalias -a` removes all the user aliases.

**Comment by akinomyoga** [comment]
@BuddhiLW Have you solved the problem? Could you take a look at the above reply when you have time?

**Comment by BuddhiLW** [comment]
Hey @akinomyoga thanks for the support. I end up installing it differently, and sourcing the package manager's build, instead of building it from source.

Sorry for the late reply.

**Comment by BuddhiLW** [comment]
Of course, here it is:

Actually, I'm using st ([https://github.com/BuddhiLW/st.git](https://github.com/BuddhiLW/st.git)), and you can reproduce my system partially by installing a fresh ubuntu, and running `main.sh`, after `git clone`  [https://github.com/BuddhiLW/dotfiles.git](https://github.com/BuddhiLW/dotfiles.git) this repo.

```shell
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu) [Ubuntu 23.04]
ble.sh, version 0.4.0-devel4+f16c0d80 (noarch) [git 2.39.2, GNU Make 4.3, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:8fb067d157b63461693a72b0885cd9b7f3c1490f, 77086 bytes) (noarch)
locale: LC_COLLATE=C LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.0-2+ri, tmux:0 (84;0;0)
```

**Comment by BuddhiLW** [comment]
Idk, I think it had to do with Guix and how it clashed often with the configs I developed over-time in Ubuntu.

To make it run smoothly in both systems was not trivial; actually, I will be working in my own channels, in Guix, in order to make my WM available with a guix-system.

Anyways, you shouldn't worry about it, for now. If I'm able to get the same error in the future, I will let you know, and I will be carefull to document it properly (reproduction steps).

What I can say for now, is that in Ubuntu to make completions work properly, after my install, I have to uncomment these lines, under `/etc/bash.bashrc` (comes commented by default):
```shell
# enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
```

**Comment by BuddhiLW** [comment]
If you wish to contact at any time, message me pedrogbranquinho@gmail.com

Cheers :D.

**Comment by akinomyoga** [comment]
Thank you for the detailed information! I'll later try to replicate the problem at my side based on the provided information!
