### ISSUE TITLE
Quoted path autocomplete

### ISSUE THREAD

**Issue by rauldipeas** [akinomyoga/ble.sh#332]
How can I disable only the _path_ autocomplete?

Those _quotes_ are not helping.

**Comment by akinomyoga** [comment]
@rauldipeas Thank you for the report. Could you explain it in a bit more detail? What do you specifically talk about by the path autocomplete and the quotes?

For example, are you talking about two separate things, 1) disabling the path candidates in auto-complete and 2) the quotes of something? Or if you are talking about something related to both the auto-complete of paths and the quotation of something, how are these two related? I think it would be useful to provide actual examples.

**Comment by rauldipeas** [comment]
When I type a path of a directory that have spaces like `/home/rauldipeas/Example\ folder`, the autocomplete goes to `'/home/rauldipeas/Example folder'`, without backslash and inside those quotes.

I want to disable this behaviour.

**Comment by akinomyoga** [comment]
Thank you for the explanation. I've added an option [`bleopt complete_requote_threshold`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-bleopt-complete_requote_threshold) in commit bb7e118e9146d56a9cf298ffab1a543306fd6022. Please check the description in the linked page. To entirely disable the behavior, you can write the following setting:

```bash
# ~/.blerc

bleopt complete_requote_threshold=-1
```

If you would like to simplify the quoting only when the number of characters reduces, you can use the following setting:

```bash
# ~/.blerc

bleopt complete_requote_threshold=1
```

If you would like to simplify the quoting when the number of characters reduces by at least e.g. five characters, the following setting can be used:

```bash
# ~/.blerc

bleopt complete_requote_threshold=5
```

**Comment by rauldipeas** [comment]
I've completely disabled it, works great! Thank You!

**Comment by akinomyoga** [comment]
Thanks for checking!
