### ISSUE TITLE
Incomprehensible (and maybe atrocious) bludgeoning of all gh commands pertaining to the GitHub CLI system

### ISSUE THREAD

**Issue by arnoldmashava** [akinomyoga/ble.sh#338]
1. **System Specifications**

`ble version`

```bash
>_ ble version
ble.sh, version 0.4.0-devel4+f16c0d80 (noarch)
```

`GNU bash and Linux Environment`

```bash
>_ bash --version
GNU bash, version 5.2.15(1)-release (x86_64-suse-linux)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

2. **Illustration of Cited Glitch**

Any decent form of access and interaction with the `GitHub CLI` system through the prescribed `gh` commands is bludgeoned without execution and the outputted `[ble: exit]` code does not provide additional verbosity to assist in debugging the termination of the `gh` commands: 

```bash
>_ which gh
/usr/bin/gh

>_ whereis gh
gh: /usr/bin/gh /usr/share/man/man1/gh.1.gz

>_ gh
[ble: exit 1]

```

3. **Musings**

In the absence of succinct verbosity (as would be anticipated in an interactive `GNU bash` session), the `[ble: exit]` codes just become a cryptic nuisance and painful computational impediment, with no starting point for the Developer to iterate towards the desired solution. 

When the `ble.sh` script is disabled in my `~/.bashrc` configuration, the `GitHub CLI` system responds to and interacts with all `gh` commands but I cannot decipher what `[ble: exit 1]` represents without additional system output (verbosity) on why the `gh` commands are being bludgeoned.

Can `ble.sh` and the `GitHub CLI` system coexist in the same `GNU bash` environment, without both the bludgeoning of `gh` commands and the outputting of `[ble: exit]` codes that are devoid of verbosity?

Muchas Gracias y Saludos Cordiales,

Arnold Mashava.

![Screenshot_20230629_055158](https://github.com/akinomyoga/ble.sh/assets/5759101/0fce7cf6-baeb-466d-a0a5-69c5fe8da060)

**Comment by akinomyoga** [comment]
Thank you for the report. I now try to reproduce the problem. How do you source `ble.sh` in `~/.bashrc`?

**Comment by arnoldmashava** [comment]
@akinomyoga Thank you so much, for the instantaneous attention.

Herewith the snippets from my `~/.bashrc` file:

```bash
# ble.sh configuration to appear at the head of the ~/.bashrc file
[[ $- == *i* ]] && source /home/Arnold.Mashava/.local/share/blesh/ble.sh --noattach
...
...
# ble.sh configuration to appear at the foot of the ~/.bashrc file
[[ ${BLE_VERSION-} ]] && ble-attach
```

**Comment by akinomyoga** [comment]
Thank you for providing the information for your `~/.bashrc`. It doesn't seem to reproduce in my environment, Fedora.

To make it clear, the behavior that you observed is not intended. `[ble: exit 1]` shouldn't be output from the `gh` command when ble.sh and gh coexist in the system. Ble.sh doesn't restrict any other programs to be installed on the same system. In fact, in my Fedora, it doesn't seem to cause the unintended output even when both are installed in the system.

Now I'm trying to reproduce the problem in OpenSUSE Tumbleweed, but it would take time. I'm now updating the OpenSUSE Tumbleweed, but 1215 packages are now being updated. After that I will try to install the `gh` command and see if the problem arises.

----

**Q2**: In the meantime, could you also try to see if the problem arises with the following simple `~/.bashrc`? Please back up your `~/.bash_history` before you try this (the history might be truncated unexpectedly).

```bash
# Only the following these two lines.
[[ $- == *i* ]] && source /home/Arnold.Mashava/.local/share/blesh/ble.sh --noattach
[[ ${BLE_VERSION-} ]] && ble-attach
```

Could you also try with the same `~/.bashrc` a child session of Bash? A child session can be started by running the `bash` command in the parent Bash session.

```bash
$ bash # <-- start a child session
$ gh # <-- see if the problem arises
$ exit # <-- exit the child session
```

**Comment by arnoldmashava** [comment]
@akinomyoga Thanks, I will also isolate the `~/.blerc` configuration file and experiment with the system. 

From conjecture, the glitch could be residing in the `~/.blerc` configuration file and emanating from 3 possibilities: 

1. the content replicated from the [ble.sh Recipes](https://github.com/akinomyoga/ble.sh/wiki/Recipes) in the [ble.sh Wiki](https://github.com/akinomyoga/ble.sh/wiki/Home)

2. the content replicated from the [blesh-contrib](https://github.com/akinomyoga/blesh-contrib) repository

3. my ageing brain and fading mental faculties, where in the `~/.blerc` configuration file, there will exist errors from a seemingly wayward soul

I will update (and maybe close) the issue thereafter.

Have a pleasant day ahead.

**Comment by akinomyoga** [comment]
> From conjecture, the glitch could be residing in the `~/.blerc` configuration file and emanating from 3 possibilities:

Thanks. To see if `~/.blerc` is the culprit or not, you can turn off `~/.blerc` by specifying `--norc` to the source line of ble.sh.

```bash
[[ $- == *i* ]] && source /home/Arnold.Mashava/.local/share/blesh/ble.sh --noattach --norc
```

**Comment by arnoldmashava** [comment]
@akinomyoga My deepest appreciation for the hack. Thank you so much. I will fully update and close Issue #338 as soon I conclude the troubleshooting process. 

Yes, I need both `ble.sh` and the `GitHub CLI` to coexist in the same `GNU bash` environment: the autocompletions and command input syntax highlighting are only possible through a flawlessly configured `ble.sh`.

Muchas Gracias.

**Comment by akinomyoga** [comment]
I've finished upgrading OpenSUSE and installed `gh` in OpenSUSE. I confirmed that the problem still doesn't reproduce also in OpenSUSE. I believe some other third configurations interfere with them.

**Comment by arnoldmashava** [comment]
Thank you so much, for taking the time to update your `openSUSE Tumbleweed` workstation and running rigorous tests on our beloved `ble.sh`. As alluded to in the initial hypothesis, after initially isolating the `~/.blerc` configuration in the sourcing of the `ble.sh` script:

```bash
[[ $- == *i* ]] && source /home/Arnold.Mashava/.local/share/blesh/ble.sh --noattach --norc
```

the `GitHub CLI` system fired up perfectly, with no `[ble: exit 1]` code in response to the input of the `gh` command. 

The glitch therefore emanated from the contents of the `~/.blerc` configuration file, which after blanking it and incrementally populating it with the desired configuration replicated from the content in the [blerc.template](https://github.com/akinomyoga/ble.sh/blob/master/blerc.template), [ble.sh Recipes](https://github.com/akinomyoga/ble.sh/wiki/Recipes) and [blesh-contrib](https://github.com/akinomyoga/blesh-contrib) repository, I was able to link the error to the [integration/fzf-git](https://github.com/akinomyoga/blesh-contrib#pencil-integrationfzf-git) section from the [blesh-contrib](https://github.com/akinomyoga/blesh-contrib) repository.

Regrettably, I do not have acumen to decipher why the `gh` command is bludgeoned by the `fzf-git` integration code snippet in the `~/.blerc` file:

```bash
_ble_contrib_fzf_git_config=key-binding:sabbrev:arpeggio
ble-import -d integration/fzf-git
```

I am happy to confirm that the declared Environment Variable:

```bash
_ble_contrib_fzf_base=/home/Arnold.Mashava/.fzf/shell/
```
does not interfere with the `gh` command and the error is specifically confined to the importation of the `fzf-git` script.

Herewith attached, the resultant of the iterative *Kiss and Tell* dance. As I conclude and close off Issue #338 , I hereby express my heartfelt acknowledgements, for the immense exertion and investment in time, multiple `Linux` workstations and the mental aptitude, to result in the conception of a colorful, somewhat finicky and intuitive child called `ble.sh`. 

Muchas Gracias y Saludos Cordiales,

Arnold Mashava.

![Screenshot_20230629_170648](https://github.com/akinomyoga/ble.sh/assets/5759101/4aefed14-3a57-4f3c-92bb-0f493dbb32a6)

**Comment by akinomyoga** [comment]
> I was able to link the error to the [integration/fzf-git](https://github.com/akinomyoga/blesh-contrib#pencil-integrationfzf-git) section from the [blesh-contrib](https://github.com/akinomyoga/blesh-contrib) repository.

Thank you for the detailed investigation. I remembered that the `fzf-git` module contains a shell function of the conflicting name `gh`. `fzf-git` is basically a port from [`junegunn/functions.sh`](https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236). The original version seems to have switched from `gh` to `_gh` on  2020-09-24, and it seems to have even switched to `_fzf_git_hashes` in another repository [`junegunn/fzf-git.sh`](https://github.com/junegunn/fzf-git.sh) (2022-08-14 [`9867a4a`](https://github.com/junegunn/fzf-git.sh/commit/9867a4ac3c3ca453178c1414442c69a5c8c7ee5f)).

**Comment by arnoldmashava** [comment]
@akinomyoga Thanks a span buddy, in our seemingly infinite Universe of `Linux` and `BSD`, everything is *Work in Progress* - hence the constantly evolving `git commits`. 

Yes, the `fzf-git` module will require a little bit of some tweaking and refinement, but that does not take away the credit that is due to an otherwise innovative and futuristic methodology of automating the interactions with the `Linux` shell.

The undying love for `GNU bash` and `ble.sh` - it has been such immense elevation (and maybe levitation) interacting and working with you.

!Gracias!

**Comment by akinomyoga** [comment]
I've updated `contrib/fzf-git` module so that it doesn't conflict with GitHub's `gh`.

**Comment by arnoldmashava** [comment]
@akinomyoga Thank you so much, I will allocate some time to run some `fuzzy finder` and `git` experiments with the module and communicate the outcomes thereafter. Thank you, for updating and maintaining the `ble.sh` code repositories.

Gracias.

**Comment by akinomyoga** [comment]
Thanks!

**Comment by arnoldmashava** [comment]
1. Acknowledgements

I can hereby confirm that after executing the latest `ble update`, the `ble-import -d integration/fzf-git` directive if specified in the `~/.blerc` configuration, is no longer conflicting with the initialization `gh` command for the `GitHub CLI`. 

However, this is not the case in full operation mode, where the full `gh` commands take the form: 

```bash
>_ gh <command> <subcommand> [flags]
```

After inputting `gh` and pressing `<Space>` in attempting to input any `gh <command> <subcommand> [flags]`, the initialization `gh` is deleted to result in an input in the form: 

```bash
>_ <command> <subcommand> [flags]
```

without the preceding `gh` and this still blights the `fzf-git` integration to remain partially dysfunctional.

Outside of my preferred `KDE Konsole`, the observation of this cited glitch is replicable on `Tilix`, `Kitty`, the `GNOME Console` and `GNOME Terminal`.

2. Conclusion

I am of the highest conviction that in documenting the resolution of Issue #338, in as much as it is inevitable and imperative to update the existing installation of the `ble.sh` to the latest `git commit e5cea281`, it is also significant and admissible to simultaneously update the existing local workstation `git clone` of the [blesh-contrib](https://github.com/akinomyoga/blesh-contrib) repository to the latest `git commit f1c89b1` - where if specified in the `~/.blerc` configuration, the `ble-import -d integration/fzf-git` directive will also have to take into account the code refinements in the [integration/fzf-git](https://github.com/akinomyoga/blesh-contrib/tree/f1c89b1129ebaee1f464f8c476269da7aa8e81f3#pencil-integrationfzf-git) module:

![Screenshot_20230710_083058](https://github.com/akinomyoga/ble.sh/assets/5759101/4ace94f2-867f-4105-bf2b-974379368510)

Como siempre: ¡muchas gracias y saludos cordiales!

Arnold Mashava.

**Comment by akinomyoga** [comment]
> After inputting `gh` and pressing `<Space>` in attempting to input any `gh <command> <subcommand> [flags]`, the initialization `gh` is deleted to result in an input in the form:
> 
> ```shell
> >_ <command> <subcommand> [flags]
> ```

This is because you specify `sabbrev` in your `_ble_contrib_fzf_git_config`, in which case the above behavior is intentional one. As explained in [README](https://github.com/akinomyoga/blesh-contrib#pencil-integrationfzf-git) of blesh-sabbrev, when you specify `sabbrev` in the variable `_ble_contrib_fzf_git_config`, it means that you want sabbrev expansions, `gh`, `gf`, `gb`, etc.

> 2. Conclusion
> 
> I am of the highest conviction that

I don't think that's the case. `ble-update` performs the updates of **both** the main repository and the `blesh-contrib` repository.

**Comment by arnoldmashava** [comment]
Cool, thanks a lot.
