### ISSUE TITLE
Return to line edito from menu-complete 

### ISSUE THREAD

**Issue by dylankb** [akinomyoga/ble.sh#34]
I have a questions about the menu-complete feature if that's ok.

Given existing terminal content of `cd` while in a directory containing other directories, if I enter `TAB` you will get a series of suggestions you can navigate with `TAB` and `S-TAB`. Before I hit `TAB` or `S-TAB` after hitting `TAB` I am still able to use the terminal line editor, however once I hit `TAB` or `S-TAB` I'm not able to exit and return. I have to hit `C-c` to exit completely. Is there another way to exit the menu and return to the existing content on the line editor?

**Comment by akinomyoga** [comment]
It's <kbd>C-g</kbd>. <kbd>C-g</kbd> is widely used for canceling the current operation in Emacs bindings.

**Comment by akinomyoga** [comment]
If you want to configure <kbd>C-c</kbd> to cancel the menu-complete, you can use the following setting:

```bash
# blerc

# Write completion settings in this function
function my/complete-load-hook {
  ble-bind -m menu_complete -f C-c menu_complete/cancel
}
blehook/eval-after-load complete my/complete-load-hook
```

**Comment by dylankb** [comment]
Thanks for the info - `C-g` is fine for now for me! That wiki looks like it will be really useful.

**Comment by akinomyoga** [comment]
Thank you!
