### ISSUE TITLE
Face 'menu_filter_*' not found

### ISSUE THREAD

**Issue by anuramat** [akinomyoga/ble.sh#352]
## Info
```
GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)
ble.sh, version 0.4.0-devel3+1a5c451c (noarch) [git 2.39.0, GNU Make 4.3, GNU Awk 5.1.1, API: 3.1 (GNU MPFR 4.1.0-p13, GNU MP 6.2.1)]
locale: LC_ALL=en_US.UTF-8 LC_CTYPE=UTF-8 LC_TERMINAL=iTerm2 LC_TERMINAL_VERSION=3.4.19
terminal: TERM=xterm-256color wcwidth=12.1-west/15.0-2+ri, xterm:95 (0;95;0)
```
# Problem
`menu_filter_input` and `menu_filter_fixed` ble-faces don't work when sourced from `.bash_rc` or `init.sh`, but work perfectly fine when called set interactively:
```
$ ble-face: face 'menu_filter_input' not found
ble-face: face 'menu_filter_fixed' not found
```
What works:
- Typing the command interactively
- Sourcing a script interactively
What doesn't:
- Sourcing from bashrc, bash_profile, init.sh, bleshrc

Other faces mentioned in README work fine.

## To reproduce
```bash
# .bash_profile
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export LC_ALL="en_US.UTF-8"
source "$XDG_DATA_HOME/blesh/ble.sh" --noattach
export HOMEBREW_PREFIX="/opt/homebrew"
eval "$("$HOMEBREW_PREFIX/bin/brew" shellenv)" # brew env variables
[[ ${BLE_VERSION-} ]] && ble-attach

# ~/.config/blesh/init.sh
ble-face -s menu_filter_input fg=blue,bold
ble-face -s menu_filter_fixed bold
```

**Comment by akinomyoga** [comment]
`menu_filter_*` is not supposed to be set at the top level of `init.sh`. You can see the top of [Manual §7 Completion](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#7-completion) for the description:

> # 7. Completion
>
> The settings for completion need to be performed through the hook complete_load.
>
> ```bash
> # blerc (Example)
>
> function my/complete-load-hook {
>   bleopt complete_auto_delay=300
> }
> 
> blehook/eval-after-load complete my/complete-load-hook
> ```

**Comment by anuramat** [comment]
Oops, sorry for not RTFM and thank you for your work.

On a related note, I suppose the `blerc.template` should be fixed then, since it has basically the same problem [here](https://github.com/akinomyoga/ble.sh/blob/dc0cdb30718dba23057556cf88ce832ecfde2491/blerc.template#L851)? I would also propose to uncomment everything that's possible, for syntax highlighting and to make it easier to move from default settings.
I can file a PR, if you want.

**Comment by akinomyoga** [comment]
Ah, I see. You are right. Those faces in `blerc.template` are added in response to some requests from other users, but the added way is wrong.

> I would also propose to uncomment everything that's possible, for syntax highlighting and to make it easier to move from default settings.

These settings add extra costs to the startup time (for parsing the arguments, translating the graphics specs to the internal representation, etc.). If the settings of all the faces are turned on, the startup time becomes significantly longer. As far as a face is the same as the default, I recommend not to explicitly specify the face.

**Comment by akinomyoga** [comment]
I decided to move the definitions of `menu_filter_*` to the main file `ble.sh` (af022266), so now you can put the settings of `menu_filter_*` at the top level of `blerc`.

**Comment by anuramat** [comment]
Thanks, I think it's more convenient/idiot-proof now. I guess the issue can be closed now?

**Comment by akinomyoga** [comment]
Thanks! Then, I'll close it.
