### ISSUE TITLE
Add key binding for: Left Alt + Backspace (M-DEL) to 

### ISSUE THREAD

**Issue by joaovarelas** [akinomyoga/ble.sh#355]
Bash has Ctrl+W to delete word but won't work with, for example `word1/word2/word3` it will delete whole line.

Using `LAlt + Backspace` it deletes `word3` and remains `word1/word2`. How to keybind in ble.sh, any widget?

Thanks in advance.

References:

- https://unix.stackexchange.com/questions/27927/is-it-possible-to-configure-ctrl-w-delete-word#119513
- https://superuser.com/questions/212446/binding-backward-kill-word-to-ctrlw

**Comment by akinomyoga** [comment]
The simplest setup is, as described in the references you provided [with `\C-w` replaced with `\e\C-?` (<kbd>M-DEL</kbd>)],

```bash
# The default of plain Bash
bind '"\e\C-?": backward-kill-word'

# or Words delimited by slashes
bind '"\e\C-?": unix-filename-rubout'
```

The above just works in ble.sh. These are the corresponding commands in ble.sh's native way of keybinding:

```bash
ble-bind -f 'M-C-?' kill-backward-cword
ble-bind -f 'M-DEL' kill-backward-cword

ble-bind -f 'M-C-?' kill-backward-fword
ble-bind -f 'M-DEL' kill-backward-fword
```

**Comment by joaovarelas** [comment]
@akinomyoga Those keybinds are working perfectly.

Thanks!

**Comment by akinomyoga** [comment]
Thanks!
