### ISSUE TITLE
blesh and nano

### ISSUE THREAD

**Issue by squid-slime** [akinomyoga/ble.sh#357]
the issue i am having with blesh is that when editing in nano the nano keybinds are broken, ctrl+s to save now prints ;5;115~ and ctrl+x also prints ;5;120~ and this goes for all bindings, like when using gomuks i also have issues with upper case lettering now printing strings

bashrc
```
# ~/.bashrc
#
export EDITOR=/usr/bin/nvim
export VISUAL='nano'

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='\[\033[7;32m\]\u@\h \[\033[1;34m\]\d \t \[\033[0;36m\]\w\[\033[0m\]\n\$ \[\033[0m\]' 

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi

if [ "$(tty)" = "/dev/tty1" ]; then
        exec dbus-run-session sway
fi

# COLOURS! YAAAY!
export TERM=xterm-256color

[[ $- == *i* ]] && source /usr/share/blesh/ble.sh #--noattach

#Aliases
alias htop='btop'${pur}
alias webapp='nativefier'${pur}
alias ls='ls --color=auto'
alias grc='grc --colour=auto'
alias tui="python /home/squid/Documents/pyrunthis"
```

**Comment by akinomyoga** [comment]
Which terminal do you use? Some of the terminals behave differently from XTerm for the terminal feature called `modifyOtherKeys`, which was introduced by XTerm. Also, what is the result of the following command?

```bash
$ ble/widget/display-shell-version
```

**Comment by akinomyoga** [comment]
Thanks. That means you are using an old version ble-0.3. Please use ble-0.4.

**Comment by squid-slime** [comment]
thank you, this has fixed the issue

**Comment by akinomyoga** [comment]
Thanks!
