### ISSUE TITLE
[着色] Vimのコマンドモードに一度入って以降着色機能等が働かない

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#36]
**ble version**: 0.4.0-devel2+3031007
**Bash version**: 5.0.3(1)-release

```console
$ echo foo #←任意のコマンド
:@
```
Vimモードにおいて，上掲のようなコマンドラインの状態（`vi_cmap`に対してカーソルがある）の後，
<kbd>Esc</kbd>や<kbd>w</kbd><kbd>Enter</kbd>等でコマンドモードを抜けると，
それまで正常だった着色機能が働かなくなってしまいます。
（着色機能以外でも異常になっている部分があるかも知れませんが，調べ切っていません，すいません）

**Comment by akinomyoga** [comment]
ご報告ありがとうございます! 他にもカーソルの位置計算も間違っていますね。犯人は 6acb9a3 ですね…。調べます

**Comment by akinomyoga** [comment]
直しました 06ae2b1 ご確認お願いできますか?

**Comment by cmplstofB** [comment]
確認いたしました。ありがとうございます！

---

すいません，追加で質問させてください。
[`varname_number`](https://github.com/akinomyoga/ble.sh/wiki/%E8%AA%AC%E6%98%8E%E6%9B%B8-%C2%A72-%E6%8F%8F%E7%94%BB#2252-%E6%8F%8F%E7%94%BB%E8%A8%AD%E5%AE%9A-varname_number-v04)という描画設定は，算術式の数値に対して
```console
$ echo $((3 + 03 + 0x3))
          ^   ^^   ^
```
ここのみを着色するという理解で合っていますか？
困っている訳ではないのですが，16進数が私めが思ったように着色されないので，ちょっと疑問に思いました。

**Comment by akinomyoga** [comment]
ありがとうございます! 本当ですね。今確認したら16進数の対応を忘れていました。修正しました 7f0229f

**Comment by akinomyoga** [comment]
どうも細かいバグが多くてすみません。他にも変かも、という所があればどうぞお気兼ねなく。

**Comment by cmplstofB** [comment]
こちらこそ重箱の隅をつつく高慢ちきな指摘ばかりで申し訳ないです。

**Comment by akinomyoga** [comment]
いえ、全然そんなことありません。とても助かっています! 是非もっと細かいことでも仰ってください
