### ISSUE TITLE
Add a file that I can use to give history of available commands

### ISSUE THREAD

**Issue by frankhli843** [akinomyoga/ble.sh#365]
If we could provide a comma separated list of commands as history then it would be really useful to bring the memory to another pc

**Comment by akinomyoga** [comment]
Thanks, but is this a question asking a way to add such a file or is this a feature request?

The command history is already saved in `~/.bash_history`. This is the feature supported by the plain Bash and works the same also with `ble.sh`. Is the file you are talking about different from `~/.bash_history`? If so, how is it different?

**Comment by akinomyoga** [comment]
ping @frankhli843

In short, have you considered using `~/.bash_history`? What would be the problem?

**Comment by akinomyoga** [comment]
ping? @frankhli843

**Comment by frankhli843** [comment]
Hey looking into it bash history will serve thanks.

**Comment by akinomyoga** [comment]
Great! Thanks for your reply. I'll close the Issue. If you have any problem, please reopen it.
