### ISSUE TITLE
Mark when you exit ble.sh

### ISSUE THREAD

**Issue by gvlassis** [akinomyoga/ble.sh#366]
Hello!

When you exit ble.sh (for example by simply typing exit), you get [ble: exit] ouput to the terminal. Is there any way to customize this behaviour/turn it off?

**Comment by akinomyoga** [comment]
There was no way to customize that. There are many similar marks including `[ble: reload]`, `[ble: detached]`, `[ble: expand]`, `[ble: fc]`, `[ble: exit %d]`, `[ble: auto-logout]`, etc. I wouldn't like to add configuration for every such case, but I added a configuration to change the style of these marks collectively:

- [`bleopt edit_marker`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-bleopt-edit_marker)
- [`bleopt edit_marker_error`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-bleopt-edit_marker_error)

Also, I added a new configuration to specifically change `[ble: exit]`.

- [`bleopt exec_exit_mark`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-bleopt-exec_exit_mark)

To disable the exit mark, you can set an empty string. For details, please see the linked page.
