### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by gvlassis** [akinomyoga/ble.sh#367]
Hello!

ble.sh has made my interaction with bash FAR more enjoyable. As a token of my appreciation, I would like to make a small donation. How can I do this?

**Comment by akinomyoga** [comment]
Thank you very much for showing your appreciation! I've never tried to receive a donation, but this time I registered GitHub Sponsors and added a `FUNDING.yml` (3f13393635eb77d0fa260983930de3ddff378915). I'm not sure if I've correctly set it up, but now it seems the "Sponsor" button is available in the right column on the top page of `akinomyoga/ble.sh`. Probably, One-time can be chosen for a small donation.

**Comment by akinomyoga** [comment]
Thank you!
