### ISSUE TITLE
/dev/fd/63: line 1: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by dgudim** [akinomyoga/ble.sh#368]
**ble version**: 0.4.0-devel4+742cf2cc
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu)

![test](https://github.com/akinomyoga/ble.sh/assets/34401005/0ff7bc3b-0bf0-4714-88a9-980566dc4481)

In some cases typing invalid options causes the above error. (it sould be `chezmoi_modify_manager --add` instead of `chezmoi_modify_manager add`)

**Comment by akinomyoga** [comment]
This is a bug in the completion setting. The completion of [`chezmoi_modify_manager`](https://github.com/VorpalBlade/chezmoi_modify_manager) seems to be set up by [`chezmoi_modify_manager --bpaf-complete-style-bash`](https://github.com/VorpalBlade/chezmoi_modify_manager#tab-completion). The `chezmoi_modify_manager` [relies](https://github.com/VorpalBlade/chezmoi_modify_manager/blob/eaa44c628970d572a8fd7d32f2eca6fb4a5c6364/Cargo.lock#L287-L294) on a Rust library called [`bpaf`](https://github.com/pacak/bpaf) to provide this option: The `bpaf` library contains the [broken line](https://github.com/pacak/bpaf/blob/8c0e359df81166662fa5575887104b277d78792f/src/complete_shell.rs#L166). The shell language does not accept spaces around `+=`.

**Comment by dgudim** [comment]
Thanks!

**Comment by akinomyoga** [comment]
The fixed version of `bpaf` seems to have been applied in `chezmoi_modify_manager` v2.2.0. Could you update `chezmoi_modify_manager` and test it?

**Comment by dgudim** [comment]
It's not broken anymore, I think we can close this

**Comment by akinomyoga** [comment]
Thanks for the confirmation! Let's close it.
