### ISSUE TITLE
Unbind C-r and bind it to something else

### ISSUE THREAD

**Issue by dgudim** [akinomyoga/ble.sh#369]
**ble version**: 
```
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu) [EndeavourOS]
ble.sh, version 0.4.0-devel4+742cf2cc (noarch) [git 2.42.0, GNU Make 4.4.1, GNU Awk 5.2.2, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)]
bash-completion, version 2.11 (hash:2d02f73e803daa87a06e94e33b2a7b3e672a2c0c, 76338 bytes) (noarch)
locale: LANG=en_US.UTF-8 LC_ADDRESS=en_US.UTF-8 LC_IDENTIFICATION=en_US.UTF-8 LC_MEASUREMENT=ru_RU.UTF-8 LC_MONETARY=lt_LT.UTF-8 LC_NAME=en_US.UTF-8 LC_NUMERIC=en_US.UTF-8 LC_PAPER=en_US.UTF-8 LC_TELEPHONE=en_US.UTF-8 LC_TIME=ru_RU.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.1-2+ri, konsole:220380 (1;115;0)
```

I am using atuin as my command history manager, but when I import fzf integration it gets overridden by fzf history widget. I tried rebinding it back, but nothing works.

This doesn't work.
```
ble-bind -m emacs   -x C-r -
ble-bind -m vi_imap -x C-r -
```

This also doesn't work
```
bind -x '"\C-r": __atuin_history'
```

**Comment by akinomyoga** [comment]
> This also doesn't work
> 
> ```
> bind -x '"\C-r": __atuin_history'
> ```

I think this should work as far as the ordering of the settings is correctly set up. You need to put the above setting after the `fzf` configuration. If the `fzf` configuration comes after it, the `fzf` configuration will overwrite the setting you specified. Also, what is the loading order of the `atuin` configuration and the `fzf` configuration, and where did you put the above settings in the 

You wrote "does not work" but what does that mean? Does it mean the bind command produces an error? Does it mean `fzf` is still called on pressing <kbd>C-r</kbd>? Or does it mean it produces an error message on <kbd>C-r</kbd>? Or does it mean nothing seems to happen on pressing <kbd>C-r</kbd>?

**Comment by dgudim** [comment]
> Does it mean fzf is still called on pressing C-r
Yes, fzf is still called

Here is a stripped-down version of configs where this issue happens

```
#
# ~/.bashrc
#

[[ "$(whoami)" != "root" ]] && source /usr/share/blesh/ble.sh --noattach --rcfile $HOME/.config/blerc

eval "$(atuin init bash --disable-up-arrow --disable-ctrl-r)"

[[ ${BLE_VERSION-} ]] && ble-attach

bind -x '"\C-r": __atuin_history'
```

```

#
# ~/.config/blerc
#

ble-import -d integration/fzf-completion
ble-import -d integration/fzf-key-bindings
ble-bind -m emacs   -x C-r -
ble-bind -m vi_imap -x C-r -
```

**Comment by akinomyoga** [comment]
Thanks for the information! I'll later take a closer look at them.

**Comment by akinomyoga** [comment]
@dgudim Sorry for the delay. I've checked your configuration.

> ```bash
> ble-import -d integration/fzf-completion
> ble-import -d integration/fzf-key-bindings
> ```

Those `-d` flags specify that the loading of those configurations should be delayed, i.e., the loading of the settings will be deferred until the shell becomes idle. If you would like to add keybindings after `integration/fzf-key-bindings` is loaded, you need to omit `-d` from the above lines. Or another way is to make the Atuin initialization another module and load it with `-d` (such as `ble-import -d my/atuin`).

> ```bash
> ble-bind -m emacs   -x C-r -
> ble-bind -m vi_imap -x C-r -
> ```

Those lines are unnecessary.

**Comment by dgudim** [comment]
Thank you very much, I changed it and several other things to a module and now everything loads correctly end even my shell startup feels faster. :)
