### ISSUE TITLE
[履歴 & noclobber] 履歴を共有しており転送上書きを防止していると終了時に警告が生じる

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#37]
**ble version**: 0.4.0-devel2+06ae2b1
**Bash version**: 5.0.3(1)-release

（細かいことでもいいと仰ってくださったので，調子に乗って前から気になっていたことを論います……）

https://github.com/akinomyoga/ble.sh/blob/7f0229f4f0bd69a402d215113c1045ed30ab08c7/src/history.sh#L830

この箇所で，`>`という転送演算子が用いられています。
履歴を共有しており（`bleopt history_share=1`），かつ，`>`演算子等での転送による上書きを防止している（`set -o noclobber`）場合，Bashの終了時に「`bash: /run/user/1000/blesh/NNNN.history.app: 存在するファイルを上書きできません`」などと警告されます（普通にBashを起動している状態だと，終了と同時に端末が閉じる為にほぼ一瞬しか見えませんが，Bashを入れ子で起動していると子シェルの方の終了時に警告が端末上に残っているのが確認できると思います）。
警告が生じる以外に何の問題もないのですが，一応，他の箇所と同様`>|`演算子を用いたほうが良いのではないかと思います。

**Comment by akinomyoga** [comment]
本当にありがとうございます! これもうっかり忘れですね。修正しました! 604bb8b

**Comment by cmplstofB** [comment]
確認いたしました。ありがとうございます。
