### ISSUE TITLE
Multiline mode exec remapping

### ISSUE THREAD

**Issue by Adventune** [akinomyoga/ble.sh#370]
Is it possible to remap the multiline execution key to another combination (eg. C-Enter)? I am using tmux-vim-navigator with C-j binded to navigate in the window and I am unable to execute multiline commands. I also couldn't find an option for the mapping.

**Comment by akinomyoga** [comment]
> Is it possible to remap the multiline execution key to another combination (eg. C-Enter)?

Unless you use the `vi` editing mode, <kbd>C-Enter</kbd> is by default the same as <kbd>C-j</kbd> and thus can be used to run the command in the multiline mode without any additional configuration. If you are using the `vi` editing mode, you can change the binding by `ble-bind -m vi_imap -f C-RET accept-line`.

However, in order to use <kbd>C-Enter</kbd>, your terminal needs to support inputting <kbd>C-Enter</kbd>. What is your terminal? If your terminal sends the same code for <kbd>C-Enter</kbd> as <kbd>Enter</kbd>, it is impossible for the line editor to distinguish <kbd>C-Enter</kbd> from <kbd>Enter</kbd>. Some terminals support configuring the code sent to the application when a specific key combination is pressed. You may need to configure the code for <kbd>C-Enter</kbd> (<kbd>C-RET</kbd>) as described in a table in [§3.6.4](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#user-content-sec-modifyOtherKeys-manual).

**Comment by Adventune** [comment]
I am using tmux/bash. Does bash support CTRL+Enter I couldn't find anything online?

**Comment by akinomyoga** [comment]
Thanks, What is the terminal outside tmux? The terminal that sends the key input is the outside terminal, but not tmux. Tmux just transfers the key input from the outside terminal to Bash.

The plain Bash with GNU Readline doesn't handle CTRL + Enter by default, but ble.sh handles CTRL + Enter by default.

**Comment by Adventune** [comment]
Outside tmux I have bash. Ble.sh is installed as per instructions in the readme. Ctrl+enter does not result in accepting the command

**Comment by akinomyoga** [comment]
> Outside tmux I have bash.

Bash is not a terminal. What is the outside terminal? There should be a terminal (`#1`) that starts Bash (`#2`), and tmux (`#3`) is started inside `#2`, and tmux starts another Bash (`#4`). The resulting connection of streams becomes as follows:

```
[#1 outside terminal] --+--[#2 outside bash]
                        |
                        +--[#3 tmux]--[#4 bash]
```

I'm asking about the outside terminal sitting on `#1`. What is the terminal that starts the outer Bash (`#2`)?

**Comment by akinomyoga** [comment]
Could you give me the result of the following command?

```bash
$ ble/widget/display-shell-version
```

**Comment by akinomyoga** [comment]
@Adventune Did you solve your problem?

Could you find what is the outer terminal in your setup? Or if you don't know what is your outer terminal, what is your operating system and how do you open the terminal window?

**Comment by Adventune** [comment]
Sorry, forgot to get back to this. Here is the output of the command:
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) [Ubuntu 22.04.3 LTS]
ble.sh, version 0.4.0-devel4+3f13393 (noarch) [git 2.34.1, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:b42f5d6a7ad6d4921ec73838ba54a96d6bd30936, 77071 bytes) (noarch)
locale: LANG=en_US.UTF-8 LC_ADDRESS=fi_FI.UTF-8 LC_IDENTIFICATION=fi_FI.UTF-8 LC_MEASUREMENT=fi_FI.UTF-8 LC_MONETARY=fi_FI.UTF-8 LC_NAME=fi_FI.UTF-8 LC_NUMERIC=fi_FI.UTF-8 LC_PAPER=fi_FI.UTF-8 LC_TELEPHONE=fi_FI.UTF-8 LC_TIME=fi_FI.UTF-8
terminal: TERM=xterm-256color wcwidth=14.0-west/15.1-2+ri, vte:6800 (65;6800;1)
```

**Comment by akinomyoga** [comment]
Thanks, the above result implies that your outside terminal is one of the VTE-based terminals. However, it is still difficult to identify which specific terminal of the VTE-based one is yours. Can you tell which is your outside terminal? Or can you describe how you start the terminal?

**Comment by Adventune** [comment]
I run the default terminal application on Ubuntu. So I guess gnome-terminal?

**Comment by akinomyoga** [comment]
Thank you for your information.

I first checked the settings of the GNOME terminal, but there don't seem to be configuration options for the sequences sent by each keypress.

I also checked the source code of GNOME/vte, which does not seem to support Ctrl-Enter; They ignore all the modifier keys for Enter. The key input is processed in [`Terminal::widget_key_press` (`src/vte.cc`)](https://github.com/GNOME/vte/blob/a9cbd3948b3ecc75a8d725d5ed788b528b1f6f35/src/vte.cc#L4960C1-L4960C27), which [calls](https://github.com/GNOME/vte/blob/a9cbd3948b3ecc75a8d725d5ed788b528b1f6f35/src/vte.cc#L5341) another function [`_vte_keymap_map` (`src/keymap.cc`)](https://github.com/GNOME/vte/blob/a9cbd3948b3ecc75a8d725d5ed788b528b1f6f35/src/keymap.cc#L712). How each key is processed is determined based on [the entries store in the array `_vte_keymap`](https://github.com/GNOME/vte/blob/a9cbd3948b3ecc75a8d725d5ed788b528b1f6f35/src/keymap.cc#L739). The entries for <kbd>Enter</kbd> is given by [`_vte_keymap_GDK_Return`](https://github.com/GNOME/vte/blob/a9cbd3948b3ecc75a8d725d5ed788b528b1f6f35/src/keymap.cc#L111-L115). However, both `_vte_keymap` and `_vte_keymap_GDK_Return` are specified to be in the `static` scope, so there is no way to modify the key processing from the application side (i.e., the terminal side such as the GNOME terminal).

There seems to be a Feature Request [\#2658](https://gitlab.gnome.org/GNOME/vte/-/issues/2658) at the upstream VTE, which suggests a distinct key sequence for <kbd>Shift-Enter</kbd>.

----

To conclude, the terminal that you use does not support <kbd>Ctrl-Enter</kbd> (distinctly from <kbd>Enter</kbd>) and does not provide a way to customize it. You need to use another terminal that supports <kbd>Ctrl-Enter</kbd> or the feature called `modifyOtherKeys` or a terminal that provides the configuration for custom key sequences.

**Comment by Adventune** [comment]
Thank you very much! Would you be able to recommend any terminals that would support `Ctrl-Enter`.

**Comment by akinomyoga** [comment]
**Konsole** would be one of the possible options. You may configure Konsole to send a proper sequence with <kbd>Ctrl-Enter</kbd>. The configuration is described in https://github.com/akinomyoga/ble.sh/issues/187#issuecomment-1107551319. You can specify `\E[13;5u` for `Return+Ctrl-Shift`. This is an example.

![image](https://github.com/akinomyoga/ble.sh/assets/8982192/6cf18784-fc06-4a6d-b9ed-6d5d0dfef651)


**xterm** supports the `modifyOtherKeys` mode, where you don't need additional configurations. The recent terminals with the support for `modifyOtherKeys` include **foot** and **zutty**.

**Comment by Adventune** [comment]
Thank you! I'll look into those!
