### ISSUE TITLE
[Bash 5.2] bash: '_alias_completion::gh?' 'gh?': command not found

### ISSUE THREAD

**Issue by maheis** [akinomyoga/ble.sh#371]
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu) [Debian GNU/Linux trixie/sid]
ble.sh, version 0.4.0-nightly+595f905 (noarch) [git 2.42.0, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:9abb523dbcb688e7fae4b87f5fc9d155b658d9ba, 76898 bytes) (noarch)
bash-preexec, (hash:5f1208c33e624859eea70e3843bd9b8c9a06819e, 13046 bytes) (noarch)
bash-it, version +ad2b5580 (noarch), alias(), completion(aliases bash-it system), plugin()
locale: LANG=en_GB.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.1-2+ri, vte:7401 (65;7401;1)

I have defined this alias in the .bash_aliases
`alias gh?='gh copilot suggest'`
For example, if I type `gh? issue`, I get this message every time I enter a key after `gh? `:
`bash: '_alias_completion::gh?' 'gh?': command not found`

**Comment by akinomyoga** [comment]
Thanks for the report, but `_alias_completion::gh?` is not something ble.sh sets up.

> For example, if I type `gh? issue`, I get this message every time I enter a key after `gh? `:
> `bash: '_alias_completion::gh?' 'gh?': command not found`

- **Q1**: Doesn't this happen when you attempt a TAB completion in a plain Bash session (without loading ble.sh)?

I'm not sure what `_alias_completion::gh?` is but after some search, I found the following answer in Stack Exchange:

- [How can I get bash to perform tab-completion for my aliases? - Super User](https://superuser.com/a/437508)

- **Q2**: Do you have the above configuration in your configuration?
- **Q3**: What is the result of the following command?

```bash
$ type '_alias_completion::gh?'
```

**Comment by maheis** [comment]
Thanks for caring, you're doing a great job here!

**A1**: no the error is gone if I do not load ble.sh.

**A2**:
No, not directly. But I have now seen that these calls are in the .bashrc. 
![image](https://github.com/akinomyoga/ble.sh/assets/32419610/d6e33919-7012-4aab-b006-7464424cbd5a)
Behind this is probably this script: https://github.com/scop/bash-completion
But the error remains when I comment this part.

**A3**: This is the result of the query. If I query x? without defining it, I get the result below... 
![image](https://github.com/akinomyoga/ble.sh/assets/32419610/6509e7fc-68d7-43a7-aeec-7a2e81dff626)
... if I define `alias x?='echo this is a test'` as alias, then the same error occurs for x? and the result of type is this:
![image](https://github.com/akinomyoga/ble.sh/assets/32419610/508963f1-9141-4480-814e-db1c6c1afa66)

**Comment by akinomyoga** [comment]
Thank you for the information. OK, I could reproduce the problem. I'll fix it later.

**Comment by maheis** [comment]
That sounds good. Thank you and no stress. Just wanted to report it, I had noticed it. I currently have the workaround with no ?

**Comment by akinomyoga** [comment]
I fixed it in commit a7eb5d04. The problem was related to the output-format change of `complete -p` in Bash 5.2. Could you update ble.sh by running `ble-update` in a ble.sh session and see if the problem is fixed?

**Comment by maheis** [comment]
It now works wonderfully. Thanks for the quick solution!

**Comment by akinomyoga** [comment]
Thank you for the confirmation!
