### ISSUE TITLE
--help on builtins causes error code 2.

### ISSUE THREAD

**Issue by Rid1-fz-06** [akinomyoga/ble.sh#373]
**ble version**: 0.4.0-devel3+1a5c451c
**Bash version**: 5.2.21(1)-release (x86_64-redhat-linux-gnu)

If I pass the `--help` flag to any of the shell builtins (`cd` or `exit` for example), it causes an error with error code 2
![example with the exit command](https://github.com/akinomyoga/ble.sh/assets/92540820/16122d9a-27f3-426e-afea-e6b488fc5cb0)

**Comment by akinomyoga** [comment]
That is the design of Bash and unrelated to ble.sh. Even without ble.sh, Bash builtins exit status 2 with `--help`. You can check that by running following commands in a plain Bash:

```bash
$ bash --norc # start a plain Bash (without loading ble.sh)
$ exit --help
...
$ echo $?
2

```
