### ISSUE TITLE
Inconsistence in some TAB Completions

### ISSUE THREAD

**Issue by Dominiquini** [akinomyoga/ble.sh#378]
**ble version**: 0.4.0-devel4+5f9a44e 
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu) 

```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) [Ubuntu 22.04.3 LTS]
ble.sh, version 0.4.0-devel4+5f9a44e (noarch) [git 2.34.1, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:b42f5d6a7ad6d4921ec73838ba54a96d6bd30936, 77071 bytes) (noarch)
fzf key-bindings, (hash:c4dce3ba5bfafecbc6c47695f89ef02c305b984e, 5524 bytes) (noarch) (integration: on)
fzf completion, (hash:db84e06a1ee5fb43bc6ad1aaeec6657cad79c917, 14523 bytes) (noarch) (integration: on)
romkatv/gitstatus, (hash:bfe16dc24d4aebb0ed2cc9bd0eb86fa41c9c018f, 19410 bytes) (noarch)
locale: LANG=en_US.UTF8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.1-2+ri, wt:0 (0;10;1)
```

When I use the tab completion on some command (with menu or inline), sometime bash put a space in the end of the command, but sometime it doesn't:
If I start typing "apt-g<TAB>", it autocompletes to "apt-get<SPACE>"
But if I type "sudo apt-g<TAB>", it autocompletes to "apt-get"
If I only type "apt-<TAB>", to force the menu to appear, it's the same behavior! If the command is the second position, the completer don't out a space in the end!

Thanks

**Comment by akinomyoga** [comment]
That seems to be because the completion setting for `sudo` (and other commands that take another command name) internally calls `compopt -o filenames`. When `compopt -o filenames` is specified, ble.sh inserts a space only when it matches a filename. I've checked the behavior of the default Bash completion, where it seems to insert a space when it doesn't match any files or directories. I'll check if there is any background of the current design.

**Comment by Dominiquini** [comment]
> That seems to be because the completion setting for `sudo` (and other commands that take another command name) internally calls `compopt -o filenames`. When `compopt -o filenames` is specified, ble.sh inserts a space only when it matches a filename. I've checked the behavior of the default Bash completion, where it seems to insert a space when it doesn't match any files or directories. I'll check if there is any background of the current design.

Default Bash completion inserts a space, with or without sudo. I noticed this behavior because I start typing some command wrong with ble.sh that I was accustomed in Bash!

Thanks.

**Comment by akinomyoga** [comment]
In commit aef8927f, I changed ble.sh to insert a space after non-filenames even when `compopt -o filenames` is specified by the programmable completion setting. Could you update ble.sh by running `ble-update` in a ble.sh session and check the behavior?

**Comment by Dominiquini** [comment]
> In commit [aef8927](https://github.com/akinomyoga/ble.sh/commit/aef8927f04807c207c1441b4f1fe9d7f73930e62), I changed ble.sh to insert a space after non-filenames even when `compopt -o filenames` is specified by the programmable completion setting. Could you update ble.sh by running `ble-update` in a ble.sh session and check the behavior?

It's working now!

Thanks.
