### ISSUE TITLE
history -c doesn't clean ~/.bash_history

### ISSUE THREAD

**Issue by blackteahamburger** [akinomyoga/ble.sh#381]
**ble version**: 0.4.0-devel4+a3b94bb
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu)

`history -c` doesn't clean ~`/.bash_history`, which results in it only clearing the history in the current session, but no history changes after opening a new session. For example:

```
$ history
    1  2023-12-24 09:46:48 rm ~/.bash_history 
    2  2023-12-24 09:47:15 mkdir test
    3  2023-12-24 09:47:19 cd test
    4  2023-12-24 09:47:35 touch test2
    5  2023-12-24 09:47:39 rm test2
$ history -c
$ history
$ cat ~/.bash_history
#1703382408
rm ~/.bash_history 
#1703382435
mkdir test
#1703382439
cd test
#1703382455
touch test2
#1703382459
rm test2

# In a new session
$ history
    1  2023-12-24 09:46:48 rm ~/.bash_history 
    2  2023-12-24 09:47:15 mkdir test
    3  2023-12-24 09:47:19 cd test
    4  2023-12-24 09:47:35 touch test2
    5  2023-12-24 09:47:39 rm test2
$ cat ~/.bash_history
#1703382408
rm ~/.bash_history 
#1703382435
mkdir test
#1703382439
cd test
#1703382455
touch test2
#1703382459
rm test2
```

**Comment by akinomyoga** [comment]
Yes, you are right. That is the behavior of Bash. Or do you see any difference in the behavior with and without ble.sh?

In the first place, the in-memory command history and the history file is not synchronized for every command. It is only synchronized when the Bash session ends or you run `history -w` or `history -a` (depending on your preference). The command `history -c` only clears the in-memory command history. If you would like the in-memory history to be reflected in the history file, you need to run `history -w` in a row.

If you expect the in-memory history to be reflected in the history file on the session end (including the removal of the files), please make sure the shell option `histappend` is turned off (i.e., `shopt -u histappend).

**Comment by blackteahamburger** [comment]
But after running `shopt -u histappend`, `history -c` still doesn't clean `~/.bash_history`.

**Comment by akinomyoga** [comment]
`shopt -u histappend` is just a setting to control the behavior on the session end. Changing the setting doesn't immediately clean `~/.bash_history`. You need to exit the session for `shopt -u histappend` to take an effect.

If you would like to reflect the content of the in-memory command history immediately, you need to run `history -w`.

**Comment by akinomyoga** [comment]
P.S. "the session end" means that you exit the current Bash session by running `exit`, by pressing <kbd>C-d</kbd> on an empty command line, or by closing the terminal window.

**Comment by blackteahamburger** [comment]
In fact I exited the session and `~/.bash_history` still wasn't cleaned up.

**Comment by akinomyoga** [comment]
The behavior your reported does not reproduce in my environment. I tried bash-5.1 and 5.2. I also tried it with and without oh-my-bash and bash-completion.

- **Q1**: Does the reported behavior reproduce with a plain Bash plus ble.sh (without any other configurations)?

**Comment by akinomyoga** [comment]
- **Q2**: Could you give me the result of the following command?

```bash
$ ble/widget/display-shell-version
```

**Comment by blackteahamburger** [comment]
After I manually deleted `~/.bash_history`, it strangely became clearable with `history -c`.
I don't know why but it works fine now.

**Comment by akinomyoga** [comment]
Thanks for the information. Hmm, one possibility is that it was caused by the permission of the file. When I change the permission of the history file to `chmod 400 ~/.bash_history`, I can reproduce the behavior of not clearing the file content, though it doesn't allow appending new entries in `~/.bash_history` either.
