### ISSUE TITLE
Error message after updating Oh-My-Bash - Need to hit enter to escape to prompt

### ISSUE THREAD

**Issue by jkemp814** [akinomyoga/ble.sh#383]
**ble version**: 0.4.0-devel4+a7eb5d0
**Bash version**: bash: 5.2.21(1)-release

01:45:08 james@HP-Z840 ~ → "ble/widget/display-shell-version"
GNU bash, version 5.2.21(1)-release (x86_64-redhat-linux-gnu) [Fedora Linux 39.20231223.0 (Silverblue)]
ble.sh, version 0.4.0-devel4+a7eb5d0 (noarch) [git 2.42.0, GNU Make 4.4.1, GNU Awk 5.2.2, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.0-p12, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:1a7f5634b4c9816716b69a7824e0b51cfde2bca3, 76332 bytes) (noarch)
oh-my-bash (font), version 1.0.0+c61e349d (noarch), aliases(general), completions(), plugins(bashmarks git zoxide)
locale: LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.1-2+ri, vte:7402 (65;7402;1)

When ever I get the prompt to update Oh-My-Bash I get this message:

[Oh My Bash] Would you like to check for updates? [Y/n]: y
Updating Oh My Bash
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 24 (delta 18), reused 16 (delta 10), pack-reused 0
Unpacking objects: 100% (24/24), 6.00 KiB | 384.00 KiB/s, done.
From https://github.com/ohmybash/oh-my-bash
 * branch            master     -> FETCH_HEAD
   e2917d6..c61e349  master     -> origin/master
Updating e2917d6..c61e349
Fast-forward
 README.md                     |  6 ++++++
 aliases/chmod.aliases.sh      |  6 +++---
 lib/history.sh                |  2 +-
 oh-my-bash.sh                 | 12 ++++++++++++
 plugins/nvm/nvm.plugin.sh     | 16 ++++++++--------
 templates/bashrc.osh-template |  3 +++
 6 files changed, 33 insertions(+), 12 deletions(-)
         __                          __               __  
  ____  / /_     ____ ___  __  __   / /_  ____ ______/ /_ 
 / __ \/ __ \   / __ `__ \/ / / /  / __ \/ __ `/ ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /  / /_/ / /_/ (__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /  /_.___/\__,_/____/_/ /_/ 
                        /____/                            
Hooray! Oh My Bash has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on GitHub: https://github.com/ohmybash/oh-my-bash
01:36:18 james@HP-Z840 ~ → bash: ble/_ble_util_openat_fdlistay#push: No such file or directory
bash: ble/_ble_highlight_layer_listay#insert-at: No such file or directory
bash: ble/_ble_util_openat_fdlistay#push: No such file or directory

**Comment by akinomyoga** [comment]
I believe this is a duplicate of #376, which you created two weeks before. I didn't get your reply there. Did you check #376? If not, could you check my replies there? If you already checked them, and you still believe this Issue is different from #376, you can clarify the difference between this and #376. Thank you.

**Comment by jkemp814** [comment]
You are correct.I'll close this.
