### ISSUE TITLE
unable to disable auto-complete

### ISSUE THREAD

**Issue by aNeutrino** [akinomyoga/ble.sh#384]
**ble version**: 0.4.0-devel4+6f4badf

**Bash version**: 5.2.21(1)-release x86_64-pc-linux-gnu

when I type command `ls -lah`
and then I type again `ls` the `-lah` part appears on right site of the cursor.
I would like to disable this completion, and I could not.
![image](https://github.com/akinomyoga/ble.sh/assets/38576/d82fe0e4-4cf8-4577-9fbd-512d3def228b)

I would like to see no completion during typing, only after I press <TAB>,
expected: ![image](https://github.com/akinomyoga/ble.sh/assets/38576/e38f5898-d301-48f8-b3f8-d21fedab1da5)

I have tried to disable various options but none of them seems to disable auto-completion during typing.

```
bleopt | grep auto
bleopt complete_auto_complete=0
bleopt complete_auto_complete_opts=
bleopt complete_auto_delay=0
bleopt complete_auto_history=0
bleopt complete_auto_menu=
bleopt complete_auto_wordbreaks=$' \t\n'
bleopt complete_limit_auto=2000
bleopt complete_limit_auto_menu=100
bleopt complete_timeout_auto=5000
bleopt decode_isolated_esc=auto
bleopt default_keymap=auto
bleopt term_index_colors=auto
bleopt term_modifyOtherKeys_external=auto
bleopt term_modifyOtherKeys_internal=auto
```

**Comment by akinomyoga** [comment]
> ```bash
> bleopt complete_auto_complete=0
> bleopt complete_auto_complete_opts=
> bleopt complete_auto_delay=0
> bleopt complete_auto_history=0
> ```

Can you check [README §2.2](https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#22-disable-features)? You should assign an empty string to disable it.

**Comment by aNeutrino** [comment]
thnx for fast answer.

I have tried to do this, and I tried to follow README as you suggested, https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#22-disable-features
but no metter where I put those commands:

- current runtime shell
- bashrc
- blerc
I always see auto-completion here for `ls` command.

![image](https://github.com/akinomyoga/ble.sh/assets/38576/5c90cf1f-85e1-46af-94ca-203b017ec695)
![image](https://github.com/akinomyoga/ble.sh/assets/38576/cb4ca50d-6d06-45fc-b209-3991b83d4657)

**Comment by akinomyoga** [comment]
Please check README §2.2. You should assign **an empty string** to disable it. Both In the first report and in the pictures you provided, you are setting `0` to `complete_auto_complete`. This is not what README describes.

**Comment by aNeutrino** [comment]
True I am sorry I have had some kind of "similar name blindness" hence I have not noticed that I am changing wrong value with an empty string `''`.
@akinomyoga thank you for your help. It worked.
`bleopt complete_auto_complete=''`

**Comment by akinomyoga** [comment]
No problem!
