### ISSUE TITLE
[MacOS] yanking into system clipboard in vim mode

### ISSUE THREAD

**Issue by 9tin9tin9** [akinomyoga/ble.sh#385]
I have a key binding (capital Y) that yanks texts into system clipboard just like the normal y operator. eg `Yiw`

I want to recreate that key mapping in ble.sh, and I started with copy pasting and renaming `function ble/keymap:vi/operator:Y` into ~/.config/blesh/init.sh (haven't modify the function). But when I paste with `p` in normal mode, the yanked content is pasted on a new line.

Now I change the function to
```diff
function ble/keymap:vi/operator:Y {
  local beg=$1 end=$2 context=$3 arg=$4 reg=$5
  local yank_type= yank_content=
  if [[ $context == line ]]; then
    ble_keymap_vi_operator_index=$_ble_edit_ind
    yank_type=L
    yank_content=${_ble_edit_str:beg:end-beg}
  elif [[ $context == block ]]; then
    local sub
    local -a afill=() atext=()
    for sub in "${sub_ranges[@]}"; do
      local sub4=${sub#*:*:*:*:}
      local sfill=${sub4%%:*} stext=${sub4#*:}
      ble/array#push afill "$sfill"
      ble/array#push atext "$stext"
    done

    IFS=$'\n' builtin eval 'local yank_content="${atext[*]-}"'
    local IFS=$_ble_term_IFS
    yank_type=B:"${afill[*]-}"
  else
    yank_type=
    yank_content=${_ble_edit_str:beg:end-beg}
  fi

-  ble/keymap:vi/register#set-yank "$reg" "$yank_type" "$yank_content" || return 1
+  echo -n "$yank_content" | pbcopy
  ble/keymap:vi/mark/commit-edit-area "$beg" "$end"
  return 0
}
```
The line `echo -n "$yank_content" | pbcopy` doesn't seem to have executed.

What is the correct way to implement a new vim key binding?

**Comment by akinomyoga** [comment]
You are on the right path. In addition to the above function, you just need to add the following keybindings:

```bash
# blerc

blehook/eval-after-load keymap_vi "
  ble-bind -m vi_nmap -f Y 'vi-command/operator Y'
  ble-bind -m vi_omap -f Y 'vi-command/operator Y'
  ble-bind -m vi_xmap -f Y 'vi-command/operator Y'
"
```

**Comment by 9tin9tin9** [comment]
OMG IT WORKS! Thank you so much!! Actually I had the idea of implementing `operator:$value` from the vim-surround module. But I guess I missed the part that registers the mapping.
