### ISSUE TITLE
blesh sometimes adds a space after = when completing a long opt which takes an arg

### ISSUE THREAD

**Issue by bkerin** [akinomyoga/ble.sh#387]
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) [Ubuntu 22.04.3 LTS]
ble.sh, version 0.4.0-devel4+fe6b4787 (noarch) [git 2.34.1, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:b42f5d6a7ad6d4921ec73838ba54a96d6bd30936, 77071 bytes) (noarch)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=14.0-west/15.0-2+ri, vte:6800 (65;6800;1)

For example, when in a git working dir completing `git format-patch --out` (with cursor at end) will complete to `--output-directory ` (with a trailing space).

Blesh doesn't do this when completing e.g. `ls --blo` (it completes to `ls --block-size=`).

Plain bash completes them both the same (both without trailing space added).

**Comment by akinomyoga** [comment]
Thank you for the report. This is related to the workaround for the `git` completions. I've adjusted it in commit 2c7cca2f.

**Comment by bkerin** [comment]
This resolves the issue, thanks.
