### ISSUE TITLE
Terminal hangs after ble is reloaded

### ISSUE THREAD

**Issue by jpninanjohn** [akinomyoga/ble.sh#39]
**ble version**: 0.3.1+c7d314f
**Bash version**: 5.0.11

After a reload, I am not able to enter anything into my terminal. It just gets stuck.

**Comment by akinomyoga** [comment]
Thank you for the report. I'm sorry, but it's already fixed in ble-0.3.2. Could you please try 0.3.2 available [here](https://github.com/akinomyoga/ble.sh/releases/tag/v0.3.2)? The URL of the tarball is `https://github.com/akinomyoga/ble.sh/releases/download/v0.3.2/ble-0.3.2.tar.xz`

**Comment by akinomyoga** [comment]
I updated README for v0.3.2 (Actually I forgot to push the latest commit which includes the update of README). Thank you.
