### ISSUE TITLE
`auto_complete/insert-word` should insert only one directory when completing paths

### ISSUE THREAD

**Issue by Tommimon** [akinomyoga/ble.sh#397]
When it is suggesting something like `sudo nano /etc/foo/bar/file` I often want to accept only a part of the path from the completion.
For example I would like to accept it until `sudo nano /etc/foo` and then write manually the file I need from directory `foo`.

As far as I know this is not currently possible because when I accept a word from the completion, if it is a path, it will insert the full path. I couldn't find a discussion about this issue or the intended way to do it, in my opinion completing the full path and then going back removing what I don't need is not a nice experience.

My proposal is to brake words on `/` and not only spaces, or at least insert an option to do so.

**Comment by akinomyoga** [comment]
> My proposal is to brake words on `/` and not only spaces, or at least insert an option to do so.

It's in [Q&A](https://github.com/akinomyoga/ble.sh/wiki/Q%26A) "*Can I change the word delimiter for <kbd>M-right</kbd> to accept a word in auto-comlete?*" (Ah, but I now think the current category of the question is not so friendly). There is an option [`complete_auto_wordbreaks`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-bleopt-complete_auto_wordbreaks). Please use the following setting:

```bash
# blerc

bleopt complete_auto_wordbreaks=$' \t\n/'
```

**Comment by akinomyoga** [comment]
I though about it again if there is any possible conflicts with that. I think I can add the suggested binding.

**Comment by akinomyoga** [comment]
I added widgets and added a binding to <kbd>C-right</kbd> in commit 0c4b6772. I also updated the binding of <kbd>M-f</kbd> to make it consistent with the behavior outside the auto-complete state. Could you check the behavior?

**Comment by Tommimon** [comment]
It's great to hear that, give me the time to setup everything to build from last commit, so that I can check the behavior.

**Comment by akinomyoga** [comment]
OK. Actually, the nightly build of the latest commit can be downloaded from the following link, so you can just downloaded and extract it. The way to setup is described in [the release page of the nightly version](https://github.com/akinomyoga/ble.sh/releases/tag/nightly).

- https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz

**Comment by Tommimon** [comment]
I tested it in my use case and the behavior is exactly what I expected, thanks.

I tried to combine it with other shortcuts that I use and everything seams fine, unfortunately  I'm not an expert `ble.sh` user so there might important details regarding this feature that I'm not aware of.

That said, since my original request has been fulfilled, I think we can close this issue.

**Comment by akinomyoga** [comment]
Thanks!
