### ISSUE TITLE
Error messages on msys2's bash

### ISSUE THREAD

**Issue by SUCHMOKUO** [akinomyoga/ble.sh#40]
**ble version**: 0.3.2+2423f4d
**Bash version**: 4.4.23(1)-release (x86_64-pc-msys)

Hi!
I'm using ble with msys2's bash on windows, but there seems some problem.
Every time I typed a character into the terminal, I got a bunch of error messages like:
```
bash: read: read error: 10: Communication error on send
bash: read: read error: 10: Communication error on send
bash: read: read error: 10: Communication error on send
bash: read: read error: 10: Communication error on send
bash: read: read error: 10: Communication error on send
```

**Comment by akinomyoga** [comment]
Thank you for the report! I have never tried ble.sh with MSYS2, so I just installed MSYS2 (64bit) and tested it. I could reproduce the problem and fixed it 500e051 (in ble-0.3). Could you try the latest commit of ble-0.3?

To try the latest commit, you first need to have `make` and `git`. If you don't have them you can install them into MSYS2 by the following command:

```console
$ pacman -Sy git make
```

Then load ble.sh and run `ble-update` (There will be many error messages, but please continue to type `ble-update` and press  <kbd>Enter</kbd>):
```console
$ source ble-0.3.2/ble.sh
$ ble-update
```

After the update is completed, please exit with the command `exit`. Then please restart the terminal.

----

Actually I noticed that there are several other problems with ble.sh while testing it with MSYS2:

- [ ] The cursor position calculation is broken in the default terminal of MSYS2. The default terminal seems to be mintty-3.0.0. I'll check it later.
- [ ] The detection of root privileges for `\$` in `PS1` doesn't work in MSYS2.
- [ ] After `ble-update` or `ble-reload`, the environment variables and the TTY state are broken.
- [ ] Comments in `.inputrc` is not properly ignored.
- [ ] Conditionals in `.inputrc` is not properly processed.

I continue to check these problems.

**Comment by akinomyoga** [comment]
I fixed all the problems I found with MSYS2. Could you test the updated version (as described in previous comment) and see if it works in your environment?

**Comment by SUCHMOKUO** [comment]
I tried the lateset version ef23ad1bb27eccd1a30be29759ff9e188b3aa7ad in the master branch, it now works well with my machine.
Thank for your hard working!
ありがとうございました！

**Comment by akinomyoga** [comment]
Thank you very much for testing! As MSYS2 is newly supported by ble.sh this time, probably there are still other problems. If you find any strange behavior, etc., please feel free to create issues again! 谢谢!
