### ISSUE TITLE
I don't want BLE to change my terminal colors. How do i do that?

### ISSUE THREAD

**Issue by ToontjeM** [akinomyoga/ble.sh#404]
iterm2 on Mac. iTerm has its own terminal themes. I don't want BLE to overwrite the colors set by iTerm. How do i do that?

**Comment by akinomyoga** [comment]
Could you explain it in more detail? First of all, ble.sh does not change the terminal colors, so you should be describing something other as *terminal colors*, which I'm not sure.

Or one possibility is that terminfo/termcap reports the supported number of the current terminal to be less than the actual number. For example, when terminfo/termcap says the supported number of colors is 8 but your prompt uses unsupported colors, ble.sh replaces the unsupported colors with the closest color assuming the standard 16 color palette. If terminfo reports a smaller number than the actual, even supported numbers are replaced. What are the results of the following command?

```bash
$ echo "$TERM"
$ tput colors || tput Co
```

**Comment by ToontjeM** [comment]
When I press Tab I get a menu of files and folders in the directory I am at. The color of the names of the files and folders are, as far as I understand, defined by blue.sh. I want to keep the colors I set in my terminal program, I don’t want ble to color anything.

**Comment by akinomyoga** [comment]
Thank you for the explanation.

> When I press Tab I get a menu of files and folders in the directory I am at. The color of the names of the files and folders are, as far as I understand, defined by blue.sh.

Yes, your understanding is correct if "blue.sh" is a typo of "ble.sh". (Or is "blue.sh" another script to make everything blue?)

>  I want to keep the colors I set in my terminal program,

I'm confused. The colors of the files and folders in the menu are not set by the terminal even if ble.sh doesn't do anything. Or is your terminal a special terminal that colors everything at the terminal level?

> I don’t want ble to color anything.

I'm not sure if I correctly understand it, but does the following setting work?

```bash
_ble_term_colors=2
bleopt term_index_colors=
bleopt term_true_colors=
```

**Comment by ToontjeM** [comment]
> > When I press Tab I get a menu of files and folders in the directory I am at. The color of the names of the files and folders are, as far as I understand, defined by blue.sh.
> 
> Yes, your understanding is correct if "blue.sh" is a typo of "ble.sh". (Or is "blue.sh" another script to make everything blue?)

Yeah, taht was my auto-correct on my phone kicking in.

> > I want to keep the colors I set in my terminal program,
> 
> I'm confused. The colors of the files and folders in the menu are not set by the terminal even if ble.sh doesn't do anything. Or is your terminal a special terminal that colors everything at the terminal level?

I am using iTerm2 which has themes. I call themes "colors" because that's basically what they are. 

> > I don’t want ble to color anything.
> 
> I'm not sure if I correctly understand it, but does the following setting produce the results that you intend?

I want(ed) ble.sh to leave the colors as set by the iTerm2 theme.

It's ok. I figured a way around it when not using ble.sh. So i have my terminal the way i want. I was using ble.sh because of a prereq for Atuin (https://github.com/atuinsh/atuin?tab=readme-ov-file#bash), but apparently it also works fine without. So less components means less configuration and confusion.

**Comment by ToontjeM** [comment]
Using `bleopt term_index_colors=0` i have it almost the way i want. Now i just need to get rid of the underlines.

**Comment by akinomyoga** [comment]
> I want it to look like as if i was not using ble.sh:

OK, so you want it to make it *similar* to the output of `ls`. First of all, the `ls` command is a separate program unrelated to the terminal or ble.sh. The list by `ls` and the list by `ble.sh` are unrelated. ble.sh generates the list without help of the `ls` command or the help of the terminal.

There are two ways to make the highlighting *similar* to the output of `ls`.

One way is to specify the colors one by one by yourself. You can check the list of the current setting by

```bash
$ ble-face filename_@
ble-face filename_block=fg=yellow,bg=black,underline
ble-face filename_character=fg=white,bg=black,underline
ble-face filename_directory=fg=26,underline
ble-face filename_directory_sticky=fg=white,bg=26,underline
ble-face filename_executable=fg=green,underline
ble-face filename_link=fg=teal,underline
ble-face filename_ls_colors=none
ble-face filename_orphan=fg=teal,bg=224,underline
ble-face filename_other=underline
ble-face filename_pipe=fg=lime,bg=black,underline
ble-face filename_setgid=fg=black,bg=191,underline
ble-face filename_setuid=fg=black,bg=220,underline
ble-face filename_socket=fg=cyan,bg=black,underline
ble-face filename_url=fg=blue,underline
ble-face filename_warning=fg=red,underline
```

You can reset those faces with the `underline` removed from their values. Ah, OK. It seems you have already found out it by yourself.

**Comment by akinomyoga** [comment]
Another way is, if you have the `LS_COLORS` environment variable, you can do

```bash
ble-face filename_@=none
bleopt filename_ls_colors="$LS_COLORS"
```

Or if the environment variable `LS_COLORS` does not exist but the program `dircolors` exists, you can load `LS_COLORS` by evaluating the output of the command `dircolors`:

```bash
eval "$(dircolors)"
ble-face filename_@=none
bleopt filename_ls_colors="$LS_COLORS"
```

**Comment by akinomyoga** [comment]
> But i think the default should be to not touch the original colors and let the user adjust what they want.

*The original colors* do not exist. The colors you refer to are the *custom colors* specified by the `ls` command in your system. The colors of `ls` depend on the implementation, the system, and the configuration by the users, and there is no standard for the colors of the `ls` command. Also, ble.sh is a separate program unrelated to the `ls` command, which does not use the output of the `ls` command. I don't feel I need to follow the colors of another unrelated program.

**Comment by akinomyoga** [comment]
I'm closing it. Thank you for trying `ble.sh` out!
