### ISSUE TITLE
highlighted text no longer deleted

### ISSUE THREAD

**Issue by cmndrsp0ck** [akinomyoga/ble.sh#409]
I used to be able to highlight text and either delete or start typing to replace the text. Now when I highlight text and hit delete or start typing only the character under the cursor is removed or typing is started at that point. Is there a new config option I need to adjust to get that previous functionality back?

currently using: v0.4.0-devel3

**Comment by akinomyoga** [comment]
Thank you for the report. Ah, this is a bug. I recently changed the way that the selection by Shift works in commit 2cac11adc4eb39d66213c66e9faeac055d8e3df4, which introduced the bug. I'll fix it.

**Comment by akinomyoga** [comment]
I pushed a fix 98a2ae1580717e82baafff53f81df60d45aafc89. Could you update ble.sh by running `ble-update` and check if the behavior is fine now?

**Comment by cmndrsp0ck** [comment]
It's working now. Thank you!

**Comment by akinomyoga** [comment]
Thank you for the confirmation! Closing.
