### ISSUE TITLE
Unable to set ble-face `syntax_function_name`

### ISSUE THREAD

**Issue by Jai-JAP** [akinomyoga/ble.sh#419]
```
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu) [Manjaro Linux]
ble.sh, version 0.4.0-devel4+18dd51ab (noarch) [git 2.43.2, GNU Make 4.4.1, GNU Awk 5.3.0, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)]
bash-completion, version 2.11 (hash:2d02f73e803daa87a06e94e33b2a7b3e672a2c0c, 76338 bytes) (noarch)
locale: LANG=en_IN.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.1-2+ri, vte:7402 (65;7402;1)
```

Using the `ble-face` commands to customize the colors in my terminal, setting `syntax_function_name` using
```sh
ble-face -s syntax-function-name fg=108,bold

# OR

ble-face syntax-function-name='fg=108,bold'
``` 
doesn`t change the color of functions called on the shell.

EDIT:

I haven't tried changing all the faces but most of them seem ok.

The same issue is reproducible on a fresh ble.sh install.

**Comment by akinomyoga** [comment]
> ```shell
> ble-face -s syntax-function-name fg=108,bold
> 
> # OR
> 
> ble-face syntax-function-name='fg=108,bold'
> ```

You are using `syntax-function-name`. You need to use `syntax_function_name`. The underscore and hyphen are treated differently.

**Comment by akinomyoga** [comment]
What would you expect by setting `syntax_function_name`? The following phrase in the first report seems to imply that you are trying to change the color of the name of the command that matches a function name.

> doesn`t change the color of functions called on the shell.

Then, it's not `syntax_function_name` but `command_function`. The face `syntax_function_name` is used to highlight the function name of the *function definition* (such as `function HERE { ...; }` and `HERE() { ...; }`), which is determined at the syntax level. The function names appearing as part of the command are determined dynamically so are not syntax-level highlighting.

**Comment by Jai-JAP** [comment]
That seems to work fine. Sorry for the confusion.

**Comment by akinomyoga** [comment]
> Another Question: Is there a better way to separate the output of the previous command from the current prompt with an empty line?
> I currently do that with `POSTEXEC="echo ' '"`

Ah, sorry. I missed it. You can use [`bleopt prompt_ruler`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-bleopt-prompt_ruler). To separate the prompt and command line by an empty line from the output of the previous command, you can use the following setting:

```bash
# blerc

bleopt prompt_ruler=empty-line
```

**Comment by Jai-JAP** [comment]
Thanks for your quick reply. Closing this issue.

**Comment by akinomyoga** [comment]
Thanks!
