### ISSUE TITLE
blehook/eval-after-load: No such file or directory

### ISSUE THREAD

**Issue by gnstaxo** [akinomyoga/ble.sh#43]
I want to configure the vi/vim mode so I created .blerc and added this: https://github.com/akinomyoga/ble.sh/wiki/Vi-%28Vim%29-editing-mode#3-possible-preferences, but I get error (title).

**Comment by akinomyoga** [comment]
Which version of `ble.sh` do you use?

> https://github.com/akinomyoga/ble.sh/wiki/Vi-%28Vim%29-editing-mode#3-possible-preferences

The above description is for ble-0.4. If you are using ble-0.3, please use the following setting (as described [here](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A76-Vim-Mode#63-setting-vim-editing-mode)):

```bash
ble/array#push _ble_keymap_vi_load_hook my/vim-load-hook
```

**Comment by akinomyoga** [comment]
I have updated [the Wiki page](https://github.com/akinomyoga/ble.sh/wiki/Vi-%28Vim%29-editing-mode#3-possible-preferences).
