### ISSUE TITLE
Exit status 1 when using pipe and grep

### ISSUE THREAD

**Issue by ibahnasy** [akinomyoga/ble.sh#430]
**ble version**: 0.4.0-devel4+adf9ab8
**Bash version**: 5.2.15(1)-release (x86_64-pc-linux-gnu)

ble.sh exists with status 1 when running a command with pipe and grep:
```
# lsmod | grep nvidia
[ble: exit 1]
```

**Comment by akinomyoga** [comment]
Thanks for the report, but this is the expected behavior.

**Comment by ibahnasy** [comment]
This is the expected behavior as it's a known bug and will be fixed or this is normal and will last like that?

Because it's really important to use pipes and grep for system administration, otherwise I have to remove ble.sh.

**Comment by akinomyoga** [comment]
It's not specific to ble.sh. In the plain Bash and also in any other shells, the exit status in this is `1`. This is required by the POSIX standard.

**Comment by akinomyoga** [comment]
> Oh I see, I just was confused when it printed out the status instead of not printing anything by default, thanks.

Ah, yes. Maybe I've confused you, but ble.sh prints the exit status of the previous user command when it is not `0`. If you want to prevent ble.sh from printing any exit status, you can disable the feature by the following setting (as described in [README 2.2](https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#22-disable-features)):

```bash
# ~/.blerc

bleopt exec_errexit_mark=
```
