### ISSUE TITLE
Sabbrev expansions not working

### ISSUE THREAD

**Issue by dgudim** [akinomyoga/ble.sh#437]
```
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu) [EndeavourOS]
ble.sh, version 0.4.0-devel4+56765251 (noarch) [git 2.44.0, GNU Make 4.4.1, GNU Awk 5.3.0, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)]
bash-completion, version 2.11 (hash:2d02f73e803daa87a06e94e33b2a7b3e672a2c0c, 76338 bytes) (noarch)
fzf key-bindings, (hash:a290e4cad579d5ad896110460a6d6317694c80f5, 5299 bytes) (noarch) (integration: on)
fzf completion, (hash:44bb904d396f8f266c609002cf49b563375ffaf5, 16128 bytes) (noarch) (integration: on)
zoxide, version 0.9.4 (/usr/bin/zoxide)
atuin, version 18.2.0 (/usr/bin/atuin)
locale: LANG=en_US.UTF-8 LC_ADDRESS=en_US.UTF-8 LC_IDENTIFICATION=en_US.UTF-8 LC_MEASUREMENT=ru_RU.UTF-8 LC_MONETARY=lt_LT.UTF-8 LC_NAME=en_US.UTF-8 LC_NUMERIC=en_US.UTF-8 LC_PAPER=en_US.UTF-8 LC_TELEPHONE=lt_LT.UTF-8 LC_TIME=ru_RU.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.1-2+ri, konsole:220380 (1;115;0)
```

After a recent update sabbrev expansions from `integration/fzf-git` no longer work. Typing `gb` and pressing space does nothing. (Edit: seems like my own sabbrevs also don't work 🤔)

Relevant parts of the config
```

bleopt edit_magic_expand=history:sabbrev

ble-import -d integration/fzf-completion
ble-import -d integration/fzf-key-bindings
_ble_contrib_fzf_git_config=sabbrev
ble-import -d integration/fzf-git
```

**Comment by dgudim** [comment]
After updating today to `0.4.0-devel4+70a325f9` my sabbrevs work again, but not ones from `fzf-git`

**Comment by akinomyoga** [comment]
Thank you for the report and sorry for the delay. I pushed a fix 70a325f95882f4850818542fc48b9ebb5db476bb in the master. Could you update ble.sh by running `ble-update` and check it?

**Comment by dgudim** [comment]
Still seeing the save issue

**Comment by dgudim** [comment]
![test](https://github.com/akinomyoga/ble.sh/assets/34401005/4511a57f-2d5e-4bab-a2c7-3eb174160065)

**Comment by akinomyoga** [comment]
Ah, OK. I misunderstood your previous reply. I'll take a look.

**Comment by akinomyoga** [comment]
It works in my environment. Did it work before commit d66e05d2d5b57e8f5ff5931660b9796fdc86693f (which introduced the bug this time)?

Maybe you test it outside a git repository? The fzf-git sabbrevs generate empty results if you induce them outside a git repository.

**Comment by dgudim** [comment]
Damn, yes. Forgot about that part 🙃. Thanks! This can be closed then

**Comment by akinomyoga** [comment]
OK! Thank you for the report!
