### ISSUE TITLE
Disable option completion

### ISSUE THREAD

**Issue by gvlassis** [akinomyoga/ble.sh#438]
Hello again!

I looked really hard inside the manual, but I could not figure out how to disable option completion (e.g. if you press TAB after ls in an empty directory, you get a list of possible options from the man page of ls). Is there a straightforward way to do so (like bleopt complete_auto_history="", but for options)?

**Comment by akinomyoga** [comment]
> Is there a straightforward way to do so (like bleopt complete_auto_history="", but for options)?

No.

If you set up a programmable completion for `ls`, to turn off the fallback completions provided by ble.sh, you may call `compopt +o ble/default` inside the function specified by `complete -F '<function name>'`.

Or you may comment out the following line in the source:

https://github.com/akinomyoga/ble.sh/blob/70a325f95882f4850818542fc48b9ebb5db476bb/lib/core-complete.sh#L5865

**Comment by akinomyoga** [comment]
Or another way is to overwrite the function `ble/complete/source:option` with an empty one through the load hook.

```bash
# blerc

function blerc/disable-source-option {
  function ble/complete/source:option { return 0; }
}
blehook/eval-after-load complete blerc/disable-source-option
```

**Comment by akinomyoga** [comment]
> that #335 was due to the option completion. I can confirm that this fixes that issue.

Thank you for the information! I added workarounds for the old mawk in commit 4089c4e1, so the error was supposed to be fixed in `master`. Maybe there is still an oversight. Could you share the version of ble.sh and the error message?
