### ISSUE TITLE
menu-complete lines aren't cleared correctly

### ISSUE THREAD

**Issue by animecyc** [akinomyoga/ble.sh#44]
**ble version**: 0.4.0-devel2+7a99bf3
**Bash version**: 5.0.16(1)-release,x86_64-apple-darwin17.7.0

When autocomplete is invoked by pressing Tab the results are not cleared when pressing Ctrl-C (sending SIGINT).

![2020-02-26 10 49 29](https://user-images.githubusercontent.com/92036/75377043-eab75700-5885-11ea-9a28-ac869d88bc51.gif)

**Comment by akinomyoga** [comment]
Thank you very much for the report! Fixed fb794b3. Could you check the latest commit?

Actually it was the intended behavior until very recently, and I changed the behavior so that the menu is cleared before going to the newline. But this one was an oversight. Thank you.

**Comment by animecyc** [comment]
Works like a charm! Thanks for the fast turn around!
