### ISSUE TITLE
Moving down through history gets stuck in multiline

### ISSUE THREAD

**Issue by mcarans** [akinomyoga/ble.sh#443]
I can move up through history ok, but if I hit a multiline command and press down, I will end up editing that command rather than going down in the history. Is there a shortcut for going down in the history?

**Comment by akinomyoga** [comment]
> I can move up through history ok, but if I hit a multiline command and press down, I will end up editing that command rather than going down in the history. Is there a shortcut for going down in the history?

You can continue pressing <kbd>down</kbd> to go to the last line in the multiline command. Then, you can press another <kbd>down</kbd> on the last line. When <kbd>down</kbd> is pressed on the last line, it goes to the next history entry.

If you want to move to the next history entry regardless of the cursor position in the multiline command, you can check the answer to #440.

**Comment by mcarans** [comment]
Thanks! I can see from that answer that I can use page up and page down.
