### ISSUE TITLE
Cannot bind RET in nsearch mode

### ISSUE THREAD

**Issue by rkitover** [akinomyoga/ble.sh#444]
**ble version**: 0.4.0-devel4+61968497
**Bash version**: 5.2.26(1)-release (x86_64-pc-linux-gnu)

This does not work:

```bash
ble-bind -m nsearch -f RET nsearch/accept-line
```

RET always exits nsearch mode no matter what you bind it to.

**Comment by akinomyoga** [comment]
See [§3.1.1](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#user-content-sec-kspecs-ret). Your terminal probably sends <kbd>C-m</kbd>.

```bash
ble-bind -m nsearch -f C-m nsearch/accept-line
```

**Comment by rkitover** [comment]
My apologies for not reading the fine manual, thank you very much for the quick response.

By the way I wrote [this](https://gist.github.com/rkitover/970543715c23976ca86a6c3390f2cbf2) today for me and my friends and you gave me the last thing I needed!

**Comment by akinomyoga** [comment]
Don't worry. The manual is kind of TL;DR. Thank you for writing the article about ble.sh!
