### ISSUE TITLE
Incorrect behaviour with C-w

### ISSUE THREAD

**Issue by 3ximus** [akinomyoga/ble.sh#446]
```
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu) [Ubuntu 23.10]
ble.sh, version 0.4.0-devel4+59787ee5 (noarch) [git 2.40.1, GNU Make 4.3, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)]
bash-completion, version 2.11 (hash:9abb523dbcb688e7fae4b87f5fc9d155b658d9ba, 76898 bytes) (noarch)
fzf key-bindings, (hash:ac1266f574a0a38b575b3ddcbd7bab9d3ab01ce0, 3014 bytes) (noarch) (integration: on)
fzf completion, (hash:9474ea03117b565f340ee8dacb438260b29e0021, 10334 bytes) (noarch) (integration: on)
locale: LANG=en_CA.UTF-8
terminal: TERM=screen-256color wcwidth=15.0-west/15.1-2+ri, tmux:0 (84;0;0)
```

Hi there!
I've been noticing that lately C-w has been incorrectly just storing the deleted work on the shell's clipboard, so when I hit C-y it pastes the last word "cut". The behavior in default bash is that the C-w keeps appending to this internal clipboard so that if you hit C-w in succession and C-y after it pastes everything you cut. 
I find this feature really useful when cutting and pasting segments of a command around. It used to work like that on blesh but idk since when it's not been working the same. Did this became a configurable behavior that I'm not aware ?

**Comment by 3ximus** [comment]
For added context I have these :
```bash
$ bind -p | grep 'C-w'
"\C-w": unix-word-rubout
```

```bash
$ ble-bind | grep -i 'c-w'
ble-bind -m 'emacs' -f 'C-w' 'kill-region-or kill-backward-uword'
```

**Comment by akinomyoga** [comment]
Thanks for the report. This was a regression caused by [`aa92b42`](https://github.com/akinomyoga/ble.sh/commit/aa92b42a7045fd4143cfad60f354d530f7f8d33b#diff-3f46dca95427790dbbb364d92371c62104b8e571682dcb8817f3eeac9b697217). I fixed it in commit 1313390b8971ff9c6888689fc938bc8e575fbff3. Could you check the latest master? Thank you!

**Comment by 3ximus** [comment]
Yup perfect :+1: It's working now! 
Thank you once again!

**Comment by akinomyoga** [comment]
Thank you for checking!
