### ISSUE TITLE
[zellij 0.40.1] Zellij

### ISSUE THREAD

**Issue by gvlassis** [akinomyoga/ble.sh#450]
Hello!

I just noticed that when bleopt complete_auto_menu=1, the menu options do not disappear inside Zellij when the menu closes. I attach a video showing the glitch.

https://github.com/akinomyoga/ble.sh/assets/74119653/c54b4745-024c-4976-b4cf-9b2cce2dac39

**Comment by akinomyoga** [comment]
This is a bug of Zellij. I submitted PRs to the upstream.

The terminal implementation by Zellij seems sloppy as I found even other three bugs in checking only the related part. In addition, the DA2 report by Zellij seems indistinguishable from that by Alacritty. They are using the conflicting range of the terminal IDs.

**Comment by akinomyoga** [comment]
The fixes are merged in the upstream Zellij, which is an impressive speed.

@gvlassis Could you check the behavior in the latest version of Zellij?

**Comment by akinomyoga** [comment]
Thank you for the confirmation!
