### ISSUE TITLE
ble.sh seems to have a conflict with McFly shell history tool

### ISSUE THREAD

**Issue by a-dekker** [akinomyoga/ble.sh#466]
```
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu) [Debian GNU/Linux 12 (bookworm)]
ble.sh, version 0.4.0-devel4+fcbf1ed (noarch) [git 2.39.2, GNU Make 4.3, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:aefcfdd4b924e8b03db0d49be8bdb5881ad7d0cd, 77084 bytes) (noarch)
starship, version 1.19.0-master (rustc 1.78.0 (9b00956e5 2024-04-29), 2024-05-15 17:09:04 +00:00)
locale: LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_COLLATE=nl_NL.UTF-8 LC_CTYPE=en_US.UTF-8 LC_NUMERIC=nl_NL.UTF-8 LC_TIME=nl_NL.UTF-8 LC_MEASUREMENT=nl_NL.UTF-8 LC_MONETARY=nl_NL.UTF-8
terminal: TERM=screen-256color wcwidth=14.0-west/15.1-2+ri, tmux:0 (84;0;0)
```

Just installed ble.sh from git and it after some tweaking with the colors it looks very nice.

But one thing that got broken was the history tool I use, [McFly](https://github.com/cantino/mcfly). Normally, I do a search with Ctrl-r, select the command and press enter. Default behavior is that the command gets executed right away. With ble.sh active, it is not executed, but a "²" sign is placed after the command. Only after removing this "²" the command can be executed by pressing enter.

It feels like some (enter) key binding conflict, but that is a wild guess.

**Comment by a-dekker** [comment]
I seem to have found a workaround. Sourcing ble.sh before sourcing mcfly in my `.bashrc` does no longer trigger the bad mcfly behavior. And ble.sh still looks to work okay.

**Comment by a-dekker** [comment]
closing because of https://github.com/cantino/mcfly/releases/tag/v0.9.1

**Comment by akinomyoga** [comment]
@a-dekker Ah, thanks!
