### ISSUE TITLE
[glob] “failglob” 有効下では失敗する，否定系のglob書式が一致するかの如く描画される

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#47]
**ble version**: 0.4.0-devel2+10ad274
**Bash version**: 5.0.3(1)-release

Bashのglob書式には，（POSIXが規定している“`[!s]`”を含めて）指定した文字・文字列 _以外_ を選択するような，いわば「否定系glob」が用意されています（もしかしたら正式名称があるかも知れません）。
“failglob” を有効にしている状態で，「否定系glob」を含め，入力したglob（と見做される文字列）に一致するファイル等がない場合，ble.shは`ble-color-setface syntax_error`で定めた着色を行う筈です。事実，否定系でないglobに対しては，そういった装飾が為されます。しかし，否定系globに一致するファイル等がない場合は，`syntax_error`ではなく，通常のglobに対する描画設定`syntax_glob`が適応されているようです。

```
$ mkdir /tmp/empty_dir && cd /tmp/empty_dir # 任意
$ shopt -s failglob
$ echo * # ← syntax_errorの着色
-bash: 一致しません: *
[ble: exit 1]
$ echo [!x]* # ← 一致するものがないが，syntax_globの着色
-bash: 一致しません: [!x]*
[ble: exit 1]
$ echo !(*) # ← 同上
-bash: 一致しません: !(*)
[ble: exit 1]
```

**Comment by akinomyoga** [comment]
ご報告ありがとうございます!  調べてみたところ `!` または `^` が含まれる単語は「履歴展開が行われる可能性がある」として単語着色を諦めているためのようです。。不一致であれば syntax_error で一致であればファイルの種類に従った着色になるので、syntax_glob になっているという事は一致でも不一致でもなく単語着色していないということにになります。

ble.sh では構文着色(文法構造に従って着色)の上に単語着色(ファイル名の状況に応じて着色)を重ねています。グロブパターンを含む構文着色はいつでも実施しています。一方で、展開・クォート除去した結果を用いる単語着色の場合には、副作用を持つ展開を含む場合を初め複雑な単語に対して適用できないので、"単純な単語" に対してのみ実施しています。例えば、履歴展開、コマンド置換、extglob、複雑なパラメータ展開などが含まれる単語は "単純な単語" ではありません。現在 "単純な単語" は正規表現で判定しています。

```console
$ echo @(hello) # extglob (丸括弧を含む単語) は単語着色無効
bash: 一致しません: @(hello)
[ble: exit 1]
```

1efe833 bracket expressions `[!...]` と `[^...]` については `[!` と `[^` を許容する形にしてみましたが、extglob の方は `()` の入れ子まで追跡するのは面倒なので取り敢えず一律で単語着色には対応していません。因みに `[!` の組み合わせであっても `[A[!echo` 等の場合には履歴展開が有効になるようですが、面倒なので気にしないことにします (そもそも `[A[!echo` は構文着色の時点で対応しきれていないですし…)。

**Comment by cmplstofB** [comment]
`[!...]`と`[^...]`について，一致するものが無い場合にsyntax_errorで着色されることを確認いたしました。

対応ありがとうございます！

**Comment by akinomyoga** [comment]
確認ありがとうございます!
