### ISSUE TITLE
License file missing in the release package

### ISSUE THREAD

**Issue by xambroz** [akinomyoga/ble.sh#475]
Hello, 
I have noticed that the project is having a standalone license file (LICENSE.md), but it is not part of the release (ble-0.4.0-devel3.tar.xz). Please would it be possible to put that file also the pre-compiled release for the packaging and redistribution purposes?

Thank you
Michal Ambroz

**Comment by akinomyoga** [comment]
I added https://github.com/akinomyoga/ble.sh/releases/download/v0.4.0-devel3/ble-0.4.0-devel3-2.tar.xz, which includes the (manually added) related files (though the related make rule inside `GNUmakefile` of the release commit 1a5c451c8baa71439a6be4ea0f92750de35a7620 cannot be updated).

**Comment by akinomyoga** [comment]
@xambroz Can I close the issue?
