### ISSUE TITLE
[kitty] ble.sh doesn't get loaded on start

### ISSUE THREAD

**Issue by eeelbrens** [akinomyoga/ble.sh#476]
**ble version**: 0.4.0-devel4+a9b962d
**Bash version**: 5.2.15(1)-release(x86_64-pc-linux-gnu)

I've recently installed debian 12 (coming from fedora and arch and carrying the `.bashrc` and `ble.sh` files with me) and installed ble.sh successfully on my machine, even working with gnome-terminal and alacritty as intended everytime at launch. However, when opening kitty I must reload ble.sh (using `source .bashrc` or `ble-reload` to reload my configuration. Any fix I can do here?

**Comment by akinomyoga** [comment]
Which version of kitty do you use? I submitted a fix to the upstream kitty for the same phenomenon six months ago: https://github.com/kovidgoyal/kitty/pull/7107, which is included in kitty v0.32.2+. Does the problem happen in `kitty >= 0.32.2`?

**Comment by eeelbrens** [comment]
well, turns out I did install it from apt (which provides version 0.26.5). sorry, my bad
