### ISSUE TITLE
shell becomes unresponsive on resize

### ISSUE THREAD

**Issue by killermoehre** [akinomyoga/ble.sh#48]
**ble version**: 0.4.0-devel2+5327f5d
**Bash version**: 5.0.16(1)-release,x86_64-apple-darwin19.3.0

If I resize a terminal window without typing at least one character into it, the shell won't accept any commands after the resize. The corresponding `bash` process runs at 100% CPU usage and is only killable by SIGKILL(9). This is independent of the used terminal emulator.

How to reporoduce:

1. open a terminal window
2. resize it
3. see in another terminal the CPU usage rise

**PS1**: `\[\]\[\033]0;\u@\H:\W\007\]\[$(iterm2_prompt_mark)\]\$ \[\]`

**Comment by akinomyoga** [comment]
Thank you for the report! But it doesn't reproduce with my environment. I tried `ble-0.4.0-devel2+5327f5d` with `5.0.11(1)-release,x86_64-redhat-linux-gnu`, `4.4.12(3)-release,x86_64-unknown-cygwin` and `5.0.16(2)-release,x86_64-pc-linux-gnu` (bash devel branch).

> PS1: \[\]\[\033]0;\u@\H:\W\007\]\[$(iterm2_prompt_mark)\]\$ \[\]

**Question 1**: I don't have macOS, and there is no `iterm2_prompt_mark`. I would like to have a result after the expansion. Also, I guess there would be some escape sequences between `\[\]` which are not printed on the terminal. Could you give me a result of the following command?

```bash
$ cat -v <<< "${PS1@P}"
```

**Question 2**: Is this problem related to your `PS1`? For example, does this problem reproduce with a simpler prompt setting something like `PS1='\$ '`?

**Comment by killermoehre** [comment]
> Thank you for the report! But it doesn't reproduce with my environment. I tried `ble-0.4.0-devel2+5327f5d` with `5.0.11(1)-release,x86_64-redhat-linux-gnu`, `4.4.12(3)-release,x86_64-unknown-cygwin` and `5.0.16(2)-release,x86_64-pc-linux-gnu` (bash devel branch).
> 
> > PS1: [][\033]0;\u@\H:\W\007][$(iterm2_prompt_mark)]$ []
> 
> **Question 1**: I don't have macOS, and there is no `iterm2_prompt_mark`. I would like to have a result after the expansion. Also, I guess there would be some escape sequences between `\[\]` which are not printed on the terminal. Could you give me a result of the following command?
> 
> ```shell
> $ cat -v <<< "${PS1@P}"
> ```
```$ cat -v <<< "${PS1@P}"
^A^[]133;D;0^G^B^A^[]0;cXXXXXXX@apfelkuchen:~^G^B^A^[]133;A^G^B$ ^A^[]133;B^G^B
```
The username is redacted.
> 
> **Question 2**: Is this problem related to your `PS1`? For example, does this problem reproduce with a simpler prompt setting something like `PS1='\$ '`?
No, it happens regardless of the used `PS1`.

**Comment by killermoehre** [comment]
I was able to reproduce the issue on my linux machine. xfce4-terminal, VTE3-based
```
$ echo $BASH_VERION,$MACHTYPE 
,x86_64-pc-linux-gnu
$ echo $BASH_VERSION,$MACHTYPE 
5.0.16(1)-release,x86_64-pc-linux-gnu
$ cat <<< "${PS1@P}"
$
```

**Comment by akinomyoga** [comment]
Thank you for the information!

> ```
> ^A^[]133;D;0^G^B^A^[]0;cXXXXXXX@apfelkuchen:~^G^B^A^[]133;A^G^B$ ^A^[]133;B^G^B
> ```

This corresponds to the following setting. I tried but the problem wasn't reproduced.

```bash
PS1='\[\e]133;D;0\a\]\[\e]0;cXXXXXXX@apfelkuchen:~\a\]\[\e]133;A\a\]$ \[\e]133;B\a\]'
```

> No, it happens regardless of the used PS1.

OK. Thank you. Then the problem should be somewhere else.

**Question 3**: Is the problem reproduced with pure environment where only `ble.sh` is loaded in Bash? You can try this by the following steps.

1. Open terminal
2. Type the following commands

```bash
$ bash --norc
$ source /path/to/ble.sh
```

3. Resize before any inputs

**Comment by akinomyoga** [comment]
> I was able to reproduce the issue on my linux machine. xfce4-terminal, VTE3-based

Thank you. I newly built `bash-5.0.16` now and tried `xfce4-terminal` in Linux machine, but I still cannot get the behavior.

````bash
[murase@chatoyancy 0 ~]$ echo $BLE_VERSION
0.4.0-devel2+5327f5d
[murase@chatoyancy 0 ~]$ echo $BASH_VERSION,$MACHTYPE
5.0.16(1)-release,x86_64-pc-linux-gnu
[murase@chatoyancy 0 ~]$ xfce4-terminal --version
xfce4-terminal 0.8.8 (Xfce 4.14)
```

**Comment by killermoehre** [comment]
> **Question 3**: Is the problem reproduced with a pure environment where only `ble.sh` is loaded in Bash? You can try this by the following steps.
> 
> 1. Open terminal
> 2. Type the following commands
> 
> ```shell
> $ bash --norc
> $ source /path/to/ble.sh
> ```
> 
> 1. Resize before any inputs

I can't reproduce it that way. I also tried `xfce4-terminal --disable-server --rcfile ~/.local/share/blesh/ble.sh`, but this works as expected, too.
You find my bash config at https://github.com/killermoehre/personal-bash-config, maybe you know better what you are searching for.

**Comment by akinomyoga** [comment]
Thank you! I'll check your config from now. I have another question. In the case that the CPU usage 100% is caused in a shell-script infinite loop, I want to take a shell stack trace of the infinite loop.

**Question 4**: Can you try the following step to try to get a stack trace?

1. Add a line before `ble-attach` in `.bashrc` as follows:

```bash
# bashrc

[[ $- == *i* ]] && source /path/to/blesh/ble.sh --noattach

# ...

trap 'ble-stackdump >/dev/tty' USR1 # <-- ADD THIS LINE
((_ble_bash)) && ble-attach
```

2. Open a terminal (Terminal `#1`)
3. Resize Terminal `#1`
3. Check the process ID of CPU 100% Bash in another terminal (Terminal `#2`).
4. Execute the following command several times in Terminal `#2` (Please replace `<PID>` with the process ID obtained in Step 3).
```
$ kill -USR1 <PID>
```
5. Is something output in Terminal `#1`? If there is something, it should look like the following. Could you provide me the contents?

```console
stackdump:
  @ /home/murase/.mwg/src/ble.sh/out/ble.sh:1 (ble-stackdump)
  @ something:123 (something)
  @ something:321 (something)
  @ something:123 (something)
```

**Comment by killermoehre** [comment]
> Thank you! I'll check your config from now. I have another question. In the case that the CPU usage 100% is caused in a shell-script infinite loop, I want to take a shell stack trace of the infinite loop.
Thank you very much for your time and effort.
> 
> **Question 4**: Can you try the following steps to try to get a stack trace?
> 
> 1. Add a line before `ble-attach` in `.bashrc` as follows:
> 
> ```shell
> # bashrc
> 
> [[ $- == *i* ]] && source /path/to/blesh/ble.sh --noattach
> 
> # ...
> 
> trap 'ble-stackdump >/dev/tty' USR1 # <-- ADD THIS LINE
> ((_ble_bash)) && ble-attach
> ```
Done in `~/.local/share/bash/zzz-attach-ble.sh`.
> 
> 1. Open a terminal (Terminal `#1`)
> 2. Resize Terminal `#1`
> 3. Check the process ID of CPU 100% Bash in another terminal (Terminal `#2`).
> 4. Execute the following command several times in Terminal `#2` (Please replace `<PID>` with the process ID obtained in Step 3).
> 
> ```
> $ kill -USR1 <PID>
> ```
> 
> 1. Is something output in Terminal `#1`? If there is something, it should look like the following. Could you provide me the contents?
> 
> ```
> stackdump:
>   @ /home/murase/.mwg/src/ble.sh/out/ble.sh:1 (ble-stackdump)
>   @ something:123 (something)
>   @ something:321 (something)
>   @ something:123 (something)
> ```
> 
> **Edit**: There will be filename paths in the output. If you want to hide your user name, please feel free to replace them!
Unfortunately there is no output at all. Just a process running on 100% CPU not reacting to any signals but SIGKILL and SIGSTOP.

**Comment by akinomyoga** [comment]
> Unfortunately there is no output at all. 

OK... Thank you for trying out the stack trace! You can now remove the added line "`trap 'ble-stackdump >/dev/tty' USR1`".

I'm now checking your configs. Maybe the treatment of `PROMPT_COMMAND` in `ble.sh` does something wrong. I actually recently changed the treatment of `PROMPT_COMMAND` in `ble.sh`. You are now using the commit `0.4.0-devel2+5327f5d`. I want to check if the problem is reproduced with the commit f1a2818.

**Question 5**: Can you check if the problem persists after the following steps?

1. Build and install f1a2818

```bash
$ cd /path/to/blesh-repository
$ git checkout f1a2818
$ make
$ make INSDIR=~/.local/share/blesh install
```

2. Open a terminal
3. Resize
4. Check CPU usage.

Note: if you have finished the check, you can restore the ble.sh repository state by the following commands:

```bash
$ cd /path/to/blesh-repository
$ git checkout master
$ make
$ make INSDIR=~/.local/share/blesh install
```

**Comment by akinomyoga** [comment]
OK, I could reproduce the problem.

**Comment by akinomyoga** [comment]
It turned out that it is caused by a bug of Bash 4.4+. When `return` without argument is used in the context of signal handlers, the function always succeeds regardless of the exit status of the previous command. This is a terrible bug...

```bash
$ test_command='f1() { false; return; }; trap "f1 && echo unexpected" WINCH; kill -WINCH 0'
$ bash-2.05b -c "$test_command"
$ bash-3.1 -c "$test_command"
$ bash-3.2 -c "$test_command"
$ bash-4.0 -c "$test_command"
$ bash-4.1 -c "$test_command"
$ bash-4.2 -c "$test_command"
$ bash-4.3 -c "$test_command"
$ bash-4.4 -c "$test_command"
unexpected
$ bash-5.0 -c "$test_command"
unexpected
$ bash-dev -c "$test_command"
unexpected
```

**Comment by killermoehre** [comment]
Do you know that you are in fact awesome?
But now the question is: what is the correct behavior here and how can it be fixed?

**Comment by akinomyoga** [comment]
> what is the correct behavior here and how can it be fixed?

I don't know why the POSIX defines the behavior of `return` in a trap action in such a way, but I guess POSIX wanted to provide a way to preserve the value of `$?` on the start of the trap action. If that is the case, the current Bash behavior that every `return` in the function-call tree is affected is unreasonable. Only `return` at the top level of the trap action should be affected.

I think I'm going to report it in `bug-bash` mailing list, but even if the behavior would be changed in Bash 5.1, the current behavior of Bash-4.4 and 5.0 is unlikely to be modified. So as far as `ble.sh` supports those versions, I have to work around this problem. I decided to specify an explicit argument for every `return` aa09d15. We cannot use `return` without arguments in Bash-4.4 and 5.0 for this problem.

**Comment by killermoehre** [comment]
`aa09d15` works for me as expected. Thank you very much.

**Comment by akinomyoga** [comment]
Thank you very much for all your report and testing!

**Comment by akinomyoga** [comment]
FYI: https://lists.gnu.org/archive/html/bug-bash/2020-04/msg00089.html
