### ISSUE TITLE
Add option to disable showing bash command in `exec_elapsed_mark`

### ISSUE THREAD

**Issue by paulzzy** [akinomyoga/ble.sh#481]
Hi! Thanks for making this project, it makes Bash very pleasant to use :)

I've noticed that enabling `exec_elapsed_mark` prints out both the elapsed execution time and the command, e.g.:

```sh
❯ true
[ble: elapsed 4ms (CPU 100.0%)] true
```

From looking at the [source code](https://github.com/akinomyoga/ble.sh/blob/699dabb35813a80b8abc02bcad9453844fe12931/src/edit.sh#L6453-L6456), it looks like the command is hardcoded into the output. I've love to disable showing the command, e.g.:

```sh
❯ true
[ble: elapsed 4ms (CPU 100.0%)]
```

Would it be possible to add an option to support this? Or is there already a way to accomplish this?

**Comment by akinomyoga** [comment]
I wouldn't add options for every small detail. In this case, I expect users to implement their own elapsed mark by themselves:

```bash
# blerc

bleopt exec_elapsed_mark=
function blerc/my.postexec {
  if ble/exec/time#mark-enabled; then
    local format=$'\e[94m[ble: elapsed %s (CPU %s%%)]\e[m'

    # ata
    local ata=$((_ble_exec_time_ata/1000))
    if ((ata<1000)); then
      ata="${ata}ms"
    elif ((ata<1000*1000)); then
      ata="${ata::${#ata}-3}.${ata:${#ata}-3}s"
    elif ((ata/=1000,ata<3600*100)); then # ata [s]
      local min
      ((min=ata/60,ata%=60))
      if ((min<100)); then
        ata="${min}m${ata}s"
      else
        ata="$((min/60))h$((min%60))m${ata}s"
      fi
    else
      local hour
      ((ata/=60,hour=ata/60,ata%=60))
      ata="$((hour/24))d$((hour%24))h${ata}m"
    fi

    # cpu
    local cpu='--.-'
    if ((_ble_exec_time_tot)); then
      cpu=$(((_ble_exec_time_usr+_ble_exec_time_sys)*1000/_ble_exec_time_tot))
      cpu=$((cpu/10)).$((cpu%10))
    fi

    local ret
    ble/util/sprintf ret "$format" "$ata" "$cpu"
    echo "$ret"
  fi
}
blehook POSTEXEC+=blerc/my.postexec
```

**Comment by akinomyoga** [comment]
You can also find another example for custom exit/elapsed mark implementation at [`contrib/config/execmark.bash`](https://github.com/akinomyoga/blesh-contrib/blob/3ae464903f036d3542c07c01d56c9b56b951a90a/config/execmark.bash).

**Comment by paulzzy** [comment]
Makes sense to avoid adding another config option. Your custom function works perfectly, thanks!

**Comment by akinomyoga** [comment]
I added the above example at [`contrib/config/github481-elapsed-mark-without-command.bash`](https://github.com/akinomyoga/blesh-contrib/blob/master/config/github481-elapsed-mark-without-command.bash) (with some modifications). If you like it, you may enable it by

```bash
# ~/.blerc

ble-import -d config/github481-elapsed-mark-without-command
```

or you can copy and modify the file as you like and load the modified version.

**Comment by paulzzy** [comment]
Thanks so much!! Will make it easier to maintain the script, appreciate the thought you put into this.
