### ISSUE TITLE
Option to print elapsed time marker on error

### ISSUE THREAD

**Issue by TheFantasticWarrior** [akinomyoga/ble.sh#483]
Would printing the elapsed time when the process exited with an error be possible? Didn't find it in the manual

**Comment by akinomyoga** [comment]
There is an example configuration at [`contrib/config/execmark.bash`](https://github.com/akinomyoga/blesh-contrib/blob/3ae464903f036d3542c07c01d56c9b56b951a90a/config/execmark.bash). You may try it by the following command:

```bash
# ~/.blerc

ble-import config/execmark
```

Or you may write your own one by copying `contrib/config/execmark.bash` and modifying it.

**Comment by akinomyoga** [comment]
@TheFantasticWarrior I added another example [`contrib/config/github483-elapsed-mark-on-error`](https://github.com/akinomyoga/blesh-contrib/blob/master/config/github483-elapsed-mark-on-error.bash) that implements your request. After updating `ble.sh` by running `ble-update`, you can load it by using the following setting:

```bash
# ~/.blerc

ble-import config/github483-elapsed-mark-on-error
```

You can adjust the content of the elapsed mark by setting [`bleopt github483_elapsed_mark`](https://github.com/akinomyoga/blesh-contrib/blob/4eaf0929b6ebcee00fcc791e1d165f8174a9c1f5/config/github483-elapsed-mark-on-error.bash#L3).

If you would like to adjust the behavior further, you can copy and modify the file as you like and load the modified version.
