### ISSUE TITLE
Make documents optional when building ble.sh from the source

### ISSUE THREAD

**Issue by blackteahamburger** [akinomyoga/ble.sh#485]
I'm writing Gentoo ebuild (build ble.sh from the source) and I want to make documents optional (controlled by `doc` USE flag).

That is, `make` does not build documents, and `make doc` or similar build documents (or you can provide `make no_doc` or similar). So does `make install`.

**Comment by akinomyoga** [comment]
Would allowing the configuration through make variables work? For example, something like allowing `make install DOC=no` to disable the installation of the documents.

**Comment by blackteahamburger** [comment]
> Would allowing the configuration through make variables work? For example, something like allowing `make install DOC=no` to disable the installation of the documents.
> 
> **Edit**: I'd probably use `USE_DOC` as the variable name: `make install USE_DOC=no`.

Of course it works. It doesn't matter what form it takes.

**Comment by akinomyoga** [comment]
Thank you for your reply. I will add it later.

**Comment by blackteahamburger** [comment]
And I also want I varible that can change the location to install the docs because Gentoo require docs to be installed in `/usr/share/doc/${PF}` (like `/usr/share/doc/blesh-0.3.0`), thanks!

**Comment by akinomyoga** [comment]
> And I also hope a varible that can change the location to install the docs because Gentoo require docs to be installed in `/usr/share/doc/${PF}` (like `/usr/share/doc/blesh-0.3.0`), thanks!

Actually, [`make PREFIX=/usr`](https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#install) already does.

If you want a finer control, you can specify three make variables `INSDIR`, `INSDIR_LICENSE`, and `INSDIR_DOC`. Make variables `PREFIX` and `DESCDIR` automatically arranges those three variables appropriately for the system installation.

**Comment by blackteahamburger** [comment]
> Actually, [`make PREFIX=/usr`](https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#install) already does.

It does not because it will install docs to `/usr/share/doc/blesh` (without version, which is required). But I'm glad to know there's `INSDIR_DOC` to control, thanks!

**Comment by akinomyoga** [comment]
I pushed the changes: 40fe9c956a5b9837342a4016d604cfd402cfa621, https://github.com/akinomyoga/blesh-contrib/commit/5cd7b067b0f590fa5dc02d6faa1dfe4420ce4b28

**Comment by blackteahamburger** [comment]
Just a suggestion, can you make the default install dir of license to be `$DESTDIR/$PREFIX/share/blesh` when `USE_DOC=no` so that the doc dir is kept untouched? Everything else fine.

**Comment by akinomyoga** [comment]
It is hard to decide whether we should change the default install location by `USE_DOC` because the rule is already complicated. As a consequence of the combination of user-supplied `DESTDIR`, `PREFIX`, `INSDIR`, `USE_NO`, and `INSDIR_LICENSE`, the final install location of the license files would be almost unpredictable from the user's perspective (or at least, one needs to think about it for a while to get an idea). We anyway already provide a way to directly specify the directory through `INSDIR_LICENSE`, so there is no need to add another complicated rule.

I'm not sure if it was good, but I tried to reorganize the explanation in README about how the installation locations are determined and applied the suggested change in commit 134a38d1d8e269b6009ec222e73a46a173a21fac.

**Comment by blackteahamburger** [comment]
I reconsidered and it seems that ble.sh's document is not too large and can be installed unconditionally... However, if more documents will be added or documents will be more complicated (e.g. introduce additional dependencies) in the future, it is good. Anyway, it is definitly not a bad idea.

**Comment by blackteahamburger** [comment]
There's one slight problem. I'm supposed to install with `DESTDIR="${D}" PREFIX="${EPREFIX}/usr"` which makes the install dir to be `/var/tmp/portage/app-shells/blesh-9999/image//usr` in a normal system (DESTDIR=`/var/tmp/portage/app-shells/blesh-9999`, PREFIX=`//usr`). Everything else normal, but it causes `make: *** No rule to make target '/var/tmp/portage/app-shells/blesh-9999/image/usr/share/doc/blesh/LICENSE.md', needed by 'install'.  Stop.` because of `ifeq ($(findstring $(INSDIR_LICENSE),$(INSDIR) $(INSDIR_DOC)),)`.

**Comment by blackteahamburger** [comment]
> Is that a problem? As I already mentioned, the rules for resolving those variables are already too complicated and unpredictable. Is there a reason that we would further complicate them? What problem would that complication solve? You can already directly specify `INSDIR_LICENSE`.

It just causes inconsistence. But if you think it is acceptable, then just keep it.

> > I also noticed that `INSDIR_DOC` does not change the directory that documents install.
> 
> What do you mean? It does change the directory that the documents are installed as far as I test it. What specific command did you use?

I cannot reproduce it too... Maybe it's a typo.

**Comment by akinomyoga** [comment]
> > Is that a problem? As I already mentioned, the rules for resolving those variables are already too complicated and unpredictable. Is there a reason that we would further complicate them? What problem would that complication solve? You can already directly specify `INSDIR_LICENSE`.
> 
> It just causes inconsistence. But if you think it is acceptable, then just keep it.

It's actually hard to decide. Maybe we can consider an alternative setup for simplification.

For example, we currently configure `INSDIR_LICENSE` to be the same directory as documents, `$prefix/share/doc`, but we might default it to `$prefix/share/licenses` following the convention in Arch Linux. There is no single default setup that satisfies the conventions in all the distributions, so it could be an option to choose the one of Arch as the default one. Then, all the entangled interaction between `USE_DOC` & `INSDIR_DOC` vs `INSDIR_LICENSE` may be resolved by completely separating them.

Hmm, but if we change the behavior for the cases that do not use `USE_DOC`, that can break existing packages. For that reason, probably, we wouldn't want to change the behavior of the cases without `USE_DOC`.

**Comment by akinomyoga** [comment]
I don't want to unnecessarily increase the number of commits that step forward and backward, so I created branches `make` in `ble.sh` and `blesh-contrib`.

https://github.com/akinomyoga/ble.sh/tree/make
https://github.com/akinomyoga/blesh-contrib/tree/make

I'll put them in the `master` branch after you are satisfied. Could you use them?

We actually require `GNU make >= 3.81`, so I just checked the feature set available in these versions of GNU make and try to use them to reorganize `GNUmakefile`. Also, now the default location of license files is changed to `$INSDIR/licenses` (if `$INSDIR` is specified), or `${datadir}/share/blesh/licenses`.

**Comment by blackteahamburger** [comment]
It works perfectly. Thank you!

**Comment by akinomyoga** [comment]
I merged the `make` branches in `master` (c5caedf7859c2e8f7dd5749766f01bb444cf1ba6 and https://github.com/akinomyoga/blesh-contrib/commit/c869bb0b6884d9c791e0a73f5d844e77fe1111f1).

**Comment by akinomyoga** [comment]
@blackteahamburger Can I close this issue?

**Comment by blackteahamburger** [comment]
Thank you!
