### ISSUE TITLE
Vim mode `j k` for escape, keybinding

### ISSUE THREAD

**Issue by vasi786** [akinomyoga/ble.sh#486]
In the vim editing mode, Is it possible to map `j k` so that it takes me to the normal mode?

**Comment by akinomyoga** [comment]
Have you checked [Q&A](https://github.com/akinomyoga/ble.sh/wiki/Q&A)? It is the *first* item on the Q\&A page.

**Comment by vasi786** [comment]
Ahh, Didn't see that. Thanks for pointing out.
