### ISSUE TITLE
Enhancement of completion

### ISSUE THREAD

**Issue by akinomyoga** [akinomyoga/ble.sh#5]
補完について色々。現状の補完の仕組みは色々不満があるので改修する必要がある
- [x] 文脈依存のエスケープが不完全・不自然 (2018-08-25)
- [x] menu-complete, menu-complete-backward の対応が困難 (2018-09-02)
- [x] ~~重い~~ → 保留 (2018-09-02)
- [x] 候補表示をもっとちゃんとする (2018-09-02)
- [x] 自動的に候補を提示したい (2018-08-25)
- [x] 絞り込み (2018-09-02)

他に以下の要望が出ている
- [x] 略語展開 <del>(仕様は未だ何も決まっていない)</del>
  - [x] 静的略語展開
  - [x] 動的略語展開
- [x] ブレース展開の中での補完
- [ ] **追記**: ヒアストリング・ヒアドキュメントの中の補完

2018-08-25 開発ブランチ [`enhance-complete`](https://github.com/akinomyoga/ble.sh/tree/enhance-complete)

**Comment by cmplstofB** [comment]
要望ばかりで申し訳無いですが，Bash での
```bash
shopt -s no_empty_cmd_completion
# 空行時の非補完
```
のような設定を bleopt としても欲しいです。
誤って空行で補完キーを押下してしまい，四半秒程操作が効かなくなる程大量の補完が働くので。

**Comment by akinomyoga** [comment]
ご報告ありがとうございます! これは簡単なので `support-vi-mode` の方に push します。

> のような設定を bleopt としても欲しいです。

- 0673ace8076e2c8f95fbc43be2d039db565685ad `shopt -s no_empty_cmd_completion` の時は全く補完を試みないように変更

`shopt -s no_empty_cmd_completion` の時はコマンド候補を列挙しないようにしていたのですが、今回は変数名なども候補として列挙しないようにしました。当初は変数の数はそんなに多くならないので問題ないと考えていたのですが、`ble.sh` が大量に変数を定義するのでその限りではないですね…。

> 誤って空行で補完キーを押下してしまい，四半秒程操作が効かなくなる程大量の補完が働くので。

- 7f0b6d766111e8b2a50b7caee7dac13845dedcfd bleopt 変数 `complete_stdin_frequency` (既定値 50) を追加

`ble.sh` では (Bash-4.0 以降で) 入力操作があると補完候補生成処理を中断するようにしていますが、入力操作があったかのチェックは 100 候補処理する毎に行っていました。今回この周期を 50 に短縮して、更に設定できるようにしました。

- 7f0b6d766111e8b2a50b7caee7dac13845dedcfd  変数名候補の列挙でも `complete_stdin_frequency` 毎の入力チェックを実施するように変更

**Comment by cmplstofB** [comment]
ありがとうございます！確認しました。

**Comment by cmplstofB** [comment]
ありがとうございます！確認しました。

**Comment by akinomyoga** [comment]
更新 32037b9b0db37bb20036b46a7378d90a6442e33c...5c23822265cb0d301231d2ade109603874e00116 at branch [`enhance-complete`](https://github.com/akinomyoga/ble.sh/tree/enhance-complete)

**補完: 新機能**
- complete: 曖昧補完 `#D0707` `#D0708` `#D0710` `#D0713` `#D0743` (fix)
- complete: Readline 設定 `completion-ignore-case` に対応 `#D0709` `#D0710`
- complete: `ble/cmdinfo/complete:$command_name` 対応 `#D0711`
- complete: `path:...` などと入力した時の続きの補完に対応 `#D0715`
- complete: 引用符内のエスケープなどを適切に処理する `#D0717`
- complete: 自動補完に対応 `#D0724`, `#D0728`, `#D0734` & `#D0735` (vim-mode), `#D0765` (history)
- complete: カーソルの右側に補完結果の一部が含まれる時にスキップする機能 (`bind set skip-completed-text`) `#D0736`
- complete: 引用符の中で補完した時に引用符を閉じる機能 `#D0738`
- complete: 算術式内部での変数名の補完に対応 `#D0742`
- complete: 候補一覧表示の整列と着色 `#D0746` `#D0747` `#D0762` `#D0765`
- complete: menu-completion (メニュー補完) 対応 `#D0749` `#D0757` `#D0764`
- complete: menu-filter (候補絞り込み) 対応 `#D0751`
- complete: vi_cmap に於ける補完 `#D0761`

**補完: バグ修正・対策**
- complete: Cygwin でのコマンド名補完に於いて `.exe` の途中まで入力した時に正しく補完できない問題の修正 `#D0703`
- complete: `complete` によって登録されたプログラム補完に対して変数 `COMP_*` が正しく設定されない問題の修正 `#D0711`
- complete: `"` や `'` を含むファイル名の補完が正しくできない問題の修正 `#D0712` `#D0714`
- complete: 補完中に特殊キーを入力しても中断しない問題の解消 `#D0729`
- complete: クォートを認識しないプログラム補完関数に対する対策 `#D0739`
- complete: 引数の途中からのプログラム補完の不整合の修正 `#D0742` `#D0744`
- complete: パラメータ展開 `${var}` 直後からの補完が正しく実行できる様に修正 `#D0742`

**補完: 動作変更**
- complete: 補完候補生成直前の `shopt -s force_ignore` を参照して候補を制限する様に変更 `#D0704`
- complete: `FIGNORE` はエスケープされた挿入文字列に対してではなくて、候補文字列に対して判定する様に変更 `#D0704`
- complete: 関数名補完を `/` で区切られた単位で行う `#D0706` `#D0724` (曖昧一致の時は抑制)
- complete: パラメータ展開で厳密一致で一意確定の時は他の補完文脈を使うように変更 `#D0740`
- complete: パラメータ展開の補完後に挿入する文字を文脈に依存して変更 `#D0741`
- complete: パラメータ展開の直後に補完で挿入する際のエスケープを文脈に依存して変更
- complete: プログラム補完による生成候補でディレクトリ名を省略 `#D0755`                                                  

**他: 新機能**
- edit (`RET`): 文法的に不完全のときに改行を挿入 `#D0684`
- core (`ble/util/idle`): 簡易タスクスケジューラの実装 `#D0721`
- core: add a function `ble/function#try` `#D0725`
- idle: `ble/util/idle` でバックグラウンドジョブ待ち機能を実装 `#D0731` `#D0745` (history bugfix)
- base: `--attach=prompt` 対応 `#D0737`
- base: 初回初期化時の順序の変更と過程の info による表示
- decode: modifyOtherKeys 対応の改善 `#D0752` `#D0756` `#D0758` `#D0759`
- core (`ble/util/assing`): 第3引数以降にコマンドに対する引数を指定できるように変更 `#D763`

**他: バグ修正・対策**
- highlight: 単語着色が乱れるバグの修正 `#D0686`
- syntax: bash-3.2 以下で `_ble_syntax_attr: bad array subscript` のエラーが出るバグの修正 `#D0687`
- prompt: PS1 で \v が空文字列になるバグの修正 `#D0688`
- highlight: 上書きモードにおいてコマンドをキャンセルしても `disabled` レイヤーの着色が無視されるバグの修正 `#D0689`
- core (ble/term/visible-bell): 横幅の計算を誤っているバグの修正 `#D0690`
- decode: "set -o vi/emacs" で編集モードを切り替えた直後に "stty" が変になる問題の修正 `D0691`
- core: LANG=C とすると動かなくなる問題の対処 `#D0698` `#D0699` `#D0700`
- history: Cygwin で履歴の初期化に時間がかかる問題の対策 `#D0701`
- history: bashrc 読み込み直後に謎の待ち時間が発生する問題の対策 `#D0702`
- emacs: 貼り付け (bracketed paste) で文字列が二重に挿入されるバグの修正 `#D0720`
- main: POSIXLY_CORRECT が設定されている時の対策 `#D0722` `#D0726` `#D0727`
- edit: POSIXLY_CORRECT を用いた組み込みコマンド上書き対策 `#D0722`
- decode: 連想配列に依る実装のバグを修正し bash-4.0, 4.1 においても連想配列を使用 '#D0730'
- decode: `ble-bind -c` でシェルの特殊文字を含むコマンドが正しく実行できないバグの修正
- edit: 履歴項目の数が倍増するバグの修正 `#D0732`
- vi: キーボードマクロで特殊キーが再生されないバグの修正 `#D0733`
- isearch: 現在位置の表示時の 0 除算のバグの修正
- vi: `!!` をキャンセルしても操作範囲を示す着色が消えないバグの修正 `#D0760`

**他**
- refactor: `#D0725` `#D0750` `#D0753` `#D0754`
- bash-bug: Bash に対するバグ報告 `#D0692` `D0695` `D0697`

**Comment by akinomyoga** [comment]
@cmplstofB さま。

### 編集関数の改名

今回の `enhance-complete` ブランチにおける変更で以下の編集関数 (widget) の名称を変更しましたので、もし `ble-bind` を使用してこれらの編集関数に束縛している場合には、その設定を書き換えてお使い頂ければ幸いです。

- `menu_complete/accept`              → `menu_complete/exit`
- `auto_complete/accept`              → `auto_complete/insert`
- `auto_complete/accept-on-end`       → `auto_complete/insert-on-end`
- `auto_complete/accept-word`         → `auto_complete/insert-word`
- `auto_complete/accept-and-execute`  → `auto_complete/accept-line`
- `isearch/accept`                    → `isearch/accept-line`

### 略語展開

また略語展開は2種類対応しました。後でマニュアル作成時にも記述する予定ですが先にご説明します。使い勝手などで何かありましたらお知らせ頂ければ幸いです。

- **動的略語展開** (**dabbrev**) と称したものは Readline の `dabbrev-expand` 様の機能で `$COMP_WORDBREAKS` または空白文字で区切られた "単語" を履歴から検索して置換します。
  - <kbd>C-x C-r</kbd> でカーソル前の "単語" について動的略語展開モードに入ります (元々の Bash では <kbd>C-x C-r</kbd> は Readline の設定の再読込ですが `ble.sh` では意味がないので、動的略語展開に割り当てることにしました)。
  - 続けて <kbd>C-r</kbd> を押すことでより前の候補に移動します。<kbd>C-g</kbd> がキャンセルで、動的略語展開を開始する前の状態に戻します。それ以外の操作は動的略語展開のモードを抜けて通常の操作として解釈されます。
- **静的略語展開** (**sabbrev**) と称したものは `zsh-abbreviations` 様の機能で、事前に登録した単語に一致するものを置き換えます。
  - 例えば `ble-sabbrev L='| less'` などとして登録します。
  - `magic-space` (<kbd>SP</kbd>) を拡張して、履歴展開が起こらなかった場合にカーソル前の単語に対して静的略語展開を試みるようにしました。
  - <kbd>C-x '</kbd> でカーソル前の単語に対して静的略語展開を試みるようにしました。

**Comment by akinomyoga** [comment]
> 静的略語展開でのカーソル前の単語に対する展開ですが，VimにはCtrl+]というキーマップがあり，これとsabbrev-expandは意味や挙動が類似しているのでこちらに割り振ったほうがいいかなと思いました。

教えていただきありがとうございます! その様に変更いたしました e5969b7d7a17cdc41cca0e7b7ffb70b366a1fa8c。

> bleshではCtrl+]に既定でbellが割り当てられていますが，これはどういう意味でしょうか……。

`bell` は単に「何にも割り当てられていない」という事を表すためだけのものでしたので大丈夫です。

> ところで静的略語展開の設定はcomplete-load-hook経由で設定すればいいですかね。

そうでした。説明するのを忘れていました。その通りです。

**Comment by cmplstofB** [comment]
自動補完の際の描画に関して，少し微妙な問題ですが，話したいことがあります。
なお，以下，説明が徒に煩雑とするだけなので，ls(1)コマンドは存在し，「l」という名前のコマンドは存在しない（aliasによる設定もされていない）という前提で進めます。
```console
$ ls /tmp
```
というコマンドラインを実行した後，
```console
$ l@
```
のような状態では`l`という文字列は「自動補完を行なった場合にされるべき描画」がなされていますよね（この場合だと自動補完を行なった場合「`ls /tmp`」という文字列になるので，その「`l`」は`command_file`に設定された描画）。
ところが実際は「`l`」という名前のコマンドはないので，この状態で実行するとエラーになります。
結果を考えるならば，上の状態における「`l`」の描画は`syntax_error`に設定されたものにすべきではないでしょうか。

……しかし，僕自身も迷っている部分はあります。それは「自動補完は**実際のコマンドラインとみなせる**のだから，その一部を描画するとき，基準とすべきコマンドラインは自動補完された全体である」という考え方もあると思うからです。

@akinomyoga 様は，後者の考え方でもって上述のような描画にされているのでしょうか。それとも何か別の要因（実装が困難・速度が低下する など）で，そうされているのでしょうか。

**Comment by akinomyoga** [comment]
実はそれについて少し悩みました。初めは自動補完を除いた内容で着色するのが自然と思ったのですが、まさに

> それとも何か別の要因（実装が困難・速度が低下する など）で，

ということで、実装が面倒なのでした。一方で `fish` を見てみますと、コマンド名を自動補完する場合には「自動補完の前にコマンドが存在しているかどうか」で着色されますが、ファイル名を自動補完する場合には「自動補完の後にファイルが存在しているかどうか (というより現在の入力内容がファイル名の接頭辞になっているかどうか?)」で下線が引かれるようだったので、まあどちらでも良いかと思ってそのままになったのでした。

自動補完の部分は実は「実際に文字列を挿入して」実装されているので、これを綺麗に実装する方法を考えるのは少々面倒です…。

- a. 構文解析の方に "一時的に挿入されている文字列" を認識させてそこを読み飛ばさせる案? 実は構文解析は前回からの差分だけを更新するように設計されているのですが、"一時的に挿入されている文字列" という情報の差分をどういう形態で表現するのかまで含めて再設計しなければならないですね…。それに落ち着いて考えると構文解析器にこのような構文と全く関係ないとってつけたような機能を入れるのは設計として変です。

- b. 実際には文字列を挿入せずに実装する案? そうすると今度は画面上の文字の配置を計算する時に「画面上では表示されているが編集文字列には含まれない物体」を考慮に入れなければならず、これも面倒そうです。

- c. 実は実装前の検討でもう一つの案がありました。別の「ウィンドウ」をオーバーレイで表示するというものです。これはまた簡単なウィンドウシステムの仕組みを整えなければなりませんが、実装としては余り汚くならずに済みそうに思います。<br/>　以下は実装前に調べた時に見つけたページなのですが「オーバーザスポット」「オンザスポット」「オフザスポット」「ルートウィンドウ」という4種類の仮入力の方法が示されていました。丁度、今の実装は「オンザスポット」で、別のウィンドウを使うのは「オンザスポット」または「ルートウィンドウ」になりますね
  - [Big Sky :: Vim と日本語入力の話。](https://mattn.kaoriya.net/software/vim/20170905113330.htm)
  - [Seamonkey インプットメソッド仕様書](https://web.archive.org/web/20110630165743/https://www.mozilla-japan.org/projects/intl/input-method-spec.html)

**Comment by cmplstofB** [comment]
やはりそうですよね……。
fish(1)での挙動は知らなかったのですが（というか調べもせずに投稿してしまいました），そのような実装をしているということは，この辺りの問題はそれほど認知されていない，あるいは開発者の間で合意が形成されていない，またあるいは実装が面倒であるということなんでしょうかね。
僕は，素人ながら勝手に，ble.shや他のシェルの自動補完はb案のような実装がされていると思っていました。実際は違うのですね。

実は，挙げられたWebページは僕も読んだことがあります（だからなんだという話ですが）。オーバーザスポットやオンザスポットは，rxvt-unicode-256colorsという端末エミュレータにおいて日本語入力がまったくうまく行かず，設定を弄ったりしている時に遭遇した単語でした。まさか自動補完の実装において登場するとは。

**Comment by akinomyoga** [comment]
> 僕は，素人ながら勝手に，ble.shや他のシェルの自動補完はb案のような実装がされていると思っていました。実際は違うのですね。

多分、これはシェルスクリプトで実装している `ble.sh` の実装の都合なので、他のシェルでは違うんでないかなと思います。シェルスクリプトで実装していると、どうしてもデータ構造に制限がかかってしまう (複雑なデータ構造をシェル上で実現することも可能ですがとても面倒でしかもとても遅い) ということと、単純に速度の問題ですね。

(以下興味があればですが) まともなエディタですと、編集文字列は行志向で保持します (あるいは各行の範囲を別のデータ構造で保持します) ので、文字の配置計算は行内で閉じています。また、実装言語の速度も十分速いはずなので行全体に対して再計算を実行しても重くなりません。いい感じのデータ構造が使えれば b 案のような「挿入された物体」に対応するのは綺麗にできます。`ble.sh` の場合には、先ずデータ構造の速度の問題から、一本の文字列で全行の編集文字列を保持しています。更に一行に収まるような場合でも、毎回構文解析や配置計算を0からやっていたのでは重くてたまらないので、できるだけ変更があった部分だけ、最小限に更新をしています。データ構造も貧弱なので (構造体の配列が欲しい…) 「挿入された物体」などのようなものに新しく対応するのは、様々な箇所を書き換えなければならないのと速度に直接効いてくるので辛いです。因みに `zsh-syntax-highlighting` は着色のみの計算 (文字配置などは zsh 本体が計算している) で、しかも構文解析はせずに単純な着色しかしていませんが、それでも毎回全体を計算しているので長い編集文字列に対して入力に対する遅延が出ていました (少なくとも数年前実験した時は)。

これについては良い実装案が出てくるまでは置いておいて、取り敢えず今の所は対応しないということにしようかなと思っています。

**Comment by akinomyoga** [comment]
更新 8584e82...6ed51e7

**新機能**
- highlight: 変数代入の右辺及び配列要素の着色に対応 `#D0839` 854c3b4
- nsearch: (非インクリメンタル)履歴検索に対応 <kbd>C-x {C-,}{p,n}</kbd> `history-{,substring-,n}search-{for,back}ward` `#D0843` e3b7d8b 0d31cd9 253b52e
- isearch: 検索前に選択状態でがあれば検索後に復元する `#D0845` 93f3a0f
- decode: 貼り付け時など大量の入力があった時に処理の進行状況を表示 `#D0848` c2d6100
- decode: 貼り付け時などの高速化の為に一括の文字列挿入に対応 (`batch-insert`) `#D0849` 48eeb03
- decode: `bleopt decode_isolated_esc=auto` でキーマップに応じて単独 <kbd>ESC</kbd> の取扱を切り替え `#D0852` 9b20b45 edd481c
- complete: `bleopt complete_{auto_complete,menu_filter}=` で自動補完・候補絞り込みの無効化に対応 `#D0852` 4425d12
- vi: テキストオブジェクト単語の再実装 (reported by cmplstofB) `#D0855` 9f2a973 ad308ae 3a5c456 6ebcb35
- vi: オペレータ `d` の特殊ルールに対応 `#D0855` fa0d3d3

**バグ・問題修正**
- decode: `ble-bind -d` に於いて `-c` 及び `-x` の引数の引用符が二重になっている問題の修正 `#D0850`
- auto-complete: 構文エラーが自動補完により解決される時 <kbd>RET</kbd> でコマンド実行が抑止されない問題の修正 `#D0827` daf360e
- highlight: `shopt -s failglob` で配列の指示初期化子がエラー着色される問題の修正 (reported by cmplstofB) `#D0838` d6fe413
- complete: プログラム補完に対して曖昧補完が効かない時の対策 `#D0841` 713e95d
- isearch: ユーザ入力による割り込みで検索位置の記録に失敗していたバグの修正 `#D0843`
- isearch: キャンセル時に位置とマークが正確に復元されない問題の修正 `#D0847`
- isearch, dabbrev: 検索処理中にユーザが何か入力するまで現在行が更新されない問題の修正 `#D0847`
- decode: 未ロードのキーマップに対して `ble-bind -m -P` `ble-bind -m kmap -f kspecs -` が使えない問題の修正 66e202a
- auto-complete: <kbd>C-j</kbd> が単なる "確定" になっていたのを "確定して実行" に修正 `#D0852` 01476a7
- edit: <kbd>M-S-f</kbd>, <kbd>M-S-b</kbd> を束縛するべきところ <kbd>M-C-f</kbd>, <kbd>M-C-b</kbd> を束縛している箇所を修正 `#D0852` c68e7d7
- color: Bash 3.0 で算術式内の `<()` がプロセス置換と解釈される問題の対策 `#D0853` 520184d
- syntax: コメント上の単語が何故か除去されないバグの修正 (reported by cmplstofB) `#D0854` 641583f
- vi: Bash 3.1 及び 3.2 で <kbd>C-d</kbd> 受信の為のリダイレクトに失敗する問題の修正 `#D0857` d4b39b3

**動作変更**
- sabbrev, vi_imap: `sabbrev-expand` を <kbd>C-x '</kbd> ではなく <kbd>C-]</kbd> から束縛 `#D0825` e5969b7
- core: `bleopt` に設定名を指定子て設定内容を表示させる時、設定名の存在を確認する `#D0850` 725d09c
- isearch: <kbd>C-d</kbd> で現在の選択範囲を削除する様に変更 `#D0826` c3bb69e `#D0852` db28f74
- isearch: <kbd>C-m</kbd> (<kbd>RET</kbd>) で確定した時は選択範囲を解除する様に変更 `#D0826` c3bb69e
- decode: `ble-bind` のオプションを再構成 `#D0850` f7f1ec8 64ad962
- decode: 組み込みコマンド `bind` を上書きして `ble.sh` の動作が阻害されない様に引数をチェックして実行 `#D0850`
- complete: autoload `ble-sabbrev` (`core-complete.sh`), `ble-syntax:bash/is-complete` (`core-syntax.sh`) `#D0842` df0b769
- isearch: 編集関数 `isearch/accept-line` が <kbd>RET</kbd> 以外から束縛されていても <kbd>RET</kbd> を実行する様に変更 `#D0843`
- vi, [in]search: mark 名を整理 (`char`/`line`/`block`/`search` に接頭辞 `vi_` 付加し、新しい mark 名を `search` とする) `#D0843`
- edit: 関数名変更 `ble/widget/accept-single-line-or/accepts` → `ble-edit/is-single-complete-line` `#D0844`
- isearch: 空文字列で検索した時の振る舞いを再考 `#D0847` d05705e
- decode: 入力のキー復号の各種調整 `#D0850` dc013ad
- dabbrev: <kbd>C-m</kbd>, <kbd>RET</kbd> で展開終了、<kbd>C-j</kbd>, <kbd>C-RET</kbd> でコマンド実行 `#D0852` 01476a7

**内部的変更**
- isearch, dabbrev: `ble/util/fiberchain` による再実装 `#D0843`, `#D0846` 2c695cf bdf8072 95268c1
- edit, vi: 選択範囲の種類を表す mark 名を整理 a1a6272
- edit: 関数名変更 `ble/widget/accept-single-line-or/accepts` → `ble-edit/is-single-complete-line` `#D0844` 63ec9fe
- refactor: ファイルの整理 5e07e7f 1a03da2 673bd1d 55c4224 9ce944c 9a47c57 25487a7 5679ffc b7291a7
- refactor: 関数名・変数名の整理 `#D0851` d1b780c 9129c47 4d1181a

**Comment by akinomyoga** [comment]
`master` ブランチにマージしました。ヒアストリング・ヒアドキュメントの補完については何れ気が向いた時に実装することにします。
