### ISSUE TITLE
redundant widget name prefix check not working

### ISSUE THREAD

**Issue by musou1500** [akinomyoga/ble.sh#505]
**ble version**: 0.4.0-devel4+670c7ea0 

**Bash version**: 5.2.21(1)-release

variable name `command` seems wrong.
[https://github.com/akinomyoga/ble.sh/blob/master/src/decode.sh#L1777](https://github.com/akinomyoga/ble.sh/blob/670c7ea0d9f2e4debbc4021b0b8502a36b0b1999/src/decode.sh#L1777)

**Comment by akinomyoga** [comment]
Thanks for the report. This doesn't seem to have worked since it was introduced in commit 0beac334d. The variable name should be `cmd`.

**Comment by musou1500** [comment]
@akinomyoga Thank you. I created Pull-Request!

**Comment by akinomyoga** [comment]
Just for the record, I tried to confirm the behavior in the existing code, but the check actually worked:

```console
$ ble-bind -f C-t ble/widget/nop
ble-bind: Unknown widget `ble/widget/nop'. Note: The prefix 'ble/widget/' is redundant.
```

I realized that all the callers have defined the local variable `command`.

```bash
./src/decode.sh:3487:              ble-decode-key/bind "$kmap" "$kbd" "$command"
./src/decode.sh:3881:  ble-decode-key/bind "$kmap" "${keys[*]}" "$command"
./src/decode.sh:4041:      ble-decode-key/bind "$kmap" "$bind_keys" "$command"
./src/decode.sh:4047:      ble-decode-key/bind "$kmap" "${keys[*]}" "$command"
```

The function `ble-decode-key/bind` has referenced the variable defined by the caller, so the problem didn't appear.

**Comment by musou1500** [comment]
thank you for explanation!

I noticed that `ble-decode-key/bind` has following comment lines.
```bash
## @fn ble-decode-key/bind keymap keys command
##   @param[in] keymap keys command
```

Are these lines mean that referencing `command` defined by caller is intentional?

**Comment by akinomyoga** [comment]
No, it's not intentional, so it should have been fixed anyway. If the function expects a variable defined by the caller, the code documentation is supposed to include `@var[in] <variable_name>`. An example is line 2325 of the same file:

https://github.com/akinomyoga/ble.sh/blob/670c7ea0d9f2e4debbc4021b0b8502a36b0b1999/src/decode.sh#L2323-L2335

**Comment by musou1500** [comment]
Thank you for the clarification! I understand now.
