### ISSUE TITLE
Thoughts on disabling update mechanism

### ISSUE THREAD

**Issue by LecrisUT** [akinomyoga/ble.sh#511]
For Fedora packaging, we probably do not want to allow upstream updating. For the most part the user permissions should take care of disallowing it, but I wanted to get your opinion as well if you would want to make it configurable at install time. We could make a patch to print out some helpful messages of why it is disabled if you can point to where to patch.

**Comment by akinomyoga** [comment]
> I wanted to get your opinion as well if you would want to make it configurable at install time.

It's already configurable. Have you read [`_package.bash` in README](https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#_packagebash)? If you've already tried using it, what is the problem?

**Comment by LecrisUT** [comment]
Awesome, I will forward it to the actual packager and get them to comment on this issue if they find anything. I will close it for now.

Didn't rtfm, but that's a common issue with single-page READMEs. Any plans for RTD?

**Comment by akinomyoga** [comment]
What is RTD?

**Comment by LecrisUT** [comment]
> What is RTD?

https://readthedocs.org, but usually it refers to RTD + sphinx (with `myst-parser` in order to translate `.md` files to `html`)

**Comment by SuperSandro2000** [comment]
Basically a static, rendered version of the readme.

**Comment by akinomyoga** [comment]
Thanks to both of you. How does it solve the *"common issue with single-page READMEs"*?

In the first place, what is the *"common issue with single-page READMEs"*? If it refers to long READMEs, the description for packaging would be one of the things that will be removed first, so the long README actually helps in the present case.

**Comment by LecrisUT** [comment]
> How does it solve the "common issue with single-page READMEs"?

It's just that many people, me included have attention span issues. It is good practice to minimize the scrolling needed by the user. For that having a hosted page ([example](https://scikit-build-core.readthedocs.io/en/latest/)) with TOC on the side helps a lot. Could give some further tips on some common organization of that, and maybe help get a workflow up for that using RTD + sphinx + myst-parser (would be a good opportunity for me to learn to handle multi-language projects), but time-wise, probably can't start new stuff for 1-2 months, but happy to come back if you ping me about it and/or review about it.
