### ISSUE TITLE
how do disable all features except syntax highlighting?

### ISSUE THREAD

**Issue by simonLeary42** [akinomyoga/ble.sh#514]
I'm running BLE over SSH onto a VM where my home directory is NFS mounted, so I need my shell to be particularly lightweight. I find that BLE introduces lag on every keypress. I want to strip off most of the flashy features and just have the syntax highlighting. I've been reading about the options in the bleshrc template and it's long and I was wondering if someone knew off the top of their head which options I should be looking for.

Also, I would be happy to do some performance profiling if I knew how.

**Comment by simonLeary42** [comment]
https://github.com/akinomyoga/ble.sh#22-disable-features

**Comment by simonLeary42** [comment]
I disabled autocomplete and menu complete, but there is still completion happening. When I press tab+tab, blesh prints an almost-column-formatted list of suggestions, after some delay, with everything underlined. Can this be disabled as well?

my `.blerc`:
```
bleopt complete_auto_complete=
bleopt complete_auto_history=
bleopt complete_ambiguous=
bleopt complete_menu_complete=
bleopt prompt_eol_mark=''
bleopt exec_errexit_mark=
bleopt exec_elapsed_mark=
bleopt exec_exit_mark=
bleopt edit_marker=
bleopt edit_marker_error=
```

**Comment by simonLeary42** [comment]
after unbinding `tab` I have no completion at all, I would prefer to fall back to the default bash/readline completion.

**Comment by akinomyoga** [comment]
In a ble.sh session, the completion by Bash/Readline is not available. It's impossible to implement because there is no way for a script to get the results of the completion of Bash/Readline. Bash/Readline only prints the results to the terminal screen and doesn't expose the necessary programming interface for it.

**Comment by simonLeary42** [comment]
OK, that makes sense.

**Comment by akinomyoga** [comment]
I'm not sure what you want to achieve, but

- If you still want the completion but just don't want to see the list of completions, you can set the following:

```bash
# blerc

bleopt complete_menu_complete_opts=hidden
```

- If you want the completion with the menu but don't want to see the *almost-column-formatted list*, you can try other menu styles through [`bleopt complete_menu_style`](). For example,

```bash
# blerc

bleopt complete_menu_style=dense
```

- If you want the completion with the aligned menu but don't want to see the colors and underlines, you can set the following:

```bash
# blerc

bind 'set colored-stats off'
```

- If you just want the fact that the completion is performed by the built-in Bash/Readline feature, as far as I know, it's impossible as replied above.

**Comment by simonLeary42** [comment]
What does the underline represent in `colored-stats`?

**Comment by akinomyoga** [comment]
With the default `ble-face` settings, it means that the completion item is a filename. This is all configurable through `ble-face` (though the color settings are shared with the highlighting of the words in the command line). You can check the default settings as follows:

```console
$ ble-face filename_@
ble-face filename_block=fg=yellow,bg=black,underline
ble-face filename_character=fg=231,bg=black,underline
ble-face filename_directory=fg=33,underline
ble-face filename_directory_sticky=fg=231,bg=26,underline
ble-face filename_executable=fg=green,underline
ble-face filename_link=fg=teal,underline
ble-face filename_ls_colors=underline
ble-face filename_orphan=fg=16,bg=224,underline
ble-face filename_other=underline
ble-face filename_pipe=fg=lime,bg=black,underline
ble-face filename_setgid=fg=black,bg=191,underline
ble-face filename_setuid=fg=black,bg=220,underline
ble-face filename_socket=fg=cyan,bg=black,underline
ble-face filename_url=fg=blue,underline
ble-face filename_warning=fg=red,underline
```

**Comment by akinomyoga** [comment]
> since the completion delay is uncomfortably long.

I'm not sure about the real cause of the delay in your environment, but another thing you might try is to disable the programmable completion:

```bash
shopt -u progcomp
```

ble.sh performs a quite non-trivial thing to handle the programmable completion settings set up by the user or other frameworks.

**Comment by simonLeary42** [comment]
`shopt -u progcomp` didn't fix my latency issue, just for the record.
