### ISSUE TITLE
ble.sh not reading $XDG_CONFIG_HOME/blesh/init.sh

### ISSUE THREAD

**Issue by rux616** [akinomyoga/ble.sh#52]
**ble version**: 0.4.0-devel2+efe1e81
**Bash version**: 5.0.16(1)-release,x86_64-pc-linux-gnu

It looks like ble.sh currently isn't reading the XDG spec-based init file, `$XDG_CONFIG_HOME/blesh/init.sh`. The problem resides in ble.pp on lines 710 and 711, where the file checked is `$rcfile` instead of `$_ble_base_rcfile`. I'll submit a PR with a fix shortly.

**Comment by akinomyoga** [comment]
Thank you for the report! I'll merge the PR
