### ISSUE TITLE
[Arch handlr-regex 0.12.0] auto complete of handlr-regex gives unexpected results

### ISSUE THREAD

**Issue by hecto600** [akinomyoga/ble.sh#521]
**ble version**: 0.4.0-devel4+31f264ad
**Bash version**: 5.2.37(1)-release (x86_64-pc-linux-gnu)

In the example below I type `handlr m`, expected the `mime` option, but instead it autocompletes something else:
![swappy-2024-10-18_163601](https://github.com/user-attachments/assets/366b9d07-4fae-4505-a02a-a3c650ac5b47)

```
~
> handlr mbash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
bash: build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
m [.gtk-bookmarks]                                                             |
```

The error refreshes for every new character input.

![swappy-2024-10-18_163753](https://github.com/user-attachments/assets/1094456d-6e75-4255-83ab-5770a9af0737)

```
~
> handlr mbash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
bash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
mibash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
bash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
mimbash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
bash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
bash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
bash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
mimebash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr:No such file or directory
bash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
bash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
bash: /build/handlr-regex/src/handlr-regex-0.12.0/target/release/handlr: No such file or directory
```

**Comment by akinomyoga** [comment]
Thanks for the report, but is that specific to ble.sh's `auto-complete`?

- **Q1**: Does the same error appear when you attempt the TAB completion?

```bash
$ handlr m[TAB] 
```

- **Q2**: Does the same error appear without ble.sh (but with the corresponding completion)?

```bash
# In a session without ble.sh

$ handlr m[TAB]
```

- **Q3**: What is the result of the following command AFTER the error message is output in the session?

```bash
$ complete -p handlr
```

**Comment by hecto600** [comment]
Q1:
![swappy-2024-10-18_203218](https://github.com/user-attachments/assets/782bfa77-68e4-410c-b414-cff6471ca0e2)

Q2: I don't know how to do it. Is there a way to test without unistall ble.sh?

Q3:
![swappy-2024-10-18_203354](https://github.com/user-attachments/assets/4b74e040-1420-4322-9db4-8c7163e039f7)

**Comment by akinomyoga** [comment]
Thanks.

> Q2: I don't know how to do it. Is there a way to test without unistall ble.sh?

Can you comment out `source /path/toble.sh` in your `~/.bashrc` temporarily to test it? After testing, you can just uncomment it.

**Comment by hecto600** [comment]
The error appears when I press tab. Q2:
![swappy-2024-10-18_211518](https://github.com/user-attachments/assets/15e66c5f-e398-49af-9c1c-f0ad9f298982)

**Comment by akinomyoga** [comment]
Thank you. The answer to Q1 tells us that the problem also arises with the TAB completion, so it is not specific to the auto-complete feature. The answer to Q2 tells us that it is not a problem of ble.sh, but a problem of the setup of the completion setting by `handlr` / `handlr-regex`. The answer to Q3 shows `_clap_complete_handlr` as the name of the shell function that processes the completion. Then, let's go to the next questions.

- **Q4**: What are the results of the following commands?

```bash
$ (shopt -s extdebug; declare -F _clap_complete_handlr)
$ type _clap_complete_handlr
```

**Comment by hecto600** [comment]
with ble.sh re-enabled:
![swappy-2024-10-18_212528](https://github.com/user-attachments/assets/9bbd50c7-9e5f-4eca-8aba-ac8e9e876fc5)

**Comment by akinomyoga** [comment]
Sorry, could you run these commands *after the error message is output in the session*?

**Comment by hecto600** [comment]
I pressed enter for the `handlr m` incomplete command and input the code requested, resulting this output:
![swappy-2024-10-18_213058](https://github.com/user-attachments/assets/64b9744b-d8f0-4f6a-b845-7a8885a80be6)

**Comment by akinomyoga** [comment]
Thank you. I now suspect the completion file `/usr/share/bash-completion/completions/handlr` provided in the system.

- **Q5**: What are the results of the following commands?

```bash
$ ble/widget/display-shell-version
$ cat /usr/share/bash-completion/completions/handlr
```

**Comment by hecto600** [comment]
![swappy-2024-10-18_215929](https://github.com/user-attachments/assets/bfb20460-ec71-45d4-81d9-c3af1c5434c9)

**Comment by akinomyoga** [comment]
Thank you. How did you install `handlr-regex`? I see you use Arch Linux. Did you install it from AUR?

The `PKGBUILD` on AUR seems to generate the completion file on [this line](https://gitlab.archlinux.org/archlinux/packaging/packages/handlr-regex/-/blob/main/PKGBUILD?ref_type=heads#L29) and [install it at `/usr/share/bash-completion/completions/handlr`](https://gitlab.archlinux.org/archlinux/packaging/packages/handlr-regex/-/blob/main/PKGBUILD?ref_type=heads#L44). I believe this is a packaging issue of the AUR package. The current setup of the AUR package is introduced in [commit 24083d6b](https://gitlab.archlinux.org/archlinux/packaging/packages/handlr-regex/-/commit/24083d6bd0e7d6bfe9923419882021c539d96ffc) three days ago. This is after the upstream change https://github.com/Anomalocaridid/handlr-regex/pull/85 in how the completion files are generated.

**Comment by hecto600** [comment]
Im using the handlr-regex from the official extra repository https://archlinux.org/packages/extra/x86_64/handlr-regex/
![swappy-2024-10-18_222146](https://github.com/user-attachments/assets/755760c9-5105-4b8d-9004-392766861622)

**Comment by akinomyoga** [comment]
Ah, OK. I've checked it again and realized that what I was looking was actually the official one. Anyway, this is an issue of the Arch package.

**Comment by akinomyoga** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/handlr-regex/-/issues/1

**Comment by akinomyoga** [comment]
The Arch package seems to have been updated. @hecto600 Could you update `handlr-regex` using `pacman` and check the behavior?

**Comment by hecto600** [comment]
Tried different commands and, with this update, it seems that the error no longer occurs.
![swappy-2024-10-24_150434](https://github.com/user-attachments/assets/7cee70e2-516d-4092-a3e2-4bb6ec534cdb)

**Comment by akinomyoga** [comment]
Thank you for checking. Can I close the issue?

**Comment by hecto600** [comment]
Done. :)

**Comment by akinomyoga** [comment]
Thank you!
