### ISSUE TITLE
Incremental history search requires pressing enter twicee

### ISSUE THREAD

**Issue by waldolemmer** [akinomyoga/ble.sh#526]
**ble version**: 0.4.0-devel4+31f264ad
**Bash version**: 5.2.26(1)-release (x86_64-pc-linux-gnu)

When I do a reverse history search with <C-r> in vanilla Bash, pressing Enter once is enough to run a command. With ble.sh, I need to press enter twice.

I only want to use ble.sh for its syntax highlighting, since I want my muscle memory to work smoothly with vanilla Bash. I tried all the bleopt options in the "Disable features" section in the README, but none of them fixed the issue.

**Comment by akinomyoga** [comment]
By default, ble.sh chooses a behavior more consistent with the original GNU Emacs for the emacs editing mode, where <kbd>RET</kbd> (<kbd>C-m</kbd>) just ends the incremental search. ble.sh provides a way to configure keybindings for those who want to modify behaviors. If you want the Readline behavior for the incremental search, please use the following keybindings for your needs:

```bash
# blerc

ble-bind -m isearch -f C-m isearch/accept-line
ble-bind -m isearch -f RET isearch/accept-line
```

**Comment by waldolemmer** [comment]
That works well, thanks. If I notice any other non-bash-like behaviors, I'll have a look at the binds.
