### ISSUE TITLE
TAB autocompletion inconsistent between kitty and other terminal emulators

### ISSUE THREAD

**Issue by tdouilletgrellier** [akinomyoga/ble.sh#529]
`ble/widget/display-shell-version` output with  Gnome's default terminal :
```
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu) [Debian GNU/Linux 11 (bullseye)]
ble.sh, version 0.4.0-devel4+31f264a (noarch) [git 2.30.2, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:a70ad0273a4b1aec119c089386fca9864e724b94, 76580 bytes) (noarch)
fzf key-bindings, (hash:c477e0fc736054b081f42b8e188a792d5ef0911b, 149 bytes) (noarch) (integration: on)
fzf completion, (hash:c477e0fc736054b081f42b8e188a792d5ef0911b, 149 bytes) (noarch) (integration: on)
zoxide, version 0.9.4 (/home/f66379/.local/bin/zoxide)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=14.0-west/16.0-2+ri, vte:6203 (65;6203;1)
options: +notify +autocd +cdable_vars +cdspell +checkhash +direxpand +dirspell +dotglob +extglob +globstar +histappend -hostcomplete +histverify +inherit_errexit +no_empty_cmd_completion +nocaseglob
```

`ble/widget/display-shell-version` output with Kitty terminal :
```
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu) [Debian GNU/Linux 11 (bullseye)]
ble.sh, version 0.4.0-devel4+31f264a (noarch) [git 2.30.2, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:a70ad0273a4b1aec119c089386fca9864e724b94, 76580 bytes) (noarch)
fzf key-bindings, (hash:c477e0fc736054b081f42b8e188a792d5ef0911b, 149 bytes) (noarch) (integration: on)
fzf completion, (hash:c477e0fc736054b081f42b8e188a792d5ef0911b, 149 bytes) (noarch) (integration: on)
zoxide, version 0.9.4 (/home/f66379/.local/bin/zoxide)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-kitty wcwidth=15.0-west/16.0-2+ri, kitty:0 (1;4000;37)
options: +notify +autocd +cdable_vars +cdspell +checkhash +direxpand +dirspell +dotglob +extglob +globstar +histappend -hostcomplete +histverify +inherit_errexit +no_empty_cmd_completion +nocaseglob
```

If I type `vim "TAB"` in Gnome terminal, I get the `fzf-tab-completion` menu as expected (i have `fzf-tab-completion` installed).

If I type `vim "TAB"` in Kitty terminal, I get the `ble.sh` completion.

Disactivating `ble.sh` makes the `fzf-tab-completion` menu pop up as expected  in both terminals.

I tried adding `ble-bind -f 'TAB' fzf-complete` in my `.blerc`, it does show an `fzf` menu in kitty but not the `fzf-tab-completion` menu 

Any idea why the behavior is not consistent between terminals ?

Thank you in advance for your help ! And thank you for ble.sh !

**Comment by akinomyoga** [comment]
> Any idea why the behavior is not consistent between terminals ?

Because kitty supports an [advanced keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/) so that <kbd>Ctrl+I</kbd> (`C-i`) and <kbd>Tab</kbd> (`TAB`) can be distinguished, while GNOME Terminal only supports traditional keyboard protocol where <kbd>Ctrl+I</kbd> and <kbd>Tab</kbd> are both transmitted as `\x09` (`C-i`). If you use the Bash setting of [the `fzf-tab-complete` README](https://github.com/lincheney/fzf-tab-completion?tab=readme-ov-file#bash), it only binds to `\t` = `\x09` = `C-i`, i.e., <kbd>Ctrl+I</kbd>. You also need to bind `fzf_bash_completion` to Tab using `ble-bind`:

```bash
# blerc

ble-bind -x C-i fzf_bash_completion
ble-bind -x TAB fzf_bash_completion
```

**Comment by tdouilletgrellier** [comment]
Thank you it works, but I can't 'Ctrl+c" out of the fzf_bash_completion menu : kitty prints the keycode instead...

Anyway it is no longer a ble.sh issue now I think. Thank you !
