### ISSUE TITLE
`ble-bind -L` displays `illegal byte sequence`

### ISSUE THREAD

**Issue by Mossop** [akinomyoga/ble.sh#538]
```console
$ ble summary
GNU bash, version 5.2.37(1)-release (aarch64-apple-darwin24.0.0)
ble.sh, version 0.4.0-nightly+546499b (noarch) [git 2.47.1, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-preexec (.bash-preexec.sh), (hash:641346ad9e4c26b602add231e73c8894f9fb2280, 14349 bytes) (noarch)
starship, version 1.21.1 (rustc 1.81.0 (eeb90cda1 2024-09-04) (Homebrew), 2024-10-18 16:27:23 +00:00)
atuin, version 18.3.0 (/Users/dave/.atuin/bin/atuin)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=12.1-west/16.0-2+ri, xterm:276 (0;276;0)
options: +inherit_errexit
```

`ble-bind -L` outputs an error:

```
$ ble-bind -L
sed: RE error: illegal byte sequence
```

**Comment by akinomyoga** [comment]
Thanks for the report. There have been similar problems with macOS awk. I think macOS sed behaves in a similar way.

What are the outputs of the following commands?

```bash
$ type ble/bin/sed
$ type -a sed
```

**Comment by Mossop** [comment]
```shell
$ type ble/bin/sed
ble/bin/sed is a function
ble/bin/sed () 
{ 
    '/usr/bin/sed' "$@"
}
$ type -a sed
sed is /opt/homebrew/opt/gnu-sed/libexec/gnubin/sed
sed is /usr/bin/sed
```

I have installed homebrew's sed because it is more compatible with tools that expect Linux-like sed, but perhaps that is causing the problem here?

**Comment by akinomyoga** [comment]
Thank you for the results.

> I have installed homebrew's sed because it is more compatible with tools that expect Linux-like sed, but perhaps that is causing the problem here?

No, it's actually the opposite. macOS `sed` (`/usr/bin/sed`) is causing the present problem. In your setup, I guess `ble.sh` is sourced before the `PATH` environment variable is set up for the tools installed through Homebrew. The reason for my guess is that the result you provided indicates that `ble.sh` captures `/usr/bin/sed` for the `sed` location. Then, I believe the installation of Homebrew's `sed` hasn't affected the present issue.

**Comment by akinomyoga** [comment]
I added a workaround in commit a16aa59492826f1c32aaab23f69c164e32c972ee. @Mossop Since I don't have macOS, I cannot test it directly. Could you update `ble.sh` by running `ble-update` and see if the problem is fixed?

**Comment by Mossop** [comment]
Yes it works now, thanks!

**Comment by akinomyoga** [comment]
Thanks!

**Comment by LeonardoMor** [comment]
I am getting the exact same problem:
```output
❯ ble --version
ble.sh, version 0.4.0-devel4+31f264ad (noarch)
❯ type ble/bin/sed
ble/bin/sed is a function
ble/bin/sed ()
{
    '/usr/bin/sed' "$@"
}
❯ type -a sed
sed is /usr/bin/sed
```

**Comment by akinomyoga** [comment]
@LeonardoMor Thanks for the report. What is your system? Could you provide the result of `ble summary`?

```bash
$ ble summary
```

**Comment by LeonardoMor** [comment]
The command gives me this:
```output
❯ ble summary
ble (ble.sh): unrecognized subcommand 'summary'
```

Let me know if there's an alternative

**Comment by LeonardoMor** [comment]
Thanks. This fixed it. I forgot that on macOS I installed this manually and so I never updated it. I have two additional questions:

1. If I were to update blesh from a script, how would I do it? Adding `ble-update` fails to recognize that as a command. If I source `ble.sh` then it says that it is not an interactive session when I run the script.
2. How do I list all the currently configured key binds?

**Comment by akinomyoga** [comment]
> Thanks. This fixed it. I forgot that on macOS I installed this manually and so I never updated it. I have two additional questions:
> 
> 1. If I were to update blesh from a script, how would I do it? Adding `ble-update` fails to recognize that as a command. If I source `ble.sh` then it says that it is not an interactive session when I run the script.

This is [described in the first section of `README`](https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#:~:text=%23%20UPDATE%20(outside%20ble.sh%20sessions)%0A%0Abash%20/path/to/ble.sh%20%2D%2Dupdate).

> 3. How do I list all the currently configured key binds?

This is also [described in 2.7 of `README`](https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#:~:text=The%20existing%20key,ble%2Dbind%20%2DP).
