### ISSUE TITLE
[BSD awk] 履歴: 複数行の履歴を再び読み出した際，改行部分の “\” が “q” になる

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#56]
**ble version**: 0.4.0-devel2+6e3b3b5
**Bash version**: 5.0.3(1)-release

複数行に亘る命令を実行した後，一度ble.sh及びBashを終了して，新しくBash及びble.shを立ち上げた後，先程実行した複数行命令を履歴を遡って読み込むと，改行をシェルに解釈させない為に置いていた逆斜線 “\” が “q” という文字に置き換わって表示されます。

再現
```console
$ echo \
a \
b \
c
$ exit # 終了
$ #  新規に立ち上げ
$ # ^Pなどで履歴遡上
$ echo q
a q
b q
c
```

また，不明な頻度で「eval -- $'echo \\\na \\\nb \\\nc'」というような解釈前と思われる命令行が表示される場合もあります。

**Comment by akinomyoga** [comment]
ありがとうございます! Fedora で再現しなかったのですが awk が怪しいと思って FreeBSD で試したら再現しました。`\` が `q` に化ける方については修正しました 1d8adf9 。

> 不明な頻度で「eval -- $'echo \\na \\nb \\nc'」というような解釈前と思われる命令行が表示される場合もあります。

こちらは先程 FreeBSD 上で一回だけ再現できましたが、それきり再現できていません…。`\` が `q` に化けるのとは独立な問題のような気がしています。

**Comment by cmplstofB** [comment]
対応いただきありがとうございます！逆斜線が “q” に化けなくなりました。
私の環境 (Debian 10) では `awk` 命令で起動するのはGNU akwなので，BSD awkでの現象がこちらで再現するのはちょっと不思議ですが……。版次が古いんですかね (GNU Awk 4.2.1)。

（閉じます）

---

> また，不明な頻度で「eval -- $'echo \\na \\nb \\nc'」というような解釈前と思われる命令行が表示される場合もあります。

これについてですが，完全な再現はできないものの，構文上の誤りを履歴に保存した場合に発生する頻度が高くなる……ように思えます（←すいません，曖昧で）。
```console
$ echo
xxx
yyy<ここで決定>

-bash: xxx: コマンドが見つかりません
-bash: yyy: コマンドが見つかりません
$ exit
$ # （立ち上げ直す）
$ # ^Pで履歴遡上
$ eval -- $'echo\nxxx\nyyy'
```

ただし，残念ながら必ず再現する訳ではないです。

**Comment by akinomyoga** [comment]
> 私の環境 (Debian 10) では awk 命令で起動するのはGNU akwなので，BSD awkでの現象がこちらで再現するのはちょっと不思議ですが……。版次が古いんですかね (GNU Awk 4.2.1)。

確認ありがとうございます! Fedora 30 も GNU 4.2.1 ですがやはり再現しないですね…。Ubuntu の GNU 4.1.4 でも再現しないようです。以下の様に直接コマンドを実行すると q に置き換わる事は確かめられたので、何かまた別のことが起こっているのかもしれません。
```bash
$ echo 'a\b\c' | awk 'gsub(/\\/,"\q")' 2>/dev/null
```

> これについてですが，完全な再現はできないものの，斜線を入れない複数行命令を履歴に保存した場合に発生する頻度が高くなる……ように思えます

情報ありがとうございます! こちらでは相変わらず再現しませんが様子見ということにします。また何か分かったことがあればお知らせいただければ幸いです。ありがとうございました
