### ISSUE TITLE
Wrong syntax highlighting of square brackets

### ISSUE THREAD

**Issue by alvinseville7cf** [akinomyoga/ble.sh#66]
**ble version**: 
**Bash version**: 

Let's imagine we have the following code:
```
[[ "aaaAa.BBBDWG" == +([[:lower:]]).+([[:upper:]]) ]] && echo 1 || echo 0
```
This looks like this in terminal:
![bug](https://sun9-40.userapi.com/ESXNdq_bFNWm6_biMDkVcGVbRRcRSqTcCFSmAg/NcX4do1xUFA.jpg)

**Comment by akinomyoga** [comment]
OK, I haven't implemented the syntax analysis of the POSIX character classes. I'll implement it later.

**Comment by akinomyoga** [comment]
Fixed in commit 6fd9e22. I newly added the syntax analysis of the following POSIX brackets:
- character classes `[: … :]`
- equivalence classes `[= … =]`
- collating symbols `[. … .]`

Could you check the behavior? Thank you.

**Comment by akinomyoga** [comment]
Although there is no reply, I believe this has been fixed. I close this issue.

**Comment by EmilySeville7cfg** [comment]
> Although there is no reply, I believe this has been fixed. I close this issue.

![image](https://github.com/akinomyoga/ble.sh/assets/42812113/eb0b95ea-0976-4504-9e5f-1a7995d2f1b7)

It is.

**Comment by akinomyoga** [comment]
Thanks for the conformation!
