### ISSUE TITLE
[構文強調] 命令置換および算術展開

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#68]
**ble version**: 0.4.0-devel2+2f40422
**Bash version**: 5.0.18(1)-release

命令置換 (command substitution) と算術展開 (arithmetic expansion) の内部が誤って着色されます。具体的には [`syntax_error`](https://github.com/akinomyoga/ble.sh/wiki/%E8%AA%AC%E6%98%8E%E6%9B%B8-%C2%A72-%E6%8F%8F%E7%94%BB#2213-%E6%8F%8F%E7%94%BB%E8%A8%AD%E5%AE%9A-syntax_error) のように思われます。

```console
$ echo `echo a`
$ echo "$(echo a)"
$ echo $((42+1))
```
などにおいて，命令展開および算術展開される筈の場所に施される構文強調が正しくありません。

**Comment by akinomyoga** [comment]
ご報告ありがとうございます! これは簡単なミスでした。直しました [`46e2ac6`](https://github.com/akinomyoga/ble.sh/commit/46e2ac6ea43de8ff008d4bd1aef26629f50ee983#diff-f22f5241f777b5af70c554008edacf061e5001726a62567d4f3ef655a4dc84c4L6508-R6503)

**Comment by cmplstofB** [comment]
確認いたしました。ありがとうございます。

**Comment by akinomyoga** [comment]
確認ありがとうございます!
