### ISSUE TITLE
コマンド補完において誤った候補が出力される

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#7]
Commit ID: 8617258

コマンド補完に不具合があります
#### コマンドとして入力している文字列がコマンド候補に含まれている場合
```console
$ vi@
# 補完キー押下
$ vi@
vi* vim
```
`vi*`というコマンドはありません。

#### コマンドとして入力している文字列がコマンド候補に含まれていない場合
```console
$ ema@
# 補完キー押下（emaから始まるコマンドはない）
$ ema\*@
```
ちなみに，ここで更に補完キーを押下すると
```console
$ ema\*@
$ ema\\\*\*@
```
となります。以降補完キーを押下する度に文字列が長くなっていきます。

なお，この際，bleshは「エラー」とは判断していないようです；というのも不正な位置で補完キーを押下したときはビジュアルベルが作動<sup>*</sup>しますが，この場合は作動しないので。

---
\* bleoptとしてedit_vbellを有効にしています。

**Comment by akinomyoga** [comment]
ありがとうございます! `shopt -s failglob` で再現できました。後で直します

**Comment by akinomyoga** [comment]
- [`87ba74b`](https://github.com/akinomyoga/ble.sh/commit/87ba74b0e422995dc4348ce99fa3cf0f82651720#diff-a9f419c031b4580d73344eb63c1967b2R418) 直しました。

**Comment by akinomyoga** [comment]
多分、これでちゃんと直っていると思うのでもう閉じますね。
これに関してまだ問題があれば reopen しますのでまたご連絡くださいませ。

**Comment by cmplstofB** [comment]
@akinomyoga 様
直っているのを確認いたしました。対応ありがとうございます。
