### ISSUE TITLE
PROMPT_COMMAND is being evaluated too late

### ISSUE THREAD

**Issue by 3ximus** [akinomyoga/ble.sh#72]
**ble version**: 0.4.0-devel2+dabc515
**Bash version**: 5.0.17(1)-release, x86_64-pc-linux-gnu

So the problem is I have my PROMPT_COMMAND using `__git_ps1` from [this script](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh) to generate a prompt indicator for the status of a git repo. I have it setup like this (a bit of a mess..):
```sh
ALT_PS1="$(__color "$__CountColor")#\#\$(__virtualization)$(__color "$__JobColor")\$(__job_count)\$([[ \$__MainColor != \$__UserColor ]] && echo \"$(__color "$__MainColor") \u@\h\") $(__color "$__DirColor")\w\$(__virtual_env)"

ALT_PS2="$(__color 0) \$([[ \$_COMMAND_FAILED_ == 1 ]] && echo -e \"$(__color "$__ErrorColor")\")\\$ $(__color 0)"

__prompt_function() {
	[[ $? != 0 ]] && _COMMAND_FAILED_=1 || _COMMAND_FAILED_=0
	__git_ps1 "$ALT_PS1" "$ALT_PS2" "$(__color "$__GitColor") %s"
}

PROMPT_COMMAND='__prompt_function'
```

The problem I face is when i `cd` into a git repository it doesn't show the git branch information until the prompt is redrawn again as shown here:
![print](https://user-images.githubusercontent.com/9083012/100688260-db67bb80-3379-11eb-9aa1-a8431c62e197.png)

The information displayed is always from the past command:
![print_001](https://user-images.githubusercontent.com/9083012/100688788-056dad80-337b-11eb-9cf8-b10129f0e87e.png)

with normal bash the behavior is as expected:
![print_002](https://user-images.githubusercontent.com/9083012/100688846-27ffc680-337b-11eb-9182-72f3a1e592df.png)

Is there any way this can be fixed ? Or should I change something?
I would like to be able to keep my PROMPT_COMMAND as it is if possible.

Amazing project btw,
Thank you!

**Comment by akinomyoga** [comment]
Thank you for the report! This was actually a bug introduced by 06381c9. I fixed it in the commit bbda197. Could you check if it works fine now?

Thank you again!

**Comment by 3ximus** [comment]
Yup, issue is fixed! 
Perfect !

**Comment by akinomyoga** [comment]
Thank you for checking!
