### ISSUE TITLE
unbable to use italic for atleast auto_complete and disabled

### ISSUE THREAD

**Issue by rlanore** [akinomyoga/ble.sh#73]
**ble version**: 0.4.0-devel2+276baf2
**Bash version**: 5.1.0(1)-rc3, x86_64-pc-linux-gnu
**ble installed by**: TRIAL without installation

Hi all, I'm unbale to use italic style for some face

set auto_complete style with this command
```
ble-color-setface auto_complete italic
```

**Comment by akinomyoga** [comment]
Thank you for the report!

> Hi all, I'm unbale to use italic style for some face

Does it mean you can use the italic style for other faces?

Actually, to correctly render the italic style, the terminal needs to support it.

- Q1. What is your terminal?
- Q2. Do you use terminal multiplexers such as `tmux` or `screen`?
- Q3. What is the result of the following commands?

```bash
echo "$TERM"
infocmp | grep sitm
cat -A <<< [$_ble_term_sgr_sitm]
```

**Comment by akinomyoga** [comment]
Hi! How's the situation? In another Issue #75, you have reported that you are using the terminal Terminator 1.92. Can I think this Issue is also based on the same terminal? In my environment, Terminator 1.91 supports italic styles, and `ble-color-setface auto_complete italic` works as expected.

**Comment by rlanore** [comment]
Sorry for inconvenience. it'work with correct TERM into tmux.
Will not work with
```
set -g default-terminal "screen-256color"
```
And work with
```
set -g default-terminal "tmux-256color"
```

**Comment by akinomyoga** [comment]
OK! Thank you for the information! I think I'll add a description for `tmux` in the manual. Thank you!
