### ISSUE TITLE
Completion menu doesn't show new completions when ignored while completing ambigous directory names

### ISSUE THREAD

**Issue by 3ximus** [akinomyoga/ble.sh#74]
Hi, I'm not sure this is some setting that I need to set or that I have unknowingly used, since it doesn't seem like a normal behavior.

So my problem is when trying to complete directories that start with the same name, I start typing the name, hit `TAB` and the completion menu comes up:
![print_001](https://user-images.githubusercontent.com/9083012/101624319-b32f2b00-3a11-11eb-8215-2872f6708ec9.png)
Since I want to go into the `forecast` directory I type the forward slash and start writing a filename, however this will be used to filter the menu instead of generating completions for the directory itself:
![print_002](https://user-images.githubusercontent.com/9083012/101624562-ff7a6b00-3a11-11eb-88ac-7e1706a33c22.png)
To get the completions I either have to autocomplete with the menu option or cancel the completion and try again.
Is this normal behavior? Can it be tweaked somehow? Like the forward slash would reevaluate the list of completions maybe?
Thank you!

**Comment by akinomyoga** [comment]
Thank you for the report! Fixed 98fbc1c. This was just a side-effect of a change introduced in commit 5777d7f. It seems the introduced change is actually not so useful, so I reverted the change. Could you check the behavior with the latest commit? Also, if you have any additional suggestions, they are always welcome!

**Comment by 3ximus** [comment]
Yup, now it's working. Thank you very much. I was about to ask if anything could be done about generating completions for directories with a LOT of entries in them. But it seems you already improved it and its totally usable now!! :)
Props for you work, this is amazing ! I'll let you know of anything else I find.
Cheers !

**Comment by akinomyoga** [comment]
Thank you very much for checking! Actually, there is still some discussion to improve the performance of completions with many files in PR #65. I hope it will be further improved near future.
Thank you again! Cheers!
