### ISSUE TITLE
Lot of ^H char on completion

### ISSUE THREAD

**Issue by rlanore** [akinomyoga/ble.sh#75]
**ble version**: 0.4.0-devel2+276baf2
**Bash version**: 5.1.0(1)-rc3, x86_64-pc-linux-gnu
**Terminal**: Terminator version 1.92

Some time command completion add a lot of ^H char

Only type: unzip -[TAB] and shown above completion

```
# unzip -^H-
-^H-$^H$ | [MS-DOS, OS/2, NT] restore the volume label if the extraction medium is removable (e.g., a di…
-^H-2^H2 | [VMS] force unconditionally conversion of file names to ODS2-compatible names.
-^H-:^H: | [all but Acorn, VM/CMS, MVS, Tandem] allows to extract archive members into locations outside…
```

**Comment by akinomyoga** [comment]
Thank you for the report! This was caused when the options are extracted from Man pages. I modified the code in the commit b5c875a. Could you test the latest version with `ble-update`? Thank you!

**Comment by rlanore** [comment]
It work ! Thank you. ble.sh seem pretty cool. I will use this for more time and report another issue if i reach them.
Very nice work !

I use tmux with a lot of windows and pane into each. i'm little afraid to reach some performances issue.
I will comeback if it is.

**Comment by akinomyoga** [comment]
Thank you for checking and also the encouraging words for `ble.sh`! The issues are always welcome!

Thank you.
