### ISSUE TITLE
[描画] 逆斜線+改行後に，オプションと見做されるべき文字列がそう描画されない

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#76]
**ble version**: 0.4.0-devel3+b5c875a
**Bash version**: 5.0.18(1)-release

```console
$ echo -a \
-b \
-c
```

例えば上掲のコマンドラインにおいて，-b, -cというバイト列は-aと同じくオプション文字列と見做され，オプション文字列用の描画 (`argument_option`) が行なわれるべきですが，そのように描画されません。もちろん，この状況でも-aというバイト列は `argument_option` に設定した描画命令が反映されています。

**Comment by akinomyoga** [comment]
ご報告ありがとうございます!

うーん。なるほど… `\-b` や `''-b` 等の様に単語が `-` から始まらない場合には、(展開した結果として `-` で始まるようになっていても) オプションとしての着色はしない様にしていたのですが、`\` + 改行 のケースはそうでない方が良いですね。今までずっと `\`+改行 は次の単語の一部として取り扱ってきたのですが、文法的に単語の一部とは見做さず空白の一種と見做す様に変更しました 67e62d6。

文法を弄ったので他の場所でひょっとすると影響があるかもしれませんが、語頭の `\` + 改行 は単語の一部に含めないのが通常の用法的にも自然な気がするのでこのまま行きます。問題が出てきたらその時にまた対処することにしますね。因みに、これで sabbrev (文法情報を用いて単語を切り出している) も `\`+改行 の直後で動く様になった事と思います。

確認していただければ幸いです!

**Comment by cmplstofB** [comment]
確認いたしました。ありがとうございます。

**Comment by akinomyoga** [comment]
ありがとうございます
