### ISSUE TITLE
Printing output when resizing terminal window with a git prompt

### ISSUE THREAD

**Issue by 3ximus** [akinomyoga/ble.sh#78]
Hi, I'm back again :D 

I find the reason of the problem I mentioned the other day.
It turns out its when some resizing happens on the terminal while inside a git repository. Here is a gif of the issue:

![out](https://user-images.githubusercontent.com/9083012/102677928-f1a8b080-419c-11eb-820c-bed7d8b54862.gif)

Also I noticed that if i detach and reattach the messages are different and might bring you some insight into the issue:

![print](https://user-images.githubusercontent.com/9083012/102677999-57953800-419d-11eb-8afd-81fd1075d478.png)

My prompt gets generated with this script https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh
I don't know if it has something to do with it, but it doesn't happen in normal bash, so I'm guessing it is a problem with ble.sh

Cheers

**Comment by akinomyoga** [comment]
Thank you! I could finally reproduce the problem with the following simple `~/.bashrc`.

```bash
# bashrc

source 3ximus.dotfiles/.bash/git-prompt.sh
source 3ximus.dotfiles/.bash/prompts/prompt_7.sh
source ~/.mwg/src/ble.sh/out/ble.sh
```

Now I can narrow down the problem at my side, so I think I can fix it soon!

**Comment by akinomyoga** [comment]
I got the following minimal test case that reproduces the job message. It seems Bash reports the forked processes in a trap handler as terminated jobs by the command `jobs`.

```bash
# bashrc
trap '(true); jobs' WINCH
```

I don't know if this is the intended behavior of Bash or just a bug, but it reproduces in all the Bash versions I tried (i.e., 3.0-5.1). I'll think about how we can work around this Bash behavior.

**Comment by 3ximus** [comment]
> ```shell
> # bashrc
> trap '(true); jobs' WINCH
> ```

Yeah, this seems to solve it. But I don't quite get it, so by trapping window resize with a call to jobs it doesn't display forked processes anymore? Shouldn't it do the opposite and actually display background processes after resizing?

**Comment by akinomyoga** [comment]
> Yeah, this seems to solve it.

Oh, wait... I actually meant a different thing. The above setting was just a *minimal reproducer* of the messages and intended to be used *without* `ble.sh`. You can reproduce the strange messages by starting Bash with the single-line `.bashrc`,

```bash
$ bash --rcfile <(echo "trap '(true); jobs'")
```

and you will get job messages for `( true )` for each resize of the terminal.

But, yes, I now confirmed that this actually solves the problem when used with `ble.sh`. So, the current situation is:

| | without `ble.sh` | with `ble.sh` |
|:-:|:-:|:-:|
| without `trap ... WINCH` | OK | job messages |
| with `trap ... WINCH` | job messages | OK |

Actually, I'm not sure if this solution with `trap ... WINCH` is robust enough as I currently don't know why it works. I'm rather thinking of modifying `ble.sh`'s code that tracks the job status change.

**Comment by akinomyoga** [comment]
I added a workaround bc4735e. Hope it works

**Comment by 3ximus** [comment]
Yup its working fine...
Yeah its kind of a weird fix, but background jobs still show up fine so it seems there aren't any apparent side effects !
If you find out more about it let me know, I'll close the issue.
Cheers mate, many thanks once again!!

**Comment by akinomyoga** [comment]
Thank you for checking!

> Yeah its kind of a weird fix, but background jobs still show up fine so it seems there aren't any apparent side effects!

Actually, I used a different approach in bc4735e to solve the problem. Now it seems the workaround works, so there is no longer a problem with `ble.sh`. But now I'm interested in what is going on inside Bash, so I think I will look into the related Bash source code later when I have time.

Thanks!!
