### ISSUE TITLE
Changing the colors to default

### ISSUE THREAD

**Issue by rafaelribeiroo** [akinomyoga/ble.sh#79]
Hello guys, how r u? I hope fine. Well, basically I loved this project and this is working for me excellent. However I have a doubt, there some workaround to reset the match autocomplete colors to default system? (white color in my case)

![2021-01-02_01-50](https://user-images.githubusercontent.com/19275140/103451085-4a4c7300-4c9e-11eb-9d85-05473d0dab22.png)
![2021-01-02_01-50_1](https://user-images.githubusercontent.com/19275140/103451086-4b7da000-4c9e-11eb-816a-47fb87ba0ce6.png)

**Comment by akinomyoga** [comment]
Hello! Thank you for trying `ble.sh`!

Maybe I miss what you are asking, but the texts suggested by `auto-complete` is configured by the `auto_complete` face, whose default background is light gray (~ almost white). This is the intended design that works for terminals of both dark and light backgrounds.

- If you want to configure the face (i.e., colors and styles) of the suggested texts, please check [this item in Q&A](https://github.com/akinomyoga/ble.sh/wiki/Q&A#q9-how-to-change-the-color-of-suggestions-of-auto-complete)!
- I believe the white color has nothing to do with your system default colors, but if you have some reason that you think the white color is related to the system default color, you can provide us some more information in reply.

Thank you!

**Comment by rafaelribeiroo** [comment]
Sorry for the bad issue, I see the `ble-color-setface` command right now. I'm changing all colors.

**Comment by akinomyoga** [comment]
OK! Glad to hear that you have found a way! Thank you for your question!
