### ISSUE TITLE
Getting  >>> -bash: warning: setlocale: LC_CTYPE: cannot change locale

### ISSUE THREAD

**Issue by 3ximus** [akinomyoga/ble.sh#81]
Hi there, I'm getting this error on a new server. It shows up bunch of times, simply by opening the shell through ssh and at every key press:

![print_000](https://user-images.githubusercontent.com/9083012/104604722-9243a080-5675-11eb-9f69-e667fb1a0313.png)

Apparently I have LANG set to `en_US.UTF-8` and LC_CTYPE set to `pt_PT.UTF-8` and I can fix the issue by putting `export LC_TYPE=en_US.UTF-8` inside my `.bash_profile` or `.bashrc` .

However I'm wondering if that message couldn't just be ignored since default bash seems to work fine under the same conditions.

Cheers

**Comment by 3ximus** [comment]
Yeah, got it ! I guess I didn't have the pt_PT.UTF-8 which its expecting. Maybe its being sent by the ssh connection from my computer... Either way I don't use it so thank you, the problem's fixed :+1:

**Comment by akinomyoga** [comment]
OK!

> Maybe its being sent by the ssh connection from my computer...

Oh, I see. I haven't thought about that case! Yes, ssh transfers environment variables like `TERM`, `LANG`, and `LC_*` (depending on the ssh config `SendEnv`/`AcceptEnv`), so it is possible that the local locale setting causes problems in the host. Thank you!
