### ISSUE TITLE
One character disappearing from the prompt

### ISSUE THREAD

**Issue by endorfina** [akinomyoga/ble.sh#84]
Hi there! Awesome project. 😁
I've encountered one issue where after I press Enter, a character from whatever I just entered gets eaten. Just as on attached screenshots:
![Screenshot_20210130_014748](https://user-images.githubusercontent.com/35767873/106341525-e49fd680-629d-11eb-985c-efc3f216478d.png)
![Screenshot_20210130_014726](https://user-images.githubusercontent.com/35767873/106341528-e8335d80-629d-11eb-8bca-bdcc6a2991f3.png)
It's not always the last character that gets dropped.

Also, it looks like if I paste the command in, it stays intact, but when I type it in a single character always gets dropped.

**Comment by akinomyoga** [comment]
Thank you! It doesn't reproduce at my side. Maybe the problem occurs with some user settings. I have several questions:

- Does the problem reproduce also with <kbd>C-j</kbd>?
- What is the result of the following command?
```bash
$ ble-bind -P | grep C-m
```

**Comment by akinomyoga** [comment]
Ah, OK. I think the problem is related to the width calculation of the flamingo emoji in the prompt string. The emoji database in `ble.sh` is a bit old so it doesn't recognize U+1F9A9 as an emoji. I'll update the emoji database later! Thank you for your report!

**Comment by endorfina** [comment]
You're right. Removing the flamingo character does fix the issue. 

Awesome, thank you! 😇 I'll wait for your update then.

**Comment by akinomyoga** [comment]
I updated the emoji database (d1f8c27) and pushed it in `master` branch! I also supported a new option [`bleopt emoji_version`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#user-content-bleopt-emoji_version) to change the Unicode version of emoji. If you are already using the `master` branch of `ble.sh`, you can update it by the command `ble-update` in `ble.sh` session. Thanks again for your report!
