### ISSUE TITLE
ヒアドキュメント後のコマンドラインにおけるヘルプ機能がカーソル下の単語を判断しない

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/ble.sh#9]
Commit ID: 860e0fe
Version of GNU Bash: 4.4.12

（すいません，文章でできるだけ分かりやすく説明しようとしたのですが……）

```console
$ cat <<. | echo@
foo
bar
baz
.
```
このようなコマンドラインにおいて，ヘルプキー（vi-modeの既定は<kbd>K</kbd>）を押下しても，cat(1)に関するヘルプが実行されてしまいます。本来は，echo(1)に関してのヘルプが実行されるべきです。

**Comment by cmplstofB** [comment]
f56e827 にて，修正されているのを確認いたしました。対応ありがとうございます。

**Comment by akinomyoga** [comment]
ありがとうございました! 閉じます
