### ISSUE TITLE
Make Ctrl-Backspace/Alt-Backspace kill word before cursor

### ISSUE THREAD

**Issue by ofey404** [akinomyoga/ble.sh#94]
I heavily use `C-Backspace`/`M-Backspace` in bash to kill a word before cursor. ble.sh is awesome, but I really miss this feature.

Would anybody please add this feature? Or maybe show me how to understand this project, and I'll try to do it by myself.

`C-Backspace` is slightly different from stty `C-w`, which send `werase`:
> The werase action in tty line editor cannot be configured. It always erases (ASCII) whitespace-delimited words.

`C-Backspace` would treat `-`, `_` and some other delimiters as boundary of words. eg:

```bash
bash-5.0$ test kill-a-word
# After C-w
bash-5.0$ test 
```
```bash
bash-5.0$ test kill-a-word
# After C-Backspace or M-Backspace
bash-5.0$ test kill-a-
```

Tested on a bash without configuration, `INPUTRC=/dev/null bash --norc --noprofile`

Some reference:
- https://unix.stackexchange.com/questions/264791/ctrl-backspace-and-ctrl-delete-in-bash

**Comment by ofey404** [comment]
I'm reading your makefile... 

Is the code under `src` are the main part of your project? The code count varies.
```bash
[ofey@RX93 ble.sh]$ cloc .
     155 text files.
     155 unique files.                                          
      38 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.17 s (728.0 files/s, 386378.5 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
Bourne Shell                            82           5419           9847          41228
Markdown                                17            655              0           3215
awk                                      1            148            161           1308
Bourne Again Shell                      14             99             92            553
HTML                                     1             24             78            379
Pascal                                   1            109            641            299
C                                        4             21              5            155
Windows Module Definition                1             10              0            137
make                                     1             31             21            115
---------------------------------------------------------------------------------------
SUM:                                   122           6516          10845          47389
---------------------------------------------------------------------------------------
[ofey@RX93 ble.sh]$ cloc src/
       9 text files.
       9 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.06 s (139.7 files/s, 375303.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Bourne Shell                     9           2037           4116          18027
-------------------------------------------------------------------------------
SUM:                             9           2037           4116          18027
-------------------------------------------------------------------------------
```

**Comment by akinomyoga** [comment]
Thank you! In the Emacs mode of `ble.sh`, <kbd>C-BS</kbd> and <kbd>M-BS</kbd> are bound by *undo* and *copy-backward-cword*, respectively, by default. <kbd>C-BS</kbd> (*undo*) is the same as the Readline default. <kbd>M-BS</kbd> (*copy-backward-cword*) is `ble.sh` specific.

> C-Backspace would treat -, _ and some other delimiters as boundary of words. eg:

You can configure the keybindings using [`ble-bind`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#user-content-fn-ble-bind). I think your definition of the word corresponds to [`eword`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#44-wordwise-movement-and-operation) in `ble.sh`. It depends on what escape sequences your terminal sends for <kbd>C-backspace</kbd> and <kbd>M-backspace</kbd>, but here are some examples:

```bash
# blerc

ble-bind 'C-BS' kill-backward-eword
ble-bind 'C-_' kill-backward-eword
ble-bind 'M-BS' kill-backward-eword
ble-bind 'C-M-?' kill-backward-eword
```

To check what escape sequence your terminal sends for <kbd>C-backspace</kbd> and <kbd>M-backspace</kbd>, you may input <kbd>C-v C-backspace</kbd> and <kbd>C-v M-backspace</kbd> and see what will be input.

----

> Is the code under src are the main part of your project?

Yes. The files in `src/` together with `ble.pp` is the source of `ble.sh`. `ble.sh` is generated by combining these files. `ble.sh` contains the core utilities and the line editor. The files in the directory `keymap/` contain *widgets*---namely, line-editing functions--- that are specific to the Vim modes or the Emacs mode. Other miscellaneous modules and resource files are included in the directory `lib/`. For example, the code for syntax analysis and syntax highlighting is contained in the module `lib/core-syntax.sh`. The code for completions are contained in the module `lib/core-complete.sh`.

**Comment by akinomyoga** [comment]
@ofey404 Any updates on this issue? Have your questions been solved?

P.S. I came back to Japan from Beijing in April; moved to another position in Yukawa Institute, Kyoto University (京都大学). FYI, I'm not sure there will be overlap with your field, some of my group members in Kyoto will move to Fudan University soon. They are now waiting for visas.

**Comment by akinomyoga** [comment]
May I close the issue?

**Comment by ofey404** [comment]
Well, sorry for forgetting to reply to this issue for so long! My notification center is just flooded by accident for a while...XD

Actually I trained myself to get used to C-w terminal kill key combination. And I almost forget I need Ctrl-Backspace at all!

I think you can close this issue. I seemed to tried the method you give me several months ago, but somehow it doesn't work quite well, maybe I missed something. I'll try it again tomorrow.

After all, thank you for your work on `ble.sh`, it makes the computer world better. I really **love** it.

---

> P.S. I came back to Japan from Beijing in April; moved to another position in Yukawa Institute, Kyoto University (京都大学). FYI, I'm not sure there will be overlap with your field, some of my group members in Kyoto will move to Fudan University soon. They are now waiting for visas.

Best wishes!

**Comment by akinomyoga** [comment]
OK! Thank you for the reply! If you have any questions later, please feel free to open an issue again!

**Comment by anprowh** [comment]
For those who will find this in the future: <kbd>Alt-h</kbd> for current vesion
