### ISSUE TITLE
ble.sh multiline command is not working

### ISSUE THREAD

**Issue by RakibFiha** [akinomyoga/ble.sh#99]
**ble version**:  `0.4.0-devel3+0506df2`
**Bash version**:  `5.0.17(1)-release, x86_64-pc-linux-gnu`

I recently discovered ble.sh and wanted to give it a try and was truly impressed about the auto complete.

But, I am facing a issue when I try to do a multiline command. See the demo below:

![Peek 2021-04-23 10-53](https://user-images.githubusercontent.com/35771765/115806894-8e68ac80-a422-11eb-936c-19f0dbe3c68c.gif)

**Comment by akinomyoga** [comment]
Have you read [README §3.1](https://github.com/akinomyoga/ble.sh#31-use-multiline-mode)? In the multiline mode, <kbd>RET</kbd>/<kbd>C-m</kbd> is intended for newlines. To run the command, you can use <kbd>C-j</kbd>.

**Comment by RakibFiha** [comment]
> Have you read [README §3.1](https://github.com/akinomyoga/ble.sh#31-use-multiline-mode)? In the multiline mode, RET/C-m is intended for newlines. To run the command, you can use C-j.

Thank you!!

**Comment by akinomyoga** [comment]
OK! Thanks for trying `ble.sh`!

**Comment by nbenitez** [comment]
Arrived here from a Google search because I could not execute with `Return` key when pasting a multi-line command, so just let me add that to execute with `Return` key in multi-line mode I needed to add the following to my `.blerc`:
```
##-----------------------------------------------------------------------------
## Settings for Emacs mode
function blerc/emacs-load-hook {
  ## The default mapping of RET and C-m inserts newline with multiline commands
  ## or incomplete commands.  With the following setting, RET and C-m always
  ## causes the execution of the command even in the multiline mode or when the
  ## command is not syntactically completed.

  ble-bind -f 'C-m' accept-line
  ble-bind -f 'RET' accept-line

  return 0
}
blehook/eval-after-load keymap_emacs blerc/emacs-load-hook
```

For vim-mode there's also a similar setting, search "multiline" in  [here](https://github.com/akinomyoga/ble.sh/blob/master/blerc.template).
